MirrorNetworking/Mirror

Mirror/Weaver/CompilationFinishedHook.cs

Add extra paths so weaver can find referenced dlls

Fix #18 add extra unity paths

---

Mirror/Runtime/NetworkServer.cs

No need to initialize object twice,   the second initialize does nothing at all

fix #33,  remove redundant initialization

---

Mirror/Runtime/NetworkManager.cs

Fix npe calling numPlayer

---

Mirror/Runtime/ClientScene.cs

all methods are static,  nobody should instantiate this

Clientscene is a static class

---

Mirror/Runtime/NetworkReader.cs

This should be InvalidDataException,  the other exception is for something else.

Throw an appropriate exception

---

Mirror/Runtime/NetworkClient.cs
Mirror/Runtime/NetworkTime.cs

Move the ping messaging inside NetworkTime.

Modularize network time

---

migration.md

Added instructions to replace NetworkHas128 and NetworkInstanceId

Replace NetworkHas128 and NetworkInstanceId

---

Mirror/Runtime/ClientScene.cs

Lets see if we get the spawn scene object message

Add warning if we can't find scene object for #72 (DO NOT MERGE)

---

migration.md

Fix typo: NetworkHash128

---

Mirror/Runtime/ClientScene.cs
Mirror/Runtime/NetworkAnimator.cs
Mirror/Runtime/NetworkManager.cs
Mirror/Runtime/NetworkServer.cs
Mirror/Runtime/NetworkTime.cs

Use the functional method interface when possible.  It is easier to read.
I would have used var,  but vis hates it 👅

Use functional method to read messages

---

Mirror/Runtime/Messages.cs
Mirror/Runtime/NetworkManager.cs
Mirror/Runtime/NetworkServer.cs

RemovePlayerMessage is empty

---

Mirror/Runtime/UNetwork.cs

no need to reinvent the wheel here.

Reuse ReadMessage from reader

---

Mirror/Runtime/NetworkConnection.cs

Tx to MrGadget who found the issue

return false if the send fails.

---

Mirror/Weaver/Processors/NetworkBehaviourProcessor.cs

use the base OnSerialize/OnDeserialize if there is nothing to sync

Don't generate OnSerialize/OnDeserialize if not needed

---

Mirror/Runtime/Messages.cs

Useful with things like voice chat assets which return byte[] and used sendbytes in unet

Add BytesMessage

---

Mirror/Runtime/NetworkManager.cs

Display an error if you are using the wrong version of unity with mirror

Unity version check

---

Mirror/Runtime/NetworkServer.cs
Mirror/Runtime/Transport/LLAPITransport.cs
Mirror/Runtime/Transport/TelepathyTransport.cs
Mirror/Runtime/Transport/TelepathyWebsocketsMultiplexTransport.cs
Mirror/Runtime/Transport/Transport.cs

Cause max port is max ushort and min port is 0.

Changed ports to be ushorts instead of ints

---

Assets/Mirror/Editor/NetworkIdentityEditor.cs
Assets/Mirror/Editor/NetworkScenePostProcess.cs
Assets/Mirror/Runtime/NetworkIdentity.cs
Assets/Mirror/Runtime/NetworkManager.cs
Assets/Mirror/Runtime/NetworkServer.cs
Assets/Mirror/Runtime/Transport/LLAPITransport.cs
Assets/Mirror/Runtime/Transport/TelepathyWebsocketsMultiplexTransport.cs

With this changes,  master mirror should work in Unity 2018.3

2018 master

---

Assets/Mirror/Runtime/ClientScene.cs
Assets/Mirror/Runtime/Messages.cs
Assets/Mirror/Runtime/NetworkServer.cs

Fix #280, Spawn objects with rotation

---

Assets/Mirror/Runtime/NetworkBehaviour.cs

m_SyncObjects.Any creates some garbage and this code isnt really any more complex in my opinion

Reduce garbage in IsDirty

---

Assets/Mirror/Examples/Basic.meta
Assets/Mirror/Examples/Basic/Prefabs.meta
Assets/Mirror/Examples/Basic/Prefabs/Player.prefab
Assets/Mirror/Examples/Basic/Prefabs/Player.prefab.meta
Assets/Mirror/Examples/Basic/Prefabs/SpawnPoint.prefab
Assets/Mirror/Examples/Basic/Prefabs/SpawnPoint.prefab.meta
Assets/Mirror/Examples/Basic/README.md
Assets/Mirror/Examples/Basic/README.md.meta
Assets/Mirror/Examples/Basic/Scenes.meta
Assets/Mirror/Examples/Basic/Scenes/Example.unity
Assets/Mirror/Examples/Basic/Scenes/Example.unity.meta
Assets/Mirror/Examples/Basic/Scripts.meta
Assets/Mirror/Examples/Basic/Scripts/Player.cs
Assets/Mirror/Examples/Basic/Scripts/Player.cs.meta

Shows how to set up a simple mirror project

Minimum Mirror example

---

Assets/Mirror/Editor/NetworkManagerEditor.cs
Assets/Mirror/Runtime/NetworkManager.cs
Assets/Mirror/Runtime/NetworkManagerHUD.cs

everyone will need this setting in all their projects anyway.
and not everyone wants to use the ugly NetworkManagerHUD.

move startOnHeadless to NetworkManager

---

docs/Concepts/GameObjects/SpawnPlayerCustom.md

this is not supported by Mirror

Remove mention of HLAPI multiple players

---

Assets/Mirror/Runtime/Transport/LLAPITransport.cs
Assets/Mirror/Runtime/Transport/MultiplexTransport.cs
Assets/Mirror/Runtime/Transport/MultiplexTransport.cs.meta
Assets/Mirror/Runtime/Transport/Transport.cs

This transport allows you to listen to as many transports as you want simultaneously.
Use it like this:

Add multiplex transport

---

Weaver/Weaver/Extensions.cs

Nothing too radical, I just saw in other commits that code clarity and conciseness is a valued quality.

Code style and comment typo fix.

---

CONTRIBUTING.md

This is covered below One Python Way anyways.

Deleted redundant broken line.

---

docs/Classes/NetworkConnection.md

Please see commit https://github.com/vis2k/Mirror/commit/1e61aaa05a995c7a6ff9d1a60216878346eaa53c
PlayerControllers property was deprecated.

PlayerControllers deprecated

---

Weaver/Weaver/Extensions.cs

Reverts vis2k/Mirror#374
Breaks compile

Revert "Code style and comment typo fix."

---

README.md

Submitting for review by the team. This is my suggestion for updating the Usage section due to struggles we have seen in the help channel.

Update README.md to improve Usage Guide guidelines

---

Assets/Mirror/Runtime/NetworkServer.cs
Assets/Mirror/Runtime/Transport/LLAPITransport.cs
Assets/Mirror/Runtime/Transport/MultiplexTransport.cs
Assets/Mirror/Runtime/Transport/TelepathyTransport.cs
Assets/Mirror/Runtime/Transport/Transport.cs

the only client info we need on the outside is the address.

Transport.ServerGetClientAddress

---

Assets/Mirror/Components/NetworkLobbyManager.cs

Remove unused methods in NetworkLobbyManager

---

Assets/Mirror/Components/NetworkAnimator.cs
Assets/Mirror/Runtime/NetworkClient.cs

first of several NetworkClient untanglements.
this also fixes the NetworkClient.Update allocations:

Networkclient singleton

---

Assets/Mirror/Runtime/ClientScene.cs

super simple change to see if I got the git stuff right this time.

Simplified code a bit, and also removed allocation.

---

Assets/Mirror/Runtime/SyncList.cs

Greatly simplified SyncList by using Expression Bodied Members.

---

Assets/Mirror/Runtime/NetworkIdentity.cs

Network Identity Style

---

Assets/Mirror/Components/NetworkAnimator.cs
Assets/Mirror/Components/NetworkLobbyPlayer.cs
Assets/Mirror/Components/NetworkProximityChecker.cs
Assets/Mirror/Components/NetworkTransformBase.cs
Assets/Mirror/Editor/NetworkIdentityEditor.cs
Assets/Mirror/Editor/NetworkInformationPreview.cs
Assets/Mirror/Editor/NetworkManagerEditor.cs
Assets/Mirror/Editor/NetworkScenePostProcess.cs
Assets/Mirror/Editor/PreprocessorDefine.cs
Assets/Mirror/Examples/Basic/Scripts/Player.cs
Assets/Mirror/Examples/Lobby/Scripts/NetworkLobbyPlayerExt.cs
Assets/Mirror/Examples/Movement/Scripts/Move.cs
Assets/Mirror/Examples/Pong/Scripts/Ball.cs
Assets/Mirror/Examples/Pong/Scripts/Player.cs
Assets/Mirror/Runtime/CustomAttributes.cs
Assets/Mirror/Runtime/ExponentialMovingAverage.cs
Assets/Mirror/Runtime/LocalClient.cs
Assets/Mirror/Runtime/LocalConnections.cs
Assets/Mirror/Runtime/Messages.cs
Assets/Mirror/Runtime/NetworkBehaviour.cs
Assets/Mirror/Runtime/NetworkIdentity.cs
Assets/Mirror/Runtime/NetworkManager.cs
Assets/Mirror/Runtime/NetworkManagerHUD.cs
Assets/Mirror/Runtime/NetworkServer.cs
Assets/Mirror/Runtime/SyncList.cs
Assets/Mirror/Runtime/Transport/TelepathyTransport.cs
Assets/Mirror/Tests/ExponentialMovingAverageTest.cs
Assets/Mirror/Tests/NetworkWriterTest.cs
Assets/Mirror/Tests/SyncListTest.cs

Haven't tested if everything's okay with preprocessor ifs

Removed useless usings

---

Assets/Mirror/Editor/NetworkAnimatorEditor.cs

There was a question in the discord server asking for clarification about what the checkboxes were. I had to go read the code to be sure of my suspicions. This PR aims to clear that up and avoid this in the future.

Improve the clarity of the Network Animator Editor

---

Assets/Mirror/Components/NetworkLobbyManager.cs
Assets/Mirror/Runtime/ClientScene.cs
Assets/Mirror/Runtime/LocalConnections.cs
Assets/Mirror/Runtime/NetworkConnection.cs
Assets/Mirror/Runtime/NetworkManager.cs

Made member accessor debug logs consistent.

---

docs/General/WhyTCP.md

Less opinion,  more technical focused analysis on the issue.

More technical rationale

---

Assets/Mirror/Editor/NetworkScenePostProcess.cs
Assets/Mirror/Runtime/NetworkClient.cs
Assets/Mirror/Runtime/NetworkIdentity.cs
Assets/Mirror/Runtime/NetworkManager.cs
Assets/Mirror/Runtime/NetworkServer.cs

I did not rename UnetInvokeType to avoid smashing Paul's PR again.

Changed several mentions of UNet to instead say Mirror.

---

Assets/Mirror/Runtime/NetworkManager.cs

People should be able to implement their own OnValidate method and initialize their own default transport.   This can come in handy for steam .

Transport should be protected 

---

Assets/Mirror/Runtime/ClientScene.cs
Assets/Mirror/Runtime/NetworkIdentity.cs
Assets/Mirror/Runtime/Transport/LLAPITransport.cs

Reordered a bit of code in LLAPI transport to make the regions make sense.

Removed comment divider thingies and used regions where applicable.

---

Assets/Mirror/Components/NetworkAnimator.cs
Assets/Mirror/Runtime/Messages.cs
Assets/Mirror/Runtime/NetworkBehaviour.cs
Assets/Mirror/Runtime/NetworkManager.cs
Weaver/Weaver/Processors/NetworkBehaviourProcessor.cs

Finished replacing comment walls with regions.

---

Assets/Mirror/Components/NetworkAnimator.cs

Fixed animator bandwidth problem.

---

docs/Concepts/Authentication.md
docs/_data/navigation.yml

Document how to do authentication with Mirror

Document authentication

---

Assets/Mirror/Editor/Weaver/Helpers.cs
Assets/Mirror/Editor/Weaver/Processors/TargetRpcProcessor.cs
Assets/Mirror/Runtime/NetworkBehaviour.cs

works perfectly in ummorpg.
supports TargetRpc(connection, value) and TargetRpc(value) and TargetRpc()
generated code:

[TargetRPC] optional connection parameter for easier usage while still allowing for previous usage

---

Assets/Mirror/Runtime/NetworkManager.cs

Passing false prevents the switch to offline scene...pass true instead to forceReload parameter.
Tested with Lobby example and works much better.

Fix Scene Handling

---

Assets/Mirror/Runtime/NetworkConnection.cs
Assets/Mirror/Runtime/NetworkServer.cs

fix: Stop calling ClientDisconnect on host

---

Assets/Mirror/Editor/PreprocessorDefine.cs

Less code, faster and more reliable

perf: speed up preprocessor define

---

Assets/Mirror/Components/NetworkAnimator.cs

More to come, going in small bits.

perf(animator): NetworkAnimator simplification and optimization.

---

Assets/Mirror/Components/NetworkAnimator.cs

Its a bit more code, but the coming PRs will make it better.

Made dirty bits not rely on NetworkWriter position manipulation hackery.

---

Assets/Mirror/Editor/Weaver/Weaver.cs
Assets/Mirror/Runtime/NetworkReader.cs
Assets/Mirror/Runtime/NetworkWriter.cs

Cubica heavily depends on integer math,  having weaver support for Vector2Int and Vector3Int would make my life a lot easier.

feat: Add serialization support for Vector2Int and Vector3Int

---

Assets/Mirror/Runtime/NetworkManager.cs

fix: #651 GetSceneAt assumes default scene

---

Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs

Previously, during deserialize,  Mirror either called the hook for a syncvar or it set the variable, but never both. Users had to set the variable inside the hook.
```cs
class Player : NetworkBehaviour {
[SyncVar(hook=nameof(OnVarChanged))]
public int myvar;
public void OnVarChanged(int newvalue) {
Debug.Log("Got new value " + newvalue);
Debug.Log("Old value is " + myvar);
// with this pull request the following line is no longer needed
// the weaver will do this after the hook finishes
// this.myvar = newvalue;
}
}
```

fix: Set syncvar variables after calling the hook

---

Assets/Mirror/Editor/NetworkScenePostProcess.cs

No references found. Commenting and weaver rebuild+run netted no errors.

bool InActiveScene not referenced in any script?

---

Assets/Mirror/Components/NetworkLobbyManager.cs
Assets/Mirror/Runtime/NetworkManager.cs
Assets/Mirror/Runtime/NetworkManagerHUD.cs

No longer needed now that NetworkClient is static

Remove IsClientConnected

---

Assets/Mirror/Runtime/ClientScene.cs
Assets/Mirror/Runtime/NetworkClient.cs
Assets/Mirror/Runtime/NetworkConnection.cs
Assets/Mirror/Runtime/NetworkManager.cs
Assets/Mirror/Runtime/NetworkServer.cs

If we ever end up actually needing to do something on set, then that's what properties are for.

Remove proxy methods for setting playerController.

---

Assets/Mirror/Runtime/NetworkIdentity.cs

Removing all these internal(organ)s and private(part)s is making me light headed...

Removed more internals.

---

Assets/Mirror/Runtime/SyncList.cs

I'd have made this use WritePackedUInt32 too, but that'd break binary compat, so i didnt. That should be done at some point though. For now, these are only style changes.

Synclist style

---

Assets/Mirror/Runtime/SyncList.cs

perf: Use WritePackedUInt32 in SyncList

---

Assets/Mirror/Editor/Weaver/Weaver.cs

This has caused us a lot of pain, mostly in the form of breakpoints and ASMDEF-related workarounds to get breakpoints working. Direct fix for #632.
**Please test, I only tried the Mirror Examples, not a complete project.**

fix(Weaver): Don't delete the PDB after Weaving

---

Assets/Mirror/Runtime/NetworkClient.cs

These red lines are for vis ❤️

Inlined an internal method call.

---

Assets/Mirror/Tests/NetworkWriterTest.cs

and sneak in a branding fix while we are at it 😉

Add tests for strange floats, doubles, and decimals

---

Assets/Mirror/Runtime/NetworkConnection.cs

DOS attacks will happen eventually. we need to be prepared.
- someone could send invalid headers
- someone could send a writebytesandsize with a negative size
- someone could try to send an invalid message id:
which would cancel updates for all server objects after the uncaught exception.

NetworkServer.OnDataReceived catches exceptions and disconnects the connection after invalid data was received.

---

Assets/Mirror/Editor/Weaver/CompilationFinishedHook.cs
Assets/Mirror/Editor/Weaver/Program.cs

fixes #706
while this does fix all known bad states from #706 there may be additional side effects. am still testing in windows, then will test osx/lin and confirm here

fix(weaver): fix #706 find system dlls

---

Assets/Mirror/Runtime/NetworkConnection.cs

this shouldn't break anyone either

This should have been readonly from day 1 too

---

Assets/Mirror/Runtime/NetworkBehaviour.cs

I'm not sure why syncObjects is `protected`, to be frank. It should be private, I dont see any usecases for users to mess with it.

Follow naming conventions in NetworkBehaviour

---

Assets/Mirror/Runtime/NetworkConnection.cs

Also move it above the disconnect, in case Disconnect throws.

Promote the Warning in NetworkConnection to an Error, because thats how it was before.

---

Assets/Mirror/Runtime/NetworkConnection.cs
Assets/Mirror/Runtime/NetworkServer.cs

Access modifiers here are pretty bad, but i'll do that in another PR.

Simplify network connection clientOwnedObjects

---

Assets/Mirror/Components/NetworkLobbyManager.cs
Assets/Mirror/Components/NetworkLobbyPlayer.cs

fix:Fixed Lobby Example

---

Assets/Mirror/Tests/NetworkWriterTest.cs

Add Endianness testing to NetworkWriter.

---

Assets/Mirror/Runtime/NetworkWriter.cs
Assets/Mirror/Tests/NetworkWriterTest.cs

Write(Ray) was completely broken. Now it is fixed thanks to these tests.

fix(write ray): Added NetworkWriter tests, found and fixed a bug in Write(Ray).

---

Assets/Mirror/Tests/NetworkWriterTest.cs

SetLength clears data beyond the Length that is set. Test it to make sure that doesnt change. Also test that skipping bytes leaves zeros behind, not garbage bytes.

Test that SetLength and Position work as expected

---

Assets/Mirror/Runtime/MessagePacker.cs
Assets/Mirror/Runtime/NetworkClient.cs
Assets/Mirror/Runtime/NetworkConnection.cs
Assets/Mirror/Runtime/NetworkServer.cs

fix: Fix issue #763 by only catching while message decoding, and not during handling.

---

Assets/Mirror/Examples/ListServer/ListServer.cs
Assets/Mirror/Runtime/NetworkManager.cs

Fixed ListServer example - This didn't come up when I searched before.
Added EditorBrowsable(EditorBrowsableState.Never) - I keep forgetting this.

isHeadless - hopefully last one

---

Assets/Mirror/Runtime/NetworkManager.cs

fix: Round Robin Spawning by Hierarchy Order

---

Assets/Mirror/Editor/NetworkAnimatorEditor.cs.meta
Assets/Mirror/Editor/Weaver/Processors/SyncListInitializer.cs.meta
Assets/Mirror/Editor/Weaver/Processors/SyncListStructProcessor.cs.meta

This PR will be followed by another consolidated PR to remove dummy cs and meta files in future a release.

fix: Add meta files for dummies

---

Assets/Mirror/Runtime/SyncList.cs
Assets/Mirror/Tests/SyncListTest.cs

Had this extension in all my assets since day one. I use this function a lot, probably useful for others too.

SyncList.FindIndex added

---

Assets/Mirror/Runtime/ClientScene.cs

There is no need to keep the list of prefabs.
Prefabs can be spawned with the spawn handlers,  so we only need 1 mechanism.

refactor:  consolidate prefab and spawn handlers

---

Assets/Mirror/Runtime/Transport/Websocket/Ninja.WebSockets/Internal/WebSocketImplementation.cs
Assets/Mirror/Runtime/Transport/Websocket/Server.cs

Fix for #829 
May also increase performance, my game seemed smoother with it but I didn't profile.

fix(websocket): #829 fix InvalidOperationException with wss://

---

Assets/Mirror/Runtime/Transport/LLAPITransport.cs

Please squash so that the commit log only shows the latest commit in this branch, otherwise that'll be 3 extra commits.

LLAPI Transport not available on WSA/UWP (v2)

---

Assets/Mirror/Runtime/Transport/Websocket/Ninja.WebSockets/Internal/WebSocketImplementation.cs

The SemaphoreSlim used in #830 severely degraded the performance of my game, causing total desync after ~40s of play. The queue system, as originally proposed, not only fixes the original issue without introducing degradation but actually improves the performance of my game a noticeable amount.

fix(websocket): Fix for performance regression caused by previous WSS fix

---

Assets/Mirror/Runtime/Transport/Websocket/Ninja.WebSockets/Internal/WebSocketImplementation.cs

After a couple of more tests in the real game the `InvalidOperationException` reared its ugly head again. I discovered that the WS layer is writing to the stream in more than one place, as it sends its own "ping" and "pong" messages (as required by the WS protocol I believe). Technically it also writes to the stream during the Close operations, but we don't care if the client gets DC'd during that (it's DCing anyway) so I didn't wrap those.
There may be a cleaner way to fix this (one unified queue), but it would increase LOC and possibly alloc. I think this is the best solution for now.
Note: This was tested extensively in a real game. The last one was as well, but I didn't spot or run into the `InvalidOperationException` for a few runs.

fix(websocket): Use queue for Ping and Pong messages as well

---

Assets/Mirror/Runtime/LocalConnections.cs
Assets/Mirror/Runtime/NetworkClient.cs
Assets/Mirror/Runtime/NetworkConnection.cs
Assets/Mirror/Runtime/NetworkReader.cs
Assets/Mirror/Runtime/NetworkServer.cs
Assets/Mirror/Runtime/Transport/LLAPITransport.cs
Assets/Mirror/Runtime/Transport/TelepathyTransport.cs
Assets/Mirror/Runtime/Transport/Transport.cs
Assets/Mirror/Runtime/Transport/Websocket/Client.cs
Assets/Mirror/Runtime/Transport/Websocket/ClientJs.cs
Assets/Mirror/Runtime/Transport/Websocket/Server.cs

reopen: https://github.com/vis2k/Mirror/pull/846 and fix webgl

perf: Transports now give ArraySegment<byte> instead of byte[] (based on #569 and #846)

---

docs/Components/NetworkManager.md

NetworkError does not exist in UnityEngine or Mirrors but in UnityEngine.Networking.

Fix NetworkManager doc

---

Assets/Mirror/Runtime/SyncDictionary.cs

Names are now consistent with the underlying IDictionary naming

Rename types according to Microsofts naming

---

Assets/Mirror/Editor/Weaver/Readers.cs
Assets/Mirror/Editor/Weaver/Writers.cs

Same logic,  just moved inside the GenerateArrayWriter/Reader for clarity

refactor: determine element type inside GenerateArrayWriter and Reader

---

Assets/Mirror/Runtime/SyncList.cs

List\<T\>also does it, this matches the behaviour.

feat: Implement IReadOnlyList<T> in SyncLists

---

Assets/Mirror/Runtime/SyncList.cs
Assets/Mirror/Tests/SyncListTest.cs

simplify list setter and eliminate unnecessary boxing

perf: eliminate boxing with lists

---

Assets/Mirror/Runtime/ClientScene.cs
Assets/Mirror/Runtime/Messages.cs
Assets/Mirror/Runtime/NetworkBehaviour.cs
Assets/Mirror/Runtime/NetworkIdentity.cs
Assets/Mirror/Runtime/NetworkReader.cs
Assets/Mirror/Runtime/NetworkServer.cs
Assets/Mirror/Tests/NetworkWriterTest.cs

perf: Avoid allocation when reading message payload

---

docs/Concepts/Communications/NetworkMessages.md

This reverts commit bb72643c1ed5960532f005b9f0ecfcee10e89423.

Revert "doc: messages can be struct now"

---

Assets/Mirror/Tests/ArrayWriterTest.cs

Bytes are serialized separately, we should have separate tests for them

Add byte array test

---

Assets/Mirror/Runtime/NetworkWriter.cs

All tests pass.
Will run with ummorpg soon

perf: remove BinaryWriter,  it allocates like crazy

---

Assets/Mirror/Runtime/Transport/Transport.cs

Initialize Unity event objects in Transport. fix #938

---

Assets/Mirror/Examples/Lobby/Prefabs/GamePlayer.prefab
Assets/Mirror/Examples/Lobby/Scripts/NetworkLobbyManagerExt.cs
Assets/Mirror/Examples/Lobby/Scripts/NetworkLobbyPlayerExt.cs
Assets/Mirror/Examples/Lobby/Scripts/PlayerController.cs
Assets/Mirror/Examples/Lobby/Scripts/Spawner.cs

Improved Player Controller
Use Main Camera instead of prefab camera
camelCase variable names

Updated Lobby Example

---

Assets/Mirror/Examples/AdditiveScenes/Prefabs/Player.prefab
Assets/Mirror/Examples/AdditiveScenes/Scenes/MainScene.unity
Assets/Mirror/Examples/AdditiveScenes/Scripts/AdditiveNetworkManager.cs
Assets/Mirror/Examples/AdditiveScenes/Scripts/PlayerController.cs
Assets/Mirror/Examples/AdditiveScenes/Scripts/SceneLoader.cs
Assets/Mirror/Examples/AdditiveScenes/Scripts/ShootingTankBehaviour.cs

Improved Player Controller
Use Main Camera instead of camera in prefab
camelCase variable names

Updated Additive Example

---

Assets/Mirror/Components/NetworkLobbyManager.cs
Assets/Mirror/Components/NetworkLobbyPlayer.cs
Assets/Mirror/Examples/Lobby/Prefabs/GamePlayer.prefab
Assets/Mirror/Examples/Lobby/Scripts/NetworkLobbyManagerExt.cs
Assets/Mirror/Examples/Lobby/Scripts/NetworkLobbyPlayerExt.cs
Assets/Mirror/Examples/Lobby/Scripts/PlayerController.cs
Assets/Mirror/Examples/Lobby/Scripts/Spawner.cs

Lobby example update

---

Assets/Mirror/Examples/Basic/Scenes/Example.unity
Assets/Mirror/Plugins/Unity.Cecil.meta

Somehow the wrong scene was in the previous PR...this is the correct one.

Correct scene for Basic Example

---

Assets/Mirror/Examples/AdditiveScenes/Scripts/PlayerController.cs

Restores Main Camera when player clicks Stop in the HUD.

Additive Example Camera Fix

---

Assets/Mirror/Examples/Lobby/Scripts/NetworkLobbyManagerExt.cs

One-liner to use the available property

Use isHeadless

---

Assets/Mirror/Runtime/NetworkServer.cs

Fixes #978 
Fixes #974 
Fixes #870

fix: Rebuild observers when we switch scenes, fixes #978

---

Assets/Mirror/Editor/Weaver/Processors/SyncVarProcessor.cs
Assets/Mirror/Editor/Weaver/Weaver.cs
Assets/Mirror/Runtime/NetworkBehaviour.cs

fix: syncvar hooks should not affect each other, fixes #1015

---

Assets/Mirror/Runtime/NetworkManager.cs

Just like OnClientChangeScene so devs can override to do prep before the change.

Added virtual OnServerChangeScene

---

Assets/Mirror/Runtime/NetworkManager.cs

Set it back to zero in StopServer

Reset Start Position Index

---

Assets/Mirror/Runtime/NetworkManager.cs

Check if we're already in the offline scene before calling ClientChangeScene to the offline scene.

Don't reload offline scene

---

Assets/Mirror/Runtime/NetworkManager.cs

Reorders and groups methods and properties to better reflect the flow of activity and put related things together so they're easier to find.  No actual code changes, regions added.
**Note** The diff looks like a train wreck...look at the actual file instead.

Reorder NetworkManager

---

Assets/Mirror/Examples/AdditiveScenes/Prefabs/Capsule.prefab
Assets/Mirror/Examples/AdditiveScenes/Prefabs/Cube.prefab
Assets/Mirror/Examples/AdditiveScenes/Prefabs/Cylinder.prefab
Assets/Mirror/Examples/AdditiveScenes/Prefabs/Sphere.prefab
Assets/Mirror/Examples/AdditiveScenes/Prefabs/Tank.prefab
Assets/Mirror/Examples/AdditiveScenes/Scenes/MainScene.unity
Assets/Mirror/Examples/AdditiveScenes/Scenes/SubScene.unity
Assets/Mirror/Examples/Basic/Prefabs/Player.prefab
Assets/Mirror/Examples/Basic/Scenes/Example.unity
Assets/Mirror/Examples/ListServer/Scenes/Scene.unity
Assets/Mirror/Examples/ListServer/UI/ServerStatusSlot.prefab
Assets/Mirror/Examples/Pong/Prefabs/Ball.prefab
Assets/Mirror/Examples/Pong/Prefabs/Racket.prefab
Assets/Mirror/Examples/Pong/Sprites/Ball.png.meta
Assets/Mirror/Examples/Pong/Sprites/DottedLine.png.meta
Assets/Mirror/Examples/Pong/Sprites/Racket.png.meta
Assets/Mirror/Examples/Pong/WallHorizontal.png.meta
Assets/Mirror/Examples/Pong/WallVertical.png.meta
Assets/Mirror/Examples/Room/Prefabs/GamePlayer.prefab
Assets/Mirror/Examples/Room/Prefabs/Prize.prefab
Assets/Mirror/Examples/Room/Prefabs/RoomPlayer.prefab
Assets/Mirror/Examples/Room/Scenes/OnlineScene.unity
Assets/Mirror/Examples/Room/Scenes/RoomScene.unity
Assets/Mirror/Examples/Tanks/Prefabs/Projectile.prefab
Assets/Mirror/Examples/Tanks/Prefabs/Tank.prefab
Assets/Mirror/Examples/Tanks/Scenes/Scene.unity

Changes applied to scene, prefab, and meta files by Unity 2018.4.9 just by opening and saving all the Mirror examples and touching all the prefabs without actually changing them.

Unity 2018.4.9 changes

---

Assets/Mirror/Runtime/NetworkConnection.cs

no point in overcomplicating it.
will make SendMany easier

merge NetworkConnection.SendBytes and TransportSend

---

Assets/Mirror/Runtime/NetworkConnection.cs
Assets/Mirror/Runtime/NetworkServer.cs
Assets/Mirror/Runtime/Transport/Transport.cs

preparing for allocation free send.
alternative to #1118 
PR #1119 has to be merged first.

feat: Transport can send to multiple connections at once

---

Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/TargetRpcProcessor.cs

similar to #1128 but for TargetRpc

fix: TargetRpc now works accross assemblies

---

Assets/Mirror/Examples/Basic/Scripts/Player.cs

This is somewhat in preparation for writing the doc for this example....
- Rearranged code to be more logical
- Added comments to everything
- Reworked the code to use all Mirror methods

Updated Basic Example

---

Assets/Mirror/Components/NetworkRoomManager.cs
Assets/Mirror/Examples/Pong/Scripts/NetworkManagerPong.cs
Assets/Mirror/Runtime/NetworkManager.cs

Obsoletes OnServerAddPlayer(NetworkConnection conn, AddPlayerMessage extraMessage)

Obsoletes OnServerAddPlayer

---

Assets/Mirror/Runtime/SyncDictionary.cs

First argument is expected to be the argument name.

Fix invalid exception usage

---

Assets/Mirror/Runtime/NetworkIdentity.cs

Fixes #1150 
Moved code up inside the null check if block

fix: Prevent NRE

---

Assets/Mirror/Runtime/NetworkServer.cs

Rename includeSelf to includeOwner

---

Assets/Mirror/Runtime/SyncList.cs

Allows usage of custom Equality Comparers in SyncLists.
Remove, IndexOf and Contains had to be rewritten due to List<T> always using EqualityComparer<T>.Default.

SyncList custom Equality Comparer support

---

Assets/Mirror/Editor/Weaver/Processors/CommandProcessor.cs
Assets/Mirror/Editor/Weaver/Weaver.cs

Alternative to #1166 Remove he command shortcut altogether,  so Command in host mode go through a message.

feat: Remove Command shortcut for host mode, fix #1160

---

Assets/Mirror/Components/NetworkAnimator.cs
Assets/Mirror/Editor/NetworkIdentityEditor.cs
Assets/Mirror/Runtime/ClientScene.cs
Assets/Mirror/Runtime/NetworkBehaviour.cs
Assets/Mirror/Runtime/NetworkIdentity.cs
Assets/Mirror/Runtime/NetworkServer.cs

* breaking: Remove localPlayerAuthority
This flag does not do anything useful in anything but NetworkAnimator
so NetworkAnimator can keep it's own flag.
* Add tooltip with explanation

breaking: Remove localPlayerAuthority

---

Assets/Mirror/Runtime/Transport/LLAPITransport.cs
Assets/Mirror/Runtime/Transport/MultiplexTransport.cs
Assets/Mirror/Runtime/Transport/TelepathyTransport.cs
Assets/Mirror/Runtime/Transport/Transport.cs

there is no reason to make any assumptions by default.
it's too easy to miss when it's virtual.

Make Transport.Available() abstract

---

Assets/Mirror/Runtime/Transport/FallbackTransport.cs
Assets/Mirror/Runtime/Transport/FallbackTransport.cs.meta
doc/Transports/Fallback.md
doc/Transports/index.md

very useful for apathy and telepathy.
this way we use apathy for server / client where possible, and fall back to telepathy otherwise.
will need this for my assets, and most people will need this for their apathy games too.

Fallback Transport

---

Assets/Mirror/Runtime/ClientScene.cs
Assets/Mirror/Runtime/NetworkClient.cs
Assets/Mirror/Runtime/NetworkServer.cs
Assets/Mirror/Runtime/NetworkTime.cs

NetworkConnection is often not needed in handlers,  so make them optional

feat: NetworkConnection is optional for handlers

---

doc/Guides/Authority.md

clarify what client authority means.  Remove Local Player Authority references.

Improve authority docs

---

Assets/Mirror/Runtime/NetworkServer.cs

For consistency, use Spawn in all cases

Deprecate SpawnWithClientAuthority

---

Assets/Mirror/Runtime/ClientScene.cs

Simplify spawning player,  and consolidate code paths between host and client mode.

refactor: Simplify spawning player

---

Assets/Mirror/Runtime/ClientScene.cs
Assets/Mirror/Runtime/NetworkServer.cs

Initialize hasAuthority and isLocalPlayer before calling Start and isLocalPlayer

has authority and islocalPlayer early initialization

---

Assets/Mirror/Components/NetworkAnimator.cs
Assets/Mirror/Editor/NetworkInformationPreview.cs
Assets/Mirror/Runtime/ClientScene.cs
Assets/Mirror/Runtime/Messages.cs
Assets/Mirror/Runtime/NetworkClient.cs
Assets/Mirror/Runtime/NetworkIdentity.cs
Assets/Mirror/Runtime/NetworkServer.cs

feat: SyncToOwner now works with authority (#1204)

---

Assets/Mirror/Runtime/NetworkClient.cs
Assets/Mirror/Runtime/NetworkIdentity.cs

isClient now returns true during onStartServer in host mode.
see #1250

fix: isClient now reports true onStartServer in host mode

---

Assets/Mirror/Runtime/ClientScene.cs
Assets/Mirror/Runtime/NetworkIdentity.cs
Assets/Mirror/Runtime/NetworkServer.cs

Reverts vis2k/Mirror#1254
Reverted per vis request,   will discuss

Revert "fix: replacing the player does not mean giving up authority"

---

Assets/Mirror/Runtime/ClientScene.cs
Assets/Mirror/Runtime/NetworkIdentity.cs
Assets/Mirror/Runtime/NetworkServer.cs

instead of having a special case for host objects,  spawn them like client/server objects via messages

Spawn host objects via spawn, just like clients

---

Assets/Mirror/Runtime/ClientScene.cs

if you had 2 or more clients,  they could not see each other properly sometimes

fix: issue with more than 1 client

---

Assets/Mirror/Runtime/NetworkServer.cs

fix: ReplacePlayer now calls OnStartLocalPlayer

---

Assets/Mirror/Runtime/NetworkManager.cs

startPositions is a public list, so the index should be too.

Make startPositionIndex public

---

Assets/Mirror/Editor/NetworkBehaviourInspector.cs

Got a tip from Tor (Odin Inspector) for this and it works.
Fixes #1247

fix: Inspector Refresh for SyncVars

---

Assets/Mirror/Runtime/Transport/TelepathyTransport.cs

feat: telepathy can now receive port from uri

---

Assets/Mirror/Runtime/Transport/Websocket/WebsocketTransport.cs

Websockets can now receive ports and ws/wss scheme in uri

feat: websocket can receive port in url

---

doc/Guides/Sync/SyncVars.md

docs: Added video tutorial URL

---

Assets/Mirror/Examples/AdditiveScenes/Scenes/MainScene.unity
Assets/Mirror/Examples/AdditiveScenes/Scripts/PlayerController.cs
Assets/Mirror/Examples/Room/Scenes/OnlineScene.unity
Assets/Mirror/Examples/Room/Scripts/PlayerController.cs

Same change to both examples so in server only mode there's a nice top-down view of the action.

Adjust cameras for server view

---

Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/PropertySiteProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/SyncVarProcessor.cs
Assets/Mirror/Editor/Weaver/Readers.cs
Assets/Mirror/Editor/Weaver/Weaver.cs
Assets/Mirror/Editor/Weaver/Writers.cs
Assets/Mirror/Runtime/NetworkBehaviour.cs
Assets/Mirror/Runtime/NetworkConnection.cs
Assets/Mirror/Runtime/NetworkManager.cs
Assets/Mirror/Runtime/NetworkServer.cs
Assets/Mirror/Runtime/NetworkTime.cs
Assets/Mirror/Runtime/SyncList.cs
Assets/Mirror/Runtime/Transport/MultiplexTransport.cs
Assets/Mirror/Runtime/Transport/Transport.cs
Assets/Mirror/Runtime/Transport/Websocket/Client.cs
Assets/Mirror/Runtime/Transport/Websocket/ClientJs.cs
Assets/Mirror/Runtime/Transport/Websocket/Ninja.WebSockets/Internal/WebSocketImplementation.cs
Assets/Mirror/Runtime/Transport/Websocket/Server.cs
Assets/Mirror/Runtime/Transport/Websocket/WebsocketTransport.cs
Assets/Mirror/Tests/ArraySegmentWriterTest.cs
Assets/Mirror/Tests/CustomRWTest.cs
Assets/Mirror/Tests/SyncListTest.cs
Assets/Mirror/Tests/SyncVarTest.cs

No code changes, just a regex replace of triple line breaks to doubles.

Remove all extraneous blank lines

---

.releaserc.yml
appveyor.yml

The release now has a version.txt file inside Assets/Mirror

feat: Include version in release

---

Assets/Mirror/Examples/Chat.meta
Assets/Mirror/Examples/Chat/Prefabs.meta
Assets/Mirror/Examples/Chat/Prefabs/Player.prefab
Assets/Mirror/Examples/Chat/Prefabs/Player.prefab.meta
Assets/Mirror/Examples/Chat/Scenes.meta
Assets/Mirror/Examples/Chat/Scenes/Main.unity
Assets/Mirror/Examples/Chat/Scenes/Main.unity.meta
Assets/Mirror/Examples/Chat/Scripts.meta
Assets/Mirror/Examples/Chat/Scripts/ChatNetworkManager.cs
Assets/Mirror/Examples/Chat/Scripts/ChatNetworkManager.cs.meta
Assets/Mirror/Examples/Chat/Scripts/ChatWindow.cs
Assets/Mirror/Examples/Chat/Scripts/ChatWindow.cs.meta
Assets/Mirror/Examples/Chat/Scripts/Player.cs
Assets/Mirror/Examples/Chat/Scripts/Player.cs.meta

Demonstrates a few features:
* How to create a custom UI
* How to use commands and clientrpc
* How to create a custom user

feat: Chat example

---

Assets/Mirror/Runtime/NetworkManager.cs

Made loadingSceneAsync public

---

Assets/Mirror/Runtime/NetworkIdentity.cs

fix #1346
Broken in PR #1206
alternative to #1351

fix: destroy owned objects

---

.releaserc.yml

semantic release changed recently. 
This PR should finally fix adding a .unitypackage file in github

fix: release unitypackage

---

Assets/Mirror/Runtime/NetworkManager.cs

Call OnClientConnect in FinishLoadScene

---

doc/Guides/DedicatedServer/AWS/index.md

Forgot a %20 in the last picture. it didn't show. Is fixed

docs: fix last picture in AWS

---

Assets/Mirror/Examples/AdditiveScenes/Prefabs/Capsule.prefab
Assets/Mirror/Examples/AdditiveScenes/Prefabs/Cube.prefab
Assets/Mirror/Examples/AdditiveScenes/Prefabs/Cylinder.prefab
Assets/Mirror/Examples/AdditiveScenes/Prefabs/Player.prefab
Assets/Mirror/Examples/AdditiveScenes/Prefabs/Sphere.prefab
Assets/Mirror/Examples/AdditiveScenes/Prefabs/Tank.prefab
Assets/Mirror/Examples/AdditiveScenes/Scenes/MainScene.unity
Assets/Mirror/Examples/AdditiveScenes/Scenes/SubScene.unity
Assets/Mirror/Examples/Basic/Prefabs/Player.prefab
Assets/Mirror/Examples/Chat/Prefabs/Player.prefab
Assets/Mirror/Examples/Pong/Prefabs/Ball.prefab
Assets/Mirror/Examples/Pong/Prefabs/Racket.prefab
Assets/Mirror/Examples/Pong/Scenes/Scene.unity
Assets/Mirror/Examples/Room/Prefabs/GamePlayer.prefab
Assets/Mirror/Examples/Room/Prefabs/RoomPlayer.prefab
Assets/Mirror/Examples/Room/Scenes/OfflineScene.unity
Assets/Mirror/Examples/Tanks/Prefabs/Projectile.prefab
Assets/Mirror/Examples/Tanks/Prefabs/Tank.prefab

Opened and saved all example prefabs and scenes to catch them up to master changes

Update Example Prefabs & Scenes to Master

---

Assets/Mirror/Runtime/NetworkConnection.cs

make it private,  
readonly does not prevent modifying the set.  This set is not safe to modify outside of this class

fix: it is not safe to modify this outside this class

---

Assets/Mirror/Runtime/NetworkClient.cs

Definitely not safe to use this dictionary outside of this class.

refactor: this should not be accessible

---

Assets/Mirror/Components/NetworkAnimator.cs

fix: Check clientAuthority in NetworkAnimator

---

Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs

Weaver generated code before: (see OnDeserialize initialState case!)
```csharp
public class Test : NetworkBehaviour
{
[SyncVar(hook = "OnSetA")]
public int a;
[SyncVar(hook = "OnSetC")]
public int c;
[SyncVar(hook = "OnSetQ")]
public GameObject q;
[SyncVar(hook = "OnSetR")]
public GameObject r;
private uint ___qNetId;
private uint ___rNetId;
public int Networka
{
get
{
return a;
}
[param: In]
set
{
if (!SyncVarEqual(value, ref a))
{
if (NetworkServer.localClientActive && !getSyncVarHookGuard(1uL))
{
setSyncVarHookGuard(1uL, value: true);
OnSetA(value);
setSyncVarHookGuard(1uL, value: false);
}
SetSyncVar(value, ref a, 1uL);
}
}
}
public int Networkc
{
get
{
return c;
}
[param: In]
set
{
if (!SyncVarEqual(value, ref c))
{
if (NetworkServer.localClientActive && !getSyncVarHookGuard(2uL))
{ …
```

fix: #1278 - only call initial state SyncVar hooks on clients if the SyncVar value is different from the default one.

---

Assets/Mirror/Components/NetworkAnimator.cs

feat: Add ResetTrigger to Network Animator

---

Assets/Mirror/Components/NetworkAnimator.cs
doc/General/ChangeLog.md

Added per @paulpach 's request.

feat: NetworkAnimator warns if you use it incorrectly

---

Assets/Mirror/Runtime/NetworkServer.cs

same as NetworkClient in #1388

Network server handlers private

---

Assets/Mirror/Components/NetworkTransformBase.cs
Assets/Mirror/Components/NetworkTransformChild.cs

Rearranged to make them more organized in the inspector
Before
After

Reordered NetworkTransform Fields w/ Headers

---

Assets/Mirror/Components/NetworkRoomManager.cs

The room player properties were changed but this flag was not.

fix: Set AllPlayersready false in the Room scene

---

Assets/Mirror/Components/NetworkRoomManager.cs
Assets/Mirror/Components/NetworkRoomPlayer.cs

Room slots were not being updated on clients when they should have been.

fix: Fix Room Slots for clients

---

doc/Guides/Communications/NetworkBehavior.md

Corrected information in video tutorial with a new release. Link updated to new video.

Updated video tutorial link.

---

Assets/Mirror/Runtime/NetworkIdentity.cs

Also added missing summary comments

fix: Fix GetSceneIdenity name typo

---

Assets/Mirror/Components/NetworkSceneChecker.cs

Not sure why I left it private, honestly.  Being able to query the hashtable for a given scene would certainly be handy.

Make the Dictionary public

---

Assets/Mirror/Components/Discovery/NetworkDiscoveryBase.cs
Assets/Mirror/Components/NetworkAnimator.cs
Assets/Mirror/Components/NetworkTransformBase.cs
Assets/Mirror/Runtime/ClientScene.cs
Assets/Mirror/Runtime/MessagePacker.cs
Assets/Mirror/Runtime/NetworkConnection.cs
Assets/Mirror/Runtime/NetworkReader.cs
Assets/Mirror/Runtime/NetworkReaderPool.cs
Assets/Mirror/Runtime/NetworkReaderPool.cs.meta
Assets/Mirror/Runtime/NetworkServer.cs

Tested with Additive example and uMMORPG 
Logging showed the pool never got above 4 deep.

feat: Implemented NetworkReaderPool

---

Assets/Mirror/Runtime/ClientScene.cs
Assets/Mirror/Runtime/NetworkIdentity.cs

Test component added to tank from examples:
```csharp
using Mirror;
using UnityEngine;
public class Flags : NetworkBehaviour
{
public override void OnStartLocalPlayer()
{
Debug.LogWarning("OnStartLocalPlayer: local=" + isLocalPlayer + " client=" + isClient + " server=" + isServer);
}
public override void OnStartClient()
{
Debug.LogWarning("OnStartClient: local=" + isLocalPlayer + " client=" + isClient + " server=" + isServer);
}
public override void OnStartServer()
{
Debug.LogWarning("OnStartServer: local=" + isLocalPlayer + " client=" + isClient + " server=" + isServer);
}
void Start()
{
Debug.LogWarning("Start: local=" + isLocalPlayer + " client=" + isClient + " server=" + isServer);
}
void OnDestroy()
{
Debug.LogWarning("OnDestroy: local=" + isLocalPlayer + " client=" + isClient + " …
```

fix #1475: isClient is true in OnDestroy on host/client mode again. Reverts commit d00c95bb55eedceb4f0811de54604c960c9352fe

---

Assets/Mirror/Components/Discovery/NetworkDiscovery.cs
Assets/Mirror/Components/Discovery/NetworkDiscoveryBase.cs

headless server needs go straight into AdvertiseServer

feat: Add headless check to Discovery

---

Assets/Mirror/Components/NetworkTransformBase.cs

Added check of `clientAuthority`

feat: Check for client authority in CmdClientToServerSync

---

Assets/Mirror/Components/NetworkAnimator.cs

Added check for clientAuthority in Cmd's, same as #1500

feat: Check for client authority in NetworkAnimator Cmd's

---

Assets/Mirror/Runtime/NetworkManager.cs

Added headers, tooltips, region block, and moved a couple fields.
Before
After

feat: Cosmetic Enhancement of Network Manager

---

Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
Assets/Mirror/Editor/Weaver/Weaver.cs

The weaver generated code now builds properly under IL2CPP
fixes #1519
fixes #1520

fix: build in IL2CPP

---

.github/workflows/main.yml

Tests are executed with every commit.
Coverage is uploaded to sonarqube

ci: Run tests with every commit

---

Assets/Mirror/Tests/Editor/MessageTests.cs

code is set to depreciate but should still be covered until then.

adds missing addplayertest

---

Assets/Mirror/Tests/Editor/NetworkManagerTest.cs
Assets/Mirror/Tests/Editor/NetworkManagerTest.cs.meta

not complete and 1 does not reliably work

test add NetworkManagerTests

---

Assets/Mirror/Editor/NetworkBehaviourInspector.cs
Assets/Mirror/Editor/SyncVarAttributeDrawer.cs
Assets/Mirror/Editor/SyncVarAttributeDrawer.cs.meta
Assets/Mirror/Runtime/CustomAttributes.cs

This fixing position of label with HeaderAttribute
This will also make sure that label is shown for all visable fields
Fixes #1548

fix: #1548 Adding PropertyDrawer for SyncVar

---

Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/SyncVarProcessor.cs
Assets/Mirror/Tests/Editor/SyncVarVirtualTest.cs
Assets/Mirror/Tests/Editor/SyncVarVirtualTest.cs.meta

tests for https://github.com/vis2k/Mirror/issues/1581
Not sure if weaver, mono or c# causes this issue

fix: overriden hooks are invoked (fixes #1581)

---

Assets/Mirror/Tests/Runtime/NetworkManagerTests.cs
Assets/Mirror/Tests/Runtime/NetworkManagerTests.cs.meta

unit tests for https://github.com/vis2k/Mirror/pull/1576

Test for is active scene

---

Assets/Mirror/Editor/NetworkInformationPreview.cs

see https://github.com/vis2k/Mirror/pull/1619

fix: MissingReferenceException

---

Assets/Mirror/Runtime/NetworkReader.cs
Assets/Mirror/Runtime/NetworkReaderPool.cs
Assets/Mirror/Tests/Editor/NetworkReaderPoolTest.cs
Assets/Mirror/Tests/Editor/NetworkReaderPoolTest.cs.meta

Replacing stack with array for NetworkReaderPool

perf: faster NetworkReader pooling

---

.editorconfig

Code rule as discussed on discord

editor config

---

Assets/Mirror/Editor/NetworkBehaviourInspector.cs
Assets/Mirror/Editor/Weaver/Processors/CommandProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/MethodProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/MonoBehaviourProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/SyncVarProcessor.cs
Assets/Mirror/Editor/Weaver/Writers.cs
Assets/Mirror/Runtime/NetworkWriter.cs
Assets/Mirror/Runtime/Transport/Websocket/WebsocketTransport.cs
Assets/Mirror/Tests/Editor/MessagePackerTest.cs
Assets/Mirror/Tests/Editor/MessageTests.cs
Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
Assets/Mirror/Tests/Editor/NetworkTransformChildTest.cs
Assets/Mirror/Tests/Editor/NetworkWriterPoolTest.cs
Assets/Mirror/Tests/Editor/SyncVarVirtualTest.cs
Assets/Mirror/Tests/Editor/WeaverTest.cs

Running code cleanup to fix whitespace

formatting

---

Assets/Mirror/Runtime/Transport/Telepathy/Server.cs
Assets/Mirror/Tests/Common/MemoryTransport.cs
Assets/Mirror/Tests/Editor/NetworkBehaviourTests.cs
Assets/Mirror/Tests/Editor/NetworkClientTests.cs
Assets/Mirror/Tests/Editor/NetworkManagerTest.cs
Assets/Mirror/Tests/Editor/NetworkServerTest.cs

More white space cleanup, not sure why these were missed the first time

more formatting

---

Assets/Mirror/Runtime/NetworkIdentity.cs
Assets/Mirror/Runtime/NetworkManager.cs
Assets/Mirror/Runtime/NetworkWriter.cs
Assets/Mirror/Runtime/Transport/Websocket/Ninja.WebSockets/Internal/Events.cs
Assets/Mirror/Runtime/Transport/Websocket/Server.cs
Assets/Mirror/Tests/Editor/SyncVarVirtualTest.cs

Applying rules from .editorconfig

removing unnecessary this

---

Assets/Mirror/Runtime/Transport/Websocket/Ninja.WebSockets/Internal/WebSocketImplementation.cs
Assets/Mirror/Tests/Editor/FallbackTransportTest.cs

Applying rules from .editorconfig

explicit type preference

---

Assets/Mirror/Runtime/LocalConnections.cs
Assets/Mirror/Tests/Editor/LocalConnectionBufferTest.cs
Assets/Mirror/Tests/Editor/LocalConnectionBufferTest.cs.meta

I will clean up the code if testing goes well.

perf: Adding buffer for local connection

---

Assets/Mirror/Runtime/AssemblyInfo.cs
Assets/Mirror/Tests/Performance.meta
Assets/Mirror/Tests/Performance/Editor.meta
Assets/Mirror/Tests/Performance/Editor/Mirror.Tests.Performance.asmdef
Assets/Mirror/Tests/Performance/Editor/Mirror.Tests.Performance.asmdef.meta
Assets/Mirror/Tests/Performance/Runtime.meta
Assets/Mirror/Tests/Performance/Runtime/Mirror.Tests.Performance.Runtime.asmdef
Assets/Mirror/Tests/Performance/Runtime/Mirror.Tests.Performance.Runtime.asmdef.meta

Creating folders and asmdef for performance tests

adding performance test asmdef

---

Assets/Mirror/Runtime/AssemblyInfo.cs
Assets/Mirror/Tests/Performance.meta
Assets/Mirror/Tests/Performance/Editor.meta
Assets/Mirror/Tests/Performance/Editor/Mirror.Tests.Performance.asmdef
Assets/Mirror/Tests/Performance/Editor/Mirror.Tests.Performance.asmdef.meta
Assets/Mirror/Tests/Performance/Editor/NetworkWriterPerformance.cs
Assets/Mirror/Tests/Performance/Editor/NetworkWriterPerformance.cs.meta
Assets/Mirror/Tests/Performance/Runtime.meta
Assets/Mirror/Tests/Performance/Runtime/Mirror.Tests.Performance.Runtime.asmdef
Assets/Mirror/Tests/Performance/Runtime/Mirror.Tests.Performance.Runtime.asmdef.meta

requires https://github.com/vis2k/Mirror/pull/1646

performance test for NetworkWriter

---

Assets/Mirror/Runtime/AssemblyInfo.cs
Assets/Mirror/Tests/Performance.meta
Assets/Mirror/Tests/Performance/Editor.meta
Assets/Mirror/Tests/Performance/Editor/Mirror.Tests.Performance.asmdef
Assets/Mirror/Tests/Performance/Editor/Mirror.Tests.Performance.asmdef.meta
Assets/Mirror/Tests/Performance/Runtime.meta
Assets/Mirror/Tests/Performance/Runtime/Mirror.Tests.Performance.Runtime.asmdef
Assets/Mirror/Tests/Performance/Runtime/Mirror.Tests.Performance.Runtime.asmdef.meta
Assets/Mirror/Tests/Performance/Runtime/ULocalConnectionPerformance.cs
Assets/Mirror/Tests/Performance/Runtime/ULocalConnectionPerformance.cs.meta

requires https://github.com/vis2k/Mirror/pull/1646

performance test for ULocalConnection

---

Packages/manifest.json

fix: Remove Junk Packages

---

Assets/Mirror/Examples/Benchmarks/10k/Scripts/BenchmarkNetworkManager.cs
Assets/Mirror/Examples/Benchmarks/10k/Scripts/BenchmarkNetworkManager.cs.meta
Assets/Mirror/Tests/Performance/Runtime/BenchmarkPerformance.cs
Assets/Mirror/Tests/Performance/Runtime/BenchmarkPerformance.cs.meta
Assets/Mirror/Tests/Performance/Runtime/Mirror.Tests.Performance.Runtime.asmdef

Performance test that automatically runs benchmark scene for 120 frames.

Benchmark performance test

---

Assets/Mirror/Runtime/NetworkBehaviour.cs

This should users from being able to drag and drop NetworkBehaviour onto GameObjects.

Making NetworkBehaviour abstract 

---

Assets/Mirror/Tests/Performance/README.md
Assets/Mirror/Tests/Performance/README.md.meta

Adding a readme for people who copy the test folder without the manifest.json

Adding readme for performance tests

---

Assets/Mirror/Examples/Benchmarks/10k/Scripts/Health.cs
Assets/Mirror/Tests/Performance/Runtime/BenchmarkPerformance.cs

Adding to https://github.com/vis2k/Mirror/pull/1661
Adding option to test idle network objects.

Benchmark performance test 2 - Idle benchmark

---

Assets/Mirror/Runtime/LocalConnections.cs
Assets/Mirror/Runtime/NetworkWriter.cs
Assets/Mirror/Runtime/NetworkWriterPool.cs
Assets/Mirror/Tests/Editor/NetworkWriterTest.cs

Moving branch to mirror so tests run
see https://github.com/vis2k/Mirror/pull/1673

perf: Increasing Network Writer performance

---

Assets/Mirror/Editor/LogLevelWindow.cs
Assets/Mirror/Editor/LogLevelWindow.cs.meta
Assets/Mirror/Runtime/AssemblyInfo.cs
Assets/Mirror/Runtime/LogFactory.cs

Example window for https://github.com/vis2k/Mirror/pull/1611
Can be improved with features as we use the logging api more

Logger editor

---

Assets/Mirror/Tests/Performance/Runtime/BenchmarkPerformance.cs

Taking measurements for frames and lateupdate at same time.

Improving Performance Benchmark

---

Assets/Mirror/Runtime/NetworkManagerHUD.cs

Reduces the complexity of OnGUI but also makes no logic changes. Reduces the code smell count and also makes it easier to test.

smell: reduce OnGUI complexity

---

Assets/Mirror/Tests/Performance/Editor/NetworkIdentityPerformance.cs
Assets/Mirror/Tests/Performance/Editor/NetworkIdentityPerformance.cs.meta

Performance test to measure https://github.com/vis2k/Mirror/pull/1702

NetworkIdentity ServerUpdate performance test

---

Assets/Mirror/Runtime/NetworkManager.cs

docs: remove mention of networkPort from NetworkManager

---

Assets/Mirror/Runtime/SyncList.cs
Assets/Mirror/Tests/Editor/SyncListTest.cs

Adds SyncList.Find and SyncList.FindAll requested in #1710

feat: Added SyncList.Find and SyncList.FindAll

---

Assets/Mirror/Tests/Performance/Editor/NetworkIdentityPerformanceWithMultipleBehaviour.cs
Assets/Mirror/Tests/Performance/Editor/NetworkIdentityPerformanceWithMultipleBehaviour.cs.meta

Same as [NetworkIdentityPerformance](https://github.com/vis2k/Mirror/blob/6e081f3d40e6a024b572078d936b5c923bf03fe5/Assets/Mirror/Tests/Performance/Editor/NetworkIdentityPerformance.cs
) but with an array of Health

adding extra performance test for NetworkIdentity

---

Assets/Mirror/Editor/Weaver/Readers.cs

These checks are already in writer, forgot to add them to reader as well.

adding checks to weaver reader

---

Assets/Mirror/Tests/Editor/SyncDictionaryTest.cs
Assets/Mirror/Tests/Editor/SyncListTest.cs
Assets/Mirror/Tests/Editor/SyncSetTest.cs

Requires https://github.com/vis2k/Mirror/pull/1744
Cleaning up tests to use Setup

Clean up sync object tests

---

Assets/Mirror/Tests/Editor/NetworkServerTest.cs

this code is depreciated but it should have a test as long as its in the code base

add test for NS Reset

---

Assets/Mirror/Editor/Weaver/Processors/GenericArgumentResolver.cs
Assets/Mirror/Editor/Weaver/Processors/GenericArgumentResolver.cs.meta
Assets/Mirror/Editor/Weaver/Processors/SyncDictionaryProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/SyncListProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/SyncObjectInitializer.cs
Assets/Mirror/Editor/Weaver/Processors/SyncObjectProcessor.cs
Assets/Mirror/Editor/Weaver/Weaver.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncList.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncListByteValid.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncListErrorForGenericStruct.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncListErrorForGenericStructWithCustomDeserializeOnly.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncListErrorForGenericStructWithCustomSerializeOnly.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncListGenericAbstractInheritance.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncListGenericInheritance.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncListGenericInheritanceWithMultipleGeneric.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncListGenericStructWithCustomMethods.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncListInheritance.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncListMissingParamlessCtor.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncListMissingParamlessCtorManuallyInitialized.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncListNestedInAbstractClass.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncListNestedInAbstractClassWithInvalid.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncListNestedInStruct.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncListNestedInStructWithInvalid.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncListNestedStruct.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncListStruct.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncListStructWithCustomDeserializeOnly.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncListStructWithCustomMethods.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncListStructWithCustomSerializeOnly.cs

fix: https://github.com/vis2k/Mirror/issues/1657
This PR also has new passing tests for most uses of sync list

feat: Allowing extra base types to be used for SyncLists and other SyncObjects

---

Assets/Mirror/Tests/Editor/NetworkManagerTest.cs

Test failed in another PR because Telepathy gave NullReferenceException

using MemoryTransport to make test more stable

---

Assets/Mirror/Runtime/NetworkIdentity.cs
Assets/Mirror/Runtime/NetworkServer.cs
Assets/Mirror/Tests/Runtime/SceneObjectSpawningTests.cs
Assets/Mirror/Tests/Runtime/SceneObjectSpawningTests.cs.meta
Assets/Mirror/Tests/Runtime/Scenes.meta
Assets/Mirror/Tests/Runtime/Scenes/SceneObjectSpawningTestsScene.unity
Assets/Mirror/Tests/Runtime/Scenes/SceneObjectSpawningTestsScene.unity.meta
Assets/Mirror/Tests/Runtime/Scenes/TestNetworkManager.prefab
Assets/Mirror/Tests/Runtime/Scenes/TestNetworkManager.prefab.meta
Assets/Mirror/Tests/Runtime/Scenes/TestPlayer.prefab
Assets/Mirror/Tests/Runtime/Scenes/TestPlayer.prefab.meta

fixes https://github.com/vis2k/Mirror/issues/1612

feat: Allowing Multiple Concurrent Additive Scenes

---

Assets/Mirror/Runtime/NetworkBehaviour.cs

I believe it should say client instead of server for the connectionToServer summary

Fix summary mistake for connectionToServer

---

Assets/Mirror/Runtime/ClientScene.cs
Assets/Mirror/Tests/Editor/ClientSceneTests.cs

Tests and updating error messages
tests should pass once https://github.com/vis2k/Mirror/pull/1805 is merged

Tests client scene 5

---

Assets/Mirror/Runtime/ClientScene.cs
Assets/Mirror/Tests/Editor/ClientSceneTests.cs
Assets/Mirror/Tests/Editor/TestPrefabs/PrefabWithChildrenForClientScene.prefab
Assets/Mirror/Tests/Editor/TestPrefabs/PrefabWithChildrenForClientScene.prefab.meta

* Tests for ClientScene.RegisterPrefab
* Improved error messages for ClientScene.RegisterPrefab

fix: Improved error checking for ClientScene.RegisterPrefab

---

Assets/Mirror/Runtime/ClientScene.cs
Assets/Mirror/Tests/Editor/ClientSceneTests.cs

needs https://github.com/vis2k/Mirror/pull/1827 for tests to pass
requires: https://github.com/vis2k/Mirror/pull/1823

fix: Adding warning when adding prefab with RegisterPrefab if assetid already exists 

---

Assets/Mirror/Tests/Editor/ClientSceneTests.cs

Ignoring this test till we know how to fix it, see https://github.com/vis2k/Mirror/issues/1831

adding ignore

---

Assets/Mirror/Runtime/ClientScene.cs

No code changes, will merge once tests pass

Fixing code smell in clientscene

---

Assets/Mirror/Runtime/ClientScene.cs

Fixes code smell
[Code Smell 1](https://sonarcloud.io/project/issues?id=vis2k_Mirror&issues=AXCWrTUN-74HeFXg_ZZw&open=AXCWrTUN-74HeFXg_ZZw)
[Code Smell 2](https://sonarcloud.io/project/issues?id=vis2k_Mirror&issues=AXCWrTUN-74HeFXg_ZZy&open=AXCWrTUN-74HeFXg_ZZy)

Making public dictionaries in ClientScene readonly

---

Assets/Mirror/Editor/Weaver/Processors/GenericArgumentResolver.cs
Assets/Mirror/Tests/Editor/ClientSceneTestsBase.cs
Assets/Mirror/Tests/Editor/ClientSceneTests_PrepareToSpawnSceneObjects.cs
Assets/Mirror/Tests/Runtime/ClientSceneTests_DestroyAllClientObjects.cs

Cleaning up some code

---

Assets/Mirror/Tests/Runtime/SceneObjectSpawningTests.cs

adding namespace and whitespace to test

---

Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs

Clearing dictionary in test teardown

---

Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/PhysicsCollision.cs
Assets/Mirror/Runtime/LocalConnections.cs
Assets/Mirror/Runtime/NetworkConnection.cs
Assets/Mirror/Runtime/NetworkServer.cs

Creating LocalConnectionId constant

---

Assets/Mirror/Authenticators/BasicAuthenticator.cs
Assets/Mirror/Authenticators/TimeoutAuthenticator.cs
Assets/Mirror/Components/NetworkAnimator.cs
Assets/Mirror/Components/NetworkRoomManager.cs
Assets/Mirror/Components/NetworkRoomPlayer.cs
Assets/Mirror/Components/NetworkSceneChecker.cs
Assets/Mirror/Examples/AdditiveScenes/Scripts/AdditiveNetworkManager.cs
Assets/Mirror/Examples/AdditiveScenes/Scripts/ZoneHandler.cs
Assets/Mirror/Examples/Chat/Scripts/ChatWindow.cs
Assets/Mirror/Examples/ListServer/ListServer.cs
Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/Reward.cs
Assets/Mirror/Examples/Room/Scripts/NetworkRoomPlayerExt.cs
Assets/Mirror/Examples/Room/Scripts/Reward.cs
Assets/Mirror/Runtime/ClientScene.cs
Assets/Mirror/Runtime/LocalConnections.cs
Assets/Mirror/Runtime/MessagePacker.cs
Assets/Mirror/Runtime/NetworkBehaviour.cs
Assets/Mirror/Runtime/NetworkManager.cs
Assets/Mirror/Runtime/NetworkManagerHUD.cs
Assets/Mirror/Runtime/NetworkReader.cs
Assets/Mirror/Runtime/NetworkReaderPool.cs
Assets/Mirror/Runtime/NetworkServer.cs
Assets/Mirror/Runtime/NetworkTime.cs
Assets/Mirror/Runtime/NetworkWriter.cs
Assets/Mirror/Runtime/NetworkWriterPool.cs

have not updated all of the debugs in the classes yet as the logger implementation has still not been decided.

add logger to all classes that have logging but no logger

---

Assets/Mirror/Runtime/SyncList.cs
Assets/Mirror/Tests/Editor/SyncListTest.cs

Added SyncList.AddRange as suggested by @MrGadget1024  (and SyncList.InsertRange because why not)

feat: added SyncList.AddRange and InsertRange

---

Assets/Mirror/Runtime/SyncList.cs
Assets/Mirror/Tests/Editor/SyncListTest.cs

Adds List.RemoveAll functionality to SyncList.

feat: add SyncList.RemoveAll

---

Assets/Mirror/Runtime/NetworkReaderPool.cs
Assets/Mirror/Runtime/NetworkWriterPool.cs

These warning only used to be enabled when debugfilter was true

Setting default log level to error

---

Assets/Mirror/Runtime/Logging/LogFactory.cs

Example of use 
```csharp
Mirror.LogFactory.ReplaceLogHandler(new OverrideMirrorLogger());
```
Can help with https://github.com/vis2k/Mirror/issues/1866

feat: Creating method to replace all log handlers

---

doc/Guides/Attributes.md
doc/Guides/NetworkBehaviour.md

Improving docs 1

---

Assets/Mirror/Tests/Editor/SyncListClassTest.cs
Assets/Mirror/Tests/Editor/SyncListClassTest.cs.meta
Assets/Mirror/Tests/Editor/SyncListTest.cs

Adding test to try find problem that supporter was having

Adding tests and clean up logs

---

Assets/Mirror/Runtime/Logging/LogFactory.cs
Assets/Mirror/Runtime/Logging/LogSettings.cs

Puts the entries in alphabetical order
When first entering play mode:
Starting as Host:

feat: Use SortedDictionary for LogSettings

---

Assets/Mirror/Tests/Editor/SyncVarHookTest.cs
Assets/Mirror/Tests/Editor/Weaver/.WeaverTests.csproj
Assets/Mirror/Tests/Editor/Weaver/WeaverSyncVarHookTests.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverSyncVarHookTests~/FindsStaticHook.cs

requires https://github.com/vis2k/Mirror/pull/1910 for tests to pass

Tests for static syncvar hooks

---

Assets/Mirror/Editor/Weaver/Processors/CommandProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/MessageClassProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/RpcProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/SyncEventProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/SyncObjectInitializer.cs
Assets/Mirror/Editor/Weaver/Processors/SyncObjectProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/SyncVarProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/TargetRpcProcessor.cs

No code changes, should just be renaming ILProcessor variables

Renaming all ILProcessor to be called worker

---

Assets/Mirror/Runtime/NetworkConnection.cs

Moving ` lastMessageTime = Time.time;` so it is called in both constructors

moving lastMessageTime to other constructor

---

Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
Assets/Mirror/Editor/Weaver/Readers.cs
Assets/Mirror/Editor/Weaver/Weaver.cs
Assets/Mirror/Examples/Benchmarks/2k NetworkTransforms/Scripts/MonsterMovement.cs
Assets/Mirror/Examples/Benchmarks/2k NetworkTransforms/Scripts/PlayerMovement.cs
Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/MultiSceneNetManager.cs
Assets/Mirror/Examples/Room/Scripts/Reward.cs
Assets/Mirror/Examples/Tanks/Scripts/Projectile.cs
Assets/Mirror/Examples/Tanks/Scripts/Tank.cs
Assets/Mirror/Examples/Tanks/Scripts/TankGameManager.cs
Assets/Mirror/Runtime/Logging/LogFactory.cs
Assets/Mirror/Tests/Editor/LogFactoryTests.cs
Assets/Mirror/Tests/Editor/SyncVarHookTest.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverClientServerAttributeTests.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverMessageTests.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverNetworkBehaviourTests.cs

* fixing white space
* sorting using statements

Clean up scripts

---

Assets/Mirror/Editor/Weaver/Processors/CommandProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/RpcProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/TargetRpcProcessor.cs

Refactoring used in https://github.com/vis2k/Mirror/pull/1932
* Using Enum instead of checking type of attribute
* Moving code inside foreach loop to its own function

adding RemoteCallType

---

Assets/Mirror/Editor/Weaver/Processors/CommandProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/RpcProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/SyncEventProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/TargetRpcProcessor.cs

Refactoring used in https://github.com/vis2k/Mirror/pull/1932
* Renaming function so that WriteArguments and ReadArguments match
* Adding more comments to explain what is created

 renaming function

---

Assets/Mirror/Editor/Weaver/Extensions.cs

extra methods used in https://github.com/vis2k/Mirror/pull/1932

adding extension methods

---

Assets/Mirror/Editor/Weaver/Resolvers.cs

Logging method name when it could not be found

adding better error message for ResolveMethod

---

Assets/Mirror/Components/Experimental.meta
Assets/Mirror/Components/Experimental/NetworkTransform.cs
Assets/Mirror/Components/Experimental/NetworkTransform.cs.meta
Assets/Mirror/Components/Experimental/NetworkTransformBase.cs
Assets/Mirror/Components/Experimental/NetworkTransformBase.cs.meta
Assets/Mirror/Components/Experimental/NetworkTransformChild.cs
Assets/Mirror/Components/Experimental/NetworkTransformChild.cs.meta

Alternative to #1810 with just the new component in final form for merging without all the changes to examples that were done for testing.  I want to keep the other PR open for convenient refinement.
The aesthetics can be improved over time, but I want to get it into users' hands to start working with it.

feat: Experimental Network Transform

---

Assets/Mirror/Runtime/Transport/Websocket/Client.cs
Assets/Mirror/Runtime/Transport/Websocket/ClientJs.cs
Assets/Mirror/Runtime/Transport/Websocket/Server.cs
Assets/Mirror/Runtime/Transport/Websocket/WebsocketTransport.cs

Fixes #1991 
Fixes #1679 
Fixes #1826

fix: Websockets Transport now handles being disabled for scene changes

---

Assets/Mirror/Runtime/NetworkServer.cs

no code changes, will merge once tests pass

Moving spawn functions so they are all next to each other in NetworkServer

---

doc/Components/Authenticators/index.md

Fixed small typo

---

Assets/Mirror/Examples/Tanks/Scenes/Scene.unity

I goofed and built it in 2019 which broke the serialization. Rebuilt in 2018.3.6.

fixes broken ui for Tanks example

---

Assets/Mirror/Runtime/Transport/Websocket/Client.cs
Assets/Mirror/Runtime/Transport/Websocket/Server.cs

- adding if before starting task
- adding await inside loop
fixes: https://github.com/vis2k/Mirror/issues/2006
~~waiting for @Paradoks-Studio to test in his full build later tonight~~

fix: fixing lag in websockets

---

Assets/Mirror/Editor/Weaver/Weaver.cs

this will help error be more useful

rethrow error with stack

---

Assets/Mirror/Components/NetworkAnimator.cs

Making sure that trigger is called on the server

fix: triggers will now be set when using server authority 

---

Assets/Mirror/Components/NetworkAnimator.cs

some functions don't need this check as the check is done before they are called
fixes https://github.com/vis2k/Mirror/issues/1884

fix: Checking animator.enabled before calls to animator

---

Assets/Mirror/Runtime/NetworkReader.cs
Assets/Mirror/Runtime/Transport/Transport.cs

resolves: https://github.com/vis2k/Mirror/issues/2028

Fixing warning messages

---

Assets/Mirror/Components/Experimental/NetworkRigidbody.cs
Assets/Mirror/Components/Experimental/NetworkRigidbody.cs.meta

NetworkRigidBody that I use for my game.
- Just syncs velocity and isKinematic from server to client.
- Still requires NetworkTransform to sync position
**I need to make some changes to it before to make it fit the generic use case,**
resolves https://github.com/vis2k/Mirror/issues/264

feat: Experimental NetworkRigidBody 

---

Assets/Mirror/Components/Experimental/NetworkRigidbody.cs

* fixing client auth sync
* using syncInterval for client auth
* only sync if greater than Sensitivity for server auth

fix: Network rigidbody fixes

---

Assets/Mirror/Runtime/Transport/FallbackTransport.cs
Assets/Mirror/Runtime/Transport/MultiplexTransport.cs
Assets/Mirror/Tests/Runtime/FallbackTransportEnableTest.cs
Assets/Mirror/Tests/Runtime/FallbackTransportEnableTest.cs.meta
Assets/Mirror/Tests/Runtime/Mirror.Tests.Runtime.asmdef

fixes : https://github.com/vis2k/Mirror/issues/2046

fix: Fallback and Multiplex now disable their transports when they are disabled 

---

Assets/Mirror/Components/NetworkAnimator.cs

fixes: https://github.com/vis2k/Mirror/issues/2011

fix: NetworkAnimator sending if syncInterval is greater or equal to 0

---

Assets/Mirror/Components/Experimental/NetworkRigidbody.cs

resolves: https://github.com/vis2k/Mirror/issues/2062

fix: adding clientAuthority to commands in NetworkRigidbody

---

Assets/Mirror/Editor/Weaver/Processors/MessageClassProcessor.cs
Assets/Mirror/Editor/Weaver/Weaver.cs
Assets/Mirror/Tests/Editor/MessageInheritanceTest.cs
Assets/Mirror/Tests/Editor/Weaver/.WeaverTests.csproj
Assets/Mirror/Tests/Editor/Weaver/WeaverMessageTests.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverMessageTests~/MessageWithBaseClass.cs

fixes: https://github.com/vis2k/Mirror/issues/1925

fix: Message base class not being Serialized if processed in the wrong order

---

Assets/Mirror/Cloud/ListServer/ListServerServerApi.cs

ping will only stop if can not get success from cloud for 5 mins

increasing max fails to 15, and ping interval to 20

---

Assets/Mirror/Editor/Weaver/Processors/PropertySiteProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/SyncEventProcessor.cs
Assets/Mirror/Editor/Weaver/Weaver.cs

 fix: renaming call/invoke prefix for SyncEvent

---

Assets/Mirror/Runtime/ClientScene.cs
Assets/Mirror/Runtime/NetworkIdentity.cs
Assets/Mirror/Tests/Editor/ClientSceneTests_RegisterPrefab.cs

fixes: https://github.com/vis2k/Mirror/issues/2047

fix: register prefab error with same guid

---

Assets/Mirror/Cloud/ListServer/ListServerJson.cs

changing to force https://github.com/vis2k/Mirror/pull/2108 to build

feat: Adding Custom Data and Custom Address fields to list server

---

Assets/Mirror/Runtime/Transport/Telepathy/Client.cs

Hello, I noticed some logging inconsistencies and missing reports in the Telepathy client.

Improve Telepathy debug messages

---

Assets/Mirror/Tests/Runtime/Scenes/TestNetworkManager.prefab

telepathy fails this test sometimes

using memory transport in test

---

Assets/Mirror/Runtime/NetworkIdentity.cs
Assets/Mirror/Runtime/NetworkServer.cs

Formatting doc comments.
Making Comments that are before functions into doc comments

Formatting doc comments 

---

Assets/Mirror/Components/NetworkAnimator.cs

Triggers should be handled right away on owner instead of waiting for Cmd and Rpc

fix: making triggers be called right away instead on owner

---

Assets/Mirror/Runtime/ClientScene.cs

see this for tests https://github.com/vis2k/Mirror/pull/2004

splitting on spawn into functions

---

Assets/Mirror/Tests/Common/ClientSceneTestsBase.cs
Assets/Mirror/Tests/Editor/ClientSceneTests_OnSpawn.cs
Assets/Mirror/Tests/Editor/ClientSceneTests_OnSpawn.cs.meta
Assets/Mirror/Tests/Editor/ClientSceneTests_PrepareToSpawnSceneObjects.cs

Making draft PR so I don't forget about this branch

Test for OnSpawn

---

Assets/Mirror/Editor/Weaver/Processors/CommandProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/MessageClassProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/MonoBehaviourProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/RpcProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/ServerClientAttributeProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/SyncDictionaryProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/SyncEventProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/SyncObjectInitializer.cs
Assets/Mirror/Editor/Weaver/Processors/SyncObjectProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/SyncVarProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/TargetRpcProcessor.cs
Assets/Mirror/Editor/Weaver/Readers.cs
Assets/Mirror/Editor/Weaver/Weaver.cs
Assets/Mirror/Editor/Weaver/WeaverTypes.cs
Assets/Mirror/Editor/Weaver/WeaverTypes.cs.meta
Assets/Mirror/Editor/Weaver/Writers.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverClientServerAttributeTests.cs

no functional changes.
just makes it cleaner, and reduces global state.
-> Weaver.cs is now only 384 LOC
-> WeaverTypes.cs has 237 LOC

Weaver types moved into WeaverTypes, and reduce some global state

---

Assets/Mirror/Tests/Runtime/NetworkIdentityTests.cs

test for https://github.com/vis2k/Mirror/pull/2101

adding test for NetworkServer.Destroy

---

Assets/Mirror/Runtime/NetworkServer.cs

if identity is not null then the game object is also not null

perf: removing 2nd null check

---

Assets/Mirror/Editor/Weaver/Weaver.cs
Assets/Mirror/Tests/Editor/Weaver/.WeaverTests.csproj
Assets/Mirror/Tests/Editor/Weaver/WeaverMessageTests.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverMessageTests~/MessageNestedInheritance.cs

fixes: https://github.com/vis2k/Mirror/issues/2143

fix: Nested messages

---

Assets/Mirror/Editor/Weaver/Processors/ServerClientAttributeProcessor.cs

fixes https://github.com/vis2k/Mirror/issues/2145
uses tests from https://github.com/vis2k/Mirror/pull/2149

fixing IL error when using floats

---

Assets/Mirror/Runtime/NetworkAuthenticator.cs
Assets/Mirror/Runtime/NetworkManager.cs

These functions should be removed until we have a need for them.

removing Internal functions that do nothing

---

Assets/Mirror/Components/Experimental/NetworkLerpRigidbody.cs
Assets/Mirror/Components/Experimental/NetworkLerpRigidbody.cs.meta

Uses Lerp to set position and velocity

feat: Adding alternative to NetworkRigidbody

---

Assets/Mirror/Editor/Weaver/Extensions.cs
Assets/Mirror/Editor/Weaver/Readers.cs
Assets/Mirror/Editor/Weaver/Writers.cs
Assets/Mirror/Tests/Editor/Weaver/.WeaverTests.csproj
Assets/Mirror/Tests/Editor/Weaver/GeneratedReaderWriter~/CreatesForArraySegment.cs
Assets/Mirror/Tests/Editor/Weaver/GeneratedReaderWriter~/CreatesForStructArraySegment.cs
Assets/Mirror/Tests/Editor/Weaver/GeneratedReaderWriter~/GivesErrorForInvalidArraySegmentType.cs
Assets/Mirror/Tests/Editor/Weaver/GeneratedReaderWriter~/GivesErrorForInvalidArrayType.cs
Assets/Mirror/Tests/Editor/Weaver/GeneratedReaderWriter~/GivesErrorForJaggedArray.cs
Assets/Mirror/Tests/Editor/Weaver/GeneratedReaderWriter~/GivesErrorForMultidimensionalArray.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverGeneratedReaderWriterTests.cs

Test for array segment and writers

---

Assets/Mirror/Editor/Weaver/Processors/MessageClassProcessor.cs
Assets/Mirror/Tests/Editor/MessageBaseTests.cs
Assets/Mirror/Tests/Editor/Weaver/.WeaverTests.csproj
Assets/Mirror/Tests/Editor/Weaver/WeaverMessageTests.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverMessageTests~/AbstractMessageMethods.cs

fixes: https://github.com/vis2k/Mirror/issues/2133

fix: weaver test for abstract methods

---

Assets/Mirror/Runtime/NetworkClient.cs
Assets/Mirror/Runtime/NetworkServer.cs
Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
Assets/Mirror/Tests/Editor/NetworkServerTest.cs
Regex for comment.txt
alt rigidbody.txt

this helps people who want to connect without using networkmanager
resolves: https://github.com/vis2k/Mirror/issues/2163

adding assert to make sure transport is set

---

Assets/Mirror/Editor/Weaver/Extensions.cs
Assets/Mirror/Editor/Weaver/Writers.cs

No code changes, just moving stuff around.

weaver: Moving stuff around in writer

---

doc/Guides/Serialization.md
doc/Guides/toc.yml

Needs proofreading before I merge it

docs: Adding guide about Serialization

---

Assets/Mirror/Editor/Weaver/Writers.cs

Requires https://github.com/vis2k/Mirror/pull/2170

weaver: splitting up GetWriteFunc function

---

Assets/Mirror/Editor/Weaver/Writers.cs

variable should start with lower case

fixing typo

---

Assets/Mirror/Tests/Editor/Weaver/WeaverGeneratedReaderWriterTests.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverNetworkBehaviourTests.cs

Reader code doesn't run on Rpc now if a valid writer can not be found
In future PR write and read functions should be generated together as they share most of the same checks

commenting out reader error checks

---

Assets/Mirror/Runtime/NetworkIdentity.cs

- using string interpolation for logs
- return early instead of if/else
will merge when tests pass

Refactoring handle remote call

---

Assets/Mirror/Runtime/ClientScene.cs
Assets/Mirror/Runtime/NetworkIdentity.cs
Assets/Mirror/Tests/Common/FakeNetworkConnection.cs
Assets/Mirror/Tests/Common/FakeNetworkConnection.cs.meta
Assets/Mirror/Tests/Editor/ClientSceneTests_OnSpawn.cs
Assets/Mirror/Tests/Runtime/ClientSceneTests_LocalPlayer.cs
Assets/Mirror/Tests/Runtime/ClientSceneTests_LocalPlayer.cs.meta

fixes: https://github.com/vis2k/Mirror/issues/2198

fix: ClientScene.localplayer is now set to null when it is destroyed

---

doc/docfx.json

Simplifying files list
`**/*.md` should apply to every file in every folder

updating docfx.json

---

Assets/Mirror/Editor/Weaver/Weaver.cs
Assets/Mirror/Editor/Weaver/WeaverTypes.cs

weaver is a bit faster since it does not need to load these huge assemblies with cecil

perf(weaver): No need to load mirror and unity assemblies

---

Assets/Mirror/Editor/Weaver/Readers.cs

don't repeat code to generate for loop.  Refactor the code into a method and reuse it.

refactor reader for loops

---

Assets/Mirror/Editor/Weaver/Readers.cs

Just deserialize the array and transform to array segment

Refactor reading array segment

---

Assets/Mirror/Cloud/README.md

Fixes some minor typos in the cloud README

docs: typos

---

Assets/Mirror/Components/NetworkTransformBase.cs

original: https://github.com/vis2k/Mirror/pull/2311
resolves: https://github.com/vis2k/Mirror/issues/2200

feat: NetworkTranform Teleport

---

Assets/Mirror/Examples/Tanks/Scripts/Tank.cs

simple fix found when testing.

fix: NRE when running in headless server only

---

Assets/Mirror/Runtime/NetworkBehaviour.cs

should be the same performance as #2325 without the complexity

perf: use built in == instead of unity one

---

Assets/Mirror/Components/Experimental/NetworkRigidbody2D.cs

* using angularVelocitySensitivity
* removing un-needed using
* using vec2 instead of vec3
* fixing line endings

small changes

---

Assets/Mirror/Runtime/NetworkIdentity.cs

using null propagation for RemoveOwnedObject

---

Assets/Mirror/Runtime/NetworkBehaviour.cs

Per Discord discussion with @paulpach  and @James-Frowen

Make SerializeSyncVars & DeserializeSyncVars protected virtual

---

Assets/Mirror/Runtime/NetworkBehaviour.cs
Assets/Mirror/Tests/Editor/NetworkBehaviourTests.cs
Assets/Mirror/Tests/Editor/RemoteTestBase.cs
Assets/Mirror/Tests/Editor/TargetRpcTest.cs

* now give error when connection is null
* updating error message to accurately explain what went wrong

fix: improving errors in SendTargetRPCInternal

---

Assets/Mirror/Components/NetworkTransformBase.cs
Assets/Mirror/Editor/Weaver/Processors/ReaderWriterProcessor.cs
Assets/Mirror/Editor/Weaver/Readers.cs
Assets/Mirror/Editor/Weaver/Writers.cs
Assets/Mirror/Examples/Benchmark/Scripts/BenchmarkNetworkManager.cs
Assets/Mirror/Examples/Tanks/Scripts/Tank.cs
Assets/Mirror/Runtime/NetworkIdentity.cs
Assets/Mirror/Runtime/NetworkManagerHUD.cs
Assets/Mirror/Runtime/NetworkReader.cs
Assets/Mirror/Runtime/NetworkWriter.cs
Assets/Mirror/Runtime/SyncDictionary.cs
Assets/Mirror/Runtime/SyncSet.cs
Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
Assets/Mirror/Tests/Editor/NetworkWriterTest.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverSyncDictionaryTests~/SyncDictionaryGenericStructKeyWithCustomMethods.cs

* removing un-needed using
* whitespace
* using explicit types
Will run again before merge after @MrGadget1024 has finished removing stuff

Running code clean up

---

Assets/Mirror/Authenticators/BasicAuthenticator.cs

No functional change, just organization and comments

Basic Authenticator code organization and comments

---

Assets/Mirror/Runtime/Transport/MiddlewareTransport.cs
Assets/Mirror/Runtime/Transport/MiddlewareTransport.cs.meta
Assets/Mirror/Runtime/Transport/Transport.cs

* Allows Middleware to be created at the transport layer
* Middleware can choice which methods they want to override and which to let inner handle

feat: Middleware transport

---

Assets/Mirror/Components/Experimental/NetworkTransformBase.cs

Having 1 long method is hard to see what is happening and went.

Splitting up Update method

---

Assets/Mirror/Runtime/Transport/MiddlewareTransport.cs
Assets/Mirror/Tests/Editor/MiddlewareTransportTest.cs
Assets/Mirror/Tests/Editor/MiddlewareTransportTest.cs.meta

Going to write tests for this then merge.

making sure MiddlewareTransport listens for inner events

---

doc/Articles/CommunityGuides/MirrorQuickStartGuide/index.md

I did not add Jame's adjustments to my local version, so some things may be mismatched.
This edit fixes one of those i found.
Also the activeWeaponSynced variable now needs to be 1 by default.
Edit:  I have also tested the quickstart with latest Mirror version, and a variety of transports, all is fine 👍

Adjustment to Community QuickStart Guide.

---

Assets/Mirror/Components/NetworkPingDisplay.cs

added methods to update internal parameters, added textPrefix and textSuffix so developers can add text before/after ping value

NetworkPingDisplay modularity

---

.releaserc.yml

Generate release notes for breaking:xxxx commits

Update release notes with breaking:xxxx comments

---

Assets/Mirror/Components/NetworkPingDisplay.cs

I've added this RTT boolean and a tooltip, might clear up some confusion for future users.
Many believe ping is time to server, not time and back.
Its in the OnGUI and not Awake, so it can be changed in real-time.
If code can be tidied up or tooltip re-worded, feel free to 👍

Round trip time bool and tooltip.

---

Assets/Mirror/Editor/Weaver/Readers.cs
Assets/Mirror/Editor/Weaver/Writers.cs

weaver removing unneeded ImportReference

---

Assets/Mirror/Runtime/NetworkConnection.cs

renaming reader

---

Assets/Mirror/Runtime/MessagePacker.cs
Assets/Mirror/Tests/Editor/CommandTest.cs

adding try/catch to handler so server doesn't crash from user exceptions

---

Assets/Mirror/Runtime/NetworkClient.cs

requires: https://github.com/vis2k/Mirror/pull/2442

Refactor add transport handlers 2

---

Assets/Mirror/Runtime/NetworkServer.cs

moving transport handler code to functions

---

Assets/Mirror/Runtime/MessagePacker.cs
Assets/Mirror/Runtime/NetworkConnection.cs
Assets/Mirror/Tests/Editor/MessagePackerTest.cs

Messages sent to mirror must be atleast 2 bytes for the message type, disconnect if invalid message

Checking buffer length is atleast 2

---

Assets/Mirror/Runtime/Transport/Transport.cs

docs(Transport): adding rules to remarks on transport

---

Assets/Mirror/Runtime/NetworkReader.cs

comments for ReadBlittable included in this PR

docs(NetworkReader): doc comments 

---

Assets/Mirror/Examples/AdditiveScenes/Scripts/RandomColor.cs
Assets/Mirror/Examples/Basic/Prefabs/Player.prefab
Assets/Mirror/Examples/Basic/Prefabs/PlayerUI.prefab
Assets/Mirror/Examples/Basic/Prefabs/PlayerUI.prefab.meta
Assets/Mirror/Examples/Basic/Scenes/Example.unity
Assets/Mirror/Examples/Basic/Scripts/BasicNetManager.cs
Assets/Mirror/Examples/Basic/Scripts/Player.cs
Assets/Mirror/Examples/Basic/Scripts/PlayerUI.cs
Assets/Mirror/Examples/Basic/Scripts/PlayerUI.cs.meta
Assets/Mirror/Examples/Room/Scripts/RandomColor.cs

- PlayerUI is now separated from player object
- PlayerUI is event driven from the Player object
- PlayerUI is locally instantiated, instead of networked
- PlayerUI now uses a grid layout for flexible arrangement
- added border to players panel
- players are renumbered when a client leaves

feat: Updated Basic Example 

---

Assets/Mirror/Editor/Weaver/Writers.cs

needed for https://github.com/vis2k/Mirror/pull/2478

weaver: making GenerateWriter return MethodReference

---

Assets/Mirror/Editor/Weaver/Readers.cs
Assets/Mirror/Editor/Weaver/WeaverTypes.cs
Assets/Mirror/Editor/Weaver/Writers.cs
Assets/Mirror/Runtime/NetworkReader.cs
Assets/Mirror/Runtime/NetworkWriter.cs
Assets/Mirror/Tests/Editor/NetworkWriterCollectionTest.cs
Assets/Mirror/Tests/Editor/NetworkWriterTest.cs
Assets/Mirror/Tests/Editor/RpcNetworkIdentityTest.cs
Assets/Mirror/Tests/Editor/RpcNetworkIdentityTest.cs.meta
Assets/Mirror/Tests/Editor/Weaver/.WeaverTests.csproj
Assets/Mirror/Tests/Editor/Weaver/WeaverClientRpcTests.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverClientRpcTests~/BehaviourCanBeSentInRpc.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverSyncVarTests.cs

Creating read/write functions for Networkbehaviours so that they can be sent in message and rpc.

feat: Allow Networkbehaviours to be sent in rpc

---

Assets/Mirror/Runtime/NetworkReaderPool.cs
Assets/Mirror/Runtime/NetworkWriterPool.cs

Per SonarCube suggestion, eliminates 2 code smells.

Make IDisposable classes sealed

---

Assets/Mirror/Runtime/Transport/FallbackTransport.cs
Assets/Mirror/Runtime/Transport/KCP/MirrorTransport/KcpTransport.cs
Assets/Mirror/Runtime/Transport/MiddlewareTransport.cs
Assets/Mirror/Runtime/Transport/MultiplexTransport.cs
Assets/Mirror/Runtime/Transport/SimpleWebTransport/SimpleWebTransport.cs
Assets/Mirror/Runtime/Transport/TelepathyTransport.cs

feat: DisallowMultipleComponent on all transports

---

Assets/Mirror/Editor/EditorHelper.cs
Assets/Mirror/Editor/EditorHelper.cs.meta
Assets/Mirror/Tests/Editor/Mirror.Tests.asmdef
Assets/Mirror/Tests/Editor/Weaver/WeaverAssembler.cs

This allows this function to be used by other scripts

Moving FindPath to editor scripts

---

doc/Articles/FAQ.md

Update faq page with a guide about changing transports.

Update FAQ with changing transport guide.

---

Assets/Mirror/Examples/Benchmark/Scenes/Scene.unity
Assets/Mirror/Runtime/LocalConnections.cs
Assets/Mirror/Runtime/NetworkConnection.cs
Assets/Mirror/Runtime/NetworkConnectionToClient.cs
Assets/Mirror/Runtime/NetworkManager.cs
Assets/Mirror/Runtime/NetworkServer.cs
Assets/Mirror/Runtime/Transport/KCP/MirrorTransport/KcpTransport.cs
Assets/Mirror/Runtime/Transport/Transport.cs
Assets/Mirror/Tests/Common/FakeNetworkConnection.cs
Assets/Mirror/Tests/Editor/NetworkConnectionToClientTests.cs
Assets/Mirror/Tests/Editor/NetworkConnectionToClientTests.cs.meta
Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
Assets/Mirror/Tests/Editor/NetworkMatchCheckerTest.cs
Assets/Mirror/Tests/Editor/NetworkServerTest.cs
Assets/Mirror/Tests/Performance/Editor/FakeNetworkConnection.cs
Assets/Mirror/Tests/Runtime/NetworkServerRuntimeTest.cs
Assets/Mirror/Tests/Runtime/NetworkServerWithHostRuntimeTest.cs

Batches message into Transport.GetMaxPacketSize sized chunks and sends them every Update or every batchInterval if batchInterval > 0
video: https://gyazo.com/d7606081cb47e2740a2338b5e1cd69e2
- needs ccu test
**benchmark**
Unity 2018.4 LTS, localhost, Macbook pro 2015
**latency**
as discussed in discord, this would increase latency due to how mirror currently does update timing.
the question is if it's worth it or not.

perf: Batching

---

.github/workflows/main.yml
Assets/ScriptTemplates.meta
Assets/ScriptTemplates/50-Mirror__Network Manager-NewNetworkManager.cs.txt
Assets/ScriptTemplates/50-Mirror__Network Manager-NewNetworkManager.cs.txt.meta
Assets/ScriptTemplates/51-Mirror__Network Authenticator-NewNetworkAuthenticator.cs.txt
Assets/ScriptTemplates/51-Mirror__Network Authenticator-NewNetworkAuthenticator.cs.txt.meta
Assets/ScriptTemplates/52-Mirror__Network Behaviour-NewNetworkBehaviour.cs.txt
Assets/ScriptTemplates/52-Mirror__Network Behaviour-NewNetworkBehaviour.cs.txt.meta
Assets/ScriptTemplates/53-Mirror__Network Observer-NewNetworkObserver.cs.txt
Assets/ScriptTemplates/53-Mirror__Network Observer-NewNetworkObserver.cs.txt.meta
Assets/ScriptTemplates/54-Mirror__Network Room Manager-NewNetworkRoomManager.cs.txt
Assets/ScriptTemplates/54-Mirror__Network Room Manager-NewNetworkRoomManager.cs.txt.meta
Assets/ScriptTemplates/55-Mirror__Network Room Player-NewNetworkRoomPlayer.cs.txt
Assets/ScriptTemplates/55-Mirror__Network Room Player-NewNetworkRoomPlayer.cs.txt.meta
Assets/ScriptTemplates/56-Mirror__Network Discovery-NewNetworkDiscovery.cs.txt
Assets/ScriptTemplates/56-Mirror__Network Discovery-NewNetworkDiscovery.cs.txt.meta

As discussed in Discord, adding ScriptTemplates back into the repo
- The folder must be included in Asset Store package
- Includes change to main.yml to include the folder in GitHub Unity Pacakge

feat: Add ScriptTemplates to repo and package

---

Assets/Mirror/Runtime/NetworkManager.cs

Wrong /n  should be  \n  tooltip in NetworkManager Batch Interval.

---

Assets/Mirror/Tests/Runtime/SceneObjectSpawningTests.cs

Suppressed Flakey Tests

---

Assets/Mirror/Components/NetworkPingDisplay.cs

just show the ping in bottom right corner.
less code.
previously it was awkwardly shown in the top left /center area of the screen somewhere.
new:

NetworkPingDisplay simplified

---

Assets/Mirror/Runtime/NetworkManager.cs

fix: Added PersistNetworkManagerToOfflineScene

---

Assets/Mirror/Components/NetworkTransformBase.cs

interpolateScale On NT
"Set to true if scale should be interpolated, false is ideal for instant sprite flipping"
Tested, all seems to be good from my side.

interpolateScale On NT

---

Assets/Mirror/Components/Experimental/NetworkTransformBase.cs
Assets/Mirror/Runtime/Attributes.cs
Assets/Mirror/Runtime/LocalConnections.cs
Assets/Mirror/Runtime/NetworkClient.cs
Assets/Mirror/Runtime/NetworkConnection.cs
Assets/Mirror/Runtime/NetworkConnectionToClient.cs
Assets/Mirror/Runtime/NetworkConnectionToServer.cs
Assets/Mirror/Runtime/NetworkServer.cs
Assets/Mirror/Runtime/NetworkTime.cs
Assets/Mirror/Runtime/Transport/KCP/MirrorTransport/KcpTransport.cs
Assets/Mirror/Runtime/Transport/LatencySimulation.cs
Assets/Mirror/Runtime/Transport/SimpleWebTransport/SimpleWebTransport.cs
Assets/Mirror/Runtime/Transport/Telepathy/TelepathyTransport.cs
Assets/Mirror/Runtime/Transport/Transport.cs
Assets/Mirror/Runtime/Utils.cs
Assets/Mirror/Tests/Editor/BatchingTests.cs
Assets/Mirror/Tests/Editor/CustomAttrributeTest.cs
Assets/Mirror/Tests/Editor/MiddlewareTransportTest.cs

Like #2643 but updates the codebase everywhere with the new names.
**Merge this one instead of that one.**

Shorten Channel Enums

---

Assets/Mirror/Components/NetworkTransformBase.cs

https://github.com/vis2k/Mirror/pull/2646
Similar to the previous PR, see link for details.
Added  [Command(channel = Channels.Unreliable)]  to CmdClientToServerSync
Re-tested with latest master (Mirror-34.0.2), all is fine.

NetworkTransformBase sync scale boolean.

---

Assets/Mirror/Tests/Editor/NetworkTransformTest.cs

Added new syncScale boolean to NT Test writer.

Added new syncScale boolean to NT Test writer.

---

Assets/Mirror/Runtime/NetworkManager.cs

feat: Call ConfigureServerFrameRate For Headless Clients

---

Assets/Mirror/Runtime/Transport/SimpleWebTransport/Client/StandAlone/ClientHandshake.cs

This fixes the handshake for reverse proxy use

SimpleWebTransport fix ssl handshake

---

Assets/Mirror/Runtime/NetworkManager.cs

Fix a typo at line 1218 on NetworkManager.cs

Typo Fix on method Comment

---

Assets/Mirror/Runtime/Transport/KCP/kcp2k/VERSION
Assets/Mirror/Runtime/Transport/KCP/kcp2k/highlevel/KcpClientConnection.cs
Assets/Mirror/Runtime/Transport/KCP/kcp2k/highlevel/KcpServer.cs
Assets/Mirror/Runtime/Transport/KCP/kcp2k/highlevel/KcpServerConnection.cs
Assets/Mirror/Runtime/Transport/KCP/kcp2k/kcp/Kcp.cs
Assets/Mirror/Runtime/Transport/KCP/kcp2k/kcp/Segment.cs
Assets/Mirror/Runtime/Transport/KCP/kcp2k/where-allocation.meta
Assets/Mirror/Runtime/Transport/KCP/kcp2k/where-allocation/LICENSE
Assets/Mirror/Runtime/Transport/KCP/kcp2k/where-allocation/LICENSE.meta
Assets/Mirror/Runtime/Transport/KCP/kcp2k/where-allocation/Scripts.meta
Assets/Mirror/Runtime/Transport/KCP/kcp2k/where-allocation/Scripts/AssemblyInfo.cs
Assets/Mirror/Runtime/Transport/KCP/kcp2k/where-allocation/Scripts/AssemblyInfo.cs.meta
Assets/Mirror/Runtime/Transport/KCP/kcp2k/where-allocation/Scripts/Extensions.cs
Assets/Mirror/Runtime/Transport/KCP/kcp2k/where-allocation/Scripts/Extensions.cs.meta
Assets/Mirror/Runtime/Transport/KCP/kcp2k/where-allocation/Scripts/IPEndPointNonAlloc.cs
Assets/Mirror/Runtime/Transport/KCP/kcp2k/where-allocation/Scripts/IPEndPointNonAlloc.cs.meta
Assets/Mirror/Runtime/Transport/KCP/kcp2k/where-allocation/Scripts/where-allocations.asmdef
Assets/Mirror/Runtime/Transport/KCP/kcp2k/where-allocation/Scripts/where-allocations.asmdef.meta
Assets/Mirror/Runtime/Transport/KCP/kcp2k/where-allocation/VERSION
Assets/Mirror/Runtime/Transport/KCP/kcp2k/where-allocation/VERSION.meta

let's merge this after this month's asset store release

perf: kcp2k V1.11 - where-allocation - 25x reduction in Socket.SendTo/ReceiveFrom allocations

---

Assets/Mirror/Runtime/Batching/Unbatcher.cs
Assets/Mirror/Runtime/Batching/Unbatcher.cs.meta
Assets/Mirror/Runtime/NetworkClient.cs
Assets/Mirror/Tests/Editor/Batching/UnbatcherTests.cs
Assets/Mirror/Tests/Editor/Batching/UnbatcherTests.cs.meta

The Unbatcher

---

Assets/Mirror/Runtime/LocalConnections.cs
Assets/Mirror/Runtime/NetworkClient.cs
Assets/Mirror/Runtime/NetworkConnection.cs
Assets/Mirror/Runtime/NetworkConnectionToClient.cs
Assets/Mirror/Runtime/NetworkConnectionToServer.cs
Assets/Mirror/Runtime/NetworkManager.cs
Assets/Mirror/Runtime/NetworkServer.cs
Assets/Mirror/Tests/Editor/NetworkBehaviourTests.cs
Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
Assets/Mirror/Tests/Editor/TargetRpcTest.cs

prepares for tick batching / NT / batching scene fix.
saves some bandwidth too.

perf: Client -> Server batching

---

Assets/Mirror/Runtime/NetworkConnection.cs
Assets/Mirror/Runtime/NetworkConnectionToClient.cs
Assets/Mirror/Runtime/NetworkConnectionToServer.cs
Assets/Mirror/Tests/Editor/TargetRpcTest.cs

NetworkConnection cleanups

---

Assets/Mirror/Components/InterestManagement/Scene.meta
Assets/Mirror/Components/InterestManagement/Scene/SceneInterestManagement.cs
Assets/Mirror/Components/InterestManagement/Scene/SceneInterestManagement.cs.meta
Assets/Mirror/Examples/MultipleAdditiveScenes/Prefabs/Icosphere.prefab
Assets/Mirror/Examples/MultipleAdditiveScenes/Prefabs/Player.prefab
Assets/Mirror/Examples/MultipleAdditiveScenes/Prefabs/Prize.prefab
Assets/Mirror/Examples/MultipleAdditiveScenes/Scenes/Game.unity
Assets/Mirror/Examples/MultipleAdditiveScenes/Scenes/Main.unity
Assets/Mirror/Runtime/InterestManagement.cs
Assets/Mirror/Runtime/NetworkServer.cs

This adds an InterestManagement based version of the NetworkSceneChecker
Depends on #2758

feat: SceneInterestManagement

---

Assets/Mirror/Runtime/Mathd.cs
Assets/Mirror/Runtime/Mathd.cs.meta
Assets/Mirror/Runtime/SnapshotInterpolation.meta
Assets/Mirror/Runtime/SnapshotInterpolation/Snapshot.cs
Assets/Mirror/Runtime/SnapshotInterpolation/Snapshot.cs.meta
Assets/Mirror/Runtime/SnapshotInterpolation/SnapshotInterpolation.cs
Assets/Mirror/Runtime/SnapshotInterpolation/SnapshotInterpolation.cs.meta
Assets/Mirror/Tests/Editor/SnapshotInterpolationTests.cs
Assets/Mirror/Tests/Editor/SnapshotInterpolationTests.cs.meta

only the algorithm & simulations for now.
can be used in NetworkTransform, NetworkRigidbody, NetworkCharacterController and more.

feature: SnapshotInterpolation algorithm

---

Assets/Mirror/Components/NetworkMatch.cs
Assets/Mirror/Components/NetworkMatch.cs.meta
Assets/Mirror/Components/NetworkMatchChecker.cs
Assets/Mirror/Examples/MultipleMatches/Prefabs/MatchController.prefab
Assets/Mirror/Examples/MultipleMatches/Prefabs/MatchPlayer.prefab
Assets/Mirror/Examples/MultipleMatches/Scripts/CanvasController.cs
Assets/Mirror/Tests/Editor/NetworkMatchCheckerTest.cs

=> make sure to add NetworkMatch component to your match NetworkIdentity prefabs.

breaking: NetworkMatch component to hold matchId. Prepares for AOI2 match checker.

---

Assets/Mirror/Runtime/NetworkTime.cs

fix: Reset lastPingTime

---

Assets/Mirror/Components/InterestManagement/Match.meta
Assets/Mirror/Components/InterestManagement/Match/MatchInterestManagement.cs
Assets/Mirror/Components/InterestManagement/Match/MatchInterestManagement.cs.meta

feature: MatchInterestManagement

---

Assets/Mirror/Runtime/Transport/Telepathy/TelepathyTransport.cs

Otherwise any options set via script are never going to be applied with no way of doing so since everything is "locked in" in Awake

fix: Lazy create telepathy client/server

---

Assets/Mirror/Components/NetworkTransform2k/NetworkTransformBase.cs

fix: NT Base OnDrawGizmos only when playing

---

Assets/Mirror/Editor/Weaver/Readers.cs
Assets/Mirror/Editor/Weaver/Writers.cs
Assets/Mirror/Runtime/Transport/Transport.cs
Assets/Mirror/Tests/Editor/NetworkServerTest.cs

Small improvements now that some obsoletes are gone

Update weaver log, remove unused test and make transport send methods abstract

---

Assets/Mirror/Runtime/NetworkLoop.cs

See ff34a50fdfd783548e78171301df431324d8bb32 and #2826

NetworkLoop needs to be public to expose events

---

Assets/Mirror/Components/InterestManagement/Match/MatchInterestManagement.cs

- Scene objects with no NetworkMatch component
- Key not found in lastObjectMatch Dictionary

fix: Eliminate potential errors in MatchInterestMgmt

---

Assets/Mirror/Components/InterestManagement/Match/MatchInterestManagement.cs

Refactor match int mgmt

---

Assets/Mirror/Runtime/NetworkConnection.cs

- NetworkIdentity.observers is already public

Make NetworkConnection.observing public

---

Assets/Mirror/Runtime/NetworkServer.cs

fix: Check NetworkServer.active in DestroyObject

---

Assets/Mirror/Components/NetworkRoomManager.cs
Assets/Mirror/Runtime/NetworkReader.cs
Assets/Mirror/Runtime/NetworkWriter.cs

- NetworkWriter was also slightly rearraged to match NetworkReader

feat: Support more nullable types

---

Assets/Mirror/Components/InterestManagement/Distance/DistanceInterestManagement.cs
Assets/Mirror/Components/InterestManagement/SpatialHashing/SpatialHashingInterestManagement.cs
Assets/Mirror/Runtime/InterestManagement.cs
Assets/Mirror/Runtime/NetworkServer.cs
Assets/ScriptTemplates/53-Mirror__Custom Interest Management-CustomInterestManagement.cs.txt

- Used in Distance and Spatial to reset `lastRebuildTime`.

feat: Added Reset to Interest Management

---

Assets/Mirror/Runtime/NetworkBehaviour.cs
Assets/Mirror/Runtime/NetworkServer.cs

fix: Suppress Commands When Not Ready

---

Assets/Mirror/Components/NetworkTransform2k/NetworkTransformBase.cs

Shorted timeMultiplierToResetBuffers to bufferResetMultiplier as requested.

Shortened variable name.

---

Assets/Mirror/Components/NetworkTransform2k/NetworkTransformBase.cs

1: Optional boolean to allow onlySyncOnChange.
2: Checks if pos/rot/scale changed, if not, sends the value as null (1byte)
Contains the bundle of latest NT adjustments from the squad.
https://github.com/vis2k/Mirror/pull/3013
https://github.com/vis2k/Mirror/pull/3021
https://github.com/vis2k/Mirror/pull/3019
https://github.com/vis2k/Mirror/pull/3018
Along with a fix for applying latest snapshot, if it exists, before applying local data.
https://github.com/vis2k/Mirror/issues/3024

NetworkTransform Improvements Reeeeesubmission

---

Assets/Mirror/Components/InterestManagement/Team/TeamInterestManagement.cs
Assets/Mirror/Components/NetworkRoomManager.cs
Assets/Mirror/Editor/EditorHelper.cs
Assets/Mirror/Editor/NetworkInformationPreview.cs
Assets/Mirror/Editor/SceneDrawer.cs
Assets/Mirror/Runtime/NetworkIdentity.cs
Assets/Mirror/Runtime/NetworkManager.cs
Assets/Mirror/Runtime/NetworkReader.cs
Assets/Mirror/Runtime/Transport/SimpleWebTransport/Server/ServerHandshake.cs
Assets/Mirror/Runtime/Transport/SimpleWebTransport/SslConfigLoader.cs

- IsNullOrWhiteSpace covers null, empty, and just whitespace.

fix: Use IsNullOrWhiteSpace instead of IsNullOrEmpty

---

Assets/Mirror/Runtime/NetworkTime.cs

imer:
technically a behaviour change there, since the Time.timeAsDouble is the time when the frame started vs stopwatch will change during the frame
(as I've brought up before Time.timeAsDouble is probably the correct behaviour)

breaking: perf: NetworkTime.localTime uses Unity 2020 Time.timeAsDouble instead of stopwatch if available. Makes IsDirty() check a lot faster.

---

Assets/Mirror/Components/NetworkTransform2k/NetworkTransformBase.cs

fixes #3048
Tanks example:
https://user-images.githubusercontent.com/1426904/149679592-0a827e9c-d82a-4133-875f-18ddb01714fb.mp4

fix: NetworkTransform syncs initial position/rotation/scale #3048

---

Assets/Mirror/Runtime/Compression.cs
Assets/Mirror/Runtime/Extensions.cs
Assets/Mirror/Runtime/Mathd.cs
Assets/Mirror/Runtime/MessagePacking.cs
Assets/Mirror/Runtime/NetworkReader.cs
Assets/Mirror/Runtime/NetworkReaderPool.cs
Assets/Mirror/Runtime/NetworkWriter.cs
Assets/Mirror/Runtime/NetworkWriterPool.cs
Assets/Mirror/Runtime/Pool.cs
Assets/Mirror/Runtime/Utils.cs

merge, don't squash.
AFTER https://github.com/vis2k/Mirror/pull/2957 to avoid breakage

perf: inline several hot path functions

---

Assets/Mirror/Components/InterestManagement/Distance/DistanceInterestManagement.cs
Assets/Mirror/Components/InterestManagement/Match/MatchInterestManagement.cs
Assets/Mirror/Components/InterestManagement/Scene/SceneInterestManagement.cs
Assets/Mirror/Components/InterestManagement/SpatialHashing/SpatialHashingInterestManagement.cs
Assets/Mirror/Components/InterestManagement/Team/TeamInterestManagement.cs
Assets/Mirror/Components/NetworkRoomManager.cs
Assets/Mirror/Examples/AdditiveLevels/Scripts/AdditiveLevelsNetworkManager.cs
Assets/Mirror/Examples/Basic/Prefabs/Player.prefab
Assets/Mirror/Examples/Basic/Scenes/Example.unity
Assets/Mirror/Examples/Basic/Scripts/BasicNetManager.cs
Assets/Mirror/Examples/Chat/Scripts/ChatNetworkManager.cs
Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/MultiSceneNetManager.cs
Assets/Mirror/Examples/MultipleMatches/Scripts/CanvasController.cs
Assets/Mirror/Examples/MultipleMatches/Scripts/MatchController.cs
Assets/Mirror/Examples/MultipleMatches/Scripts/MatchNetworkManager.cs
Assets/Mirror/Examples/Pong/Scripts/NetworkManagerPong.cs
Assets/Mirror/Examples/Room/Scripts/NetworkRoomManagerExt.cs
Assets/Mirror/Runtime/InterestManagement.cs
Assets/Mirror/Runtime/NetworkIdentity.cs
Assets/Mirror/Runtime/NetworkManager.cs
Assets/Mirror/Runtime/NetworkServer.cs
Assets/Mirror/Tests/Common/MirrorTest.cs
Assets/Mirror/Tests/Editor/NetworkManagerStopHostOnServerDisconnectTest.cs

Just finished what you started...

breaking: Use NetworkConnectionToClient

---

Assets/Mirror/Tests/Common/MirrorTest.cs

also prepares for https://github.com/vis2k/Mirror/pull/3092/

Tests: Mirrortest isClient check and make sure it's actually set

---

Assets/Mirror/Runtime/NetworkClient.cs
Assets/Mirror/Runtime/NetworkServer.cs
Assets/Mirror/Runtime/Transport.cs
Assets/Mirror/Tests/Common/MemoryTransport.cs

tiny change.
makes profilers, statistics, etc. easier.
also allows for external assets / addons to hook into Transport events for various reasons :)
prepares for: 
https://gyazo.com/09b3c83cfb1787d1a6424c122046006b

feature: allow hooking into Transport events via += -= (prepares for NetworkStatistics)

---

Assets/Mirror/Runtime/Transport.cs
Assets/Mirror/Runtime/Transports/KCP/MirrorTransport/KcpTransport.cs
Assets/Mirror/Runtime/Transports/SimpleWebTransport/SimpleWebTransport.cs
Assets/Mirror/Runtime/Transports/Telepathy/TelepathyTransport.cs
Assets/Mirror/Tests/Common/MemoryTransport.cs

merge https://github.com/vis2k/Mirror/pull/3116 first

feature: Transport.OnClient/ServerDataSent events += (prepares for NetworkStatistics)

---

Assets/Mirror/Components/NetworkStatistics.cs
Assets/Mirror/Components/NetworkStatistics.cs.meta
Assets/Mirror/Runtime/Utils.cs
Assets/Mirror/Tests/Editor/UtilsTests.cs

merge https://github.com/vis2k/Mirror/pull/3117 first

feature: NetworkStatistics

---

Assets/Mirror/Runtime/Messages.cs
Assets/Mirror/Runtime/NetworkBehaviour.cs
Assets/Mirror/Runtime/NetworkClient.cs
Assets/Mirror/Runtime/NetworkIdentity.cs
Assets/Mirror/Runtime/NetworkServer.cs
Assets/Mirror/Runtime/RemoteCalls.cs
Assets/Mirror/Tests/Common/MirrorTest.cs

perf: Rpcs/Cmds functionHash bandwidth reduced from 4 => 2 bytes (with the potential for 1 byte VarInt)

---

Assets/Mirror/Runtime/Batching/Batcher.cs
Assets/Mirror/Runtime/LocalConnectionToServer.cs
Assets/Mirror/Runtime/NetworkConnection.cs
Assets/Mirror/Tests/Editor/Batching/BatcherTests.cs

based on https://github.com/vis2k/Mirror/pull/3127

perf: Build batches directly instead of queuing serializations

---

Assets/Mirror/Examples/Snapshot Interpolation.meta
Assets/Mirror/Examples/Snapshot Interpolation/ClientCube.cs
Assets/Mirror/Examples/Snapshot Interpolation/ClientCube.cs.meta
Assets/Mirror/Examples/Snapshot Interpolation/ClientMaterial.mat
Assets/Mirror/Examples/Snapshot Interpolation/ClientMaterial.mat.meta
Assets/Mirror/Examples/Snapshot Interpolation/ServerCube.cs
Assets/Mirror/Examples/Snapshot Interpolation/ServerCube.cs.meta
Assets/Mirror/Examples/Snapshot Interpolation/ServerMaterial.mat
Assets/Mirror/Examples/Snapshot Interpolation/ServerMaterial.mat.meta
Assets/Mirror/Examples/Snapshot Interpolation/Snapshot3D.cs
Assets/Mirror/Examples/Snapshot Interpolation/Snapshot3D.cs.meta
Assets/Mirror/Examples/Snapshot Interpolation/SnapshotInterpolation.unity
Assets/Mirror/Examples/Snapshot Interpolation/SnapshotInterpolation.unity.meta

https://gyazo.com/95007182773e09a916fc2bf744edb4d4

Snapshot Interpolation visual example

---

Assets/Mirror/Runtime/Transports/SimpleWebTransport/Server/ServerHandshake.cs

See https://github.com/vis2k/Mirror/issues/3175

fix: SWT header lookup needs to be case insensitive

---

Assets/Mirror/Components/NetworkTransform2k/NetworkTransformBase.cs
Assets/Mirror/Core/NetworkBehaviour.cs
Assets/Mirror/Core/NetworkClient.cs
Assets/Mirror/Core/NetworkIdentity.cs
Assets/Mirror/Core/NetworkManager.cs
Assets/Mirror/Core/NetworkServer.cs
Assets/Mirror/Editor/NetworkBehaviourInspector.cs
Assets/Mirror/Tests/Editor/NetworkIdentitySerializationTests.cs
Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
Assets/Mirror/Tests/Editor/SyncVarAttributeTest.cs
Assets/Mirror/Tests/Runtime/NetworkIdentityTests.cs

feature: SyncDirection to easily support client auth components without extra Rpcs/Cmds. previously OnSerialize was only server-to-client direction.

---

Assets/Mirror/Components/Discovery/NetworkDiscoveryBase.cs

iOS build prevents broadcasting to 0.0.0.0, so we needed to expose it to change it for our built

fix: NetworkDiscovery BroadcastAddress exposed for iOS support

---

Assets/Mirror/Components/RemoteStatistics.cs
Assets/Mirror/Core/NetworkServer.cs

Fix time as double unity 2019

---

Assets/Mirror/Core/NetworkManager.cs
Assets/Mirror/Editor/Welcome.cs
Assets/Mirror/Editor/Welcome.cs.meta

avoids spamming the welcome message every single time we press play.
and simplifies networkmanager a little more.

Welcome message moved out of NetworkManager into standalone Editor script, per-session instead of per-play.

---

Assets/Mirror/Core/NetworkManager.cs

Fixes this issue: https://github.com/MirrorNetworking/Mirror/issues/3309

Fixed server and client connection attempt with AddPlayer before authentication completes

---

Assets/Mirror/Core/NetworkBehaviour.cs
Assets/Mirror/Core/SyncDictionary.cs
Assets/Mirror/Core/SyncList.cs
Assets/Mirror/Core/SyncObject.cs
Assets/Mirror/Core/SyncSet.cs
Assets/Mirror/Examples/Benchmark/Prefabs/Player.prefab
Assets/Mirror/Examples/SyncDirection/Player.cs
Assets/Mirror/Examples/SyncDirection/Scene.unity
Assets/Mirror/Tests/Editor/NetworkBehaviourTests.cs
Assets/Mirror/Tests/Editor/SyncDictionaryTest.cs
Assets/Mirror/Tests/Editor/SyncListTest.cs
Assets/Mirror/Tests/Editor/SyncSetTest.cs

fix: #3315 ClientToServer SyncList support

---

Assets/Mirror/Components/NetworkTransformBase.cs

NetworkTransformBase - make snapshot lists readonly

---

Assets/Mirror/Core/NetworkBehaviour.cs
Assets/Mirror/Core/NetworkManager.cs
Assets/Mirror/Core/NetworkServer.cs
Assets/Mirror/Core/NetworkWriterExtensions.cs

This eliminates allocations, at least in the editor, per Unity docs.

Use TryGetComponent

---

Assets/Mirror/Components/NetworkTransformBase.cs
Assets/Mirror/Components/NetworkTransformUnreliable/NetworkTransformChild.cs
Assets/Mirror/Core/NetworkBehaviour.cs
Assets/Mirror/Core/NetworkClient.cs
Assets/Mirror/Core/NetworkConnection.cs
Assets/Mirror/Core/NetworkConnectionToClient.cs
Assets/Mirror/Core/NetworkIdentity.cs
Assets/Mirror/Core/NetworkManager.cs
Assets/Mirror/Core/NetworkMessages.cs
Assets/Mirror/Core/NetworkReader.cs
Assets/Mirror/Core/NetworkReaderPool.cs
Assets/Mirror/Core/NetworkReaderPooled.cs
Assets/Mirror/Core/NetworkServer.cs
Assets/Mirror/Core/NetworkWriterPool.cs
Assets/Mirror/Core/NetworkWriterPooled.cs
Assets/Mirror/Core/Tools/ExponentialMovingAverage.cs
Assets/Mirror/Core/Tools/Pool.cs
Assets/Mirror/Core/Transport.cs

- Also normalized Deprecated comments for easier searching

breaking: Removed Old Obsoletes

---

Assets/Mirror/Components/NetworkTransformReliable/NetworkTransformReliable.cs

- Fixes #3317 
- See research done in that ticket

fix: #3317 - NetworkTransformReliable: don't send last snapshot

---

Assets/Mirror/Components/NetworkTransformBase.cs

This fixes the problem of ClientToServer NT's snapping back to their original positions when authority returned to server.

fix: NetworkTransformBase - Reset when changing authority

---

Assets/Mirror/Core/SnapshotInterpolation/SnapshotInterpolation.cs
Assets/Mirror/Tests/Editor/SnapshotInterpolationTests.cs

fix(SnapshotInterpolation): Added TimelineClamp

---

Assets/Mirror/Core/NetworkClient.cs
Assets/Mirror/Core/NetworkClient_TimeInterpolation.cs
Assets/Mirror/Core/NetworkConnectionToClient.cs
Assets/Mirror/Core/NetworkManager.cs
Assets/Mirror/Core/SnapshotInterpolation/SnapshotInterpolationSettings.cs
Assets/Mirror/Core/SnapshotInterpolation/SnapshotInterpolationSettings.cs.meta

breaking: expose NetworkClient's Snapshot Interpolation settings in NetworkManager

---

Assets/Mirror/Components/NetworkTransformReliable/NetworkTransformReliable.cs

fix: NetworkTransformReliable fix jitter (fixes: #3368)

---

Assets/Mirror/Components/NetworkTransformUnreliable/NetworkTransform.cs

pending webgl interp test by mrg

fix; NetworkTransformUnreliable now broadcasts in LateUpdate as well (#3410)

---

Assets/Mirror/Transports/KCP/kcp2k/VERSION.txt
Assets/Mirror/Transports/KCP/kcp2k/highlevel/Common.cs
Assets/Mirror/Transports/KCP/kcp2k/highlevel/KcpClient.cs
Assets/Mirror/Transports/KCP/kcp2k/highlevel/KcpPeer.cs
Assets/Mirror/Transports/KCP/kcp2k/highlevel/KcpServer.cs
README.md

fix: kcp2k V1.35. secure cookie to prevent UDP spoofing. fixes: #3286

---

Assets/Mirror/Transports/KCP/KcpTransport.cs

**Map to** _IPv4_ **if** _"IsIPv4MappedToIPv6"_
"::ffff:127.0.0.1" -> "127.0.0.1"

KcpTransport: reconvert mapped ipv4->ipv6 addresses to ipv4 in ServerGetClientAddress

---

Assets/Mirror/Editor/Weaver/Processors/TargetRpcProcessor.cs

Logically, clients can never fill in a NetworkConnectionToClient parameter. fixes compilation failing for TargetRpc(NetworkConnectionToClient) with IL2CPP builds.
https://github.com/MirrorNetworking/Mirror/issues/3455

fix: #3455 TargetRpc(NetworkConnectionToClient) weaver generated InvokeTargetRpc now passes 'null' as connection parameter on clients.

---

Assets/ScriptTemplates/57-Mirror__Network Transform-NewNetworkTransform.cs.txt

Theres probably more, but this is one change i have noticed so far.

Updated ApplySnapshot ScriptTemplates

---

Assets/Mirror/Components/NetworkTransformBase.cs
Assets/Mirror/Components/NetworkTransformUnreliable/NetworkTransform.cs

Noting some others that need a "Set to true if.. "
timelineOffset
onlySyncOnChange
rotationSensitivity, scaleSensitivity (only shows tip for positionSensitivity)
- Recommendations or adjustments are welcome.

NetworkTransform tooltips need use-case explanations.

---

Assets/Mirror/Components/NetworkRoomPlayer.cs

I have someone thats manually added virtual to Start, so they can override it, it will be good for this to be added to make updating easier for them in the future.  (im sure others may use it too?)

NetworkRoomPlayer.cs Start virtual override

---

Assets/Mirror/Presets.meta
Assets/Mirror/Presets/NetworkTransform.meta
Assets/Mirror/Presets/NetworkTransform/ClientAuth-Balanced.preset
Assets/Mirror/Presets/NetworkTransform/ClientAuth-Balanced.preset.meta
Assets/Mirror/Presets/NetworkTransform/ClientAuth-FastPaced.preset
Assets/Mirror/Presets/NetworkTransform/ClientAuth-FastPaced.preset.meta
Assets/Mirror/Presets/NetworkTransform/ClientAuth-VeryCasual.preset
Assets/Mirror/Presets/NetworkTransform/ClientAuth-VeryCasual.preset.meta

Tested all 3 presets on tanks example, parent and child turret.
Scenarios were: 
1: Regular localhost
2: Latency sim (200ping, 2% loss etc)
3: Latency sim bad connection (500 ping, 5% loss etc)
Along with personal experience of the settings on NT these 3 presets should cover most peoples scenarios.
A: FastPaced (fps)
B: Balanced (my recommended default)
C: VeryCasual (social game)
Discussions and changes regarding Folder names, hierarchy and anything else are welcome.

NT-UR Example presets

---

Assets/Mirror/Core/NetworkClient.cs
Assets/Mirror/Core/NetworkMessages.cs
Assets/Mirror/Core/NetworkServer.cs

feature: NetworkMessageId <> Type lookup and log function for debugging

---

Assets/Mirror/Editor/Weaver/EntryPointILPostProcessor/ILPostProcessorAssemblyResolver.cs

perf: Weaver 22x speedup

---

Assets/Mirror/Core/NetworkConnectionToClient.cs

fixes: https://github.com/MirrorNetworking/Mirror/issues/3538

fix: #3538 calling unspawn on scene objects in DestroyOwnedObjects

---

Assets/Mirror/Core/LocalConnectionToClient.cs
Assets/Mirror/Core/Messages.cs
Assets/Mirror/Core/NetworkClient.cs
Assets/Mirror/Core/NetworkConnectionToClient.cs
Assets/Mirror/Core/NetworkServer.cs
Assets/Mirror/Core/NetworkTime.cs
Assets/Mirror/Tests/Editor/NetworkConnection/NetworkConnectionToClientTests.cs

same as client sided NetworkTime.rtt, but on server per NetworkConnectionToClient.
for statistics, lag compensation, etc.
TODO:

feature: NetworkConnectionToClient.rtt via Ping & Pong Messages

---

Assets/Mirror/Examples/TanksCoop/SceneTanksCoop.unity

Fixed background image for canvas text. Scales now no matter the ratio/resolution etc.

Adjusted UI scaling in new TanksCoop example.

---

Assets/Mirror/Examples/Common/CanvasNetworkManagerHUD.meta
Assets/Mirror/Examples/Common/CanvasNetworkManagerHUD/CanvasNetworkManagerHUD.cs
Assets/Mirror/Examples/Common/CanvasNetworkManagerHUD/CanvasNetworkManagerHUD.cs.meta
Assets/Mirror/Examples/Common/CanvasNetworkManagerHUD/CanvasNetworkManagerHUD.prefab
Assets/Mirror/Examples/Common/CanvasNetworkManagerHUD/CanvasNetworkManagerHUD.prefab.meta

Scales  
Contains features of older OnGUI HUD  
A nice optional prefab to help users
Credits to Ninja  
Video:  
https://github.com/MirrorNetworking/Mirror/assets/57072365/f587c1ff-8119-41b3-a676-5a8b0f42e185
Folder placement:  
Scales unlike older HUD.

A drag and drop Canvas UI HUD for NetworkManager

---

Assets/Mirror/Core/NetworkClient.cs
Assets/Mirror/Core/NetworkManager.cs
Assets/Mirror/Core/NetworkMessages.cs
Assets/Mirror/Core/NetworkServer.cs

this was requested a lot.
some games don't want to force disconnect players on any exception.

feature: NetworkManager.exceptionsCauseDisconnect option

---

Assets/Mirror/Editor/EditorHelper.cs
Assets/Mirror/Editor/NetworkManagerEditor.cs

https://github.com/MirrorNetworking/Mirror/assets/1426904/faf5e1c9-89a7-45c5-a49c-fa295308b440

feat: NetworkManager Populate Spawnable Prefabs button

---

Assets/Mirror/CompilerSymbols/PreprocessorDefine.cs
Assets/Mirror/Examples/CharacterSelection/Scripts/PlayerControllerScript.cs
Assets/Mirror/Examples/CharacterSelection/Scripts/PlayerEmpty.cs
Assets/Mirror/Examples/Common/CanvasNetworkManagerHUD/CanvasNetworkManagerHUD.cs
Assets/Mirror/Examples/CouchCoop/Scripts/CouchPlayer.cs
Assets/Mirror/Examples/CouchCoop/Scripts/CouchPlayerManager.cs
Assets/Mirror/Examples/MultipleMatches/Scripts/MatchController.cs
Assets/Mirror/Examples/MultipleMatches/Scripts/MatchGUI.cs

This addresses most of the ones in #3630 but not the last two having to do with Weaver tests.

fix: Fix Unity 2023 obsoletes

---

Assets/Mirror/Hosting/Edgegap/Editor/EdgegapWindow.cs

- This was Imer's idea from Discord

fix(EdgegapWindow): Simplify clearing ProgressBar

---

Assets/Mirror/Core/NetworkManagerHUD.cs

Looks like this in Editor and browser with WebGL as target platform and transport:
Works with Multiplexer but doesn't show Port field (Multiplexer limitation):

feat(HUD): Better HUD for WebGL

---

Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Client/SimpleWebClient.cs
Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Client/StandAlone/ClientHandshake.cs
Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Client/StandAlone/ClientSslHelper.cs
Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Client/StandAlone/WebSocketClientStandAlone.cs
Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Client/Webgl/WebSocketClientWebGl.cs
Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Common/BufferPool.cs
Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Common/Connection.cs
Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Common/Constants.cs
Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Common/Log.cs
Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Common/ReadHelper.cs
Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Common/ReceiveLoop.cs
Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Common/SendLoop.cs
Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Server/ServerHandshake.cs
Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Server/ServerSslHelper.cs
Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Server/SimpleWebServer.cs
Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Server/WebSocketServer.cs
Assets/Mirror/Transports/SimpleWeb/SimpleWebTransport.cs

Complete overhaul of SimpleWebTransport Logging

feat(SWT): Logging System Overhaul

---

Assets/Mirror/Components/NetworkDiagnosticsDebugger.cs
Assets/Mirror/Components/NetworkDiagnosticsDebugger.cs.meta

Add component for network diagnostics to log output of messages sent and received.
You can see how NetworkDiagnostics is used [here](https://github.com/search?q=repo%3AMirrorNetworking%2FMirror%20NetworkDiagnostics&type=code).

feat: Add component for NetworkDiagnostics to log messages sent and received

---

Assets/Mirror/Transports/Telepathy/TelepathyTransport.cs

fix(Telepathy): Shorter Simpler ToString

---

README.md

Readme: Badge Styling V2

---

Assets/Mirror/Components/NetworkTransform/NetworkTransformBase.cs
Assets/Mirror/Components/NetworkTransform/NetworkTransformUnreliable.cs
Assets/Mirror/Components/NetworkTransform/TransformSnapshot.cs

- fixes tabs to spaces
- removes manual alignments because IDE's won't preserve them

Code Formatting in NT scripts

---

Assets/Mirror/Components/NetworkTransform/NetworkTransformUnreliable.cs

On by default, uses smallest 3, lowers by 12 bytes.
Has tooltip etc

feat: Compress network transform rotation boolean.

---

README.md

Readme: added Features Matrix

---

Assets/Mirror/Core/NetworkManager.cs
Assets/Mirror/Core/Tools/Utils.cs

feat(NetworkManager): Ability to toggle auto-start in Editor

---

Assets/Mirror/Components/NetworkTransform/NetworkTransformBase.cs
Assets/Mirror/Components/NetworkTransform/NetworkTransformReliable.cs
Assets/Mirror/Components/NetworkTransform/NetworkTransformUnreliable.cs

No functional change, just moved identical settings to NT Base
- Compress Rotation
- Only Sync On Change

fix(NT Base): Consolidate NT fields to NT Base

---

Assets/Mirror/Tests/Editor/Transports/MultiplexTransportTest.cs
Assets/Mirror/Transports/Multiplex/MultiplexTransport.cs

fix(Multiplexer): Avoid KeyNotFoundException in OriginalId

---

Assets/Mirror/Components/NetworkTransform/NetworkTransformUnreliable.cs

Credits to ninja of course :D
Fixes twerking tank, which is very noticeable on lower send.

fix: NT-Unreliable Quaternion Compression Fix

---

Assets/Mirror/Core/NetworkManager.cs

- Throws error if server isn't active
- allows for changing to offline scene regardless

fix(NetworkManager): Prevent client from calling ServerChangeScene

---

Assets/Mirror/Core/RemoteCalls.cs
Assets/Mirror/Editor/Weaver/Processors/CommandProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/RpcProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/ServerClientAttributeProcessor.cs
Assets/Mirror/Editor/Weaver/Processors/SyncVarAttributeAccessReplacer.cs
Assets/Mirror/Editor/Weaver/Processors/TargetRpcProcessor.cs
Assets/Mirror/Editor/Weaver/Weaver.cs

Hold for #3731 to be merged first.

feat(RemoteProcedureCalls): Added GetFunctionMethodName

---

Assets/Mirror/Core/NetworkServer.cs
Assets/Mirror/Core/RemoteCalls.cs

- Attempt to dig up the Object, component, and method name to make debugging easier

fix(NetworkServer): Improve Warnings

---

Assets/Mirror/Core/NetworkClient.cs
Assets/Mirror/Core/NetworkServer.cs

Throws error for disconnect, warning otherwise.

fix: NetworkServer and NetworkClient respect exceptionDisconnect

---

Assets/Mirror/Tests/Editor/NetworkServer/NetworkServerTest.cs

fix(NetworkServerTest): Updated tests

---

Assets/Mirror/Transports/Multiplex/MultiplexTransport.cs

Prevents KeyNotFoundException when Multiplexer has already disposed the connection:
```
KeyNotFoundException: The given key '[-2071260962, 0]' was not present in the dictionary.
at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x00000] in <00000000000000000000000000000000>:0
at Mirror.MultiplexTransport.MultiplexId (System.Int32 originalConnectionId, System.Int32 transportIndex) [0x00000] in <00000000000000000000000000000000>:0
at Mirror.MultiplexTransport+<>c__DisplayClass26_0.<AddServerCallbacks>b__3 (System.Int32 originalConnectionId) [0x00000] in <00000000000000000000000000000000>:0
at kcp2k.KcpServer+<>c__DisplayClass20_0.<CreateConnection>g__OnDisconnectedCallback|4 () [0x00000] in <00000000000000000000000000000000>:0
at kcp2k.KcpPeer.Disconnect () …
```

fix(MultiplexTransport): Use TryGetValue for Lookups

---

Assets/Mirror/Core/NetworkManager.cs

Transports may need networkAddress for binding to IP / FQDN.

fix(NetworkManager): FinishStartHost-Don't force localhost

---

Assets/Mirror/Core/NetworkServer.cs

We already did this in CleanupSpawned. 
Should've just moved it to Destroy instead to begin with!

fix: NetworkServer.Destroy never destroys scene objects anymore since unlike prefabs, once they are gone we can never instantiate them again

---

Assets/Mirror/Transports/Encryption/EncryptionTransport.cs

Link to the newly created docs page

chore: EncryptionTransport help url

---

Assets/Mirror/Transports/Edgegap/EdgegapRelay/EdgegapKcpTransport.cs

see https://github.com/MirrorNetworking/Mirror/issues/3708 and also https://github.com/MirrorNetworking/Mirror/commit/56a1aa096fd22ff54e952458772942cf18536a23

fix: EdgegapKcp StopHost() null reference exception

---

Assets/Mirror/Transports/Edgegap/EdgegapLobby/EdgegapLobbyKcpTransport.cs
Assets/Mirror/Transports/Edgegap/EdgegapLobby/LobbyApi.cs
Assets/Mirror/Transports/Edgegap/EdgegapLobby/LobbyServiceCreateDialogue.cs
Assets/Mirror/Transports/Edgegap/EdgegapRelay/EdgegapKcpTransport.cs

- "token " is now removed from the start of the api key instead of silently handling it in the background
- window has a title instead of the class name
- min size is more reasonable
- loading dots are now 3 spaced dots
- updated help urls

chore: Edgegap Lobby Create UI Tweaks

---

Assets/Mirror/Core/SyncDictionary.cs

- This is preparation for Actions coming in subsequent PR.
- This is all private / internal...no change for the end user.

SyncDictionary: Add oldValue to AddOperation

---

Assets/Mirror/Editor/LagCompensatorInspector.cs
Assets/Mirror/Editor/LagCompensatorInspector.cs.meta
Assets/Mirror/Editor/Mirror.Editor.asmdef

Looks nicer than Obsolete
If you'd prefer, I can change it to an Info icon...it would look like this:

chore: Added LagCompensatorInspector

---

Assets/Mirror/Hosting/Edgegap/Editor/EdgegapBuildUtils.cs

fix(EdgegapHosting): only include enabled scenes in build

---

Assets/Mirror/Components/NetworkRigidbody/NetworkRigidbodyReliable.cs
Assets/Mirror/Components/NetworkRigidbody/NetworkRigidbodyReliable2D.cs
Assets/Mirror/Components/NetworkRigidbody/NetworkRigidbodyUnreliable.cs
Assets/Mirror/Components/NetworkRigidbody/NetworkRigidbodyUnreliable2D.cs

- NetworkRigidbodyReliable
- NetworkRigidbodyUnreliable
- NetworkRigidbodyReliable2D
- NetworkRigidbodyUnreliable2D

fix(NetworkRigidbody Components): Added missing OnTeleport overrides

---

.github/workflows/Semantic.yml
.releaserc.yml

Improved CI for producing release packages
- Generates and includes version.txt
- Extended types for releases and release notes
- unity-packer is executed by semantic-release
- releaserc fully rewritten with comments

Update Semantic Release

---

Assets/Mirror/Editor/SyncObjectCollectionsDrawer.cs

fix(SyncObjectCollectionField): Pretty SyncCollection Name

---

Assets/Mirror/Examples/CouchCoop/MirrorCouchCoop.unity
Assets/Mirror/Examples/CouchCoop/Scripts/CameraViewForAll.cs
Assets/Mirror/Examples/CouchCoop/Scripts/CameraViewForAll.cs.meta
Assets/Mirror/Examples/CouchCoop/Scripts/CouchPlayer.cs

Added fancy camera for couch co-op example.
https://github.com/MirrorNetworking/Mirror/assets/57072365/d0bf0a50-7e53-4cc3-a969-7ffd7bd6966c

feat: Fancy camera for couch coop example, and player list.

---

Assets/Mirror/Examples/_Common/Scripts/CanvasNetworkManagerHUD/CanvasNetworkManagerHUD.cs
Assets/Mirror/Examples/_Common/Scripts/CanvasNetworkManagerHUD/CanvasNetworkManagerHUD.prefab

As title says, the canvas prefab was out of date in comparison to the OnGUI hud, I have added the Port section.
Mirror/Examples/_Common/CanvasNetworkManagerHUD

feat: Port input field for UI Canvas Prefab.

---

Assets/Mirror/Plugins/BouncyCastle/Mirror.BouncyCastle.Cryptography.dll.meta

Forgot we need to change these when files are renamed 😇

chore: new GUID for bouncycastle dll meta file

---

Assets/Mirror/Examples/CharacterSelection/_ReadMe.txt

Kudos to Gadget for seeing it.

Updated ReadMe for CharacterSelection example.

---

Assets/Mirror/Examples/CharacterSelection/Prefabs/Characters/CharacterAssault.prefab
Assets/Mirror/Examples/CharacterSelection/Prefabs/Characters/CharacterHeavy.prefab
Assets/Mirror/Examples/CharacterSelection/Prefabs/Characters/CharacterMedic.prefab
Assets/Mirror/Examples/CharacterSelection/Scripts/PlayerControllerScript.cs
Assets/Mirror/Examples/CharacterSelection/Scripts/SceneCamera.cs
Assets/Mirror/Examples/CharacterSelection/Scripts/SceneCamera.cs.meta

After this is merged, PlayerControllerScript will be replaced with Common/PlayerController

fix(CharacterSelection Example): Separate SceneCamera script

---

Assets/Mirror/Transports/Edgegap/EdgegapLobby/EdgegapLobbyKcpTransport.cs

Missing return, oops.
Also some minor readability cleanup (might want to hide whitespace changes for looking at the diff..)

fix: Edgegap Lobby Error continues to Connecting

---

Assets/Mirror/Editor/NetworkManagerEditor.cs

https://github.com/MirrorNetworking/Mirror/issues/3619

feat(NetworkManager): Clear Spawnable Prefabs button (#3619)

---

Assets/Mirror/Core/NetworkManager.cs
Assets/Mirror/Tests/Editor/NetworkManager/NetworkManagerTest.cs
Assets/Mirror/Transports/Threaded/ThreadedTransport.cs

two part fix.
merge, not squash.

fix: #3787

---

Assets/Mirror/Core/Transport.cs

Feel free to close this if this isn't a mistake! 
Just confused me when I read it 🙂

Tiny Spelling Nit in Transport.cs

---

Assets/Mirror/Components/Profiling/Prefabs/NetworkGraph.prefab
Assets/Mirror/Components/Profiling/Prefabs/NetworkGraph.prefab.meta

Universal netgraph that shows:
- bandwidth in/out on the left side
- latency (ping/jitter) on the right side

feat(netgraph): universal NetworkGraph with bandwidth + ping in one

---

Assets/Mirror/Editor/NetworkScenePostProcess.cs

fixes https://github.com/MirrorNetworking/Mirror/issues/3262

fix: #3262 allow running a mirror project from edit prefab mode again

---

Assets/Mirror/Core/Attributes.cs

Hopefully adds additional support in preventing confusion.

Updated Server/Client attribute help text.

---

Assets/Mirror/Components/NetworkTransform/NetworkTransformUnreliable.cs

Removed comma before fullstops in tooltip

Update tooltip for NetworkTransformUnreliable.cs

---

Assets/Mirror/Components/NetworkTransform/NetworkTransformHybrid.cs

Same as NT Base and NetworkAnimator

fix(NetworkTransformHybrid) Default SyncDir to ClientToServer

---

Assets/Mirror/Components/Discovery/NetworkDiscoveryBase.cs
Assets/Mirror/Components/Discovery/NetworkDiscoveryHUD.cs
Assets/Mirror/Examples/Discovery/Scenes/MirrorDiscovery.unity

Handler would not be added if component ref not null.

fix(NetworkDiscoveryHUD): More robust OnValidate / Reset

---

Assets/Mirror/Components/NetworkTransform/NetworkTransformHybrid.cs
Assets/Mirror/Core/NetworkBehaviourHybrid.cs
Assets/Mirror/Core/NetworkBehaviourHybrid.cs.meta

Second major step towards quake style unreliable sync in Mirror core.
This PR abstracts all the hard stuff from Network**Transform**Hybrid into Network**Behaviour**Hybrid.
This is very similar to the old hybrid PR, but with more issues solved this time.

feature: NetworkBehaviourHybrid & NetworkTransformHybrid simplified

---

Assets/Mirror/Components/NetworkTransform/NetworkTransformBase.cs

Usage case:
```cs
void OnVelRotChanged(Vector3 newVelocity, Vector3 newRotation)
{
animVelocity = -MathF.Round(transform.InverseTransformDirection(newVelocity).z / moveSpeedMultiplier, 1);
animRotation = -MathF.Round(newRotation.y / maxTurnSpeed, 1);
if (animator)
{
animator.SetFloat("Forward", MathF.Round(Mathf.MoveTowards(animator.GetFloat("Forward"), animVelocity, moveSpeedMultiplier * Time.deltaTime), 1));
animator.SetFloat("Turn", MathF.Round(Mathf.MoveTowards(animator.GetFloat("Turn"), animRotation, maxTurnSpeed * Time.deltaTime), 1));
}
}
```

feat(NetworkTranformBase): Provide velocity and angular velocity

---

Assets/Mirror/Components/NetworkTransform/NetworkTransformBase.cs

- ResetState is called from OnTeleport
- Avoids fighting with Char Controller / Rigidbodies

fix(NT Base): Call Physics.SyncTransforms in ResetState

---

Assets/Mirror/Components/NetworkTransform/NetworkTransformHybrid.cs
Assets/Mirror/Core/NetworkBehaviourHybrid.cs

Don't hijack Unity's Reset...use Reset correctly with OnValidate

fix(NT Hybrid): ResetState instead of Reset

---

Assets/Mirror/Components/NetworkTransform/NetworkTransformBase.cs
Assets/Mirror/Components/NetworkTransform/NetworkTransformHybrid.cs
Assets/Mirror/Components/NetworkTransform/NetworkTransformReliable.cs
Assets/Mirror/Components/NetworkTransform/NetworkTransformUnreliable.cs
Assets/Mirror/Examples/_Common/Controllers/PlayerControllerRB/PlayerControllerRBBase.cs
Assets/Mirror/Examples/_Common/Controllers/PlayerControllerRB/PlayerControllerRBHybrid.cs
Assets/Mirror/Examples/_Common/Controllers/PlayerControllerRB/PlayerControllerRBReliable.cs
Assets/Mirror/Examples/_Common/Controllers/PlayerControllerRB/PlayerControllerRBUnreliable.cs

- Required for non-kinematic rigidbody controllers
- Tested all in PlayerTest with long strafe runs.
Fixes #3931 
Fixes #3965

feat(NetworkTransform): Support for FixedUpdate

---

Assets/Mirror/Components/NetworkTransform/NetworkTransformHybrid.cs

- ResetState is called from OnTeleport
- Avoids fighting with Char Controller / Rigidbodies

fix(NT Hybrid): Call Physics.SyncTransforms in ResetState (#3987)

---

Assets/Mirror/Components/InterestManagement/SpatialHashing/HexGrid3D.cs
Assets/Mirror/Components/InterestManagement/SpatialHashing/HexGrid3D.cs.meta
Assets/Mirror/Components/InterestManagement/SpatialHashing/HexSpatialHash3DInterestManagement.cs
Assets/Mirror/Components/InterestManagement/SpatialHashing/HexSpatialHash3DInterestManagement.cs.meta
Assets/Mirror/Examples/HexSpatialHash.meta
Assets/Mirror/Examples/HexSpatialHash/HexSpatialHash.unity
Assets/Mirror/Examples/HexSpatialHash/HexSpatialHash.unity.meta
Assets/Mirror/Examples/HexSpatialHash/Mateirals.meta
Assets/Mirror/Examples/HexSpatialHash/Mateirals/RandomColor.mat
Assets/Mirror/Examples/HexSpatialHash/Mateirals/RandomColor.mat.meta
Assets/Mirror/Examples/HexSpatialHash/Prefabs.meta
Assets/Mirror/Examples/HexSpatialHash/Prefabs/HexPlayer.prefab
Assets/Mirror/Examples/HexSpatialHash/Prefabs/HexPlayer.prefab.meta
Assets/Mirror/Examples/HexSpatialHash/Prefabs/SpawnPrefab.prefab
Assets/Mirror/Examples/HexSpatialHash/Prefabs/SpawnPrefab.prefab.meta
Assets/Mirror/Examples/HexSpatialHash/Scripts.meta
Assets/Mirror/Examples/HexSpatialHash/Scripts/HexNetworkManager.cs
Assets/Mirror/Examples/HexSpatialHash/Scripts/HexNetworkManager.cs.meta
Assets/Mirror/Examples/HexSpatialHash/Scripts/HexPlayer.cs
Assets/Mirror/Examples/HexSpatialHash/Scripts/HexPlayer.cs.meta

Highly optimized 3D spatial hash interest management based on hexagonal volumes
- Fully configurable
- Gizmo drawn cells in editor
- HexSpatialHash example included
- Documentation to be done after this is merged

feat(Interest Management): Hex Spatial Hash 3D

---

Assets/Mirror/Components/Discovery/NetworkDiscoveryHUD.cs
Assets/Mirror/Components/GUIConsole.cs
Assets/Mirror/Components/InterestManagement/SpatialHashing/SpatialHashing3DInterestManagement.cs
Assets/Mirror/Components/InterestManagement/SpatialHashing/SpatialHashingInterestManagement.cs
Assets/Mirror/Components/NetworkPingDisplay.cs
Assets/Mirror/Components/NetworkRoomPlayer.cs
Assets/Mirror/Components/NetworkStatistics.cs
Assets/Mirror/Components/NetworkTransform/NetworkTransformBase.cs
Assets/Mirror/Components/RemoteStatistics.cs
Assets/Mirror/Core/NetworkClient.cs
Assets/Mirror/Core/NetworkManager.cs
Assets/Mirror/Core/NetworkManagerHUD.cs
Assets/Mirror/Examples/BenchmarkStinkySteak/Dependencies/netcode-benchmarker-util/Runtime/Scripts/UI/BaseGUIGame.cs
Assets/Mirror/Examples/BilliardsPredicted/Ball/WhiteBallPredicted.cs
Assets/Mirror/Examples/HexSpatialHash/Scripts/Hex2DPlayer.cs
Assets/Mirror/Examples/HexSpatialHash/Scripts/Hex3DPlayer.cs
Assets/Mirror/Examples/LagCompensation/ClientCube.cs
Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/PlayerScore.cs
Assets/Mirror/Examples/Room/Scripts/NetworkRoomManagerExt.cs
Assets/Mirror/Examples/Room/Scripts/NetworkRoomPlayerExt.cs
Assets/Mirror/Examples/Room/Scripts/PlayerScore.cs
Assets/Mirror/Examples/Snapshot Interpolation/ClientCube.cs
Assets/Mirror/Examples/SyncDirection/Player.cs
Assets/Mirror/Examples/_Common/Scripts/FPS.cs
Assets/Mirror/Transports/Edgegap/EdgegapLobby/LobbyServiceCreateDialogue.cs
Assets/Mirror/Transports/Edgegap/EdgegapRelay/EdgegapKcpTransport.cs
Assets/Mirror/Transports/KCP/KcpTransport.cs
Assets/Mirror/Transports/KCP/ThreadedKcpTransport.cs

Wraps all OnGUI methods in `#if !UNITY_SERVER . . . #endif`

perf: Exclude OnGUI from server builds

---

Assets/Mirror/Core/NetworkManager.cs

fix(NetworkManager): Unsubscribe from OnSceneLoaded in OnDestroy

---

Assets/Mirror/Components/NetworkTransform/NetworkTransformBase.cs
Assets/Mirror/Components/NetworkTransform/NetworkTransformHybrid.cs
Assets/Mirror/Components/NetworkTransform/NetworkTransformReliable.cs
Assets/Mirror/Components/NetworkTransform/NetworkTransformUnreliable.cs
Assets/Mirror/Examples/PlayerTest/CharacterController/PlayerHybrid.prefab
Assets/Mirror/Examples/PlayerTest/CharacterController/PlayerReliable.prefab
Assets/Mirror/Examples/PlayerTest/CharacterController/PlayerUnreliable.prefab
Assets/Mirror/Examples/PlayerTest/PlayerTestScene.unity
Assets/Mirror/Examples/PlayerTest/Rigidbody/PlayerRBHybrid.prefab
Assets/Mirror/Examples/PlayerTest/Rigidbody/PlayerRBReliable.prefab
Assets/Mirror/Examples/PlayerTest/Rigidbody/PlayerRBUnreliable.prefab
Assets/Mirror/Examples/PlayerTest/Tank/TankHybrid.prefab
Assets/Mirror/Examples/PlayerTest/Tank/TankReliable.prefab
Assets/Mirror/Examples/PlayerTest/Tank/TankUnreliable.prefab
Assets/Mirror/Examples/_Common/Controllers/PlayerControllerRB/PlayerControllerRBHybrid.cs
Assets/Mirror/Examples/_Common/Controllers/PlayerControllerRB/PlayerControllerRBReliable.cs
Assets/Mirror/Examples/_Common/Controllers/PlayerControllerRB/PlayerControllerRBUnreliable.cs

- Examples Updated accordingly.

feat(NetworkTransform): Update/FixedUpdate/LateUpdate Enum

---

Assets/Mirror/Tests/Editor/NetworkBehaviour/NetworkBehaviourTests.cs
Assets/Mirror/Tests/Editor/NetworkConnection/LocalConnectionTest.cs
Assets/Mirror/Tests/Editor/NetworkIdentity/NetworkIdentityTests.cs
Assets/Mirror/Tests/Editor/NetworkServer/NetworkServerTest.cs
Assets/Mirror/Tests/Editor/Rpcs/CommandTest.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverNetworkBehaviourTests_IsValid/NetworkBehaviourTargetRpcDuplicateName.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverNetworkBehaviourTests_IsValid/NetworkBehaviourTargetRpcParamNetworkConnection.cs
Assets/Mirror/Tests/Editor/Weaver/WeaverTargetRpcTests_IsSuccess/TargetRpcValid.cs

This is all that's left, and they're intentional

chore(Tests): Update tests to use NetworkConnectionToClient everywhere

---

Assets/Mirror/Components/NetworkTransform/NetworkTransformBase.cs
Assets/Mirror/Core/NetworkBehaviour.cs
Assets/Mirror/Editor/NetworkBehaviourInspector.cs

Elimintate NetworkTransformBase dependency

fix(NetworkBehaviourInspector): Use showSyncMethod

---

Assets/Mirror/Components/NetworkName.cs
Assets/Mirror/Components/NetworkName.cs.meta

donated from ummorpg, useful all the time

feat: NetworkName component

---

Assets/Mirror/Core/NetworkBehaviour.cs
Assets/Mirror/Core/NetworkIdentity.cs

feat: NetworkBehaviour/NetworkIdentity 'isHost'

---

Assets/Mirror/Editor/Weaver/Processors/CommandProcessor.cs
Assets/Mirror/Editor/Weaver/WeaverTypes.cs
Assets/Mirror/Tests/Editor/NetworkServer/NetworkServerTest.cs
Assets/Mirror/Tests/Editor/Rpcs/CommandTest.cs

fix: #4046 [Command]s are now immediately invoked in host mode in order to fix edge cases & race conditions
