- appveyor.yml
Zip the output folder, so that users can easily download and install the builds from appveyor.
> Zip up the output folder

- Unity-Technologies-networking/Runtime/NetworkBehaviour.cs
- Unity-Technologies-networking/Runtime/NetworkIdentity.cs
`GetDirtyChannel`  is a combination of 2 features:  dirtiness and network channel.
These 2 features are independent of each other.  Combining them in a single method violates the [Single Responsibility principle](https://en.wikipedia.org/wiki/Single_responsibility_principle)
This makes the code easier to read.  Channels are not dirty,  so `GetDirtyChannel` makes no sense.
Note `GetDirtyChannel` was internal so it is not used outside HLAPI.
This also avoids magic numbers "-1".    In general, if you have to explain it in a comment,  it is probably bad code.
> Separate dirtiness and network channel

- Unity-Technologies-networking/Weaver/UNetBehaviourProcessor.cs
Simplify the generated OnSerialize.  Code is 100% equivalent.
I split the work in 2 commits:  one that does the actual change,  and another that adds a bunch of comments to make it easier to understand what is being generated.
Here is an example class:
```
public class SampleBehavior : NetworkBehaviour
{
[SyncVar]
public int intData;
[SyncVar]
public string strData;
public SyncListInt intsynclist = new SyncListInt();
}
```
Here is what was generated before:
```
public override bool OnSerialize(NetworkWriter writer, bool forceAll)
{
if (forceAll)
{
writer.WritePackedUInt32((uint)this.intData);
writer.Write(this.strData);
SyncListInt.WriteInstance(writer, this.intsynclist);
return true;
}
bool flag = false;
if ((base.get_syncVarDirtyBits() & 1uL) != 0uL)
{
if (!flag)
{ …
```
> Simplify onSerialize generation

- Unity-Technologies-networking/Runtime/NetworkIdentity.cs
Fix issue #11 
When we send a spawn message to a client,  don't reset the dirty bits, because we might still need to synchronize existing clients.
> Clear dirty bits only during synchronization,  not during spawn

- Mirror/Runtime/NetworkWriter.cs
_Ported to Mirror from original @paulpach PR._
This is a no-op with BinaryWriter/MemoryStream, but this is necesary if we do
any sort of transformation, such as BitWriter, compression or encryption.
> Flush when sending message

- Mirror/Runtime/NetworkIdentity.cs
OnStartAuthority throws NPE when there is more than one NetworkIdentity in a gameobject.  
This PR improves the error message and gives the developer a hint about what to do.
> Print a more informative error than NPE

- Mirror/Runtime/NetworkIdentity.cs
Not all users have a NetworkManager,  and they should not have to.
This method needs to be public so that users can call it if they don't have a NetworkManager
> Make method public

- Mirror/Runtime/NetworkClient.cs
If the user wants to send messages after the connection,  we need to ensure the connection is in a valid state before calling the handler.
Should fix issue #35
> set the state to connected before message handler

- Unity-Technologies-networking/Runtime/NetworkWriter.cs
This is a no-op with BinaryWriter/MemoryStream,  but this is necesary if we do
any sort of transformation,  such as BitWriter, compression or encryption
> Flush when starting or finishing a message.

- Unity-Technologies-networking/Runtime/NetworkServer.cs
People should not need to cast to short when calling RegisterHandler.   Everyone using RegisterHandler in HLAPI gets compilation errors when switching to HLAPI CE. 
This pull request fixes those compilation errors.
> Add source compatibility with HLAPI,  people should not need to cast

- Mirror/Runtime/NetworkClient.cs
- Mirror/Runtime/NetworkServer.cs
Register and Unregister handlers can receive the enumeration without casting.
This avoid compilation errors for people migrating from HLAPI,  and enforces type safety when using MsgType
> Type safe register/unregister handlers

- Mirror/Runtime/NetworkReader.cs
- Mirror/Runtime/NetworkWriter.cs
- Mirror/Tests/NetworkWriterTest.cs
byte array sizes are now varinted, so that we can serialize large arrays.
> Allow for serializing large arrays.  Fix #42

- Mirror/Runtime/NetworkManager.cs
- Mirror/Runtime/Transport/Transport.cs
- Mirror/Tests/NetworkWriterTest.cs
This fixes the unit tests,  by avoiding initializing the transport prematurely.
> Initialize transport in network manager

- Mirror/Runtime/NetworkAnimator.cs
This is an old pull request that I made in the UNET repo that never got merged:
https://bitbucket.org/Unity-Technologies/networking/pull-requests/21/cache-animator-parameters-to-avoid/diff
> This is a simple optimization to minimize the amount of calls to the `Animator.parameters` getter which turns out to be an extremely costly operation.
> *  Profiler before: https://i.imgur.com/2hDW2Lf.png
> *  Profiler after: https://i.imgur.com/tjeb0Fi.png
Keep in mind that we could go with this even *further* and cache the parameters in the NetworkAnimator object to avoid allocations completely. However, I'm not sure how that would behave in practice, especially in development. The developer could tweak the parameters at runtime - maybe we could handle that separately as a specific `#if …
> Network animator optimizations

- Mirror/Runtime/ClientScene.cs
- Mirror/Runtime/ExponentialMovingAverage.cs
- Mirror/Runtime/Messages.cs
- Mirror/Runtime/Mirror.Runtime.csproj
- Mirror/Runtime/NetworkClient.cs
- Mirror/Runtime/NetworkServer.cs
- Mirror/Runtime/NetworkTime.cs
- Mirror/Runtime/Transport/LLAPITransport.cs
- Mirror/Runtime/Transport/TelepathyTransport.cs
- Mirror/Runtime/Transport/TelepathyWebsocketsMultiplexTransport.cs
- Mirror/Runtime/Transport/Transport.cs
- Mirror/Runtime/UNetwork.cs
- Mirror/Tests/ExponentialMovingAverageTest.cs
- Mirror/Tests/Mirror.Tests.csproj
NetworkClient and NetworkServer  now send a ping/pong message back and forth with times.
The times are used to synchronize clocks as well as calculate rtt.
The statistics are updated using EMA to smooth out erratic network behavior.
> Synchronize network time and calculate rtt

- Mirror/Weaver/UNetBehaviourProcessor.cs
- Mirror/Weaver/Weaver.cs
https://github.com/vis2k/Mirror/issues/29
Based on the issue above. These two fixes should improve compatibility with the new compiler.
> Incremental compiler compatibility fixes

- Mirror/Runtime/UNetwork.cs
Method is not used,
Also it is horribly inefficient,  this should use string.join  or StringBuilder instead
> Remove unused inefficient method

- Mirror/Runtime/NetworkReader.cs
- Mirror/Runtime/NetworkWriter.cs
64 bits packing produces the same exact values bit by bit for values 32 bits or less.
> reuse packing algorithm for 32 and 64 bits

- Mirror/Runtime/NetworkIdentity.cs
It was assumed that CacheBehaviours was called to set m_NetworkBehaviours
With this change, the dependency is no longer there,  the behaviours are simply cached the first time they are used
> Ensure network behavior cache consistency

- Mirror/Runtime/ClientScene.cs
- Mirror/Runtime/Messages.cs
- Mirror/Runtime/NetworkBehaviour.cs
- Mirror/Runtime/NetworkIdentity.cs
- Mirror/Runtime/NetworkServer.cs
If you add the same NetworkBehaviour twice to a gameobject, only the commands in the first one work.
This can also happen if you have a base class, you inherit it, and you add more than one of the inherited classes to the same gameobject.
It should fix issue #75 for commands, ClientRpc, TargetRPC and SyncEvents.
> Fix #75, determine the RPC target

- Mirror/Weaver/Weaver.cs
When we try to generate a reader for a class that references itself,  we have infinite recursion and editor crash
This PR stops the infinite recursion and displays an error instead just like with writers
> Fix #91 editor crash

- Mirror/Runtime/SyncList.cs
- Mirror/Tests/SyncListTest.cs
C# has events for this kind of things.
The problem with callback is that if 2 separate objects want to get called back,  they will override each other's callbacks, a subtle and difficult to debug problem.
> Use standard C# events instead of one callback

- Mirror/Runtime/CustomAttributes.cs
- Mirror/Runtime/LocalConnections.cs
- Mirror/Runtime/NetworkBehaviour.cs
- Mirror/Runtime/NetworkConnection.cs
- Mirror/Runtime/NetworkServer.cs
- Mirror/Runtime/Transport/LLAPITransport.cs
- Mirror/Runtime/Transport/TelepathyTransport.cs
- Mirror/Runtime/Transport/TelepathyWebsocketsMultiplexTransport.cs
- Mirror/Runtime/Transport/Transport.cs
- Mirror/Runtime/UNetwork.cs
- Mirror/Weaver/UNetBehaviourProcessor.cs
To send a message via unreliable channel do:
```
// Start your messages at 50+
short CustomMessageID = 50;
NetworkMessage message = new MyCustomMessage();
connection.Send(CustomMessageID, message, Channels.DefaultUnreliable);
```
Register a handler for CustomMessageID on the other end as usual.
Use LLAPI transport:   in your NetworkManager add this:
```
public override void InitializeTransport()
{
Transport.layer = new LLAPITransport();
}
```
Note that the channel is ignored if you are using Telepathy.
> Allow for sending message on unreliable channels

- Mirror/Runtime/NetworkServer.cs
Fixes a bug: When you have NetworkManager unticked for server bind to ip and have the server bind address blank, it in fact passes "127.0.0.1" to ServerStart. The fix passes null if nothing is specified in which case the server should not bind to a IP.
This has not been an issue before as TelepathyTransport.cs ignores the passed value.
Should consider adding the functionality to Telepathy.
> hard coded bind to 127.0.0.1 on other transports

- Mirror/Runtime/NetworkManagerHUD.cs
If the application starts in headless mode,   the HUD should just start a server immediately since nobody can click the buttons.
> Start server if headless mode

- Mirror/Weaver/UNetBehaviourProcessor.cs
The restriction is arbitrary.  Let the user use any name they want.
> Don't require Cmd, Rpc and Target prefixes

- Mirror/Runtime/NetworkConnection.cs
- Mirror/Runtime/Transport/LLAPITransport.cs
- Mirror/Runtime/Transport/TelepathyTransport.cs
- Mirror/Runtime/Transport/TelepathyWebsocketsMultiplexTransport.cs
- Mirror/Runtime/Transport/Transport.cs
so different channels can have different max packet sizes.
Useful for transports where you have an unreliable channel that's limited differently, for example to MTU size.
> Added int channelId to GetMaxPacketSize

- Mirror/Runtime/NetworkClient.cs
- Mirror/Runtime/NetworkServer.cs
NetworkClient.cs was unable to load the scene on connect under certain circumstances. This was because NetworkClient.pauseMessageHandling had been set to false on a previous failed connection attempt. On a subsequent connect it would then never accept messages after it connected successfully so didnt know to load the scene. Simple fix to set NetworkClient.pauseMessageHandling to false when connecting. It should never be true at this point.
> Network client stale pause message handling

- Mirror/Runtime/NetworkClient.cs
- Mirror/Runtime/NetworkServer.cs
NetworkServer.cs was not clearing connections on stopping. This meant when then starting again it was trying to communicate with old connections. Simply clear the list in DisconnectAllConnections. Also put in InternalListen for just in case as there should never be any connections at that point.
> Network server stale connections

- Mirror/Runtime/NetworkServer.cs
When the server shut down,  all clients are disconnected,  but we were not calling OnDisconnect for the in the server
so we did not clean up their objects
> Fix #133, destroy all objects when server shutdowns

- Mirror/Runtime/NetworkIdentity.cs
Creating the sync message is expensive to do every frame.
With this change we check if there is anything to send before we make the message.  This should have the  same performance gains than #124
> Check if any component is dirty before serializing stuff

- Mirror/Runtime/NetworkConnection.cs
This really helps with debugging,  with this PR  you get messages such as:
```
ConnectionRecv con:0 msgType:SpawnPrefab content:8D-DA-08-DC-F2-14-9B-40-A4-99-53-26-37-08-1C-B7-F1-00-00-C0-C2-00-00-00-00-00-00-00-C2-00-00-00-80-00-00-00-80-00-00-00-80-00-00-80-3F-01-20-03-AB-A0-FF-FF-FF-E0-FF-FF-FF-FF-FF-FF-FF-01-08-01-00-00-00-00-00-00-00-00-00-00-00-17-00-00-AB
```
instead of the cryptic
```
ConnectionRecv con:0 msgType:3 content:8D-DA-08-DC-F2-14-9B-40-A4-99-53-26-37-08-1C-B7-F1-00-00-C0-C2-00-00-00-00-00-00-00-C2-00-00-00-80-00-00-00-80-00-00-00-80-00-00-80-3F-01-20-03-AB-A0-FF-FF-FF-E0-FF-FF-FF-FF-FF-FF-FF-01-08-01-00-00-00-00-00-00-00-00-00-00-00-17-00-00-AB
```
> Display message name in ConnectionRecv log

- Mirror/Runtime/NetworkServer.cs
Initialize() is internal and should not be called externally so shouldn't be public
> Initialize() is internal and should not be called externally

- Mirror/Runtime/NetworkManager.cs
It was possible that the headless HUD would try to start the server before initializing the transport
Now the transport is always initialized when the NetworkManager singleton is initialized
> Fix NRE when running headless with HUD

- Assets/Mirror/Runtime/NetworkIdentity.cs
`prefab = (GameObject)PrefabUtility.GetCorrespondingObjectFromSource(gameObject);` was repeated in both cases so should be outside the if. Also removed extra unnecessary { } to be more in keeping with the coding style.
> Minor syntax change - duplicated line

- Mirror/Runtime/NetworkTransform.cs
See the attached video for a comparison of all three compression at different rotation rates. If you cant tell a difference then hopefully that means its not an issue to compress a little more :). The cubes are rotating between 50/100/200 speed*deltaTime in an Update with no VSync. Video at 60fps.
Video: https://www.dropbox.com/s/h2op1du6qdk8gg2/RotationCompressionTest.flv?dl=0
Hint:
Left = No Compression (Float)
Middle = Low Compression (Int16)
Right = High Compression (byte)
> Moved High rotation compression to Low. Added new High

- Mirror/Runtime/SyncList.cs
- Mirror/Tests/SyncListTest.cs
If users try to modify a synclist in the client, it will now complain loudly with an InvalidOperationException
instead of silently doing the change and breaking synclists.
> SyncLists are now readonly in the client

- Mirror/Runtime/NetworkTime.cs
DateTime has potential issues with daylights savings time,  it is not as accurate and is very slow.
Use Stopwatch instead to keep track of server uptime and calculate NetworkTime
> Fix #182,  use Stopwatch to keep track of NetworkTime

- Mirror/Runtime/NetworkTime.cs
When synchronizing time,  keep an upper and lower bound for the time offset and discard values that are not in range.   This can dramatically improve accuracy by eliminating noise introduced by network latency.
Before:
after: 
In the before chart,  the time offset slowly converges towards the optimal time offset.   It takes 40 seconds to synchronize time with the server as it gradually adjusts the offset towards the optimal value.
In the after chart,  you can see that it takes roughly 2 seconds to synchronize time with the server.
> Dramatically improve accuracy of network time

- Mirror/Weaver/Processors/NetworkBehaviourProcessor.cs
This reverts commit 6eec19b205938df356563238cb200864bdd89d4c.
It fails to weave this code:
```cs
class A : NetworkBehaviour  {}
class B: A 
{
[SyncVar] public int pepe;
}```
> Revert "Don't generate OnSerialize/OnDeserialize if not needed (#199)"

- Mirror/Editor/Mirror.Editor.csproj
- Mirror/Runtime/Mirror.Runtime.csproj
- Mirror/Tests/Mirror.Tests.csproj
- Mirror/Weaver/Mirror.Weaver.csproj
- Mirror/Weaver/Weaver.cs
Unity uses c# 4 with old scripting runtime, we should switch mirror projects to use it to be 100% safe that'll be working.
> Fix language version to use one used by unity

- Mirror/Runtime/NetworkBehaviour.cs
consider this case:
```cs
[Command]
public void Cmdaa ()
{
}
[Command]
public void CmdbB()
{
}
```
both have the same hash:  723692803
so only the first one was being registered,  and every time you tried to call the second one the first one got called.
This PR changes it so that mirror detects hash collisions when registering commands and rpc and give the user an error
> Fix #230 Detect hash collisions in rpc registration

- Mirror/Runtime/ClientScene.cs
- Mirror/Runtime/NetworkServer.cs
The RemovePlayerController call sets the playerController to null, causing a null dereference  (and a memory leak as pointed out by @paulpach, since gameobjects are never destroyed)
I haven't tested this code, I just came across it while digging through the internals to figure out some unrelated question, dont see any reason why it shouldn't work though.
This code is also only triggered when the client explicitly asks for the player controller to be removed, as opposed to just closing the whole connection down, which is probably also why this bug hasn't popped up yet.
> Correct order of Destroy in RemovePlayer

- docs/Events/Client.md
It used to mention it being called on the server, which is false
> Corrected doc for OnClientConnect

- Assets/Mirror/Runtime/NetworkManager.cs
I'm using Ignorance which is udp. I can specify my own udp port to use when the transport is initialized in my network manager. But the problem is that I cannot change it at runtime. From my testing, I can change it if I override port to return my udp port instead. I need to be able to change port at runtime in order to connect to different game server port.
> Add virtual to port so that it can be overrided

- Assets/Mirror/Runtime/NetworkManager.cs
If a client tries to connect a server that doesn't exist, it will fail and reload the offline scene (if it's set). It is caused by the `if (newSceneName == networkSceneName)` check in ClientChangeScene and since networkSceneName is empty from the start, it goes ahead and reloads the scene.   
By setting the networkSceneName variable in Awake to the offline scene, it prevents that reload from happening.
> Fixed offline scene reload on client connection fails.

- Assets/Mirror/Editor/NetworkBehaviourInspector.cs
syncInterval resets back to 0.1f (Value that is set in the NetworkBehaviour class) if changed using the editor. The issue is present when changing both, scene objects as well as prefabs.
To reproduce the issue:
1. Create an empty game object
2. add NetworkTransform (+ NetworkIdentity)
4. Save it as a prefab
4. Change syncInterval value
5. Hit play mode
6. Observe the syncInterval value - (gets reset)
> Changed syncInterval value is not saved - fix

- Assets/Mirror/Examples/Movement/Scripts/Move.cs
- Assets/Mirror/Examples/Pong/Scripts/Ball.cs
- Assets/Mirror/Examples/Pong/Scripts/Player.cs
Having objects like "Player" in the default namespace will interfere with a lot of people's code.
Make sure the examples are in their namespace to avoid name collisions with user's scripts.
Note the real change is 3 LOC,  which is the namespaces for the classes.   The rest the patch is just indentation
> Do not pollute default namespace with examples

- Assets/Mirror/Runtime/NetworkIdentity.cs
If there are no clients connected,  or the object has no observers,  there is no need to serialize the data. 
Here is a test with 1000 objects with 3 components each in server only mode with no client
Before:
After:
> Don't serialize the object if there are no observers

- Assets/Mirror/Runtime/NetworkManagerHUD.cs
Users can now turn off that behavior.
This is useful if people want to customize transports before it is auto started
> Start on Headless is optional

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/NetworkManager.cs
if we merge this then we can move NetworkReader.ReadMessage to NetworkMessage. untangles that complexity once and for all.
> OnServerAddPlayer uses NetworkMessage parameter instead of NetworkReader. Removes last dependency on NetworkReader.ReadMessage

- docs/_data/navigation.yml
Part of removing the redundant Contributions page in docs - no point in having two of them.
> Remove navigation to Contributions

- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Runtime/Transport/LLAPITransport.cs
- Assets/Mirror/Runtime/Transport/TelepathyTransport.cs
- Assets/Mirror/Runtime/Transport/Transport.cs
-> only 1 extra LOC
-> people can hook into transport events easily
-> it might be worth making NetworkServer/NetworkClient a component too later, in which case we could setup the callbacks right in the Inspector without any extra code
Note: we could also hide the Transport.cs callbacks in Inspector if that's too much at the moment.
> Dispatch Messages as Events - via UnityEvent

- Assets/Mirror/Runtime/NetworkManager.cs
Immediately after the deleted lines is a call to `OnClientDisconnect(netMsg.conn);` which calls `StopClient();` which has the exact same code on line 344 as what I'm proposing be deleted here.
> Superfluous Code

- docs/Classes/NetworkServer.md
Please see commit https://github.com/vis2k/Mirror/commit/d979a458706077921cabc8bd52efab90a23e7c34
The objects property has been deprecated and is handled by `NetworkIdentity.spawned` dictionary at this time.
> Dictionary 'objects' is no longer present in NetworkServer class

- Assets/Mirror/Runtime/Transport/TelepathyTransport.cs
Found this bug when joining a server using Unity 2018.3 
TelepathyTransport delivers the first message which tells the client to change scenes and load the next scene.
However because the LateUpdate has already started, it doesn't check that this.enabled and processes the rest of the message queue during the scene transition.
Debugged and diagnosed with Paul to find this issue.
> BUG: TelepathyTransport delivers messages even when this.enabled == false across scene loads

- Assets/Mirror/Components/NetworkAnimator.cs
- Assets/Mirror/Editor/NetworkAnimatorEditor.cs
If you have more than 6 variables,  current NetworkAnimator throws an IndexOutOfBoundException.
we do not need the parameters array at all,  it is only used to display it in the editor.
> Fix #371, NetworkAnimator can support more than 6 variables

- docs/Classes/SyncLists.md
SyncList callback functionality is achieved through event handling. I've updated the documentation here to better represent a generic SyncList as well as a custom data type.
> SyncList callback functionality was incorrectly represented

- Assets/Mirror/Runtime/NetworkManager.cs
extremely useful for server-only mode (not only headless).
high tick rate lowers latency (important for shooters)
low tick rate lowers CPU usage (important for MMOs)
> Configurable Server Tickrate

- Assets/Mirror/Runtime/UNetwork.cs
Low hanging fruit,
make NetworkMessage a value type to eliminate allocations.
It does not add any complication.
It works for me,  but needs more testing
> NetworkMessage can be value type.  It eliminates per message allocation

- Assets/Mirror/Editor/PreprocessorDefine.cs
- Assets/Mirror/Editor/PreprocessorDefine.cs.meta
Fix #431 
Adds MIRROR and versioned mirror define so asset developers can easily detect if mirror is available
This is an alternative to #437
> Add MIRROR define and version

- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkWriter.cs
- Assets/Mirror/Runtime/UNetwork.cs
- Assets/Mirror/Tests/NetworkWriterTest.cs
MemoryStream has 3 values:
* Position indicates where we are writing,  useful if you want to go back and rewrite a value such as message length
* Length indicates how much data we have written.  Notice that Position<= Length 
* Capacity indicates how much memory is allocated in the stream.  Notice that Length <= Capacity
When we get the data in a NetworkWriter,  we should always get all the data that was written regardless of position.  When we reset a NetworkWriter.  We should reset the length and position,  but leave the capacity intact so that we can reuse the NetworkWriter without reallocations.
Notice this gets rid of a low hanging fruit allocation in NetworkWriter.  ToArray was allocating the array twice.
Before:
After:
That is a single message sent in the Basic example.
That is …
> Use Length instead of position for getting the written data

- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkWriter.cs
- Assets/Mirror/Runtime/UNetwork.cs
I found .Reset really confusing when the pr was around the first time, but couldn't tell why.
SetLength(0) actually makes a lot of sense. it sets the internal .length. I think it's valuable to have that as function name instead, so everyone knows exactly what it does by just looking at it.
> Rename NetworkWriter.Reset to SetLength(value). Seems more obvious. Reset could mean a lot of things.

- Assets/Mirror/Tests/NetworkWriterTest.cs
As it can be seen, using symbols can be error prone... (The comment on TestWritingLargeMessage claims it is <32kb, yet the test is for >32kb.)
> Expanded symbols in test comments to english.

- Assets/Mirror/Runtime/NetworkBehaviour.cs
This fix reduces GC spike frequency by avoiding List.ForEach. Proof:
Before (List.ForEach version)
After (for loop version)
Here's what a GC spike looks like:
> Remove List.ForEach on hot path.

- Assets/Mirror/Runtime/MessagePacker.cs
- Assets/Mirror/Runtime/MessagePacker.cs.meta
- Assets/Mirror/Runtime/NetworkMessage.cs
- Assets/Mirror/Runtime/NetworkMessage.cs.meta
- Assets/Mirror/Runtime/UNetwork.cs
Reduce the responsibility of UNetwork, by moving out NetworkMessage, MessagePacker, and Utils. Utils is a bad name however, so it is renamed to FloatBytePacker. IsHeadless check is moved into NetworkManager, since no one else uses it, and its equally accessible there.
> First pass of moving stuff out of UNetwork.

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkManagerHUD.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Runtime/Transport/Transport.cs
This is a very simple fix which allows NetworkManager to be more easily replaced. This is the bulk of the references to it.
> Transport.activeTransport instead of NetworkManager.singleton.transport

- Assets/Mirror/Components/NetworkTransformBase.cs
The function sets lastRotation to the current rotation every frame, regardless of whether or not it detected a change. Because comparing two similar, but different Quaternions return true, only quickly rotating objects will return true; slow turning objects will return false, and the rotation will not be synced. By not updating lastRotation until a difference is spotted, any rotation will be synced.
This fix allowed my slow rotating spaceship to sync rotation.
TL;DR
lastRotation should be the last time this function returned true, not the rotation last frame.
> This doesn't sync slow rotating objects

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/NetworkClient.cs
There is no reason why it should be in ClientScene, especially since it passes a NetworkClient, which is very strange. Additionally, not all delegates are in ClientScene anyway (like NetworkTime)
> move RegisterSystemHandlers from ClientScene to NetworkClient

- Weaver/Weaver/Mirror.Weaver.csproj
So there exists a possibility to crash Unity by:
- Doing a weaver debug build for testing
- Doing a weaver release build for pushing
- Waiting for the explosion when Unity runs the AssemblyUpdater.exe
AssemblyUpdater.exe uses Cecil and when it finds your release weaver dll with non matching debug symbols file it will explode. It might just error into console if you are lucky, but it can crash the editor. The exception is:
```
System.InvalidOperationException: Operation is not valid due to the current state of the object.
at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
```
And traces all the way back up to AssemblyUpdater's entry point
These new msbuild post build targets in the Weaver csproj file simply delete any symbol files that might exist in our plugin folder of the …
> extending msbuild to automatically protect against cecil issues

- Assets/Mirror/Components/NetworkAnimator.cs
NetworkAnimator does not have to be on the same game object as the Animator, no reason to require the component really. It doesn't even auto-assign the Animator reference anyways.
> Removed RequireComponent(Animator)

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/LocalClient.cs
- Assets/Mirror/Runtime/MessagePacker.cs
- Assets/Mirror/Runtime/Messages.cs
- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkMessage.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Runtime/NetworkTime.cs
- Assets/Mirror/Runtime/UNetwork.cs
- docs/Concepts/Communications/NetworkMessages.md
Currently,  sending a message looks like this:
```cs
// sending
MyMessage msg = new MyMessage();
connection.send(MsgId, msg);
...
// receiving
public void MsgHandler(NetworkMessage netMsg) {
MyMessage msg= netMsg.ReadMessage<MyMessage>();
...
}
connection.RegisterHandler(MsgId, MsgHandler);
```
This PR makes it so that we can send and receive messages without an explicit message id.  For example:
```cs
// sending
MyMessage msg = new MyMessage();
connection.send(msg);
...
// receiving
public void MsgHandler(MyMessage msg) {
...
}
connection.RegisterHandler<MyMessage>(MsgHandler);
```
This eliminates the possibility of mismatch between the message id and the data values, and makes it a lot easier to add custom messages since the user does not need to ensure message ids are unique or try to …
> #418 Send messages without id

- Assets/Mirror/Components/NetworkLobbyManager.cs
- Assets/Mirror/Examples/Lobby/Scripts/NetworkLobbyPlayerExt.cs
- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/NetworkManager.cs
We are getting rid of NetworkMessage,  so the addplayer methods should not pass a NetworkMessage to the user anymore,  but pass the extra data
> Simplify add player extra data

- Assets/Mirror/Runtime/MessagePacker.cs
- Assets/Mirror/Runtime/Messages.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Runtime/NetworkServer.cs
Now we have the logic of how many bits in just one place and we free up MessageBase for eventually converting to an interface
> Move GetId<T> to MessagePacker

- Assets/Mirror/Runtime/MessagePacker.cs
- Assets/Mirror/Tests/MessagePackerTest.cs
- Assets/Mirror/Tests/MessagePackerTest.cs.meta
Provide a convenient method for unpacking messages.  This is useful for OnServerAddPlayer.
This is how you call AddPlayer:
```cs
class Credentials : MessageBase
{
public string username;
public string password;
}
// now add a player
Credentials credentials = new Credentials() 
{
username = "Joe",
password = "Gabagaba"
};
client.AddPlayer(connection,  MessagePacker.pack(credentials));
// and this is how you receive it:
public override void OnServerAddPlayer(NetworkConnection conn, AddPlayerMessage extraMessage)
{
Credentials credentials = MessagePacker.Unpack<Credentials>(extraMessage.value);
...
}
```
This PR also adds a unit test for packing/unpacking
> Allow users to unpack messages too

- Assets/Mirror/Runtime/Transport/Websocket/Client.cs
- Assets/Mirror/Runtime/Transport/Websocket/ClientJs.cs
- Assets/Mirror/Runtime/Transport/Websocket/Server.cs
- Assets/Mirror/Runtime/Transport/Websocket/WebsocketTransport.cs
Otherwise we have classes named Mirror.Client and Mirror.Server which are very misleading because they are only for websockets
> Websocket transport should be namespaced

- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/UNetwork.cs
This is to finish off the removal of all unnecessary references to UNet.
> Renamed UNetInvokeType to MirrorInvokeType.

- docs/Components/NetworkManager.md
Mention about Awake is removed from startOnHeadless description. It was redundant anyway, imho. And now, in view of [latest commit](https://github.com/vis2k/Mirror/commit/508ba558fc69af651b91bc1144a01f8d9a506b61) to master, it becomes false. 
I also fixed a couple of minor issues.
> Updated docs - Components - NetworkManager.md

- Assets/Mirror/Editor/NetworkInformationPreview.cs
- Assets/Mirror/Editor/NetworkScenePostProcess.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
Fix sceneId bugs once and for all, hopefully.
This version generates a random sceneId of form 0x00FFFFFF in OnValidate and sets the scene dirty to force the user to save it.
OnPostProcessScene then copies a buildIndex byte into it, so 0x00FFFFFF becomes 0x12FFFFFF or similar. This makes sure that sceneIds are unique across scenes.
This works perfectly fine with uMMORPG and NetworkZones.
**Note:** when building a scene that wasn't opened with this Mirror version yet (where the sceneIds weren't set yet), the generated sceneIds won't be saved but an error message will be shown at runtime in OnPostProcessScene that tells the user to resave that scene.
> Persistent sceneid

- Weaver/Weaver/Processors/CommandProcessor.cs
- Weaver/Weaver/Processors/MessageClassProcessor.cs
- Weaver/Weaver/Processors/MonoBehaviourProcessor.cs
- Weaver/Weaver/Processors/NetworkBehaviourProcessor.cs
- Weaver/Weaver/Processors/RpcProcessor.cs
- Weaver/Weaver/Processors/SyncEventProcessor.cs
- Weaver/Weaver/Processors/SyncListProcessor.cs
- Weaver/Weaver/Processors/SyncListStructProcessor.cs
- Weaver/Weaver/Processors/SyncVarProcessor.cs
- Weaver/Weaver/Processors/TargetRpcProcessor.cs
- Weaver/Weaver/Resolvers.cs
- Weaver/Weaver/Weaver.cs
Rather than sprinkling WeaverFailed=true all over the place,  we call a Weaver.Error(message)  where an error occurs.
This way we can enforce consistency in weaver error reporting
> Simplify weaver error handler.

- Assets/Mirror/Components/NetworkAnimator.cs
This should also further improve bandwidth, too, since it now only writes modified variables, and includes a dirtyBits mask to read them out later. The previous implementation was flawed because it was kind of half way between implementations: parameters were only written if they were changed, but no dirty bits were written, so things got busted at deserialization.
> Fixed the NetworkAnimator issue I introduced in the bandwidth fix. 

- Assets/Mirror/Components/NetworkAnimator.cs
Maybe we should do float sync when the Abs of newValue - lastValue > 0.001f
> Fix network animator doesn't sync float value as expected

- Assets/Mirror/Components/NetworkTransformBase.cs
This allows you to leave rotation out of the NetworkTransform if you only need position.
Right now if you don't need to sync rotation and you set compression to Lots, it can move your object in ways not expected. This forces you to use no compression as a fix. Using more bandwidth for something you don't need. I think this is all that is needed, tested it in my game and it works.
> feature: Add NoRotation to NetworkTransform

- Assets/Mirror/Editor/Weaver/Processors/SyncListProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/SyncListProcessor.cs.meta
- Assets/Mirror/Editor/Weaver/Weaver.cs
- Assets/Mirror/Runtime/SyncList.cs
- Assets/Mirror/Tests/WeaverTest.cs
- Assets/Mirror/Tests/WeaverTests~/SyncListStructGenericGeneric.cs
- Assets/Mirror/Tests/WeaverTests~/SyncListStructMemberBasicType.cs
- Assets/Mirror/Tests/WeaverTests~/SyncListStructMemberGeneric.cs
- Assets/Mirror/Tests/WeaverTests~/SyncListStructMemberInterface.cs
- Assets/Mirror/Tests/WeaverTests~/SyncListStructValid.cs
Previously, if you wanted a synclist of structures,  you would do:  `SyncListSTRUCT<MyStruct>`
Now you can use `SyncList<MyStruct>`
SyncListSTRUCT is left there, but obsolete
> feature: SyncList now support structs

- .gitignore
- Assets/Mirror/Runtime/MessagePacker.cs
- Assets/Mirror/Runtime/Messages.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Runtime/NetworkMessage.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Runtime/NetworkWriter.cs
- Assets/Mirror/Tests/MessageBaseTests.cs
- Assets/Mirror/Tests/MessageBaseTests.cs.meta
- Added a `IMessageBase` as an interface to `MessageBase`. Existing messages which inherit `MessageBase` (including ones which do not implement Serialize/Deserialize and rely on the weaver) will continue to work in exactly the same way as before.
- Modified any methods which were generic `T where T : MessageBase` to be `T where T : IMessageBase`. This does not change things at all for all existing usages of the methods.
These changes allow messages to be structs instead of classes. This itself does not make any improvements to performance, but allows a much more efficient use of the API (currently anyone sending a message is forced into allocating). As discussed with @paulpach on Discord, this is a necessary step in his ongoing efforts to replace all Mirror built in messages with structs, …
> refactor: Generic `IMessageBase` to allow struct message types

- Assets/Mirror/Editor/Weaver/Processors/SyncListProcessor.cs
- Assets/Mirror/Tests/WeaverTest.cs
As it turns out this never really worked:
```cs
class SyncListByte : SyncList<byte> {};
```
You had to write your own serializeItem / deserialize item for native types.
This change lifts the restriction, now you can use a synclist of anything that mirror can serialize/deserialize
> feature(synclist): allow SyncList of primitive types

- Assets/Mirror/Editor/Weaver/Processors/SyncListProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/SyncObjectProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/SyncObjectProcessor.cs.meta
- Assets/Mirror/Tests/WeaverTest.cs
SyncList serialization code generator can now be used for syncdict and other structures.
No logic change,  just refactored to make it reusable
> synclist code generator is now reusable

- Assets/Mirror/Runtime/NetworkManager.cs
Fixes #567 
If you want to do your own logic for the target frame rate,  override the "ConfigureServerFramerate" in your network manager class.  for example:
```cs
class MyNetworkManager : NetworkManager 
{
public override void ConfigureServerFrameRate()
{
// configure the frame rate however you want
}
}
```
> refactor: configure frame rate in a virtual method

- Assets/Mirror/Runtime/NetworkClient.cs
The random int representing the Message is less human readable.
> Add the name of the Message back to the debug

- Assets/Mirror/Components/NetworkAnimator.cs
No effect on bandwidth for people who dont use it due to varint.
> Use ulong instead of uint to support up to 64 animator parameters.

- Assets/Mirror/Runtime/NetworkClient.cs
Unnecessary duplicated storage of the address in NetworkClient.
Arguably, addresses *could* be removed entirely from Mirror and left to the transports. They aren't actually used except for 1. logging, and 2. exposing to users. Look at NetworkConnection.address.
> Removed duplicated address storage.

- Assets/Mirror/Runtime/ClientScene.cs
Remove s_ prefix because the entire class is static, the prefix doesn't actually specify anything.
> Remove ClientScene s_ prefix on statics

- Assets/Mirror/Runtime/NetworkServer.cs
Remove s_ prefix because the entire class is static, the prefix doesn't actually specify anything.
> Remove NetworkServer s_ prefix on statics.

- Assets/Mirror/Runtime/ClientScene.cs
These can be private, no one references them outside of ClientScene.
> Internal access modifier removals from methods in ClientScene

- Assets/Mirror/Runtime/NetworkManager.cs
If we are going to keep an obsolete method,  it should still work.
Make that we still call the obsoleted `OnStartClient(NetworkClient)`,  otherwise it would still compile but nothing works,  which is worse than a compilation error.   This code can be removed once we get rid of the `[Obsolete]` method
> fix: call Obsoleted OnStartClient

- Assets/Mirror/Components/NetworkLobbyManager.cs
- Assets/Mirror/Runtime/NetworkManager.cs
Any person that overrides these methods has a broken game.  These methods are never called anywhere.
The user gets a warning because they are overriding an obsolete method,  which might get ignored if they have lots of other warnings.   They would run their game and their game would not work at all.  No errors.
By removing these methods, users that override these methods will get a compile time error instead.  So they can catch this error at compile time instead of at runtime.
> feat: Show compile time error if overriding unused OnServerAddPlayer

- Assets/Mirror/Components/NetworkAnimator.cs
- Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
- Assets/Mirror/Editor/Weaver/Weaver.cs
- Assets/Mirror/Runtime/Messages.cs
- Assets/Mirror/Runtime/NetworkReader.cs
- Assets/Mirror/Runtime/NetworkWriter.cs
- Assets/Mirror/Runtime/SyncList.cs
- Assets/Mirror/Tests/NetworkWriterTest.cs
This implements standard zigzag algorithm.
Previously, it took 5 bytes to serialize -1.   With this PR, small negatives take only 1 byte.
Zigzag is well known and well documented algorithm described here:
https://gist.github.com/mfuerstenau/ba870a29e16536fdbaba
Maps negative values to positive values while going back and forth 
(0 = 0, -1 = 1, 1 = 2, -2 = 3, 2 = 4, -3 = 5, 3 = 6 ...)
> perf: Implement zigzag algorithm so negatives pack efficiently

- Assets/Mirror/Runtime/SyncDictionary.cs
With this constructor,  now syncdictionaries can be used to create SortedLists, SortedDictionary, or any other IDictionary implementation.  For example:
```cs
class MySortedList : SyncDictionary<int, string> {
public MySortedList() : base(new SortedList<int,string>()) {}
}
```
Or any other arbitrary IDictionary implementation.
> feat: SyncDictionary can now be used for any IDictionary

- Assets/Mirror/Runtime/SyncList.cs
Now SyncList can use any IList implementation.   For example:
```cs
class MySyncList : SyncList<int> 
{
public MySyncList() : base(new MyIntList())  {}
}
```
> feat: SyncList now supports any IList implementation

- Assets/Mirror/Runtime/NetworkReader.cs
- Assets/Mirror/Tests/NetworkWriterTest.cs
Note: PackedUInt64 does not have this issue because there is no case for which the initial byte defines an invalid long.
> fix: Potential DOS attack on server by sending packed ulongs when packed uints are expected.

- Assets/Mirror/Tests/NetworkWriterTest.cs
Note: the invalid byte tests pass, this is not a read-corruption test but a write-corruption test. (they are expected to pass.)
> Add more test cases to string read/write.

- Assets/Mirror/Runtime/LocalClient.cs
This file should ship with 1.7 to the Asset Store, and can be removed when 1.8 is ready to publish to the store in a May 2019.
This should avoid causing this mess for users:
> Add LocalClient.cs Dummy for Asset Store

- Assets/Mirror/Tests/NetworkWriterTest.cs
This is gonna take quite a bit of work to correct, but if we truly want to advertise being MMO scale, we need to be stable and endure angry players trying to break our servers. Letting exceptions bubble up to unity, without being handled, stops execution for that tick, and leaves everything else unprocessed, which can cause all sorts of bad things, ranging from not accepting other player's inputs, to not sending packets to any clients at all.
> Add tests for buffer overrun, raising the bar on NetworkReader.

- Assets/Mirror/Runtime/NetworkReader.cs
- Assets/Mirror/Tests/NetworkWriterTest.cs
Also sneaked in two more tests for 0-length byte arrays because the conventional test didnt apply to them, since they didnt throw when there wasnt any data for them.
Also made NetworkReader throw when it can't satisfy a request to read bytes past EOS.
> Fixed NetworkReader tests, everything passes now

- Assets/Mirror/Runtime/NetworkReader.cs
- Assets/Mirror/Tests/NetworkWriterTest.cs
and simplify comments.
checked() is literally a language feature purpose-built for exactly this use case. Lets use it!
All tests pass.
> Use checked() syntax to throw on overflow

- Assets/Mirror/Runtime/NetworkIdentity.cs
this is a breaking change, but really *nobody* should be setting this. To be honest, this dict should be hidden away as an implementation detail. But im not gonna go die on that hill.
> This should have been readonly from day 1

- Assets/Mirror/Runtime/NetworkWriter.cs
- Assets/Mirror/Tests/NetworkWriterTest.cs
There were several problems with WriteBytesAndSize, all are covered by this test:
1. negative count check happened *after* Write(isNull), which meant that you could provide a negative count argument which should be rejected, and have it still write a boolean out, modifying Position.
2. negative count check didnt throw any exception, only logged an error.
All tests pass.
> fix: Added WriteBytesAndSize tests, and fixed the function to be pedantic.

- Assets/Mirror/Tests/NetworkWriterTest.cs
Also added tolerance threshold to Ray normal test since that test was being rickety.
> Add float binary compatibility tests to NetworkWriter

- Assets/Mirror/Runtime/NetworkIdentity.cs
No functionality changes. Figuring out when we should use cache and when we shouldnt is for another PR. This is just to make the name less confusing, because before the two names were identical except for capitalization of the first letter.
> Renamed networkBehaviours to networkBehavioursCache to reduce confusion

- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Runtime/NetworkServer.cs
I'm not sure if this is the correct way to obsolete them, I have a feeling that we might need to add (Un)Register<T>() methods to NetworkConnection. But i wanted to get your feedback first.
> These should have been obsoleted with Paul's Message<T> PR

- Assets/Mirror/Runtime/NetworkManager.cs
IsHeadless() was just added in Feb. 2019, so I wouldn't expect wide usage so quickly, but since there have been 3 asset store publishes since then, it should be obsoleted for a bit.
Also made `isHeadless` camelCase now that it's a property, which made obsoleting it possible.
> Obsoleted IsHeadless()

- Assets/Mirror/Editor/Weaver/Weaver.cs
Notice that cecil disposes the SymbolReader when it disposes the AssemblyDefinition (I checked the source).
It appears that us disposing it ourself causes it to freak out when the AssemblyDefinition is closed
> remove unnecessary manual dispose calls in weaver

- Assets/Mirror/Editor/Weaver/Extensions.cs
- Assets/Mirror/Editor/Weaver/Readers.cs
- Assets/Mirror/Editor/Weaver/Weaver.cs
- Assets/Mirror/Editor/Weaver/Writers.cs
enums are serialized according to their size.
if enum extend byte,  they use 1 byte
if enum extend short, they use 2 bytes
if enum extend int,  they are varinted
if enum extend long, they are varinted
So on average,  most enums will take 1 byte.   Previously they always required 4 bytes
> perf: Reduce enum bandwidth

- Assets/Mirror/Editor/Weaver/CompilationFinishedHook.cs
Loading the assembly to read its refs was causing you to see the JIT compiler shim for netstandard.dll. It only exports types and has no definitions. This is what caused the stack overflow as mono bounced back and forth between two assemblies (mscorlib shim and netstandard shim) both of which exported but did not define the types from mscorlib.
Should be resolved with this, although some errors do pop up when doing the re-import trick. They are from the unity upgrade tool that uses cecil and is likely unhappy about symbols not matching the assembly. Everything still weaves and the errors do not recur. Why this triggers on an import project and not otherwise, I do not know.
> fix: #791 corrected assembly paths passed to weaver

- Assets/Mirror/Editor/Weaver/Weaver.cs
fixes #805
This fixes newly created issues with once again not having correct debug line numbers in backtrace. Also fixed are all other issues related to unity cecil tool errors. My bad for not catching this sooner. Basically we *need* to be writing those symbols out and not doing so was a mistake.
> fix: added new read/write symbol params

- Assets/Mirror/Runtime/NetworkManager.cs
I don't understand why we're forcing position and rotation to be 0,0,0 when a prefab's stored values can be used.
Capsules in particular need to be positioned at least Y>=1 to not fall through a floor that's at Y=0.
We shouldn't need to use a NetworkStartPosition or code an override to get the prefab to spawn where we defined in the prefab.
> fix: Respect Player Prefab Position & Rotation

- Assets/Mirror/Runtime/NetworkManager.cs
- Early out if startPositions.Count = 0
- Reduces the normal returns to single LOC each
- Only resets startPositionIndex if it reaches int.MaxValue
- Uses modulo and increment-after against count to pick round robin index
- Eliminates unnecessary last return that could never be reached
> Simplify GetStartPosition

- Assets/Mirror/Examples/AdditiveScenes/Scripts/PlayerController.cs
- Assets/Mirror/Examples/Lobby/Scripts/PlayerController.cs
- Assets/Mirror/Examples/Lobby/Scripts/Reward.cs
Only the Additive and Lobby examples are changed for their SyncVar's - no testing with uMMORPG needed.
> Avoid memory leak from cloned materials

- Assets/Mirror/Runtime/NetworkClient.cs
This is to achieve parity with NetworkConnection:
```cs
public virtual bool Send<T>(T msg, int channelId = Channels.DefaultReliable) where T: IMessageBase
{
// pack message and send
byte[] message = MessagePacker.Pack(msg);
return SendBytes(message, channelId);
}
```
> fix: Add channelId to NetworkClient.Send Method

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
Added one logging improvement to prevent the entire spawnable dictionary from being dumped during a mismatch.
Added SceneID logging to help diagnose issues with SceneID spawning
> Logging Improvements

- Assets/Mirror/Runtime/NetworkManager.cs
See issue #865 for more details on this, but someone forgot to use `newSceneName`, not `networkSceneName`! This causes Mirror to load the offline scene and not the online scene, causing all sorts of weirdness (like players spawning in the wrong scene, etc).
Tested and confirmed working on the repro project linked in 865. No other ill side effects detected.
> fix(NetworkManager): ClientChangeScene always (re)loads the networkSceneName instead of newSceneName

- Assets/Mirror/Runtime/NetworkManager.cs
Include fix from PR #866.
ClientChangeScene did not use new parameters available for loading scene. 
Scenes would always be loaded in LoadSceneMode.single & LocalPhysicsMode.None on clients.
> fix(NetworkManager) : properly load scene on clients using new load parameters

- Assets/Mirror/Runtime/Transport/Websocket/Ninja.WebSockets/Internal/WebSocketImplementation.cs
- Assets/Mirror/Runtime/Transport/Websocket/WebsocketTransport.cs
This removes the queues implemented in #839 for the reasons described in #874.
It also temporarily removes SSL functionality. It never properly worked in Mirror. After 30-120 seconds all standalone clients or servers will experience the `nested call` issue, which is gamebreaking. The send queues were introduced to fix this and did not work. [According to Unity themselves, asynchronous interleaved write to an SslStream is not possible in Unity.](https://forum.unity.com/threads/unity-2017-1-tls-1-2-still-not-working-with-net-4-6.487415/#post-3561106) There is a possible workaround technique actively being investigated by me and Paul that will come in a separate PR to re-enable SSL.
Testing strategy: this patch has been tested in 3-4 production games and also with 2 Mirror examples, for …
> fix(websocket): Remove send queues and temporarily disable SSL

- Assets/Mirror/Components/NetworkLobbyManager.cs
- Assets/Mirror/Components/NetworkLobbyPlayer.cs
- Assets/Mirror/Examples/Lobby/Scripts/PlayerController.cs
- Assets/Mirror/Runtime/ClientScene.cs
?? and something? don't work with unitys objects, use == null instead.
Tested with Pong Example, due to the nature of changes, it shouldn't cause any issues.
> Remove conditional accesses on unity objects

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/NetworkServer.cs
Allow games where world origin is different for each players (Augmented reality for example) to spawn objects at the right position in the scene.
With PR #779 this should make Mirror a good solution for multiplayer projects running on Hololens, ARCore, ARkit devices.
> Spawn objects in local space instead of world space

- Assets/Mirror/Components/Mirror.Components.asmdef
- Assets/Mirror/Components/Mirror.Components.asmdef.meta
- Assets/Mirror/Editor/Mirror.Editor.asmdef
- Assets/Mirror/Editor/Mirror.Editor.asmdef.meta
- Assets/Mirror/Examples/AdditiveScenes/README.md
- Assets/Mirror/Examples/Mirror.Examples.asmdef
- Assets/Mirror/Examples/Mirror.Examples.asmdef.meta
Mirror is not fully ASMDEF capable (Example scripts can't be referenced from other assemblies). This adds three additional ASMDEFs to make that work.
> ASMDEF for Examples

- Assets/Mirror/Components/NetworkProximityChecker.cs
fix: #840 by allowing Mirror to respect the forceHidden flag on NetworkProximityChecker.
This bug was introduced in ab44ac8 on 4/1/2019
> fix: #840 by allowing Mirror to respect the forceHidden flag

- Assets/Mirror/Editor/Weaver/Processors/CommandProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/MessageClassProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/MonoBehaviourProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/PropertySiteProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/RpcProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/SyncEventProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/SyncObjectInitializer.cs
- Assets/Mirror/Editor/Weaver/Processors/SyncObjectProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/SyncVarProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/TargetRpcProcessor.cs
- Assets/Mirror/Editor/Weaver/Readers.cs
- Assets/Mirror/Editor/Weaver/Resolvers.cs
- Assets/Mirror/Editor/Weaver/Weaver.cs
- Assets/Mirror/Editor/Weaver/Writers.cs
- Assets/Mirror/Tests/WeaverTest.cs
Updated weaver error messages to make them easier for users to fix.  For example:
Before:
After:
> feat: user friendly weaver error messages

- Assets/Mirror/Runtime/NetworkBehaviour.cs
Eliminate this allocation that happens in every remote method call:
> perf: eliminate small allocation on remote calls

- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Runtime/StringHash.cs
Eliminates this allocation during all rpc calls:
> perf: eliminate string concat during remote method calls

- Assets/Mirror/Runtime/NetworkIdentity.cs
Tested with 1000 objects.   
Before:
After:
> perf: Optimize interest management

- Assets/Mirror/Editor/Weaver/Readers.cs
- Assets/Mirror/Editor/Weaver/Weaver.cs
- Assets/Mirror/Editor/Weaver/Writers.cs
When you pass a null array,  don't convert it to empty array.  For example:
```cs
[Command]
public void CmdTest(int [] data, int [] data2,  int [] data3)
{
// data should be null,    mirror was giving []
// data2 should be []
// data 3 should be [3]
}
public void OnClientStart()
{
CmdTest(
null,
new int[] {},
new int [] {3});
}
```
> fix: don't convert null arrays to empty array

- Assets/Mirror/Editor/Weaver/Processors/MessageClassProcessor.cs
- Assets/Mirror/Runtime/Messages.cs
- Assets/Mirror/Runtime/NetworkReader.cs
- Assets/Mirror/Tests/ArraySegmentWriterTest.cs
- Assets/Mirror/Tests/ArraySegmentWriterTest.cs.meta
ReadBytesAndSizeSegment needs to create a new array in case users want to use the ArraySegment after we get rid of the buffer.
> fix: ArraySegment<byte> work in Messages

- Assets/Mirror/Runtime/NetworkBehaviour.cs
On the "death by 1000 cuts" theme,   here is a fix for a small boxing that happens every time you set a value in a syncvar
> perf: remove syncvar boxing

- Assets/Mirror/Runtime/NetworkWriterPool.cs
Similar to #911 ,  but keeping lifecycle management separate from NetworkWriter.
> feat: network writer pool to avoid expensive allocations

- Assets/Mirror/Runtime/NetworkReader.cs
- Assets/Mirror/Runtime/NetworkWriter.cs
- Assets/Mirror/Tests/NetworkWriterTest.cs
Breaks compatibility with older versions, saves 1 byte for non null arrays, doesn't make null arrays the same as empty ones.
> perf: Use 0 for null byte arrays

- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
Uses the new NeworkWriterPool for syncvars
> perf: remove allocations during syncvar sync

- LICENSE
IANAL but my understanding from the MIT license,  is that we cannot modify unity's copyright notice.
But we can add our own copyright notice.  
This should fix this issue
> fix: maintain Unity's copyright notice

- Assets/Mirror/Runtime/NetworkManager.cs
ForceReload is always true, and the only use of it required it to be false, so it's no longer needed.
> Remove ForceReload

- Assets/Mirror/Runtime/Transport/TelepathyTransport.cs
Doing it in Awake and also before assigning to clients skips connection ID 1.
> fix: Don't increment counter in Awake

- Assets/Mirror/Runtime/NetworkMessage.cs
Avoid creating messages in the stack if messages are structs.
When combined with #987 ,  it gets rid of this:
> perf: avoid allocation with message structs

- Assets/Mirror/Runtime/Messages.cs
- Assets/Mirror/Runtime/NetworkTime.cs
I would like to do this for all messages,  let's start with a simple one.
Messages should be value types,  this avoids unnecessary allocations and avoid NPE
It gets rid of this small allocation per message
> perf: ping messages should be value types

- Assets/Mirror/Runtime/Messages.cs
Gets rid of this allocation per rpc call
> perf: rpc messages are now value types

- Assets/Mirror/Runtime/NetworkIdentity.cs
This PR fixes sceneIDs not being set to 0 in prefab variants (#976).
It seems that prefab variants that are loaded in the prefab stage are considered instances of the base prefab. ThisIsASceneObjectWithPrefabParent() returns true and a new sceneId is assigned when opening the prefab variant. Because of this, the next check, where the NetworkIdentity would detect being loaded in a prefab stage, is not executed. Swapping the order of the two checks fixes this.
Per the instructions of @MrGadget1024, I tested this fix with the AdaptiveLoading and Lobby examples and didn't see any issues.
> fix: SceneId was not set to 0 for prefab variants (#976)

- Assets/Mirror/Runtime/NetworkManager.cs
Eliminates the extraneous method by having StopClient (the only caller) call the fuller method directly..
> Simplify ClientChangeScene Call Sequence

- Assets/Mirror/Components/NetworkTransformBase.cs
Closes #999 
Previously only position and rotation were synchronizedin NetworkTransformBase, with this commit scale is synchronized similarly to position.
I played with it a little and it seems to work as expected. (Created an empty project and changed the scale on a NetworkTransform-ed object manually and through a script as well and it synced correctly)
Please let me know if I should do something differently, or write some tests, or whatever else.
> Synchronize scale with NetworkTransformBase

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
NetworkIdentity.OnStartClient(); sets isClient = true so there's no need to set it right before calling it in these three places.
> Remove redundant code

- Assets/Mirror/Runtime/Transport/Websocket/WebsocketTransport.cs
This same change was done in TelepathyTransport.  The counter is incremented when the first client connects so it doesn't need to be done here.  With this change, first client gets ID 1 instead of 2.
> Don't increment counter in constructor

- Assets/Mirror/Runtime/NetworkManager.cs
Functionally the same, but moves safety checks to an internal method that is registered as the handler and calls the virtual method.
From reviewing user code samples, my observation is that when OnServerAddPlayer is overridden, devs often don't call the base method (for good reasons) and never include these safety checks in their override, and IMHO they shouldn't have to.  Virtual methods should be empty or as tiny as possible so that overrides don't have to copy a bunch of code.
> Internalize OnServerAddPlayer Safety Checks 

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
Get rid of the pendingOwnerNetIds  hash table.   Lunacy from Unity
> refactor:  simplify owner initialization

- Assets/Mirror/Editor/NetworkBehaviourInspector.cs
- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/SyncVarTest.cs
+ no weaver magic
+ no breaking projects
+ OnSerialize/OnDeserialize is unchanged
+ OnSerialize is still only called once, not twice (not guaranteed to get same result when calling it twice, also not guaranteed to not break user's timing code if called twice)
+ no attributes/custom tags needed
+ no [SyncVar(owner=true)] SyncListInt magic
+ no dirtyBit magic
+ only a few more lines of code, a lot of it are comments
+ saves computations (only serialize each component once)
+ **Runtime SyncMode changes** supported to go invisible, etc. Previously there was no good way for a player to go truly stealth mode.
+ **Ease of use:** people could set their inventories to OWNER with just a mouse click
> feat: component based SyncToOwner, fixes #39

- Assets/Mirror/Examples/Pong/Prefabs/Ball.prefab
- Assets/Mirror/Examples/Pong/Prefabs/Racket.prefab
- Assets/Mirror/Examples/Pong/Scenes/Scene.unity
- Assets/Mirror/Examples/Pong/Scripts/Ball.cs
- Assets/Mirror/Examples/Pong/Scripts/NetworkManagerPong.cs
- Assets/Mirror/Examples/Pong/Scripts/Player.cs
Individual Commits
- Set Sync Interval to zero for ball and racquet to make it smoother
- Turned off Simulated in Ball prefab and set true in OnStartServer
- Cached GetComponent<Rigidbody2D>() in OnStartServer and OnStartLocalPlayer instead of calling it repeatedly in FixedUpdate
- Used Find to get Ball prefab from Network Manager's Spawnable Prefabs list instead of having a separate field for spawning it
> Updated Pong 2

- Assets/Mirror/Editor/Weaver/Processors/ReaderWriterProcessor.cs
During first import,  the weaver will be called before all assemblies
are built.  No need to look for custom readers and writers if the assemblies
are not built.
fixes #1051
> fix: error with missing assemblies

- Assets/Mirror/Runtime/NetworkManager.cs
For reference, this is what's in `ClientScene.Ready()`
```cs
public static bool Ready(NetworkConnection conn)
{
if (ready)
{
Debug.LogError("A connection has already been set as ready. There can only be one.");
return false;
}
if (LogFilter.Debug) Debug.Log("ClientScene.Ready() called with connection [" + conn + "]");
if (conn != null)
{
conn.Send(new ReadyMessage());
ready = true;
readyConnection = conn;
readyConnection.isReady = true;
return true;
}
Debug.LogError("Ready() called with invalid connection object: conn=null");
return false;
}
```
> Don't call Ready if we're ready already

- Assets/Mirror/Editor/Weaver/Processors/ReaderWriterProcessor.cs
Should speed up build slightly.
If user has old symbols we don't care, so don't give an error.
> No need to read symbols

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
These methods are needed by the profiler to display useful information about the messages
> Expose methods for profiler

- Assets/Mirror/Runtime/NetworkIdentity.cs
Why require the correct owner to be provided, and why return a bool?
Just hand the object back to the server, no matter who owns it, and notify the owner, if there was one.
> Make RemoveClientAuthority easier to use

- Assets/Mirror/Runtime/LocalConnections.cs
- Assets/Mirror/Runtime/MessagePacker.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Runtime/Transport/MultiplexTransport.cs
- Assets/Mirror/Runtime/Transport/TelepathyTransport.cs
- Assets/Mirror/Runtime/Transport/Transport.cs
Transports can choose to implement one of two ServerSend methods.
They can implement 
```cs
public override bool ServerSend(int connectionId, int channelId, byte[] data)
{
// do your thing
}
```
or they can implement:
```cs
public override void ServerSend<T>(IList<int> recipients, int channelId, T msg) 
{
...
}
```
You may want to implement the second one if you want an allocation free transport.
In a similar way,  transports can chose to implement one of two ClientSend methods.
> feat: transports can now send to multiple connections

- Assets/Mirror/Runtime/LocalConnections.cs
- Assets/Mirror/Runtime/MessagePacker.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Runtime/NetworkMessage.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Runtime/Transport/LLAPITransport.cs
- Assets/Mirror/Runtime/Transport/MultiplexTransport.cs
- Assets/Mirror/Runtime/Transport/TelepathyTransport.cs
- Assets/Mirror/Runtime/Transport/Transport.cs
- Assets/Mirror/Runtime/Transport/Websocket/WebsocketTransport.cs
BREAKING CHANGE: transports now must report the channel where they receive the data or -1 if not available
> Transports now give the channel when receiving message

- Assets/Mirror/Editor/Weaver/Processors/CommandProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
This changes how code is generated for commands.
Previously,  it generated code like this:
```cs
private void CmdUpdate(int something, string other)
{
Debug.Log((object)$"id {something} data {other}");
}
private void Update()
{
if (base.isClient && Input.GetKeyDown(32))
{
CallCmdUpdate(playerNo, playerData.ToString());
}
if (base.isLocalPlayer)
{
image.set_color(new Color(1f, 1f, 1f, 0.1f));
}
playerNameText.set_color(playerColor);
playerNameText.set_text($"Player {playerNo:00}");
playerDataText.set_text($"Data: {playerData:000}");
}
private void MirrorProcessed()
{
}
protected static void InvokeCmdCmdUpdate(NetworkBehaviour obj, NetworkReader reader)
{
if (!NetworkServer.active)
{
Debug.LogError((object)"Command CmdUpdate called on client.");
}
else
{ …
```
> fix: Cmds can be called from any assembly, fix #1108

- Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/RpcProcessor.cs
Similar to #1128 but for client rpc
> fix: ClientRpc methods now work accross assemblies

- Assets/Mirror/CompilerSymbols.meta
- Assets/Mirror/CompilerSymbols/Mirror.CompilerSymbols.asmdef
- Assets/Mirror/CompilerSymbols/Mirror.CompilerSymbols.asmdef.meta
- Assets/Mirror/CompilerSymbols/PreprocessorDefine.cs
- Assets/Mirror/CompilerSymbols/PreprocessorDefine.cs.meta
- Assets/Mirror/Editor/PreprocessorDefine.cs
- Assets/Mirror/Runtime/Mirror.asmdef
**The Paradox:**
Compiler errors prevented the editor script from adding the symbol that would cure them.
Move the PreprocessorDefine script to its own folder "CompilerSymbols" with its own AsmDef, and make Mirror's core AsmDef dependent on it to force the MIRROR_4_0_OR_NEWER symbol to get added first so that all the transports and whatever else can compile.
An empty PreprocessorDefine.cs is left in the Editor folder to replace the old one to prevent duplicates when upgrading.
> fix: Prevent Compiler Paradox

- Assets/Mirror/Runtime/SyncSet.cs
Allows usage of custom Equality Comparers in SyncHashSet.
Doesn't need any changes because HashSet properly supports custom IEqualityComparers.
> SyncHashSet custom Equality Comparer support

- Assets/Mirror/Editor/Weaver/Processors/SyncVarProcessor.cs
- Assets/Mirror/Editor/Weaver/Weaver.cs
- Assets/Mirror/Runtime/NetworkBehaviour.cs
This is the generated code before:
```cs
public int NetworkplayerData
{
get
{
return playerData;
}
[param: In]
set
{
if (NetworkServer.localClientActive && !getSyncVarHookGuard(4uL))
{
setSyncVarHookGuard(4uL, value: true);
OnPlayerDataChanged(value);
setSyncVarHookGuard(4uL, value: false);
}
SetSyncVar(value, ref playerData, 4uL);
}
}
```
This is the generated code after:
```cs
public int NetworkplayerData
{
get
{
return playerData;
}
[param: In]
set
{
if (!SyncVarEqual(value, ref playerData))
{
if (NetworkServer.localClientActive && !getSyncVarHookGuard(4uL))
{
setSyncVarHookGuard(4uL, value: true);
OnPlayerDataChanged(value);
setSyncVarHookGuard(4uL, value: false);
}
SetSyncVar(value, ref playerData, 4uL);
}
}
}
```
> fix: don't call hook in host if no change,  fixes #1142

- Assets/Mirror/Editor/NetworkInformationPreview.cs
hasAuthority and isLocalPlayer can change at runtime.  This window needs to reflect those changes.
> Refresh Data For Preview Window

- Assets/Mirror/Editor/Weaver/Processors/MessageClassProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/SyncVarProcessor.cs
- Assets/Mirror/Editor/Weaver/Readers.cs
- Assets/Mirror/Editor/Weaver/Writers.cs
- Assets/Mirror/Tests/WeaverTest.cs
reported by smasson99 in discord.
Syncvars are not working for scriptable objects.  This allows people to make custom serializers for:
* Scriptable Objects
* Network Behaviours
* Generics
* Interfaces
> feat: Users may provide custom serializers for any type

- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
Server always has "god rights" on everything.  Host Player needs to act like a client as much as possible, so should only have `hasAuthority == true` if explicitly assigned.
This PR only effects scene and spawned objects.
Player objects that have Local Player Authority checked are not effected, nor are objects spawned via `NetworkServer.SpawnedWithClientAuthority()`.
Fixes #959
> fix: Don't give host player authority by default

- Assets/Mirror/Runtime/NetworkManager.cs
Fixes #1159 
When `NetworkManager.ServerSceneChange` is invoked, it's possible for client to change scenes and return a Ready message to server before the server has finished changing scenes.  Without this fix, server fires off a spawn message to that client of all the objects in the prior scene, resulting in the image below.
With this change, server transport is paused until FinishScene re-enables it, and any Ready messages held in abeyance are correctly handled in the context of the new scene.
> fix: Suspend server transport while changing scenes

- Assets/Mirror/Editor/NetworkIdentityEditor.cs
- Assets/Mirror/Editor/NetworkInformationPreview.cs
- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/MessagePacker.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Runtime/NetworkServer.cs
use ToString to display connections.
Users should not need the connection id at all.  That should be encapsulated by mirror.
This is the first of many patches that clean up connections
> refactor:use ToString() to display connections

- Assets/Mirror/Runtime/NetworkServer.cs
Don't force authority in `SetupLocalPlayerForConnection` because `SetLocalPlayer` that immediately follows will set it correctly in any case.
This is called by `AddPlayerForConnection` and `InternalReplacePlayerForConnection`, neither of which need authority to be forced here.
This PR will be followed by a couple more to simplify authority, especially with regard to the host player.
`SetLocalPlayer` and `SetNotLocalPlayer` can likely be simplified after this is merged.
Baby steps.
> Remove Authority Set

- Assets/Mirror/Runtime/NetworkServer.cs
Spawn calls SpawnObject which calls Reset which sets hasAuthority = false so calling ForceAuthority(false) does nothing:
```cs
internal void ForceAuthority(bool authority)
{
if (hasAuthority == authority)
{
return;
}
```
> Remove redundant force authority

- Assets/Mirror/Runtime/LocalConnections.cs
- Assets/Mirror/Runtime/NetworkClient.cs
Local connections should now be testable.   They don't depend on a static global queue,  rather they manage an internal queue of messages.  The local connection objects now keep a reference to each other
> refactor: local connections maintain their own queue

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
gets rid of pendingLocalPlayer,
instead the ClientScene keeps track of which object was the player in the already existing variable.
> Simplify local player setting

- Assets/Mirror/Components/NetworkAnimator.cs
- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
This flag does not do anything useful in anything but NetworkAnimator, and confuses the hell out of everyone.
so NetworkAnimator can keep it's own (much more readable) flag.
> breaking: Remove localPlayerAuthority

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/Messages.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkServer.cs
Previously there were 2 separate messages:
* SpawnPrefabMessage
* SpawnSceneObjectMessage
These were almost the same, except that one of them had an assetId and the other had a sceneId.  The spawning logic also had a lot in common.
This PR changes it to just SpawnMessage.   The spawn message either has a sceneId or it has an assetId, and the client uses that to locate the object to be spawned.
> refactor: Simplify spawn message

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
Previously,  in master when spawning the sequence was:
1)  Begin spawn
2) spawn  object
3) spawn object
4) spawn player  (client sets pendingOwner = true)
5) spawn object
6) End spawn  (client loops through all spawned objects looking for the one with pendingOwner = true and initializes it as local player)
With this PR,  logic is simpler:
1)  Begin spawn
2) spawn  object
3) spawn object
4) spawn player  (client sets ClientScene.localPlayer = object)
5) spawn object
6) End spawn  (client initializes localPlayer as local player)
> refactor: remove pending Owner

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Runtime/NetworkTime.cs
Most message handlers in the client don't really need the connection object.  So make it optional.  Note this does not break anything,  handlers with connection still work fine.
> feat: NetworkConnection is optional for handlers

- Assets/Mirror/Components/NetworkAnimator.cs
- Assets/Mirror/Editor/NetworkInformationPreview.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
connectionToClient is now used for player and for owned objects.
> refactor: reuse connectionToClient for authority

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/Messages.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
Now when Authority is granted/removed,  we respawn the object,  which resets all the variables and authority (does not create a new one).
With this change, sync2owner should work with authority.
fixes #1061
> feat: SyncToOwner now works with authority

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
Player object in host mode does not need special case.  Follow the same code path as client/server mode.  This reduces a lot of complexity and makes host mode more consistent with client/server mode.
> refactor: Remove special case for host mode

- Assets/Mirror/Runtime/NetworkBehaviour.cs
Per @GabeBigBoxVR this was a useful fix for us!
> fix: Pass the name of the invoking class and desired command when an object has no authority.

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/UNetwork.cs
Spawn handler should receive entire message,  not just position.  Note this PR keeps backwards compatibility.
Before,  this is how you would register a spawn handler:
```cs
public GameObject MySpawnHandler(Vector3 position, Guid guid)
{
//  hmmm,  I don't have access to the rotation or scale,  only the position.
return Instantiate(myPrefab);
}
public void Start()
{
ClientScene.RegisterSpawnHandler(myguid,  MySpawnHandler,  myUnspawnHandler);
}
```
That still works fine.
But now you can instead register a handler that receives the message:
```cs
public GameObject MySpawnHandler(SpawnMessage msg)
{
// yay,  now I have access to position, rotation, scale,  or anything else in SpawnMessage
return Instantiate(msg.position, msg.rotation, myPrefab);
}
public void Start()
{ …
```
> feat: Pass SpawnMessage to spawn handler

- Assets/ScriptTemplates/50-Mirror__Network Manager-NewNetworkManager.cs.txt
- Assets/ScriptTemplates/50-Mirror__Network Manager-NewNetworkManager.cs.txt.meta
- Assets/ScriptTemplates/51-Mirror__Network Authenticator-NewNetworkAuthenticator.cs.txt
- Assets/ScriptTemplates/51-Mirror__Network Authenticator-NewNetworkAuthenticator.cs.txt.meta
- Assets/ScriptTemplates/52-Mirror__Network Behaviour-NewNetworkBehaviour.cs.txt
- Assets/ScriptTemplates/52-Mirror__Network Behaviour-NewNetworkBehaviour.cs.txt.meta
- Assets/ScriptTemplates/53-Mirror__Network Room Manager-NewNetworkRoomManager.cs.txt
- Assets/ScriptTemplates/53-Mirror__Network Room Manager-NewNetworkRoomManager.cs.txt.meta
- Assets/ScriptTemplates/54-Mirror__Network Room Player-NewNetworkRoomPlayer.cs.txt
- Assets/ScriptTemplates/54-Mirror__Network Room Player-NewNetworkRoomPlayer.cs.txt.meta
This adds script templates to Mirror for improved ease of use.
Given all the virtual methods we have in these classes, users invariably need to make their own custom versions of them that inherit from ours.  These templates have all the available overrides included, calling base methods where necessary, and are fully documented with summary comments so devs can easily learn what all is available to them and what everything does as a supplement to the docs.
Notes:
- The ScriptTemplates folder has to be in the root Assets folder for Unity to find it.  It won't work from inside the Mirror folder.
- The naming of the files is specific to Unity and the pattern it expects.
- Just like the Add Component menu, Unity must be restarted after Mirror is imported for the menus to show these templates. …
> feat: Script Templates

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
hasAuthority is now guaranteed to be set before OnStartClient:
Before, for host mode player:
```
OnStartServer IsClient True  isServer True hasAuthority False localPlayer False
OnStartClient IsClient True  isServer True hasAuthority False localPlayer True
OnStartLocalPlayer Client IsClient True  isServer True hasAuthority True localPlayer True
OnStart IsClient True  isServer True hasAuthority True localPlayer True
```
After:
```
OnStartServer IsClient True  isServer True hasAuthority False localPlayer False
OnStartClient IsClient True  isServer True hasAuthority True localPlayer True
OnStartLocalPlayer Client IsClient True  isServer True hasAuthority True localPlayer True
OnStart IsClient True  isServer True hasAuthority True localPlayer True
```
Note ideally they would all be true,  more …
> fix: set hasAuthority before calling OnStartClient

- Assets/Mirror/Components/NetworkAnimator.cs
- Assets/Mirror/Editor/NetworkInformationPreview.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
NEED TO TEST AGAIN.
**NetworkServer.InternalReplacePlayerForConnection (line 898) is new here. make sure this makes sense.**
* refactor: reuse connectionToClient for authority
* Fix compilation issue
* Make PR easier to read
* Better error message
* Update Assets/Mirror/Runtime/NetworkIdentity.cs
Co-Authored-By: @MrGadget1024
> refactor: reuse connectionToClient for authority (#1200)

- Assets/Mirror/Runtime/ClientScene.cs
This method has several problems:
* During the first spawn,  it does nothing at all.  The object has not been spawned at this point yet,  so this method can't find it and just exits.
* If the player is respawned, Then this method will call SetNotLocalPlayer and then call InternalAddPlayer again,  even if the player has not changed.
* If the player does change, then the if I added in CheckForLocalPlayer calls SetNotLocalPlayer for the previous player.
* This method is never called in host mode,  so host mode and client mode behave differently when the local player is spawned or is changed. 
* It is redundant,  all the stuff done in here is done again in CheckForLocalPlayer
> fix: remove problematic OnSpawnMessageForLocalPlayer

- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkServer.cs
In Master,  OnStartServer is called before host mode is properly initialized,  which causes the hooks not to fire.
Consider this code:  
```cs
public class PlanetsSpawner : NetworkBehaviour   //  Create Server Only GabeObject in Scene
{
public GameObject Planet;
public override void OnStartServer()
{
base.OnStartServer();
for (int i = 0; i < 5; i++)
{
GameObject planet = Instantiate(Planet, new Vector3(Random.Range(-5f, 5f), Random.Range(-5f, 5f), 0), 
Quaternion.identity);
// this does not fire the hook in host mode.  
// if this code is in a method after OnStartServer,  the hook fires fine.
planet.GetComponent<Planet>().Clr = Random.ColorHSV();
NetworkServer.Spawn(planet);
}
}
}
public class Planet : NetworkBehaviour   // This is for prefab to by spawned as Planet
{
[SyncVar(hook = …
```
> fix: Call hooks when initializing objects OnStartServer on host

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
See #1250
Before:
```
Void Awake() hasAuthority=False isClient=False isLocalPlayer=False
Void OnStartServer() hasAuthority=False isClient=False isLocalPlayer=False
Void OnStartClient() hasAuthority=False isClient=True isLocalPlayer=False
Void OnStartAuthority() hasAuthority=True isClient=True isLocalPlayer=True
Void OnStartLocalPlayer() hasAuthority=True isClient=True isLocalPlayer=True
Void Start() hasAuthority=True isClient=True isLocalPlayer=True
```
After:
```
Void Awake() hasAuthority=False isClient=False isLocalPlayer=False
Void OnStartServer() hasAuthority=True isClient=False isLocalPlayer=False
Void OnStartClient() hasAuthority=True isClient=True isLocalPlayer=False
Void OnStartAuthority() hasAuthority=True isClient=True isLocalPlayer=True
Void OnStartLocalPlayer() …
```
> fix: hasAuthority is now visible in all overrides

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
See #1250
Before:
```
Void Awake() hasAuthority=False isClient=False isLocalPlayer=False
Void OnStartServer() hasAuthority=False isClient=False isLocalPlayer=False
Void OnStartClient() hasAuthority=False isClient=True isLocalPlayer=False
Void OnStartAuthority() hasAuthority=True isClient=True isLocalPlayer=True
Void OnStartLocalPlayer() hasAuthority=True isClient=True isLocalPlayer=True
Void Start() hasAuthority=True isClient=True isLocalPlayer=True
```
after
```
Void Awake() hasAuthority=False isClient=False isLocalPlayer=False
Void OnStartServer() hasAuthority=False isClient=False isLocalPlayer=True
Void OnStartClient() hasAuthority=False isClient=True isLocalPlayer=True
Void OnStartAuthority() hasAuthority=True isClient=True isLocalPlayer=True
Void OnStartLocalPlayer() …
```
> fix: isLocalPlayer works in host mode onStartServer

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
If you replace a player,  the old player should remain attached to the connection.
Following the single responsibility principle,  we should not try to combine these 2 actions in one method.
> fix: replacing the player does not mean giving up authority

- Assets/Mirror/Runtime/ClientScene.cs
related to #1250 but for client mode.
Before:
```
Void Awake() hasAuthority=False isClient=False isLocalPlayer=False
Void OnStartClient() hasAuthority=True isClient=True isLocalPlayer=False
Void OnStartAuthority() hasAuthority=True isClient=True isLocalPlayer=False
Void OnStartLocalPlayer() hasAuthority=True isClient=True isLocalPlayer=True
Void Start() hasAuthority=True isClient=True isLocalPlayer=True
```
After:
```
Void Awake() hasAuthority=False isClient=False isLocalPlayer=False
Void OnStartClient() hasAuthority=True isClient=True isLocalPlayer=True
Void OnStartAuthority() hasAuthority=True isClient=True isLocalPlayer=True
Void OnStartLocalPlayer() hasAuthority=True isClient=True isLocalPlayer=True
Void Start() hasAuthority=True isClient=True isLocalPlayer=True
```
> fix: isLocalPlayer is true during OnStartClient for Player

- Assets/Mirror/Runtime/NetworkIdentity.cs
No need to keep track of this state per object.   Either all object are server objects or none of them are.
> Simplify isServer

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
In the room example,  OnStartLocalPlayer is called twice
> fix: don't call OnStartLocalPlayer twice

- Assets/Mirror/Components/NetworkRoomManager.cs
`ReplacePlayerForConnection` strips authority so this reapplies it.
> Restore Room Player Authority

- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/ScriptTemplates/50-Mirror__Network Manager-NewNetworkManager.cs.txt
I put this overload in and later determined that I can't extend ServerChangeScene the way I thought.  Since these extra parameters were never wired up to anything, no one could be using this method in a useful way, so I'd like to just quietly remove it without obsoleting it.
This would have no impact on uSurvival or uMMORPG.
> Removed non-implemented overload

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
This is an alternative to #1257
Now the user can pass a parameter to ReplacePlayer to indicate
that the old player should remain attached to the connection.
Note the user could simply pass true and then call RemoveAuthority themselves
which was the approach in #1257
Personally I would prefer #1257,  but this is at least better than
master because authority is removed the proper way.
> fix: replace player (remove authority by default)

- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/Transport/Transport.cs
Now you can start the client using a uri instead of host name.
for example,  instead of this:
```cs
networkManager.address = "myhost.xxx.org";
networkManager.StartClient();
```
you have the option of using uri:
```cs
networkManager.StartClient(new Uri("tcp://myhost.xxx.org"));
```
Note the old way is still in place,  not even deprecated.
> feat: new way to connect using uri

- Assets/Mirror/Editor/Weaver/Processors/MessageClassProcessor.cs
- Assets/Mirror/Tests/MessageInheritanceTest.cs
- Assets/Mirror/Tests/MessageInheritanceTest.cs.meta
When mirror generates Serialize/Deserialize for messages, it now calls the parents method.
This way messages can now have a rich hierarchy.  
Consider this code:
```cs
abstract class MyBaseMessage : MessageBase
{
public int commonData;
}
class MyChildMessage : MyBaseMessage
{
public int childData;
}
```
if you send a `MyChildMessage`,  it now will include both fields.
> feat: Mirror now supports message inheritance

- Assets/Mirror/Editor/NetworkBehaviourInspector.cs
As described. Since this required a minor refactor anyways, I also took the liberty to do the following:
- Horizontal groups aren't pointlessly allocated for all non-SyncVar properties. This is both an optimization (layout groups are expensive) and a bug fix, since it can cause a bunch of layouting issues to call arbitrary property drawers while in a horizontal scope.
- Drawing of the actual SyncVar property is now also wrapped in an additional vertical group scope, for the same reason as outlined above; it's a bad idea to be in a horizontal layout scope when invoking other code that is usually implicitly assuming a vertical scope, since that is the default.
- Made syncVarIndicatorContent static to avoid superfluous allocations per editor instance - originally this was in #1289 as a …
> fix: Draw SyncVar label for Unity objects inline 

- Assets/Mirror/Runtime/Transport/LLAPITransport.cs
url format is "unet://host:port"
Do we want to pass any option in the url?
> feat: LLAPI transport can receive port from uri

- Assets/Mirror/Runtime/Transport/MultiplexTransport.cs
If the multiplex transport receives an url for connection,
try all the underlying transports until it finds a suitable one
For example,  let's say you configure a multiplex transport with telepathy and websocket,  if you try:
```cs
NetworkManager.StartClient("tcp4://host:port");
```
then the multiplex transport will use telepathy.
if we pass:
```cs
NetworkManager.StartClient("ws://host:port");
```
then the multiplex transport will select websocket
> feat: Multiplex based on url

- Assets/Mirror/Runtime/NetworkIdentity.cs
This field isn't used anywhere anymore.
The comment above it actually belongs to hasAuthority.
> Unused isOwner

- Assets/Mirror/Runtime/NetworkManager.cs
Right above this line we set `clientLoadedScene` to `true`, and then call this:
```cs
public virtual void OnClientConnect(NetworkConnection conn)
{
if (!clientLoadedScene)
{
// Ready/AddPlayer is usually triggered by a scene load completing. if no scene was loaded, then Ready/AddPlayer it here instead.
if (!ClientScene.ready) ClientScene.Ready(conn);
if (autoCreatePlayer)
{
ClientScene.AddPlayer();
}
}
}
```
I realize this is a virtual, but there's no reason to call this more than once per connected session, and anyone overriding this would either call the base method or wrap their code in the same `if`.
> No point in calling this here

- Assets/Mirror/Runtime/NetworkIdentity.cs
Apparently some people were using this delegate to subscribe server-side actions when client authority was assigned or removed.
This PR only restores the server part of what was removed in PR #1204
> Restore clientAuthorityCallback

- Assets/Mirror/Authenticators/BasicAuthenticator.cs
Turns out `Invoke(nameof(conn.Disconnect), 1);` doesn't actually work as one might expect.
Made it into a coroutine.
> Fix Delayed Disconnect

- Assets/Mirror/Runtime/NetworkIdentity.cs
Use the lazy network behaviors cache everywhere, so this can never be null
fixes #1301
> fix: error when there are no network behaviors

- Assets/Mirror/Runtime/Messages.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/ScriptTemplates/50-Mirror__Network Manager-NewNetworkManager.cs.txt
Adds an optional flag `customHandling` to SceneMessage that allows devs to bypass our built-in scene loading and apply their own.
- Some devs have expressed a desire to use their own `AsyncOperation` so they can show a scene loading screen with their own progress bar.
- Addressables / Asset Bundles require unique handling that we can't directly support adequately, especially since Addressables would force a dependency on us for a Unity package.
The transport is disabled and `OnClientChangeScene` is called right before the customHandling bool is checked, and that virtual is where devs can do their own thing.  We can therefore assume that if `customHandling` is true they've done their part and we can go straight to FinishLoadScene where we proceed normally and re-enable the transport.
> feat: Allow Custom Scene Handling

- Assets/Mirror/License.txt
- Assets/Mirror/Plugins/Mono.Cecil/License.txt
- Assets/Mirror/Plugins/Mono.Cecil/License.txt.meta
Removes the generic license.txt file from Mirror folder and adds the license file from the original Cecil repository with link to that repo in the Plugins/Mono.Cecil folder.
> Replace License.txt

- .releaserc.yml
Goal is to have the download file name for the unity package include the version like the zip does.
> feat: add version to package file

- Assets/Mirror/Editor/Weaver/Processors/MessageClassProcessor.cs
- Assets/Mirror/Editor/Weaver/Weaver.cs
- Assets/Mirror/Tests/MessageBaseTests.cs
- README.md
Allow Weaver to add bodies to IMessageBase structs with empty de/serialize methods
This checks whether both methods added via the interface are empty (nop/ret) and uses the usual path to weave in the readers/writers, effectively just replacing the empty bodies.
> feat: generate serializers for IMessageBase structs

- doc/Guides/DedicatedServer/toc.yml
Stop showing overview on the left. It's the same as the title so doesn't need to be shown
> docs: remove redundant "overview" menu item

- Assets/Mirror/Components/NetworkRoomManager.cs
This trick no longer works in Unity 2018.4.x.
Per Unity Docs DDOL scene is not accessible at runtime, and they recommend putting persistent objects in an additive scene.
https://docs.unity3d.com/Manual/MultiSceneEditing.html
> Remove DDOL escape

- Assets/Mirror/Components/NetworkTransformBase.cs
This allows non-player objects that have been assigned authority to the client to be moved around by the client and their positions updated from that client appropriately when clientAuthority is also true.
> fix: Use hasAuthority instead of isLocalPlayer

- Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
Weaver generated code before: (see OnDeserialize initialState case!)
```csharp
public class Test : NetworkBehaviour
{
[SyncVar(hook = "OnSetA")]
public int a;
[SyncVar(hook = "OnSetC")]
public int c;
[SyncVar(hook = "OnSetQ")]
public GameObject q;
[SyncVar(hook = "OnSetR")]
public GameObject r;
private uint ___qNetId;
private uint ___rNetId;
public int Networka
{
get
{
return a;
}
[param: In]
set
{
if (!SyncVarEqual(value, ref a))
{
if (NetworkServer.localClientActive && !getSyncVarHookGuard(1uL))
{
setSyncVarHookGuard(1uL, value: true);
OnSetA(value);
setSyncVarHookGuard(1uL, value: false);
}
SetSyncVar(value, ref a, 1uL);
}
}
}
public int Networkc
{
get
{
return c;
}
[param: In]
set
{
if (!SyncVarEqual(value, ref c))
{
if (NetworkServer.localClientActive && !getSyncVarHookGuard(2uL))
{ …
```
> fix: #1278 - only call initial state SyncVar hooks on clients if the SyncVar value is different from the default one.

- Assets/Mirror/Runtime/NetworkManager.cs
- doc/General/ChangeLog.md
StopHost calls StopServer and StopClient, both of which invoke a scene change to the offline scene.  This PR creates a separate method for StopHostClient that does exactly what StopClient does without the scene change.
I considered just adding an optional bool to StopClient to indicate it was the host client but that would break the list server example.  If you want to change the example to accommodate something like
```cs
public void StopClient(bool hostClient = false) { }
```
then we can do that instead.
> fix: StopHost with offline scene calls scene change twice

- LICENSE
With this change, github recognizes it is MIT license so it shows as MIT when searching github
> Proper MIT license

- Assets/Mirror/Editor/NetworkIdentityEditor.cs
- Assets/Mirror/Editor/NetworkIdentityEditor.cs.meta
Restore NetworkIdentityEditor as empty file to replace existing file for those updating from previous Mirror version.
This file was deleted in 
https://github.com/vis2k/Mirror/commit/6fb8a32f5b442ef7f43791c1d137ff69683ce678
> fix: Restore Empty NetworkIdentityEditor

- Assets/Mirror/Runtime/NetworkManager.cs
When a game has additive scenes on server, the client has to be told to load one or more additive scenes before spawning the player so that spawn messages for networked objects in those additive scenes are known on the client and work correctly.
This is best handled by overriding OnServerAddPlayer and sending out one or more Scene messages with the LoadAdditive SceneOperation before instantiating the player object, optionally putting the player object into an additive scene on the server (which effects Observers), and finally invoking NetworkServer.AddPlayerForConnection when the client is ready for that to happen.
Since the client doesn't have the player object yet, we don't want it to keep sending more AddPlayer messages after each additive load and throwing errors on the server.
> fix: Prevent AddPlayer after Additve Scene operation

- Assets/Mirror/Editor/NetworkBehaviourInspector.cs
Added a header to the Sync properties so they're nicely separated from whatever else might be in the component.
In the image below, the header only shows when Sync Mode and Sync Interval are visible.  Player Controller is a Network Behaviour without SyncVars, and so, correctly, no header appears.
> Add Header to NetworkBehaviourInspector

- Assets/Mirror/Components/NetworkTransformBase.cs
This feature was only added 2 weeks ago, so I think the rename is safe without an obsolete.
> Breaking: Renamed localEulerAnglesSensitivity

- Assets/Mirror/Runtime/SyncDictionary.cs
- Assets/Mirror/Tests/Editor/SyncDictionaryTest.cs
When the callback for SyncDictionary is called in the server
for set or add
it is getting called before the syncdictionary is updated.
In the client this happens after.  
Example:
```cs
public void OnScoreUpdatedCallback(ScoreSyncDict.Operation op, uint ident, int score) 
{
if (op == ScoreSyncDict.Operation.OP_SET) 
Debug.Log($"The value in the dictionary is {scoreDict[ident]}");
}
```
In host mode this prints the previous value.   In client mode this prints the current value.  This PR fixes this problem and makes both print the current value
> fix: call callback after update dictionary in host

- Assets/Mirror/Editor/Weaver/Readers.cs
- Assets/Mirror/Editor/Weaver/Writers.cs
- Assets/Mirror/Tests/Editor/WeaverTest.cs
- Assets/Mirror/Tests/Editor/WeaverTests~/TestingScriptableObjectArraySerialization.cs
With this fix,  you can now serialize an array of unsupported types
if you provide a custom serializer for scriptable object
Big thanks to Uchiha who found the problem and showed how
it could be fixed in #1466
> fix: weaver support array of custom types

- Assets/Mirror/Runtime/ClientScene.cs
`readyConnection` needs to be completed before sending `ReadyMessage`.
In master we have this in ClientScene.Ready
```cs
conn.Send(new ReadyMessage());
ready = true;
readyConnection = conn;
readyConnection.isReady = true;
```
This is fine for remote clients because by the time the server round-trips the lines after the Send have executed, however for Host client, the `Send` goes straight through to ClientScene.InternalAddPlayer and fails for a null `readyConnection`.
**To reproduce the fault in master:**
Create an empty scene with an empty game object with a custom Network Manager with the code below and the HUD and Telepathy, and assign any appropriate prefab to the playerPrefab field and **uncheck** Auto Create Player, and play as Host:
```cs
public class NetManager : NetworkManager
{ …
```
> fix: Host Player Ready Race Condition

- Assets/Mirror/Components/NetworkSceneChecker.cs
Use Scene instead of scene name because additive subscenes may be loaded at once and the name won't be unique.
> feat: NetworkSceneChecker use Scene instead of string name

- doc/Guides/Sync/SyncVarHook.md
Added "using Mirror;" instead of "using UnityEngine.Networking;"
> Changed namespace in code snippet for SyncVar hooks.

- Assets/Mirror/Runtime/NetworkServer.cs
- doc/General/ChangeLog.md
@SoftwareGuy discovered this one with @rxmarccall and @AnthonE 
Broken by bc7e116a
> fix: Add missing channelId to NetworkConnectionToClient.Send calls

- Assets/Mirror/Runtime/NetworkManager.cs
StopServer and StopClient both set this at the appropriate time...don't need it here.
> Remove Redundant Set of mode = Offline

- Assets/Mirror/Runtime/NetworkManager.cs
Per Discord discussion...all other Start methods are not virtual and this one shouldn't be.
Comparable to the others, it calls OnStartHost which is virtual.
> Make StartHost Not virtual

- Assets/Mirror/Components/NetworkTransformBase.cs
NetworkTransform was comparing rotations by getting the euler angles and comparing the distance between them.
The problem with that is that euler angles suffer from gimbal lock.  This will cause problem when you look straight up. even if you are not rotating much,  there could be lots of false positives.
The correct way to compare rotations is by either getting the dot product (cosine if they are normalized) or by calling Quaternion.Angle
> fix: properly detect NT rotation

- Assets/Mirror/Tests/Editor/Telepathy/TransportTest.cs
Telepathy tests are flaky and don't work in our CI/CD pipeline.
Disabling them so we get coverage report.
> tests: Disable telepathy tests until they are fixed

- Assets/Mirror/Runtime/NetworkServer.cs
We calculate a bool out of SendToObserver, but it is not clear what it is
and we don't use the result at all.  So just simplify things.
> refactor: SendToObserver returns void

- Assets/Mirror/Editor/Weaver/Processors/CommandProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/MethodProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/MethodProcessor.cs.meta
- Assets/Mirror/Editor/Weaver/Processors/RpcProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/TargetRpcProcessor.cs
When replacing command and rpc methods,  we now correctly move over
the debugging information.
Now you can put breakpoints in commands and Rpc
Should fix #1550
> fix: Command and Rpc debugging information

- Assets/Mirror/Runtime/NetworkIdentity.cs
- doc/General/ChangeLog.md
> fix: Prevent Double Call of NetworkServer.Destroy

- Assets/Mirror/Runtime/NetworkConnection.cs
Since messages behave similar to events and given the process is not technically breaking, using LogError seems incorrect. Using Log, maybe LogWarning would be more appropriate. Added additional text to clarify why the user may be seeing that log entry.
> fix: Change LogError to Log. Added more details.

- Assets/Mirror/Editor/NetworkBehaviourInspector.cs
If target's base class is changed from `NetworkBehaviour` to `MonoBehaviour` then Unity temporarily keep using this Inspector causing things to break.
> Fixing exceptions

- Assets/Mirror/Editor/Weaver/AssemblyInfo.cs
- Assets/Mirror/Editor/Weaver/AssemblyInfo.cs.meta
- Assets/Mirror/Editor/Weaver/Weaver.cs
- Assets/Mirror/Tests/Editor/Mirror.Tests.asmdef
- Assets/Mirror/Tests/Editor/WeaverTest.cs
- Assets/Mirror/Tests/Editor/WeaverTests~/NetworkBehaviourClient.cs
- Assets/Mirror/Tests/Editor/WeaverTests~/NetworkBehaviourServer.cs
- Adding check to make sure weaver adds code
- Adding tests for NetworkBehaviour
Using hard coded strings `"System.Boolean Mirror.NetworkServer::get_active()"` because `Weaver` is private making it hard to access `Weaver.NetworkServerGetActive`
> Weaver test for adding guard code

- Assets/Mirror/Runtime/NetworkServer.cs
Currently, despite the parameters being optional, `SendToReady` is actually ambiguous unless all parameters are specified.  Making the `channelId` non-optional resolves the ambiguity without breaking anything.
All of these are now valid:
```cs
void Test(NetworkConnection conn)
{
NetworkServer.SendToReady(conn.identity, new SceneMessage { sceneName = "foo" });
NetworkServer.SendToReady(conn.identity, new SceneMessage { sceneName = "foo" }, 0);
NetworkServer.SendToReady(conn.identity, new SceneMessage { sceneName = "foo" }, true);
NetworkServer.SendToReady(conn.identity, new SceneMessage { sceneName = "foo" }, true, 0);
}
```
> fix: Make SendToReady non-ambiguous

- Assets/Mirror/Tests/Editor/SyncListStructTest.cs
- Assets/Mirror/Tests/Editor/SyncListStructTest.cs.meta
- Assets/Mirror/Tests/Editor/SyncListTest.cs
Tests to make sure structs sync when their fields are updated
We should probably update the docs to say that this is the correct way to update a struct field when using SyncLists
```csharp
TestPlayer player = serverList[index];
player.item.price = 15;
serverList[index] = player;
```
> Tests for SyncLists that use structs

- Assets/Mirror/Components/NetworkRoomManager.cs
- Assets/Mirror/Components/NetworkRoomPlayer.cs
- Assets/Mirror/Editor/SceneDrawer.cs
- Assets/Mirror/Examples/AdditiveScenes/Scenes/MainScene.unity
- Assets/Mirror/Examples/Room/Scenes/OfflineScene.unity
- Assets/Mirror/Examples/Room/Scripts/NetworkRoomPlayerExt.cs
- Assets/Mirror/Runtime/NetworkManager.cs
Instead of using scene name, scenes are now identified by path.
This fixes a couple problems:
1) In the room example, now you can assign the scenes even if they have
not been added to the editor.  This was a constant pain because if you
open the offlinescene, all the scenes got wiped.  You had to add the
scenes to the editor and reassign them all again.   With this PR you
will still need to add them to the editor, but they will remain
assigned.
2) It is possible for multiple scenes to have the same name,  but it is
not possible for multiple scenes to have the same path. So this is
a more robust way to identify scenes
This also greatly simplifies scene SceneDrawer
> feat: now you can assign scenes even if not in Editor

- Assets/Mirror/Runtime/NetworkManager.cs
We definitely should stop client first, then stop server.
There is a risk that we silently break something somewhere though.
Tests all pass so far.
> NetworkManager.StopHost stops client, then server. Seems more consistent this way.

- Assets/Mirror/Runtime/NetworkWriter.cs
This mask is redundant, because casting to byte is doing the same thing.
> perf: Remove redundant mask

- Assets/Mirror/Runtime/MessagePacker.cs
- Assets/Mirror/Runtime/NetworkConnection.cs
According to vis benchmark in #1614 
isValueType is an expensive operation.
This micro-optimization replaces isValueType for a faster (not so readable) alternative
> perf: replace isValueType with faster alternative

- Assets/Mirror/Editor/NetworkInformationPreview.cs
Fixes issue in information panel.
```
MissingReferenceException: The object of type 'GameObject' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.GameObject.GetComponent[T] () (at C:/buildslave/unity/build/Runtime/Export/GameObject.bindings.cs:28)
Mirror.NetworkInformationPreview.HasPreviewGUI () (at Assets/Mirror/Editor/NetworkInformationPreview.cs:77)
UnityEditor.InspectorWindow.GetEditorsWithPreviews (UnityEditor.Editor[] editors) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:808)
UnityEditor.InspectorWindow.DrawPreviewAndLabels () (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:898)
UnityEditor.InspectorWindow.OnGUI () (at …
```
> fix: MissingReferenceException

- Assets/Mirror/Runtime/NetworkWriter.cs
- Assets/Mirror/Runtime/NetworkWriterPool.cs
- Assets/Mirror/Tests/Editor/NetworkWriterPoolTest.cs
Using an array is ~50% faster than Stack/Queue/List
> perf: faster NetworkWriter pooling

- Assets/Mirror/Tests/Editor/WeaverAssembler.cs
Weaver tests fail if they are moved to a different folder
Using 
`.../Mirror/Tests/Editor/WeaverAssembler.cs`
to find path to 
`.../Mirror/Tests/Editor/WeaverTests~/`
> Finding WeaverAssembler path before running tests

- Assets/Mirror/Runtime/NetworkManager.cs
There should be no reason to set singleton outside of networkmanager.
Setting single currently happens inside `InitializeSingleton` setting it outside of this may cause problems.
> making singleton private set

- Assets/Mirror/Runtime/LogFactory.cs
- Assets/Mirror/Runtime/LogFactory.cs.meta
- Assets/Mirror/Tests/Editor/LogFactoryTests.cs
- Assets/Mirror/Tests/Editor/LogFactoryTests.cs.meta
Provide a logger (from unity framework) per class, based on unity logging api
it can track loggers per class and use  Debug.unityLogger by default
This is how you would use it:
```cs
class NetworkClient
{
private static ILogger logger = LogFactory.GetLogger<LogFactoryTests>();
public void DoSomething()
{
// do something
logger.Log("Something just happened");
}
}
```
By default, the logger only displays warnings and above,  but let's say you want to see debug messages on a class,   then you can change it at runtime:
```cs
GetLogger<NetworkClient>.filterLogType = LogType.Log;
```
Eventually the vision is to create this editor window available at runtime
> feat: logging api

- Assets/Mirror/Runtime/NetworkManager.cs
Currently if you have a Network Manager in another scene and the original one from Offline scene runs into it, the 2nd is destroyed in InitializeSingleton however that doesn't happen until the end of the frame, so it lives just long enough to run the rest of the code in Awake.
> fix: Destroyed NetMan due to singleton collision must not continue.

- Assets/Mirror/Runtime/NetworkIdentity.cs
UpdateVarsMessage is currently a struct so field no longer needs to be cached
> removing cached field

- Assets/Mirror/Tests/Editor/Telepathy/TransportTest.cs
- Assets/Mirror/Tests/Editor/WeaverTest.cs
Allows us to filter tests, and "Run All" only on a subset of test.
Works as a flag allowing us to run multiple Categories at once
> adding Category to weaver and Telepathy tests

- .github/workflows/main.yml
prevents breakage in case there are newer versions of the action
> Use specific version for github action

- Assets/Mirror/Editor/Weaver/Processors/SyncVarProcessor.cs
Weave creates code that will throw this execption at run time
> fix: Fixing SyncVar hooks with static methods

- .gitignore
Unity create `StreamingAssets` folder for performance test in versions 2018.3/4
> adding StreamingAssets folder to gitignore

- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
Cleaning up the `OnSerializeAllSafely` function by moving the component count check to when the cache is created.
We do not support adding/removing components at runtime so running the check when the cache is created shouldn't change the functionality just when and how many error logs there are.
> Moving error check to when cache is created

- Assets/Mirror/Runtime/NetworkManager.cs
We set `Transport.activeTransport.enabled = false;` 15 lines above this switch case
> fix: Re-enable transport if aborting additive load/unload

- Assets/Mirror/Examples/AdditiveScenes/Scripts/AdditiveNetworkManager.cs
- Assets/Mirror/Runtime/NetworkManager.cs
Now that we store full path in scene fields, we need to check for both name and path in additive loading and unloading.
> fix: Check SceneManager GetSceneByName and GetSceneByPath

- Assets/Mirror/Tests/Performance/Editor/Mirror.Tests.Performance.asmdef
- Assets/Mirror/Tests/Performance/Editor/NetworkWriterPerformance.cs
- Assets/Mirror/Tests/Performance/Runtime/BenchmarkPerformance.cs
- Assets/Mirror/Tests/Performance/Runtime/Mirror.Tests.Performance.Runtime.asmdef
- Assets/Mirror/Tests/Performance/Runtime/ULocalConnectionPerformance.cs
Adding `versionDefines` so that tests dont break in 2019.3 with wrong package version.
versionDefines do not work in earlier versions of unity so we also need to check if we are on an earlier version of unity.
The version define is only needed for unity 2019.3 because that is the only version of Performance test that can use  > 2.0.0 (which breaks our scripts.
> Adding defines to performance tests

- Assets/Mirror/Tests/Performance/Runtime/ULocalConnectionPerformance.cs
`testPlayerPrefab` was causing problems with OnPostProcessScene in other runtime tests. Cleaning up object after fixes this.
> making ULocalConnectionPerformance clean up new objects

- Assets/Mirror/CompilerSymbols/PreprocessorDefine.cs
this stops ProjectSettings being marked as dirty and showing up in git (with no changes) each time the editor is opened
> Adding changed check to PreprocessorDefine

- Assets/Mirror/Components/NetworkProximityChecker.cs
- Assets/Mirror/Components/NetworkSceneChecker.cs
- Assets/Mirror/Runtime/NetworkVisibility.cs
Upon reviewing all 4 custom observers, they all have the exact same code for `OnSetHostVisibility`.
This PR makes that method a virtual with the default code in it, and removes the overrides from the other 2 that are currently in Mirror.
NetworkGridProximityChecker in uMMORPG can also have its override removed.
NetworkMatchChecker #1688  will have its override removed after this is merged.
> feat: Make OnSetHostVisibility virtual with default functionality

- Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Tests/Editor/NetworkBehaviourSerializeTest.cs
- Assets/Mirror/Tests/Editor/NetworkBehaviourSerializeTest.cs.meta
this will allow SyncVars to still work if user overrides OnSerialize as long as they call base.OnSerialize
> fix: Fixing SyncVars not serializing when OnSerialize is overridden

- Assets/Mirror/Tests/Editor/Weaver/WeaverClientRpcTests.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverClientServerAttributeTests.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverCommandTests.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverGeneralTests.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverMessageTests.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverMonoBehaviourTests.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverNetworkBehaviourTests.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverSyncVarTests.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverTargetRpcTests.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverTests.cs
Requires https://github.com/vis2k/Mirror/pull/1704 , This PR is just for last commit: f887a2c
Creating a different base class for tests that want to automatically build test Assembly from test name
`BuildAndWeaveTestAssembly(TestContext.CurrentContext.Test.Name);`
> Moving weaver tests 2

- Assets/Mirror/Runtime/NetworkManager.cs
Fixes a problem where a client that starts hosting after previously disconnecting from a game ends up forcing new clients to change scenes to the previously disconnected game's scene.
This should allow the NetworkManager to be a bit more re-usable between sessions without having to destroy and recreate it.
> fix: NetworkManager doesn't reset networkSceneName after client/server disconnect

- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
- Assets/Mirror/Tests/Editor/SyncVarTest.cs
- Assets/Mirror/Tests/Editor/SyncVarVirtualTest.cs
Is dirty check for https://github.com/vis2k/Mirror/issues/1614
performance, master vs this PR
https://james-frowen.github.io/Mirror/charts/dirtyCheck.html
`NetworkManager.LateUpdate()` is about 30% faster frame times for idle objects
performance of just `NetworkIdentity.ServerUpdate`
https://james-frowen.github.io/Mirror/charts/dirtyCheckEditmode.html
No difference when object is dirty but is 114% faster when object isn't dirty and
> perf: Adding dirty check before update sync var

- Assets/Mirror/Tests/Editor/NetworkServerTest.cs
We dont need to call ` NetworkServer.Shutdown();` in every test if we run it in `TearDown`
> fixing TearDown and removing extra calls to shutdown in NetworkServerTest

- Assets/Mirror/Tests/Performance/Runtime/ULocalConnectionPerformance.cs
Telepathy sometimes causes errors for tests, adding fake transport class to use instead.
> using MemoryTransport for ULocalConnectionPerformance test

- Assets/Mirror/Components/NetworkAnimator.cs
Added `isServer` checks to the Rpc's.
Fixes #1508
> fix: Eliminate NetworkAnimator SetTrigger double firing on Host

- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/Runtime/NetworkServerTest.cs
- Assets/Mirror/Tests/Runtime/NetworkServerTest.cs.meta
`conn.DestroyOwnedObjects();` already destroys the player object...once is enough.
> fix: Don't destroy the player twice

- Assets/Mirror/Runtime/LogFactory.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverTests.cs
This allows us to set the log function in weaver tests back to LogError/LogWarning
> Default log level option

- Assets/Mirror/Editor/Weaver/Readers.cs
- Assets/Mirror/Editor/Weaver/Writers.cs
- Assets/Mirror/Tests/Editor/Weaver/GeneratedReaderWriter~/CanUseCustomReadWriteForInterfaces.cs
- Assets/Mirror/Tests/Editor/Weaver/GeneratedReaderWriter~/GivesErrorWhenUsingInterface.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverGeneratedReaderWriterTests.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverMessageTests.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverSyncVarTests.cs
- Adding tests `GivesErrorWhenUsingInterface` and `CanUseCustomReadWriteForInterfaces`
- Checking for "Cannot generate reader" error message
- Updating error message to be consistent
> Weaver error messages and tests for using interfaces

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/Editor/NetworkBehaviourTests.cs
- Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
- Assets/Mirror/Tests/Editor/NetworkServerTest.cs
OnNetworkDestroy is not a good name,  is it server? is it client?
you can't tell by the name.
Moreover,  we have OnStartClient,  API should be symetric so we should
have a corresponding OnStopClient.
Note this keeps backwards compatibility with an Obsolete for now
> Rename OnNetworkDestroy to OnStopClient

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
- Assets/Mirror/Tests/Editor/NetworkServerTest.cs
MarkForReset was useful to preserve network information during destroy (see #1484),  and yet allow scene objects to be reset if we reconnect.
To address #1484, override OnStopServer instead (see #1743).
This PR simplifies the whole thing by getting rid of MarkForReset and simply resetting objects when they are unspawned.
> Remove MarkForReset

- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/SyncDictionary.cs
- Assets/Mirror/Runtime/SyncList.cs
- Assets/Mirror/Runtime/SyncObject.cs
- Assets/Mirror/Runtime/SyncSet.cs
- Assets/Mirror/Tests/Editor/SyncDictionaryTest.cs
- Assets/Mirror/Tests/Editor/SyncListTest.cs
- Assets/Mirror/Tests/Editor/SyncSetTest.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverSyncVarTests~/SyncVarsSyncList.cs
feature: https://github.com/vis2k/Mirror/issues/1714
Not sure sure if this is classed as a breaking change. Anyone who implements `SyncObject` interface will need to add  `void Reset();`
> fix: Allow sync objects to be re-used

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkManagerHUD.cs
This is dead code since extraData was removed last month.  Since the AddPlayerMessage doesn't contain the `byte[] extraData` property this code, despite being public, is effectively unreachable.
The only handler we have is
`void OnServerAddPlayerInternal(NetworkConnection conn, AddPlayerMessage msg)`.
> fix: Remove leftover AddPlayer methods now that extraData is gone

- Assets/Mirror/Runtime/NetworkServer.cs
the current state is an untestable if statement. the if (!dont) is not pretty but the same logic is used later in the same file under Listen()
> remove empty if statement

- Assets/Mirror/Editor/Weaver/Readers.cs
- Assets/Mirror/Editor/Weaver/Writers.cs
- Assets/Mirror/Tests/Editor/Weaver/GeneratedReaderWriter~/ExcludesNonSerializedFields.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverGeneratedReaderWriterTests.cs
feature https://github.com/vis2k/Mirror/issues/1229
tldr, if user adds `[System.NonSerialized]` to a field, weaver doesn't try to Serialize it.
> feat: Exclude fields from weaver's automatic Read/Write using System.NonSerialized attribute 

- Assets/Mirror/Editor/Weaver/Extensions.cs
- Assets/Mirror/Editor/Weaver/Processors/SyncDictionaryProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/SyncListProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/SyncObjectProcessor.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncListInheritanceWithOverrides.cs
test and fix for sync lists that have overriden `SerializeItem`/`DeserializeItem` in base class
> fix: weaver syncLists now checks for SerializeItem in base class

- Assets/Mirror/Tests/Performance/Runtime/BenchmarkPerformance.cs
- Assets/Mirror/Tests/Performance/Runtime/ULocalConnectionPerformance.cs
- Assets/Mirror/Tests/Runtime/HostSetup.cs
- Assets/Mirror/Tests/Runtime/NetworkIdentityTests.cs
- Assets/Mirror/Tests/Runtime/NetworkManagerTests.cs
- Assets/Mirror/Tests/Runtime/NetworkServerTest.cs
**HOLD until #1724 is merged**
Adding different namespace to make sure we dont have problem with test classes with the same name in the editmode tests
> adding namespace to runtime tests

- Assets/Mirror/Components/NetworkAnimator.cs
I can't find a good reason for this attribute on Network Animator.  It's plausible for a networked object to have multiple animators in its hierarchy that change state independently, for example a bunch of doors or lights scattered around a scene that operate independently.
> feat: Allow Multiple Network Animator

- Assets/Mirror/Runtime/NetworkServer.cs
This adds an optional sendToReadyOnly parameter to SendToAll and a shorthand SendToReady method for server-wide messages to all **ready** clients without needing a NetworkIdentity for observers / owner checks.
> feat: NetworkServer.SendToReady

- Assets/Mirror/Plugins/Mono.Cecil/Mono.CecilX.Mdb.dll.meta
- Assets/Mirror/Plugins/Mono.Cecil/Mono.CecilX.Pdb.dll.meta
- Assets/Mirror/Plugins/Mono.Cecil/Mono.CecilX.Rocks.dll.meta
- Assets/Mirror/Plugins/Mono.Cecil/Mono.CecilX.dll.meta
Mono.Cecil is only used by weaver so does not need to be included in builds
> Making Mono.Cecil editor only

- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkServer.cs
Replacing a handler by mistake will lead to code not running when it is expected to.
If people replace handlers often then it might be worth adding a `ReplaceHandler` method that ignores the `ContainsKey` check
> feat: Adding ReplaceHandler functions to NetworkServer and NetworkClient

- Assets/Mirror/Runtime/ClientScene.cs
RegisterPrefab(GameObject prefab) has the option to add new AssetId but the versions that add custom spawn handlers did not have this option
> Adding method overloads for setting newAssetId

- Assets/Mirror/Runtime/LogFactory.cs
Logger.LogError tries to add tag to message causes `:` to be added to the front of error messages
See 
```csharp 
private const string kTagFormat = "{0}: {1}";
public void LogError(string tag, object message)
{
if (IsLogTypeAllowed(LogType.Error))
logHandler.LogFormat(LogType.Error, null, kTagFormat, new object[] {tag, GetString(message)});
}
```
https://github.com/Unity-Technologies/UnityCsReference/blob/master/Runtime/Export/Logging/Logger.cs#L13
https://github.com/Unity-Technologies/UnityCsReference/blob/master/Runtime/Export/Logging/Logger.cs#L118
> fixing error message

- Assets/Mirror/Editor/NetworkBehaviourInspector.cs
syncMode and syncInterval now show up in Inspector when only sync vars are used
> fix: fixing syncmode not showing up in Inspector

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Tests/Editor/ClientSceneTests.cs
Replacing a handler by mistake will lead to code not running when it is expected to.
> fix: Adding warning when adding handler with RegisterSpawnHandler if assetid already exists

- Assets/Mirror/Runtime/LogFactory.cs
- Assets/Mirror/Runtime/NetworkManager.cs
In built games, there is currently no way to show debug logs for classes that are using the new logger.
This PR also allows us to keep support for `showDebugMessages` for a few versions.
> fix: fixing showDebugMessages with new logger

- Assets/Mirror/Runtime/NetworkServer.cs
Handlers should be cleared when NetworkServer is shut down.
> fix: clear all message handlers on Shutdown

- Assets/Mirror/Runtime/Transport/TelepathyTransport.cs
Message can disable transport so we need to check if it is still enabled before checking the next message.
Fixing problem with this
https://github.com/vis2k/Mirror/blob/d0e15b13787d6ac7a2d8ac9ccf054255e4dbcd15/Assets/Mirror/Runtime/NetworkManager.cs#L861-L865
> adding enabled check to loops

- Assets/Mirror/Runtime/NetworkManager.cs
This was already called in StartClient - calling it again here throws warnings that the handlers are being replaced needlessly.
> fix: Don't call RegisterClientMessages twice

- Assets/Mirror/CompilerSymbols/PreprocessorDefine.cs
- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/Messages.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/ScriptTemplates/50-Mirror__Network Manager-NewNetworkManager.cs.txt
BREAKING CHANGE: Eliminates RemovePlayerMessage
RemovePlayerMessage is a built-in message that Mirror inherited from UNet. Since it's an automatically handled message, that Mirror devs may not know about or pay much attention to, it exposes a security risk where a molested client could push this message and get the player object removed while holding the connection open, potentially cascading to bunches of unexpected Null Ref Exceptions.
This PR cuts out all the functionality, while leave an Error-tagged Obsolete so after upgrading users will be aware of it and make necessary changes, if any.
By gutting the code out of the obsolete methods, the risk is mitigated, and the obsolete methods will be removed in the June Asset Store release.
The unity tests for RemovePlayerMessage remain, and …
> breaking: Eliminates RemovePlayerMessage As Security Risk

- Assets/Mirror/Tests/Editor/Weaver/WeaverTests.cs
Adding ignoreFailingMessages around error logging
> Stopping logger error causing weaver tests to fail

- Assets/Mirror/Runtime/NetworkManager.cs
Fixes #1856 
Not sure why the old version was using `Resources.FindObjectsOfTypeAll` so we need to test this fix in real projects before we merge
> fix: Cleaning up network objects when server stops

- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/Runtime/NetworkServerRuntimeTest.cs
`NetworkClient.Shutdown` cleans up client objects so `NetworkServre.Shutdown` should clean up server objects
depends on https://github.com/vis2k/Mirror/pull/1868
> Moving CleanupNetworkIdentities to NetworkServer

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Tests/Runtime/ClientSceneTests_DestroyAllClientObjects.cs
If `DestroyAllClientObjects` throws `InvalidOperationException` then the rest of `OnApplicationQuit` stops causing the host to not close the open port.
`InvalidOperationException` can be cause by the user modifying `NetworkIdentity.spawned` during the loop
> fix: InvalidOperationException thrown in DestroyAllClientObjects 

- Assets/Mirror/Runtime/NetworkManager.cs
Calling RegisterClientMessages every scene change isn't necessary.
We call it from StartHostClient and that's sufficient.
The Room example is the only one with multiple scene changes, and spams warnings about replacing prefabs in master.  This PR cleans that up, and the example works correctly.
> fix: Don't call RegisterClientMessages every scene change

- Assets/Mirror/Runtime/Transport/Telepathy/Client.cs
If someone calls `NetworkClient.Connect(networkAddress);` or `Transport.activeTransport.ClientConnect(address);` while an existing client is connecting/connected the user has no way of knowing that the new connect fails. 
This can be a problem if a user tries to connect to multiple servers quickly before first request times out.
> fix: Adding warning to Telepathy Client connect when client is already connecting or connected

- Assets/Mirror/Editor/Weaver/Processors/CommandProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
- Assets/Mirror/Runtime/CustomAttributes.cs
- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/Editor/CommandAttrributeTest.cs
- Assets/Mirror/Tests/Editor/CommandAttrributeTest.cs.meta
- Assets/Mirror/Tests/Editor/CustomAttrributeTest.cs
- Assets/Mirror/Tests/Editor/NetworkBehaviourTests.cs
- Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
- Assets/Mirror/Tests/Editor/NetworkServerTest.cs
- Assets/Mirror/Tests/Editor/Weaver/.WeaverTests.csproj
- Assets/Mirror/Tests/Editor/Weaver/WeaverCommandTests.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverCommandTests~/CommandThatIgnoresAuthority.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverCommandTests~/CommandValid.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverCommandTests~/CommandWithArguments.cs
See #1917 
PR can be reviewed on a per-commit basis.
**Current State:**
Need solution for `NetworkServer.OnCommandMessage` where authority is checked on incoming messages for how/where to access the `ignoreAuthority` parameter of the Command being called.
Tests are just patched for now - more tests will be added.
Haven't started ClientRpc work yet.
> feat: Adding ignoreAuthority Option to Command

- Assets/Mirror/Runtime/Logging/LogFactory.cs
- Assets/Mirror/Runtime/NetworkReader.cs
Increasing log level to warning for NetworkReader can't find a NetworkIdentity.
Also adding extension methods to check when other log levels are enabled
> making log warning

- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Tests/Editor/NetworkBehaviourTests.cs
- Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
- Assets/Mirror/Tests/Editor/NetworkServerTest.cs
this removes all delegates, which is a problem because other tests register their handles in static constructors so have no way to re-add their handlers
```csharp
// we need a way to clean up delegates after tests
[EditorBrowsable(EditorBrowsableState.Never)]
[System.Obsolete("Removing all delegates will cause problems with other tests as their hashs can not be re-added without reloading scripts", true)]
internal static void ClearDelegates()
{
cmdHandlerDelegates.Clear();
}
```
Swapping tests to use `RegisterDelegate` instead of `RegisterCommandDelegate` to get returned value. Making `RegisterCommandDelegate` return the has a well requires Weaver to be changed.
> fix: Replacing ClearDelegates with RemoveDelegates for test

- Assets/Mirror/Runtime/NetworkIdentity.cs
Had a `NullReferenceException` caused by `HandleRemoteCall` in my game. Checking `this` instead of `this.gameobject` should fix the problem
> fix: Fixing NullReferenceException caused by calling this.gameObject inside null unity object

- Assets/Mirror/Runtime/NetworkWriter.cs
If transform is not null then gameObject will also be not null
> Removing extra null check

- doc/Guides/Sync/index.md
- the return value is not currently used in mirror
- OnSerialize is currently only called when IsDrity is true
> docs: replacing paragraph on return with is dirty

- Assets/Mirror/CompilerSymbols/PreprocessorDefine.cs
- Assets/Mirror/Runtime/Transport/Websocket/WebsocketTransport.cs
Alternative to #1966 and includes version update in PreprocessorDefine.
Changes how the transport locates the PFX Certificate file.
Currently it's an undocumented relative path from Unity's `Application.dataPath` that differs by platform, so it's difficult to know where the PFX file must be located within the deployed server build.
With this change, users specify the full path to the PFX, and therefore it can be anywhere on the server that the dev finds convenient, perhaps auto-generated by LetsEncrypt on a 90-day interval, and makes it easier to update the server deployment without losing / displacing the PFX, and allows multiple server builds of different games on the same server to all use the same PFX without needing umpteen copies of it.
Also includes Headers and Tooltips for the …
> breaking: Websocket Transport now requires full path to PFX

- Assets/Mirror/Runtime/SyncDictionary.cs
SyncDictionary don't implement readonly interfaces unlike Dictionary or SyncList. This fixes it.
> Implement IReadOnlyDictionary for SyncDictionaries

- Assets/Mirror/Runtime/ClientScene.cs
This is called in the NetworkManager and in doing the work to make a fully custom NetworkManager - as i talked about in vis2k#2039 I found i needed to call this on the NetworkClient.RegisterHandler callback - as you can see here https://github.com/vis2k/Mirror/blob/master/Assets/Mirror/Runtime/NetworkManager.cs#L1265
Honestly though walking the code for this is a very weird situation where NetworkServer.SetClientNotReady() which sends a NotReadyMessage message to the client which it then eventually in NetworkManager calls ClientScene.ready = false feels very weird to me because the other side of things has a dedicated function ClientScene.Ready() - so it feels like there should be a ClientScene.NotReady() and the property should be left as is.
Likely not something to fix here and now - …
> Missed one internal call that the NetworkManager uses

- Assets/Mirror/Runtime/Transport/Websocket/Plugins/WebSocket.jslib
See #1486
Short: Socket is undefined (in my case) if I use client.ClientConnected() before I connect and cause error in the webgl version. The change fixes that.
> Fix: If socket is undefined it will return false. See #1486

- Assets/Mirror/Editor/Weaver/Processors/SyncEventProcessor.cs
- Assets/Mirror/Tests/Editor/SyncEventTest.cs
- Assets/Mirror/Tests/Editor/SyncEventTest.cs.meta
- Assets/Mirror/Tests/Editor/Weaver/.WeaverTests.csproj
- Assets/Mirror/Tests/Editor/Weaver/WeaverSyncEventTests.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverSyncEventTests~/MultipleSyncEvent.cs
fixes: https://github.com/vis2k/Mirror/issues/2005
> fix: weaver now processes multiple SyncEvent per class

- appveyor.yml
With this change, if there are errors in the docs,  then the PR will be marked as failed.
The docs appear to have some problems that have been overlooked.  See this:
https://ci.appveyor.com/project/vis2k73562/hlapi-community-edition/builds/33894429
> ci: if docs have errors, fail the PR

- Assets/Mirror/Components/NetworkProximityChecker.cs
If you have low-frequency calls, InvokeRepeating is a lot faster than
Update().  Use InvokeRepeating for NetworkProximityChecker
A little hard to measure,  but it saves roughly 3-5% CPU time in the 2k example in the server.
Before:
After:
> perf: Use invokeRepeating instead of Update

- Assets/Mirror/Authenticators/TimeoutAuthenticator.cs
Overrides the `OnStartClient()` and `OnStartServer()` methods to pass the calls to the nested authenticator.
This will fix #2073
> Refactor TimeoutAuthenticator to pass through client/server start callbacks

- Assets/Mirror/Editor/Weaver/Processors/CommandProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/RpcProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/TargetRpcProcessor.cs
We use the original method name so we do not need to remove the prefix.
The test coverage shows that these lines are never called.
> Removing code that isnt needed

- Assets/Mirror/Editor/Weaver/Processors/CommandProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/MethodProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/RpcProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/TargetRpcProcessor.cs
- Assets/Mirror/Editor/Weaver/Weaver.cs
Now that Cmd prefix isnt need generated functions are more likely to collide with other user functions
renaming them to UserCode and InvokeUserCode would also make then easier to understand
> fix: renaming call/invoke prefix for Cmd/Rpc

- Assets/Mirror/Components/Discovery/NetworkDiscoveryBase.cs
This pull request is done in order to address the issue in https://github.com/vis2k/Mirror/issues/2099. As you requested i made the change. I also underline that I simply changed the .cs file without opening it in Unity so the .meta file has not been updated. However, I believe this should not be an issue. 
If I can be of any other help let me know.
Regards,
Francesco Strada
> changing serverBroadcastListenPort variable access permissions to protected

- Assets/Mirror/Editor/Weaver/Processors/MessageClassProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
- Assets/Mirror/Editor/Weaver/Resolvers.cs
- Assets/Mirror/Tests/Editor/MessageBaseTests.cs
fixes #2117 
This now works:
```cs
class ArrayIntMessage : IMessageBase
{
public int[] array;
// Mirror will fill out these empty methods
public void Deserialize(NetworkReader reader) { }
public void Serialize(NetworkWriter writer) { }
}
```
> fix: auto fill serialize/deserialize for classes

- Assets/Mirror/Runtime/Transport/Websocket/WebsocketTransport.cs
Chrome is now requiring TLS 1.2 for HTTPS and WSS.  I could not find anywhere in Mirror WebsocketsTransport where this is configurable.  
This PR exposes the SSL/TLS Version as a property of `WebSocketsTransports` as well as in the Unity UI:
The default value has not changed, but I would advocate updating the default to be TLS 1.2.  I'm unsure if that would be a breaking change or not, but at least for WebGL/Browser games, this would be necessary for Chrome support.
> SSL/TLS version in Websockets now configurable

- Assets/Mirror/Editor/Weaver/Processors/ServerClientAttributeProcessor.cs
- Assets/Mirror/Runtime/NetworkBehaviour.cs
Function might be called when neither server or client is active, so saying it was "called on client" is misleading.
> fix: correctly error message so they are not misleading

- Assets/Mirror/Runtime/NetworkBehaviour.cs
We only need to check `netIdentityCache == null` a 2nd time after we call `GetComponent`
> perf: Only checking netIdentityCache == null once 

- .github/workflows/main.yml
Some files and folders not need to be included in code coverage, we can ignore them using `/d:sonar.coverage.exclusions`
files ignored in code coverage:
`Assets/Mirror/Runtime/Transport/Telepathy/**` - has its one test in the Telepathy repo
`Assets/Mirror/Runtime/Transport/Websocket/**` - needs tests but should be done in its own repo
`Assets/Mirror/Runtime/Transport/LLAPITransport.cs` - is Obsolete so does not need tests
`Assets/Mirror/Cloud/**` - has its own tests in private cloud repo
`Assets/Mirror/Examples/**` - examples dont need test coverage
I have tested with `dotnet-sonarscanner.exe` locally and it works on my fork
> Adding coverage exclusions

- Assets/Mirror/Runtime/Transport/Telepathy/Telepathy.asmdef
- Assets/Mirror/Runtime/Transport/Telepathy/Telepathy.asmdef.meta
- Assets/Mirror/Tests/Editor/Mirror.Tests.asmdef
Mirror has to reference telepathy as it is the default transport. This also means that TelepathyTransport has to be in the mirror asmdef, which is fine because it is already there and does not need to be moved.
> Adding asmdef to telepathy

- Assets/Mirror/Components/NetworkAnimator.cs
Now NetworkAnimator is aware of each layer weight on it's references
Animator and will sync layer weights across the network.
This could be a little nicer, especially the changes in CheckAnimStateChanged. I can make changes on request.
- Ran tests and all passed
- Copied edited script into another project and ran with two clients to confirm layer weight is synced
> Added Layer Weight to NetworkAnimator

- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
When calling `NetworkServer.Destroy` the `isServer` variable will be reset before the `OnDestroy` method is called.
If the object is being destroyed we don't need to also reset them.
> fix: isServer false in OnDestroy

- Assets/Mirror/Components/NetworkRoomManager.cs
- Assets/Mirror/Components/NetworkRoomPlayer.cs
When a player object joins `NetworkRoomManager.OnRoomClientEnter` is called before the player is in the roomslot. This is a problem because there is no way to get the new player that joins using `OnRoomClientEnter`.
`NetworkRoomPlayer.OnClientEnterRoom` is called in the start method of `NetworkRoomPlayer` and `CallOnClientEnterRoom`.
This change will mean that `NetworkRoomManager.OnRoomClientEnter` and `NetworkRoomPlayer.OnClientEnterRoom`  are called when the NetworkRoomPlayer is created
> fix: moving where CallOnClientEnterRoom is called

- Assets/Mirror/Editor/Weaver/Processors/PropertySiteProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/ServerClientAttributeProcessor.cs
- Assets/Mirror/Tests/Editor/Weaver/.WeaverTests.csproj
- Assets/Mirror/Tests/Editor/Weaver/WeaverClientServerAttributeTests.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverClientServerAttributeTests~/ClientAttributeOnAbstractMethod.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverClientServerAttributeTests~/ClientAttributeOnOverrideMethod.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverClientServerAttributeTests~/ClientAttributeOnVirutalMethod.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverClientServerAttributeTests~/ServerAttributeOnAbstractMethod.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverClientServerAttributeTests~/ServerAttributeOnOverrideMethod.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverClientServerAttributeTests~/ServerAttributeOnVirutalMethod.cs
Adding an error because adding Server/Client to abstract method does nothing and may lead people to leave the attribute off the overridden method.
also test for virtual, abstract and override methods
> fix: adding error when Server/Client is used on abstract methods

- Assets/Mirror/Components/Discovery/NetworkDiscoveryBase.cs
- Assets/Mirror/Examples/Room/Scripts/NetworkRoomManagerExt.cs
- Assets/Mirror/Runtime/Logging/NetworkHeadlessLogger.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Tests/Editor/NetworkManagerTest.cs
- Assets/Mirror/Tests/Runtime/HostSetup.cs
Using Server Build instead of checking GraphicsDeviceType could help stop confusion with new users create server only builds.
- using `-batchmode` does not mean that `isHeadless` is true, `-nographics` is also required.
- This causes confusion because `startOnHeadless`'s comment say to use  "the -batchMode command line arguement"
- Server build add both `-batchmode` and `-nographics` automatically
- Server build is true when "Server build" is checked in build menu, or `BuildOptions.EnableHeadlessMode` flag is in `BuildOptions`
resolves: https://github.com/vis2k/Mirror/issues/2063
this is probably classed as breaking, before we merge we will have to add new version defines
> breaking: replacing isHeadless with isServerBuild

- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/Editor/NetworkServerTest.cs
Dont need to run Server Update if there are no connections.
It would be useful to use the same game code for single player and multiplayer, this helps to remove the overhead when running in host mode with no other connections.
> perf: adding check for no connections

- Assets/Mirror/Editor/Weaver/Readers.cs
- Assets/Mirror/Editor/Weaver/Writers.cs
- Assets/Mirror/Tests/Editor/Weaver/.WeaverTests.csproj
- Assets/Mirror/Tests/Editor/Weaver/WeaverGeneratedReaderWriterTests.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverGeneratedReaderWriterTests~/CanUseCustomReadWriteForAbstractClass.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverGeneratedReaderWriterTests~/GivesErrorWhenUsingAbstractClass.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverNetworkBehaviourTests.cs
weaver can not initialize class abstract class so cant not create a reader
this gives a helpful error telling the server to make a custom reader
Will merge once tests pass
> fix: adding error for generated read writer for abstract class

- Assets/Mirror/Runtime/NetworkIdentity.cs
Replacing `prefabAssetPath` with `assetPath` for PrefabStage to stop warning:
```
prefabAssetPath has been deprecated. Use assetPath instead.
```
I have tested and it seems that both properties give the same value.
> fix: replacing obsolete method with new version

- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
Removing `HandleCommand` and `HandleRPC`
These methods only set the enum then call `HandleRemoteCall`, instead the Handlers functions can set the enum and then call `HandleRemoteCall` themselves.
Changing tests to use `HandleRemoteCall`
> removing methods that only set enum

- CONTRIBUTING.md
* VisualStudio and VisualStudioCode with c# extension automatically add space between { }
* Formatting tools automatically add space between { } so the option is to have no automatic formatting or use { }
* There does not seem to be an editorconfig setting to override this behaviour
> docs: removing point about empty class bodies  in  CONTRIBUTING.md 

- CONTRIBUTING.md
adding paragraph before testing header
updating testing paragraph to better convey that testing is to help find bugs and issues
> docs: updating Contribute

- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Tests/Editor/NetworkBehaviourTests.cs
- There should be no reason to manually invoke remote code
- They are marked with `EditorBrowsableState.Never` which implies they should not be called by the user
- `GetMethodHash`  is currently internal so users have no way to create hash needed to call this method
If user does need to invoke remote code then that code should be in a non remote method, the purple of Cmd/RPC is to be invoked on other instances (server/client)
> breaking: Removing manual invoke for Cmd and RPC

- Assets/Mirror/Components/NetworkRoomManager.cs
- Assets/Mirror/Components/NetworkRoomPlayer.cs
`OnClientExitRoom` wasn't being called on all client when a client left, it was only called on the client that left.
`OnClientEnterRoom` is called on every client, so `OnClientExitRoom` should match it.
> fix: making sure CallOnClientExitRoom is called when object is disabled/destroyed

- Assets/Mirror/Runtime/NetworkIdentity.cs
adding doc comment to say when `ClearObservers` is called 
helps to explain why `conn.RemoveFromVisList(this, true);` has isDestroyed as true
> adding doc comment

- Assets/Mirror/Runtime/ClientScene.cs
User was having this exception 
```cs
MissingReferenceException: The object of type 'NetworkIdentity' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.Object.get_name () (at <ee47be73f7ef409ca5e5ce4b121745b7>:0)
Mirror.ClientScene.CheckForLocalPlayer (Mirror.NetworkIdentity identity) (at Assets/Mirror/Runtime/ClientScene.cs:1003)
Mirror.ClientScene.OnObjectSpawnFinished (Mirror.ObjectSpawnFinishedMessage _) (at Assets/Mirror/Runtime/ClientScene.cs:876)
Mirror.NetworkClient+<>c__DisplayClass31_0`1[T].<RegisterHandler>b__0 (Mirror.NetworkConnection _, T value) (at Assets/Mirror/Runtime/NetworkClient.cs:331)
Mirror.MessagePacker+<>c__DisplayClass7_0`2[T,C].<MessageHandler>b__0 …
```
> fix: fixing NullReferenceException when loading scene

- Assets/Mirror/Runtime/NetworkServer.cs
There is no need to pack message if there are no observers to send it to
> pref: increasing performance when Send is called on no observers

- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Runtime/NetworkServer.cs
return early from `SendToObservers` and `SendToReady` instead of having everything nested in an if
depends on https://github.com/vis2k/Mirror/pull/2244
> flip equals to return early

- Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
- Assets/Mirror/Editor/Weaver/WeaverTypes.cs
InvokeUserCode was using `NetworkConnection` instead of `NetworkConnectionToClient`, `CmdDeligate` already used `NetworkConnectionToClient` so there the InvokeUserCode  function can also use it.
fixes: https://github.com/vis2k/Mirror/issues/2122
will merge when tests pass
> fix: fixed sender connection in commands for il2cpp

- Assets/Mirror/Editor/Weaver/Extensions.cs
- Assets/Mirror/Editor/Weaver/Processors/MonoBehaviourProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/ServerClientAttributeProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/SyncVarProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/TargetRpcProcessor.cs
- Assets/Mirror/Editor/Weaver/Readers.cs
- Assets/Mirror/Editor/Weaver/Weaver.cs
- Assets/Mirror/Editor/Weaver/Writers.cs
This is hard to read:
```
if (ca.AttributeType.FullName == typeof(Mirror.CommandAttribute).FullName) {
...
}
```
```
if (ca.AttributeType.Is<Mirror.CommandAttribute>()) {
...
}
```
> Enhance code readability by using extension method

- Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/SyncVarProcessor.cs
- Assets/Mirror/Editor/Weaver/Readers.cs
- Assets/Mirror/Editor/Weaver/Weaver.cs
- Assets/Mirror/Editor/Weaver/Writers.cs
The plan is to remove WeaverLists at some point so moving the functions out of Weaver to here for now and then we can move them closer to where they are actually used when we start to remove WeaverLists.
> weaver: moving WeaverLists functions to WeaverLists

- Assets/Mirror/Editor/Weaver/WeaverExceptions.cs
- Assets/Mirror/Editor/Weaver/WeaverExceptions.cs.meta
- Assets/Mirror/Editor/Weaver/Writers.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests.cs
The goal of this and future PR is to simplify error handling in weaver and to only return 1 error message to the user per error.
- Throwing GenerateWriterException instead of returning null.
- This PR only changes stuff inside of Writers, in future PR `GetWriteFunc` not catch the error and instead let the caller deal with it.
See this comment for more of plan https://github.com/vis2k/Mirror/pull/2173#issuecomment-675425003
> weaver: throwing within writers

- Assets/Mirror/Editor/Weaver/Readers.cs
- Assets/Mirror/Editor/Weaver/Writers.cs
Currently,  whenever we want to serialize an enum,
we simply serialize the underlying type (byte, short, int)
This works fine,  but in order to get the reader and writer
at runtime I need a function for each type.
With this PR, we generate a reader and writer function for enums too,
the function body simply calls the underlying reader and writer.
> Generate reader and writer functions for enums

- Assets/Mirror/Editor/Weaver/Readers.cs
- Assets/Mirror/Editor/Weaver/Writers.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverGeneralTests.cs
Remove all the recursionCount nonsense.
This was added to prevent infinite recursion with types that reference themselves.
No need to check anymore,  the weaver can generate readers and writers for types that reference themselves such as:
```cs
class Tree {
Tree child1;
Tree child2;
}
```
This works by the weaver doing it the way the compiler does:  Create a function first,  memoize it,  then write the body.  If the body needs the function,  it will get itself and issue a call to itself.
> feat: Support recursive data types

- Assets/Mirror/Editor/Weaver/Extensions.cs
- Assets/Mirror/Editor/Weaver/Processors/GenericArgumentResolver.cs
- Assets/Mirror/Editor/Weaver/Processors/SyncDictionaryProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/SyncListProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/SyncObjectProcessor.cs
- Assets/Mirror/Editor/Weaver/Weaver.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncListGenericInheritanceWithMultipleGeneric.cs
The weaver was not able to figure out the synclist type in code like this:
```cs
public class SomeList<G, T> : SyncList<T> { }
public class SomeListInt : SomeList<string, int> { }
```
This code fixes that problem, and greatly reduces the complexity
of argument lookup.
> fix: generic arguments resolution

- Assets/Mirror/Editor/Weaver/Extensions.cs
- Assets/Mirror/Editor/Weaver/Processors/ReaderWriterProcessor.cs
- Assets/Mirror/Editor/Weaver/Readers.cs
- Assets/Mirror/Editor/Weaver/Weaver.cs
- Assets/Mirror/Editor/Weaver/Writers.cs
- Assets/Mirror/Runtime/NetworkReader.cs
- Assets/Mirror/Runtime/NetworkWriter.cs
- Assets/Mirror/Tests/Editor/NetworkReaderWriterTest.cs
- Assets/Mirror/Tests/Editor/NetworkReaderWriterTest.cs.meta
Currently in mirror,  there is no way for Mirror itself to invoke
readers and writers for types it does not know about.
This causes us to have to generate code for lists, dictionaries and messages.
This PR makes it so that if there is a reader and writer anywhere in the
code for type X, then the writer can be invoked like this:
```cs
X x = ...;
writer.Write<X>(x);
```
and the reader can be invoked like this:
```cs
X x = reader.Read<X>();
```
> feat: new generic Read and Write methods for all types

- Assets/Mirror/Editor/Weaver/Extensions.cs
- only catching AssemblyResolutionException
- using null propagation instead of null ref
Will merge when tests pass
> using null propagation instead of catching null ref

- Assets/Mirror/Runtime/ClientScene.cs
I was looking through the open bugs in the project to contribute to it. Since I am using it in my own project it only felt right to contribute somehow. This is my first pull request in the project so I am sorry if am breaking the guidelines. I read through them but still sorry if I did the PR wrong.
I was looking through the codebase to understand why OnStopClient was not being called on client side when connection dropped/disconnected as stated in these bugs #2119 #2232 
The reason behind that is, it is only being referenced in [NetworkServer](https://github.com/vis2k/Mirror/blob/master/Assets/Mirror/Runtime/NetworkServer.cs) for shutdown/disconnect purposes. I looked through for similar calls on Client side which I could utilize rather than creating my own. I found out that there is a …
> Fixed OnStopClient not being called on Client Side

- Assets/Mirror/Editor/Weaver/Processors/SyncObjectInitializer.cs
Weaver should initialize `public SyncList<int> myList;`  in the same way it does for `SyncListInt`
> fix: fixing Initializer for generic synclists

- Assets/Mirror/Editor/Weaver/Processors/SyncObjectInitializer.cs
- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests.cs
Users need to initialize their SyncLists themselves.  For example:
```cs
public class Pepe: NetworkBehavior {
// BAD
public SyncList<int> mylist;
// GOOD
public SyncList<int> mylist = new SyncList<int>();
}
```
This is completely unnecessary magic we inherited from HLAPI.   Users normally have to initialize their normal lists,  so why should SyncLists be different?  This also means that sync objects no longer have to have a default constructor.
This also affects SyncSets and SyncDictionaries.
BREAKING CHANGE: You must initialize all your SyncLists, SyncSets and SyncDictionaries
> breaking: Users must initialize synclists (#391)

- Assets/Mirror/Components/Experimental/NetworkRigidbody2D.cs
- Assets/Mirror/Components/Experimental/NetworkRigidbody2D.cs.meta
Added `Mirror.Experimental.NetworkRigidbody2D`, which supports 2D rigid bodies instead of regular ones.
> Support for 2D rigidbodies

- Assets/Mirror/Runtime/NetworkConnection.cs
A more useful error in cases where the transport sends an empty array to mirror
> checking if incoming message has length 0 before checking its id

- Assets/Mirror/Editor/Weaver/Readers.cs
- Assets/Mirror/Editor/Weaver/Writers.cs
- Assets/Mirror/Runtime/NetworkReader.cs
- Assets/Mirror/Runtime/NetworkWriter.cs
- Assets/Mirror/Tests/Editor/NetworkWriterTest.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverGeneratedReaderWriterTests.cs
The code to serialize lists, arrays, and array segments is now in the runtime instead of generated in the weaver.
removes about 300 LOC of weaver witchcraft
> simplify serializing collections (#416)

- Assets/Mirror/Runtime/LocalConnections.cs
- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Runtime/NetworkConnectionToClient.cs
- Assets/Mirror/Runtime/NetworkServer.cs
* moving check to base connection because it could be used for either
* renaming to IsAlive
* passing in timeout so it doesn't need to check NetworkServer
* updating doc comment
> Simplifing IsClientAlive check

- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Runtime/NetworkServer.cs
* `clientOwnedObjects` is a hashset which doesn't need to be disposed
* `DestroyOwnedObjects` already clears list which is called by `networkmanager` when connection disconnects
> Removing IDisposable from NetworkConnection

- Assets/Mirror/Components/NetworkRoomManager.cs
- Assets/Mirror/Components/NetworkRoomPlayer.cs
- Assets/Mirror/Components/NetworkTransformBase.cs
- Assets/Mirror/Runtime/ClientScene.cs
- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkManagerHUD.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Runtime/SyncDictionary.cs
- Assets/Mirror/Runtime/SyncList.cs
- Assets/Mirror/Runtime/SyncSet.cs
- Assets/Mirror/Runtime/Transport/LLAPITransport.cs
- Assets/Mirror/Runtime/Transport/TelepathyTransport.cs
`EditorBrowsable(EditorBrowsableState.Never)` does nothing helpful within the same Solution, so this removes them all.
Some were with Obsolete's, and those will be removed in separate PR(s).
> Remove EditorBrowsable Never Attributes

- Assets/Mirror/Runtime/NetworkIdentity.cs
* stops error prone behaviour of using = from multiple scripts
BREAKING CHANGE: `= callback` now needs to be `+= callback`
> breaking: Making ClientAuthorityCallback an event

- Assets/Mirror/Authenticators/BasicAuthenticator.cs
- Assets/Mirror/Runtime/NetworkAuthenticator.cs
Ease of use:  Devs can just call the base methods instead of having to invoke.
> Add Accept and Reject methods to Authenticator

- Assets/Mirror/Editor/Weaver/Processors/PropertySiteProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/ReaderWriterProcessor.cs
- Assets/Mirror/Editor/Weaver/Readers.cs
- Assets/Mirror/Editor/Weaver/Weaver.cs
- Assets/Mirror/Editor/Weaver/Writers.cs
* Making `ReaderWriterProcessor` return if it found custom functions (not counting ones in mirror.dll)
* Always writing `generateContainerClass` if modified
* processing `PropertySiteProcessor` if either `ReaderWriterProcessor` or `WeaveModule` are successful
* creating `generateContainerClass` in WeaverList constructor
* Moving new WeaverList to after `WeaverTypes.SetupTargetTypes`
> fix(weaver): Fixing weaver not writing when assemble didn't have NetworkBehaviour

- Assets/Mirror/Components/Experimental/NetworkTransformBase.cs
It is best practice to put variables above all methods in c#
> Moving variable to top of file.

- Assets/Mirror/Runtime/Mirror.asmdef
- Assets/Mirror/Runtime/Transport/KCP/MirrorTransport/KcpTransport.cs
- Assets/Mirror/Runtime/Transport/KCP/kcp2k/highlevel/KcpConnection.cs
- Assets/Mirror/Runtime/Transport/KCP/kcp2k/kcp2k.asmdef
- Assets/Mirror/Runtime/Transport/KCP/kcp2k/kcp2k.asmdef.meta
kcp2k doesn't depend on mirror so should be in its own asmdef. This means that kcp scripts one be re-compiled each time a change is made to mirror and that internal function are not used when they are not intended to be.
Added public getters for SendQueueCount (and others) so they can be used to should debug info not only by KcpTransport but also other if they want to use the kcp2k library.
Removing the `allowUnsafeCode` checkbox for mirror as it no longer needs it if kcp2k is in its own asmdef
> adding asmdef to kcp2k folder

- Assets/Mirror/Runtime/Transport/KCP/MirrorTransport/KcpTransport.cs
- Assets/Mirror/Runtime/Transport/SimpleWebTransport/SimpleWebTransport.cs
Defines are not set when mirror is first imported so will give errors if we use `#IF MIRROR` or other defines within the mirror package.
Tested in `2018.4.28f1` and `2019.4.3f1`. 
- New empty project
- Download v26.1 package from github
- Get this error
> fix: fixing first import of package 

- Assets/Mirror/Components/NetworkRoomManager.cs
- Assets/Mirror/Examples/Basic/Scenes/Example.unity
- Assets/Mirror/Examples/Basic/Scripts/BasicNetManager.cs
- Assets/Mirror/Examples/Basic/Scripts/BasicNetManager.cs.meta
- Assets/Mirror/Examples/Basic/Scripts/Player.cs
- Assets/Mirror/Examples/MultipleAdditiveScenes/Scenes/Game.unity
- Assets/Mirror/Examples/MultipleAdditiveScenes/Scenes/Main.unity
- Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/MultiSceneNetManager.cs
- Assets/Mirror/Examples/Room/Scripts/PlayerScore.cs
These examples all relied on connectionID being sequential from the transport (e.g. Telepathy) but KCP doesn't use sequential id's.
Changed them all to use a clientIndex instead.
> fix: Examples No Longer Rely On Sequential connectionId

- Assets/Mirror/Runtime/NetworkManager.cs
Pull request for issue #2071.
I supposed you could prevent every try to start a server or a client when it's already active.
> prevent multiple client or server to start

- Assets/Mirror/Runtime/NetworkReader.cs
- Assets/Mirror/Runtime/NetworkWriter.cs
SQUASH!
consistent read/write(u)int functions in extensions for networkreader and writer.
makes further performance and bandwidth improvements from 'x' branch possible afterwards.
this is good no matter what, because weaver will look for all read/write(u)int functions in one place.
right now, if we were to remove the packed functions then weaver would break with strange errors because it doesn't find regular write/read(u)int functions. this costs a lot of time to debugger, and is avoided this way.
> Networkwriter consistency

- Assets/Mirror/Runtime/Transport/KCP/MirrorTransport/KcpTransport.cs
Changed the default 100ms to 10ms
Double checked with Vis in Discord  "tooltip is meant to say 10ms."
Already seen one screenshot of a Discord user that set this from 10 to 100, due to the typo, believing 100 was meant to be default and not 10.
> Adjusted KCP tooltip typo.

- doc/Articles/CommunityGuides/MirrorQuickStartGuide/index.md
Removed due to possible confusion (as seen on discord), shouldn’t be needed in a temporary quickstart guide.
> QuickStart namespace removed.

- Assets/Mirror/Runtime/NetworkReaderPool.cs
- Assets/Mirror/Runtime/NetworkWriterPool.cs
- Assets/Mirror/Runtime/Pool.cs
- Assets/Mirror/Runtime/Pool.cs.meta
- Assets/Mirror/Tests/Editor/NetworkReaderPoolTest.cs
- Assets/Mirror/Tests/Editor/NetworkWriterPoolTest.cs
- Assets/Mirror/Tests/Editor/PoolTests.cs
- Assets/Mirror/Tests/Editor/PoolTests.cs.meta
keep it simple & stupid.
Stack<T> has already been built into C#, might as well use it.
same functionality while removing 200 LOC that we won't have to worry about anymore.
> Pool<T>; NetworkReader/WriterPools simplified by using Pool<T>

- Assets/Mirror/Runtime/NetworkReader.cs
- Assets/Mirror/Runtime/NetworkWriter.cs
Previously this just gave NRE, which does not help the user address the problem.
provides a better error for #2411
> feat: Provide user friendly error with undefined reader/writer

- Assets/Mirror/Editor/Weaver/Readers.cs
- Assets/Mirror/Editor/Weaver/Writers.cs
Generating readers and writers for structs in other assemblies
could sometimes cause a
```
System.ArgumentException: Member 'xxx' is declared in another module and needs to be imported
```
This in particular affected unity mathematics.
fixes #2406
> fix: using mathematics in commands and rpcs

- Assets/Mirror/Runtime/MessagePacker.cs
- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Tests/Editor/MessagePackerTest.cs
rename + obsolete.
MessagePacker.Unpack is easier to use than MessagePacker.UnpackMessage, which is unnecessarily verbose.
> MessagePacker.UnpackMessage renamed to Unpack for consistency with Pack and because the class is already named MessagePacker anyway

- Assets/Mirror/Runtime/NetworkConnection.cs
Planning to remove `InvokeHandler<T>` in https://github.com/vis2k/Mirror/pull/2397 so the code in InvokeHandler is only done in 1 place. Moving it to TransportReceive avoids the need for the return true/false
> Finding handler inside TransportReceive so we dont need to check bool

- Assets/Mirror/Runtime/Mirror.asmdef
- Assets/Mirror/Runtime/NetworkReader.cs
- Assets/Mirror/Runtime/NetworkWriter.cs
- Assets/Mirror/Runtime/UNetwork.cs
- Assets/Mirror/Tests/Editor/Mirror.Tests.asmdef
- Assets/Mirror/Tests/Editor/NetworkWriterTest.cs
Write/ReadBlittable<T> from DOTSNET.
**Benchmark:**
**Reasons to use Blittable**
+ 4-6x faster within Unity versions
+ (2020.1 + Blittable is 10x faster than 2018.4 without Blittable)
+ The code is a lot cleaner.
+ Removes 160 LOC
+ All Unity 2018+ platforms are little endian
+ This has been heavily tested in DOTSNET
+ Non-Blittable types still work fine
+ Invisible change to the user
+ No more UIntFloat etc. conversion structs
+ The more complex the type, the more significant the performance gain compared to serializing each member manually
+ Will allow us to reduce generated weaver code later. All blittable types can simply use WriteBlittable.
It's 4-6x performance for free. Would be silly not to use it.
**Unity Platform Endianness**
[Little] Windows
[Little] Mac(Intel)
[Little] …
> perf: NetworkWriter/Reader Write/ReadBlittable<T> for 4-6x performance improvement!

- Assets/Mirror/Runtime/NetworkWriter.cs
Public methods should have human readable comments to explain what they do and how/when to use them
> docs(NetworkWriter): doc comments

- Assets/Mirror/Editor/Weaver/Readers.cs
- Assets/Mirror/Editor/Weaver/Writers.cs
- Assets/Mirror/Tests/Editor/Weaver/.WeaverTests.csproj
- Assets/Mirror/Tests/Editor/Weaver/WeaverGeneratedReaderWriterTests.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverGeneratedReaderWriterTests~/GivesWarningWhenRegisteringExistingExtensionMethod.cs
Adding warning message when trying to register a write or read function for a type that is already in dictionary. Previously weaver would be silent about this making it hard to know when an extension method overrides another one.
Will write test for this soon
> fix(weaver): Warning for multiple write/read functions for the same type

- Assets/Mirror/Editor/Weaver/Readers.cs
- Assets/Mirror/Editor/Weaver/Writers.cs
Having near identical lines in these functions is confusing at first glace. Having RegisterWriteFunc call Register makes it more clear exactly what is going on
Adding doc comments to explain when each method should be called
> Calling Register from RegisterWriteFunc and adding comments

- Assets/Mirror/Runtime/NetworkReader.cs
url needs double `{{`, unsure why the docfx docs are unclear
> ci(docs): fixing xrefService for docfx

- Assets/Mirror/Editor/NetworkScenePostProcess.cs
Previously it would give 'a scene needs to be resaved', which is confusing.
> fix: NetworkScenePostProcess gives proper error message if currently in prefab edit mode.

- Assets/Mirror/Editor/NetworkScenePostProcess.cs
Better than launching with sceneId errors, which never works.
requires #2467
> fix: NetworkScenePostProcess now stops editor for invalid sceneIds

- doc/Articles/Guides/DevServer/AWS/index.md
- doc/Articles/Guides/DevServer/gcloud/index.md
Now that Kcp Transport is the default for Mirror's Network Manager, let's update the docs to provide info on how setting up a dev server may be differ.
> Update Dev Server docs for Kcp Transport

- Assets/Mirror/Components/NetworkTransformBase.cs
- Assets/Mirror/Tests/Editor/NetworkTransformTest.cs
1024 entity rotations=> 4KB instead of 16KB
@James-Frowen implemented quaternion compression, might as well use it :)
> perf: NetworkTransform compresses rotation from 16 to 4 bytes.

- Assets/Mirror/Editor/Weaver/Extensions.cs
Avoids the need to do `td.Resolve().IsDerivedFrom`, `TypeDefinition` inherits from `TypeReference`.  
this now matches `public static bool Is<T>(this TypeReference td) => Is(td, typeof(T));`
used in https://github.com/vis2k/Mirror/pull/2471
> weaver: adding IsDerivedFrom for TypeReference

- Assets/Mirror/Editor/Weaver/Extensions.cs
- Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/SyncVarProcessor.cs
removes duplicate code in `NetworkBehaviourProcessor` and `SyncVarProcessor`
used in https://github.com/vis2k/Mirror/pull/2471
> weaver: moving IsNetworkIdentityField to extensions

- Assets/Mirror/Editor/Weaver/Readers.cs
- Assets/Mirror/Editor/Weaver/TypeReferenceComparer.cs
- Assets/Mirror/Editor/Weaver/TypeReferenceComparer.cs.meta
- Assets/Mirror/Editor/Weaver/Writers.cs
- Assets/Mirror/Tests/Editor/NetworkWriterCollectionTest.cs
- Assets/Mirror/Tests/Editor/NetworkWriterCollectionTest.cs.meta
* Using TypeReference  with IEqualityComparer instead of string to keep reference to type
* using targetType to initialize write/read functions
* test to make sure write function is set
> weaver: using TypeReference with comparer instead of string

- Assets/Mirror/Runtime/ClientScene.cs
* matches server side logic
* if an object is being fully destroyed it doesn't need its values to be reset
flipping logic so it is:
```
if user handler
else if not scene object
else scene object 
```
reset should be called for userhandler and scene object, not destroyed objects (so that value arn't reset in OnDestroy)
> fix: stopping values being reset before OnDestory is called

- Assets/Mirror/Runtime/NetworkManager.cs
Seems like this has come up a few times so here is a commit to sort this out.
We shouldn't have to worry about the order of the using, we should just let plugins automatically sort them. They are sorted into alphabetical order expect for system becase we have `dotnet_sort_system_directives_first = true` enabled in `.editorconfig`, 
edit: what `dotnet_sort_system_directives_first ` does: https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/formatting-rules#dotnet_sort_system_directives_first
> Sorting usings

- Assets/Mirror/Components/NetworkTransformBase.cs
`byte[] payload` will cause a new array to be created when parameters are read, using `ArraySegment<byte>` avoids this.
> perf(NetworkTransform): removing allocations from Command

- Assets/Mirror/Editor/Weaver/Extensions.cs
- Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/SyncVarProcessor.cs
- Assets/Mirror/Editor/Weaver/Readers.cs
- Assets/Mirror/Editor/Weaver/WeaverTypes.cs
- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Runtime/NetworkReader.cs
- Assets/Mirror/Tests/Editor/NetworkWriterTest.cs
- Assets/Mirror/Tests/Editor/SyncVarHookTest.cs
- Assets/Mirror/Tests/Editor/SyncVarTest.cs
- Assets/Mirror/Tests/Editor/SyncVarTestBase.cs
- Assets/Mirror/Tests/Editor/SyncVarTestBase.cs.meta
Creating backing field for NetworkBehaviour syncvar so that they work the same as NetworkIdentity and GameObject syncvars
requires: 
https://github.com/vis2k/Mirror/pull/2475
https://github.com/vis2k/Mirror/pull/2476
https://github.com/vis2k/Mirror/pull/2478
> feat: allow types that inherit from Networkbehaviour to be used in syncvar's

- Assets/Mirror/Runtime/Transport/KCP/MirrorTransport/KcpTransport.cs
Setting the debugLog flag off on KCP transport does not remove such logs from console (e.g. when you have a headless server).
This PR overwrites the default Console.Log function when the flag is off.
> Disable KCP console logging when debugLog flag is off

- Assets/Mirror/Editor/Weaver/WeaverTypes.cs
Unity has added new private LogWarning methods in 2020.2 which causes weaver to find the wrong method. Checking the parameters as we as the name will find the correct method.
fixes: https://github.com/vis2k/Mirror/issues/2366
> fix(weaver): Weaver finds correct log methods for unity 2020.2

- Assets/Mirror/Runtime/NetworkReader.cs
- Assets/Mirror/Tests/Editor/NetworkWriterTest.cs
A poison message could contain an invalid length causing us to allocate massive arrays
> fix: prevent allocation of massive array

- doc/Articles/General/Migration.md
This is the only occurrence of LLAPITransport I could find. Replacing it with a reference to UDP and Steam transports seems best.
> Remove LLAPITransport language and replace with UDP and Steam. 

- Assets/Mirror/Editor/Logging/LogLevelsGUI.cs
- Assets/Mirror/Editor/ScriptableObjectUtility.cs
This allows ScriptableObjectUtility to be used for other folders not just Asset/Mirror
> feat: Adding default folder as argument for ScriptableObjectUtility

- Assets/Mirror/Runtime/Mirror.asmdef
- Assets/Mirror/Runtime/NetworkReader.cs
- Assets/Mirror/Runtime/NetworkWriter.cs
- Assets/Mirror/Runtime/UNetwork.cs
- Assets/Mirror/Tests/Editor/Mirror.Tests.asmdef
- Assets/Mirror/Tests/Editor/NetworkWriterTest.cs
This PR Fixes #2511, #2518 (confirmed in private DMs on Discord) and any other developers' issues about Mirror randomly crashing on ARMv7 devices running on Mono backend with **SIGBUS BUS_ADRALN** codes. This PR reverts commit 1947f061add00b9a8b02a8778f5bd9bc2b7cd158 and brings both NetworkReader and NetworkWriter up to date in a no-Blittable branch.
This PR removes WriteBlittable, which was a supposedly 4x - 6x performance increase from DOTSNET. Unfortunately it bugs out on Android devices. It also reverts it back to a slower but stable Write method.
**Now tested and confirmed working. No more NullPointerExceptions on Mono ARMv7.**
Quoting vis:
> imho let's just revert. who knows where else it'll fail.
> breaking: Revert WriteBlittable. Fixes Android on ARMv7 devices firing SIGBUS BUS_ADRALN error codes.

- Assets/Mirror/Tests/Editor/NetworkWriterTest.cs
I'm dumb, forgot to patch NetworkWriterTest.cs in last PR. It's patched now.
> fix: NetworkWriterTest.cs failing due to Blittable removal

- Assets/Mirror/Runtime/NetworkTime.cs
Gives an order of magnitude better rtt and less clock error on transports that support unreliable channel such as KCP
> perf: synchronize network time over unreliable

- doc/Articles/Components/NetworkLerpRigidbody.md
I believe this should say you should NOT have a network transform on a gameobject with a network rigidbody.
> Fixing typo on Network Lerp Rigidbody

- doc/Articles/CommunityGuides/MirrorQuickStartGuide/index.md
Mentioned by a few users in Discord for part 11.
Added note to attach NetworkIdentity component to SceneScript, if it has not automatically done so.
> Clarity update for SceneScript NetworkIdentity.

- Assets/Mirror/Runtime/NetworkManager.cs
- Moves Network Manager out of DDOL before going to offline scene to avoid collision and let a fresh Network Manager be created.
> feat: Move Network Manager out of DDOL in StopServer and StopClient

- Assets/Mirror/Runtime/NetworkManagerHUD.cs
remove unnecessary complexity.
use, or don't use the component.
> obsolete NetworkManagerHUD.showGUI

- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/Editor/NetworkServerTest.cs
keep it simple. one version should do.
> NetworkServer: obsolete redundant RegisterHandler version without connection parameter

- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkLoop.cs
- Assets/Mirror/Runtime/NetworkLoop.cs.meta
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/Editor/NetworkLoopTests.cs
- Assets/Mirror/Tests/Editor/NetworkLoopTests.cs.meta
- Assets/Mirror/Tests/Editor/NetworkServerTest.cs
- Assets/Mirror/Tests/Editor/RemoteTestBase.cs
- Assets/Mirror/Tests/Runtime/NetworkServerWithHostRuntimeTest.cs
simply adds NetworkEarly/LateUpdate functions.
they aren't being used yet.
step by step.
unit tests:
pressing play multiple times still only adds one early/lateupdate each time
> feature: add custom NetworkEarlyUpdate (before any Update/FixedUpdate), NetworkLateUpdate (after any Update/FixedUpdate/LateUpdate)

- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Runtime/Transport/Transport.cs
- Assets/Mirror/Tests/Editor/NetworkServerTest.cs
- Assets/Mirror/Tests/Editor/RemoteTestBase.cs
- Assets/Mirror/Tests/Runtime/NetworkServerWithHostRuntimeTest.cs
merge #2604 first
all transports that still use LateUpdate will show a warning.
the new functions are virtual for now so we don't break anything.
=> everything still works, we can modify transports over time
> perf: Transport.Client/Server Early/LateUpdate to fix data races and allow transports to reduce latency by doing all receiving & sending in one frame.

- Assets/Mirror/Editor/SceneDrawer.cs
When the user renamed offline scene or online scene, it will always cause editor rendering errors in `NetworkManager`. To solve it, I had to re-add the component `NetworkManager`. This is happening because the previous path to the scenes is preserved. The script tries to load it, and it can't find it, which causes `NullReferenceException`.
Sample error:
```
NullReferenceException: Object reference not set to an instance of an object
Mirror.SceneDrawer.GetBuildSettingsSceneObject (System.String sceneName) (at Assets/Mirror/Editor/SceneDrawer.cs:43)
Mirror.SceneDrawer.OnGUI (UnityEngine.Rect position, UnityEditor.SerializedProperty property, UnityEngine.GUIContent label) (at Assets/Mirror/Editor/SceneDrawer.cs:18)
UnityEditor.PropertyDrawer.OnGUISafe (UnityEngine.Rect position, …
```
> fix: scene rename handling NullReferenceException in NetworkManager

- Assets/Mirror/Components/Discovery/NetworkDiscoveryBase.cs
If you want to extend NetworkDiscoveryBase using the templates, you may hit this problem where you want to disable the automatic discovery. But you can't without modifying the base class. This is a proposition that is not breaking for users of the NetworkDiscovery.
> feat: Added bool to Discovery to disable automatic active discovery

- Assets/Mirror/Runtime/Transport/MultiplexTransport.cs
When MultiplexTransport is used with KcpTransport, SimpleWebTransport or TelepathyTransport it does not call update methods from new NetworkLoop. It breaks the transmission of any network messages.
> fix: Add missing virtual update methods in MultiplexTransport

- Assets/Mirror/Runtime/NetworkLoop.cs
Networkloop breaks other libraries that use playerloop (eg UniTask) so it's impossible to use Mirror with them together.
> fix: networkloop breaks other libraries that use playerloop

- Assets/Mirror/Runtime/NetworkConnection.cs
Adds the size of a too large packet to the log, can then be used to know if a packet was only just over the size limit or if there's a serious issue somewhere.
> Log oversize packet size

- Assets/Mirror/Runtime/NetworkClient.cs
StopClient called from user code triggers Disconnected event from transport which calls StopClient again
Check in OnDisconnected and short circuit running the Shutdown process twice.
> fix: Prevent client shutdown from running twice

- Assets/Mirror/Runtime/NetworkManager.cs
This will prevent this unhelpful warning:
`Replacing existing prefab with assetId 'c3ee5d2b-0807-ecb4-f85b-93753624468e'. Old prefab 'Player', New prefab 'Player'`
> feat: Prevent Player Prefab from being added to spawnPrefabs

- Assets/Mirror/Authenticators/BasicAuthenticator.cs
- Assets/Mirror/Authenticators/TimeoutAuthenticator.cs
- Assets/Mirror/Runtime/NetworkAuthenticator.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/ScriptTemplates/51-Mirror__Network Authenticator-NewNetworkAuthenticator.cs.txt
As was done in other areas, now using `NetworkClient.connection` instead of passing a `conn` parameter around.
- Abstract NetworkAuthenticator now has obsoletes.
- Basic and Timeout Authenticators Updated
- Network Manager Updated
- Script Template Updated
> fix: Network Authentators: Removed NetworkConnection parameter

- Assets/Mirror/Components/NetworkTransformBase.cs
Tidied up sync scale / interpolate scale.
Added interpolate rotation and position booleans.
Tooltips with use-case for both.
Rotation option was added for a discord user, who was experiencing strangeness with his retro snake-like character movement.
Seemed ideal to also add Position boolean for grid based/movement snapping users at the same time.
Tested all cases, but double checking from anyone else would be greatly appreciate too ;)
> sync scale and interpolation adjustments

- Assets/Mirror/Runtime/NetworkConnectionToClient.cs
- Assets/Mirror/Runtime/NetworkWriter.cs
- Assets/Mirror/Tests/Editor/EnumReadWriteTests.cs
- Assets/Mirror/Tests/Editor/MessageInheritanceTest.cs
- Assets/Mirror/Tests/Editor/NetworkWriterTest.cs
- Assets/Mirror/Tests/Editor/StructMessagesTests.cs
- Assets/Mirror/Tests/Editor/SyncListTest.cs
- Assets/Mirror/Tests/Editor/SyncVarTestBase.cs
**NetworkWriter currently has:**
.Position
.Length
.Capacity
**Which is super confusing.**
EnsureLength is always called when writing anything, which is super unnecessary.
SetLength(0) behaves different than Position=0, which is confusing.
ToArray/Segment works up to 'Length', not up to 'Position' which is confusing and error prone.
**In DOTSNET I only have .Position.**
That's totally enough and way easier to use.
We can't expect anyone to remember that .ToArray is until 'Length', not until 'Position', etc.
Bitpacking won't have this anyway.
**Can't Obsolete**
We can't obsolete and tell people to only use .Position instead, because .ToArray previously copied until .Length.
This is (and should be) a breaking change.
Pretty sure nobody uses Length anyway, we only used it in …
> breaking: perf: remove NetworkWriter.Length/SetLength/EnsureLength. Position is enough.

- Assets/Mirror/Components/Discovery/NetworkDiscoveryBase.cs
Avoids "Only one listener per port error" when returning to offline scene and restarting host.
> fix: Shutdown Discovery in OnDisable / OnDestroy

- README.md
Added missing url for Cubica pointing to "https://github.com/vis2k/Mirror/blob/master" instead of "https://www.cubica.net/"
> Missing URL Cubica

- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
**IMPORTANT: AddComponent<NetworkBehaviour> was never allowed at runtime to begin with.**
This PR would make NetworkBehaviour components added at runtime NOT initialize anymore at all.
It's all done from NetworkIdentity.Awake() now.
For Mirror users there should be no difference.
Only in tests where we add NetworkBehaviours at runtime.
=> all tests pass
=> works fine in uMMORPG
> breaking: NetworkBehaviour .netIdentity, .ComponentIndex, .NetworkBehaviours[] simplified by setting it from NetworkIdentity.Awake()

- Assets/Mirror/Runtime/NetworkServer.cs
Fixes #2737
Added call to RemoveFromObservingsObservers in NetworkServer.DestroyPlayerForConnection
> fix: Clear observers from other clients

- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkServer.cs
merge client->server batching PR first
> fix: #2651 scene changing with batching would cause errors because we wouldn't stop the batch processing after a scene message

- Assets/Mirror/Components/Experimental/NetworkRigidbody.cs
- Assets/Mirror/Components/Experimental/NetworkRigidbody2D.cs
Provide the same interface access for runtime changes like the NetworkTransform class.
> fix: clientAuthority access

- Assets/Mirror/Runtime/Batching/Batcher.cs
- Assets/Mirror/Runtime/Batching/Unbatcher.cs
- Assets/Mirror/Runtime/LocalConnections.cs
- Assets/Mirror/Runtime/MessagePacking.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Runtime/NetworkConnectionToClient.cs
- Assets/Mirror/Runtime/NetworkConnectionToServer.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Runtime/NetworkTime.cs
- Assets/Mirror/Tests/Common/FakeNetworkConnection.cs
- Assets/Mirror/Tests/Editor/Batching/BatcherTests.cs
- Assets/Mirror/Tests/Editor/Batching/UnbatcherTests.cs
- Assets/Mirror/Tests/Editor/InterestManagementTests_Common.cs
- Assets/Mirror/Tests/Editor/NetworkBehaviourTests.cs
- Assets/Mirror/Tests/Editor/NetworkConnectionToClientTests.cs
- Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
- Assets/Mirror/Tests/Editor/NetworkMatchCheckerTest.cs
- Assets/Mirror/Tests/Editor/NetworkServerTest.cs
- Assets/Mirror/Tests/Editor/TargetRpcTest.cs
- Assets/Mirror/Tests/Runtime/NetworkServerRuntimeTest.cs
- force enables batching at all times
- every batch includes a remote timestamp
- can be used for snapshot interpolation without sending one timestamp per message etc.
=> NetworkConnection.remoteTimeStamp can be used by the end user. for any given message/rpc/cmd, this was the time on the remote end when it was sent.
TESTS:
+ all unit tests run
+ works in ummorpg finally: https://gyazo.com/466fdb86ec9c3b53907a18c27eb78fd5
> feature: Timestamp Batching

- Assets/Mirror/Runtime/NetworkManager.cs
`FinishLoadScene` will be called from `UpdateScene`  if `loadingSceneAsync != null && loadingSceneAsync.isDone` and it's the responsibility of the user in their custom handler to assign `loadingSceneAsync` to something to block `FinishLoadScene` until that completes. If they don't, `UpdateScene` will call `FinishLoadScene` in the next frame.
Original issue was discussed in [Discord](https://discord.com/channels/343440455738064897/656822943384469504/836508781423755284).
> fix: Don't call FinishLoadScene when customHandling

- Assets/Mirror/Editor/Weaver/Processors/MethodProcessor.cs
Forces the new weaver generated method to be private, preventing users from mistakenly calling weaver generated methods in dropdown menus (such as buttons) in the inspector.
> fix: Weaver Generated Cmd/Rpc should be private

- Assets/Mirror/Runtime/NetworkClient.cs
Client message handlers may call conn.Disconnect, which will make connection = null, so we must check for that after calling `handler.Invoke`.
> fix: Avoid NRE in UnpackAndInvoke

- Assets/Mirror/Runtime/NetworkManager.cs
Moves check for `NetworkServer.active` to appropriate place after OnClientChangeScene is called.
> fix: OnClientChangeScene not firing for host client

- Assets/Mirror/Runtime/NetworkIdentity.cs
This is a small QoL change.
NetworkBehaviour error messages currently use Debug.LogError.
`Debug.LogError("Exception in OnStopAuthority:" + e.Message + " " + e.StackTrace);`
Call stacks are unclickable in console, which is kinda annoying. Also slightly less readable than normal stack traces.
Unity has a variant of Debug.Log specifically for logging exceptions, might as well use it.
`Debug.LogException(e, comp);`
Call stacks are now clickable, and they tell you enough that it came from OnStartServer.
By providing context parameter this comes with an additional benefit of highlighting relevant object when clicked.
> Use Debug.LogException for NetworkBehaviour error messages

- Assets/Mirror/Tests/Runtime/NetworkIdentityTests.cs
There's currently an issue with dropped/skipped serializations once a server has been running for around a week, this test should highlight the potential cause
> Add (failing) test for large timestamp serialization

- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/Runtime/NetworkIdentityTests.cs
risk free alternative to https://github.com/vis2k/Mirror/pull/2811
> fix: serialization precision over days by using frameCount instead of single precision time

- Assets/Mirror/Runtime/LocalConnections.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Tests/Editor/NetworkClientTests.cs
test added to prevent it in the future too.
> fix: #2822 - OnClientDisconnect wasn't called for host disconnect because LocalConnectionToServer wouldn't call OnTransportDisconnected

- Assets/Mirror/Runtime/InterestManagement.cs
- Assets/Mirror/Runtime/NetworkServer.cs
This simplifies managing per-object state in interest management a lot since you're now told when a new object is spawned/destroyed
Once this is in, we can move towards feature parity with the new interest management. 
For example, implementing something like this for the distance based aoi to override visibility ranges:
```c#
// straight forward Vector3.Distance based interest management.
using System.Collections.Generic;
using UnityEngine;
namespace Mirror
{
public class DistanceInterestManagement : InterestManagement
{
[Tooltip("The maximum range that objects will be visible at.")]
public int visRange = 10;
[Tooltip("Rebuild all every 'rebuildInterval' seconds.")]
public float rebuildInterval = 1;
double lastRebuildTime;
private Dictionary<NetworkIdentity, DistanceVisibilityOverride> …
```
> feat: Add OnSpawned/OnDestroyed events to interest management

- Assets/Mirror/Runtime/NetworkManager.cs
Calling StopServer from OnStartServer or StopClient from OnStopClient (or from user code invoked from those virtual methods) would create a recursion overflow.
This PR moves the setting of `isNetworkActive = false;` up above the virtual method calls in both cases, and adds a check to early out if false to prevent recursion and overflow.
Debug logs were also moved up nearer the top of the method.
Fixes: #2080
> fix: Prevent recursion overflow when stopping

- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Runtime/Transport/Transport.cs
- Assets/ScriptTemplates/50-Mirror__Network Manager-NewNetworkManager.cs.txt
Transports can raise OnServerError and OnClientError
Both are propagated up through NetworkServer & NetworkClient & NetworkManager
Virtual methods added to Network Manager and Template
Fixes: #2782
> feat: Transport Exception Handling

- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Tests/Editor/SyncVarTest.cs
Currently the float time will run out of precision and start skipping being dirty after ~a week of runtime.
Here's the tank example after 30 days of runtime with float time: https://share.dl.je/2021/07/2021-07-07_17-16-23_EKInti5s4v.mp4 (not fps lag)
Using double time fixes this
This should probably be used with #2838 to not encounter weird edge cases
> fix: NetworkBehaviour dirty check uses double time

- Assets/Mirror/Components/NetworkTransform2k/NetworkTransformBase.cs
Changed !isLocalPlayer to !hasAuthority because object might not be player object.
> fix: From !isLocalPlayer to !hasAuthority - NetworkTransform2k/NetworkTransformBase.cs

- Assets/Mirror/Runtime/Compression.cs
- Assets/Mirror/Tests/Editor/CompressionTests.cs
Adds back zigzag compression for signed ints so -1 doesn't compress as ulong.MaxValue
> feat: ZigZag VarInt Compression

- Assets/Mirror/Editor/Weaver/Readers.cs
- Assets/Mirror/Tests/Editor/ClientRpcTest.cs
- Assets/Mirror/Tests/Editor/SyncVarTest.cs
Currently Mirror does not support generating reader functions of abstract classes and structs.
`Readers.GenerateReader()` checks if the type is abstract and stops.
This makes sense on normal cases, but this causes inconveniences when you want to create an abstract class deriving from NetworkBehaviour.
```csharp
public abstract class ProjectileBase : NetworkBehaviour
{
protected abstract Vector3 SolvePosition();
....
}
public class ArrowProjectile : ProjectileBase
{
protected override Vector3 SolvePosition()
{
....
}
}
... // some random codes
[ClientRpc]
private void RpcDoSomething(ProjectileBase proj) // Weaver fails here! 
{ // Cannot generate reader for abstract type ProjectileBase
....
}
```
Mirror has reader and writer prepared for NetworkBehaviour types, letting types deriving from …
> Allow reader generation of abstract NetworkBehaviours by reordering checks in Readers.GenerateReader()

- Assets/Mirror/Components/NetworkTransform2k/NetworkTransformBase.cs
catchupThreshold needs to be at least bufferTimeMultiplier + 3, or it will interfere/conflict with checking if we have at least 3 old enough buffers. Catchup will decrease buffer while check needs at least 3 older.
> Changes to validation of catchupThreshold - NetworkTransform2k - NetworkTransformBase

- Assets/Mirror/Components/NetworkTransform2k/NetworkTransformBase.cs
#if UNITY_EDITOR || DEVELOPMENT_BUILD for OnGUI() added.
Related to this post, and discord discussion: https://github.com/vis2k/Mirror/issues/2871
"OnGUI calls allocate gc even when not doing anything"
This should give developers a mini optimisation, and means no manual editing needed of NTB.cs for their final releases.
Will apply to the other components, if accepted/good idea.  <thumbs up emoji>
> NTB.cs defines for OnGUI

- Assets/Mirror/Components/InterestManagement/SpatialHashing/SpatialHashingInterestManagement.cs
- Assets/Mirror/Runtime/Transport/KCP/MirrorTransport/KcpTransport.cs
Related to: https://github.com/vis2k/Mirror/pull/2874
"OnGUI allocates even if it does nothing. avoid in release."
KcpTransport.cs
SpatialHashingInterestManagement.cs
The other OnGUI's i found could be arguably important for client/non dev builds, such as NetworkManagerHUD, the above two are the ones i found that in most cases the GUI shouldn't exist in release.
> Defines for OnGUI

- Assets/Mirror/Components/InterestManagement/Match/MatchInterestManagement.cs
- Assets/Mirror/Components/InterestManagement/Scene/SceneInterestManagement.cs
- Assets/Mirror/Runtime/InterestManagement.cs
- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkReader.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/Common/MirrorTest.cs
- Assets/Mirror/Tests/Editor/ClientSceneTests_OnSpawn.cs
- Assets/Mirror/Tests/Editor/InterestManagementTests_Common.cs
- Assets/Mirror/Tests/Editor/NetworkBehaviourTests.cs
- Assets/Mirror/Tests/Editor/NetworkServerTest.cs
- Assets/Mirror/Tests/Editor/SyncVarHookTest.cs
- Assets/Mirror/Tests/Editor/SyncVarTest.cs
- Assets/Mirror/Tests/Runtime/ClientSceneTests_DestroyAllClientObjects.cs
- Assets/Mirror/Tests/Runtime/NetworkServerRuntimeTest.cs
to prepare for:
- true server & client tests where we spawn an object on server AND on client
- SyncDirection (tests for SyncDirection require above change)
- Host Mode improvements (easier if state is actually separated between server & client)
- NetworkServer/NetworkClient as component (maybe)
for tests, we can now call CreateNetworkedAndSpawn which returns both server & client object:
note that tests are generally more obvious now. for example:
-> all tests pass.
-> uMMORPG still works.
> breaking: NetworkIdentity.spawned split into NetworkServer/Client.Spawned

- Assets/ScriptTemplates/50-Mirror__Network Manager-NewNetworkManager.cs.txt
> fix: The type or namespace name 'Exception' could not be found

- Assets/Mirror/Components/NetworkTransform2k/NetworkTransformBase.cs
- Old default variables are for 'worst case connection' types, or fine for casual social game movement.
- It should be set as minimum delay, whilst still containing some smooth buffer data by default.
- Tool tip suggests what users can change it to for non-ideal connections from the new default value.
- First impressions are vital.
> Default NT2k variables adjusted.

- Assets/Mirror/Editor/Weaver/Processors/TargetRpcProcessor.cs
- Assets/Mirror/Editor/Weaver/WeaverTypes.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverGeneralTests~/TestingScriptableObjectArraySerialization.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverGeneratedReaderWriterTests~/CanUseCustomReadWriteForAbstractClass.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverGeneratedReaderWriterTests~/CanUseCustomReadWriteForInterfaces.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverGeneratedReaderWriterTests~/GivesWarningWhenRegisteringExistingExtensionMethod.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverMonoBehaviourTests.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverMonoBehaviourTests~/MonoBehaviourSyncList.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverSyncDictionaryTests~/SyncDictionaryGenericStructItemWithCustomMethods.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverSyncDictionaryTests~/SyncDictionaryGenericStructKeyWithCustomMethods.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncList.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncListGenericStructWithCustomMethods.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncListInheritance.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverSyncListTests~/SyncListInterfaceWithCustomMethods.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverSyncSetTests~/SyncSet.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverSyncVarTests.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverSyncVarTests~/SyncVarsSyncList.cs
-Weaver uses NetworkConnection.connection instead of NetworkConnection.readyConnection for targetrpcs
-Update weaver tests to use new NetworkReader/Writer API
-Update weaver tests to use SynccList<int> instead of SyncListInt
> Remove obsolete weaver method calls

- Assets/Mirror/Components/Discovery/NetworkDiscoveryBase.cs
If, you cancel discovery the clientUdpClient is set to null.
However, nothing cancels ClientListenAsync. If we change the if(true) to check if the client is null. You can properly cancel the discovery, and kill the listen thread.
Prior to this fix, if you cancel the discovery search. It crashes the thread, and is super noisy in the output. As well as causes issues on the quest.
> Fixes a crash, if you stop discovery.

- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Runtime/SyncDictionary.cs
- Assets/Mirror/Runtime/SyncList.cs
- Assets/Mirror/Runtime/SyncObject.cs
- Assets/Mirror/Runtime/SyncSet.cs
- Assets/Mirror/Tests/Editor/NetworkBehaviourDirtyBitsTests.cs
- Assets/Mirror/Tests/Editor/SyncDictionaryTest.cs
- Assets/Mirror/Tests/Editor/SyncListStructTest.cs
- Assets/Mirror/Tests/Editor/SyncListTest.cs
- Assets/Mirror/Tests/Editor/SyncSetTest.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverSyncVarTests~/SyncVarsSyncList.cs
previously SyncObjects stored their own IsDirty flag.
NetworkBehaviour had to scan through all of them to figure out which are dirty.
this was costly. especially in large worlds where for each entity's NetworkBe
haviour components, it would search through each SyncObject.
(big thanks to imer for non-weaver idea)
**in other words, this code is gone:**
**replaced with this**:
all tests pass.
tested in ummorpg, still only syncs the slots when changed:
> perf: breaking: SyncObjects (SyncList/SyncSet/SyncDict) Dirty Searching (O(N)) replaced with bit mask (O(1))

- Assets/Mirror/Runtime/NetworkManager.cs
Prevents NetworkManager.ServerChangeScene from being called when networkmanager is already processing a scene change for the requested scene.
Just in case someone (definitely not me) accidentally calls ServerChangeScene in Update multiple times and is confused why they're getting "There is already a player for this connection" error messages from clients trying to load the same scene multiple times.
> fix: Prevent NetworkManager.ServerChangeScene from being called while already loading the requested scene

- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Tests/Editor/NetworkServerTest.cs
Unspawning scene objects doesn't destroy them on clients, just hides them.  Similar applies for object pools where the object is returned to a pool instead of destroyed.  If such objects were assigned to a client, that needs to be cleared on client and OnStopAuthority raised.
Server correctly removes authority, but doesn't tell the client under the assumption that the object will be destroyed.
UnSpawnAndClearAuthority test included.
> fix: Clear hasAuthority when Unspawning

- Assets/Mirror/Runtime/SyncDictionary.cs
Seemed like a missing overload.
I debated whether to accept IDictionary or just Dictionary as input, but I think it could make sense in some cases to accept another kind of IDictionary but want to convert it to Dictionary.
> Add a constructor overload for creating a SyncDictionary from an IDictionary

- Assets/Mirror/Runtime/Messages.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
Fixes #2393 
Fixes #2256 
- Separates ownership change from Spawn message
- NetworkIdentityTests updated
> feat: Implemented ChangeOwnerMessage

- Assets/Mirror/Runtime/NetworkManager.cs
DDOL is only valid for scene root objects.  Sometimes users try to "organize" their scene by putting things under empty elements with names like folders.  This forces the Network Manager object to scene root before calling `DontDestroyOnLoad`.
> Force Network Manager to scene root if DDOL

- Assets/Mirror/Editor/Weaver/Processors/SyncObjectInitializer.cs
- Assets/Mirror/Editor/Weaver/Processors/SyncObjectProcessor.cs
- Assets/Mirror/Runtime/SyncDictionary.cs
- Assets/Mirror/Runtime/SyncList.cs
- Assets/Mirror/Runtime/SyncObject.cs
- Assets/Mirror/Runtime/SyncSet.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverSyncVarAttributeTests~/SyncVarsSyncList.cs
- NetworkBehaviour stores all SyncObjects in a list. they should always be a class, otherwise a struct would be copied by value and OnSerialize wouldn't use the original one, but the copy
- [Obsolete] Flush() can be defined in base, instead of doing it in every implementation
- default OnDirty, IsRecording can be defined in base instead of every implementation
- prepares for SyncVar<T> where we need default behaviour for OnDirty which wasn't initialized
it just makes life easier.
> breaking: SyncObject as class instead of interface

- Assets/Mirror/Runtime/NetworkManager.cs
- Moved the setting of `mode = NetworkManagerMode.Offline` up above `NetworkClient.Disconnect`
- Added check for `mode == NetworkManagerMode.Offline` to `OnClientDisconnect` and `StopClient`
Fixes #2940
> fix: Prevent StopClient from running twice

- Assets/Mirror/Runtime/NetworkServer.cs
This PR aims to fix a bug where clients (including host) lose authority of scene objects when the server loads a scene.
Since I don't think this behaviour isn't reproducible with the built-in examples, I copied the AdditiveScenes example and did one major change which was was to load the SubScene on demand for the host as well as the clients instead of at Start. This is how my own game works so that the host doesn't need to have the whole map loaded in at the same time, which however comes at the cost of having to make sure the players are mostly in the same areas at the same time. The example [AdditiveScenesPlayerHost.zip](https://github.com/vis2k/Mirror/files/7475667/AdditiveScenesPlayerHost.zip), can be imported to the examples folder and should run with the latest version, i.e. …
> Pass connection when spawning scene objects so that authority is not lost

- Assets/Mirror/Runtime/NetworkManager.cs
OnValidate runs everytime a value changes, this caused issues as if you want to set the transport to null it will run OnValidate and set it to a value again. Therefor code that only needs to run once when the NetworkManager was added was moved to Reset()
Additionally RecordObject has to be called before changes are made, so it was moved. I also removed the comment that called it "insane" that UnityEditor namespace is not accessible in builds as this is totally normal that this obviously works only in the editor.
> fix: networkmanager undo and move some validation into Reset()

- Assets/Mirror/Components/NetworkTransform2k/NetworkTransformBase.cs
NT should not be calling Cmd's when client isn't ready.
Client is made not ready during scene changes...NT needs to respect that.
```
Send command attempted while NetworkClient is not ready.
0x00007FF65DC8189C (Unity) StackWalker::GetCurrentCallstack
0x00007FF65DC85841 (Unity) StackWalker::ShowCallstack
0x00007FF65C2DC4E5 (Unity) GetStacktrace
0x00007FF65E93FB2E (Unity) DebugStringToFile
0x00007FF65DCE5441 (Unity) DebugLogHandler_CUSTOM_Internal_Log
0x000001C0E1C2E4FB (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
0x000001C0E1C2E3AB (Mono JIT Code) UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
0x000001C0E1C2D9DE (Mono JIT Code) …
```
> fix: NT checks NetworkClient.ready

- Assets/Mirror/Runtime/NetworkIdentity.cs
Calling RemovePlayerForConnection followed by AddPlayerForConnection with the same player object fails to call OnStartLocalPlayer again because previousLocalPlayer was't properly reset to null.
> fix: Set previousLocalPlayer null in NI.Reset

- Assets/Mirror/Components/Experimental/NetworkLerpRigidbody.cs
Changed targetPosition to target.position, it was discussed to provide better results, not personally tested.
Screenshot:
Discord link:
https://discord.com/channels/343440455738064897/467961162558865408/913319303795855360
> fix: NetworkLerpRigidbody target position assignment

- Assets/Mirror/Components/NetworkTransform2k/NetworkTransformBase.cs
- added defines by request, to easier revert or disable new addition.
- added cachedSnapshotComparison by request.
- adjusted default variable and buffer check + thoroughly tested.
Majority of credits to Ninja.
Check comments, tooltips, and messages us if further clarification needed.
> fix: onlySendOnMove for new NetworkTransform

- Assets/Mirror/Runtime/Transport/SimpleWebTransport/Client/StandAlone/ClientHandshake.cs
As per [RFC 2616](https://datatracker.ietf.org/doc/html/rfc2616/#section-4.2) HTTP headers are case-insensitive, this PRs fixes an issue where the WebSockets handshake fails to find the `Sec-WebSocket-Accept` header if the case doesn't match.
Not doing a case-insensitive check can be a problem when the WebSocket server is served through a reverse proxy, I've had this issue with Traefik returning the header as `Sec-Websocket-Accept`.
This issue does not happen on WebGL builds.
> fix: Websocket Transport: ignore headers case when checking handshake key

- Assets/Mirror/Runtime/NetworkReader.cs
- Assets/Mirror/Tests/Editor/NetworkWriterTest.cs
Returning default alone doesn't return give a true null. Explicit types required.
> fix: Explicit types for default nullables

- Assets/Mirror/Runtime/Transport/Transport.cs
backward compatibility and not all transports use channels
> fix: Transport default channel  = Reliable

- Assets/Mirror/Runtime/Mirror.asmdef
- Assets/Mirror/Runtime/NetworkReader.cs
- Assets/Mirror/Runtime/NetworkWriter.cs
- Assets/Mirror/Tests/Editor/NetworkWriterTest.cs
Restored the PR because it supposedly works on Android now.
-------------
Write/ReadBlittable<T> from DOTSNET.
**Benchmark:**
**Reasons to use Blittable**
+ 4-6x faster within Unity versions
+ (2020.1 + Blittable is 10x faster than 2018.4 without Blittable)
+ The code is a lot cleaner.
+ Removes 160 LOC
+ All Unity 2018+ platforms are little endian
+ This has been heavily tested in DOTSNET
+ Non-Blittable types still work fine
+ Invisible change to the user
+ No more UIntFloat etc. conversion structs
+ The more complex the type, the more significant the performance gain compared to serializing each member manually
+ Will allow us to reduce generated weaver code later. All blittable types can simply use WriteBlittable.
It's 4-6x performance for free. Would be silly not to use it.
**Unity …
> perf: NetworkWriter/Reader Write/ReadBlittable<T> for 4-6x performance improvement! (based on #2441)

- Assets/Mirror/Components/InterestManagement/Distance/DistanceInterestManagement.cs
- changes dist. interest management to use TryGetComponent instead of GetComponent and null checking, TryGet doesn't allocate in the editor if nothing is found (component == null), whereas GetComponent will.
https://docs.unity3d.com/ScriptReference/Component.TryGetComponent.html
> fix: Use TryGetComponent in DistantInterestManagement

- Assets/Mirror/Runtime/NetworkReader.cs
- Assets/Mirror/Runtime/NetworkWriter.cs
- Assets/Mirror/Runtime/Utils.cs
Restored the PR because it supposedly works on Android now.
-------------
Write/ReadBlittable<T> from DOTSNET.
**Benchmark:**
**Reasons to use Blittable**
+ 4-6x faster within Unity versions
+ (2020.1 + Blittable is 10x faster than 2018.4 without Blittable)
+ The code is a lot cleaner.
+ Removes 160 LOC
+ All Unity 2018+ platforms are little endian
+ This has been heavily tested in DOTSNET
+ Non-Blittable types still work fine
+ Invisible change to the user
+ No more UIntFloat etc. conversion structs
+ The more complex the type, the more significant the performance gain compared to serializing each member manually
+ Will allow us to reduce generated weaver code later. All blittable types can simply use WriteBlittable.
It's 4-6x performance for free. Would be silly not to use it.
**Unity …
>  perf: NetworkWriter/Reader Write/ReadBlittable<T> for 4-6x performance improvement! (based on #2441, #3036). This time with Android fix.

- Assets/Mirror/Runtime/Transport/MiddlewareTransport.cs
Correctly invoke the methods `ClientEarlyUpdate`, `ServerEarlyUpdate`, `ClientLateUpdate`, `ServerLateUpdate` and `GetBatchThreshold` for the inner transport on `MiddlewareTransport`, in the same way `MultiplexTransport` does.
Fixes #3067
> fix: middleware Transport call inner transport update events

- Assets/Mirror/Editor/Weaver/Processors/SyncVarAttributeProcessor.cs
- Assets/Mirror/Editor/Weaver/WeaverTypes.cs
- Assets/Mirror/Runtime/NetworkBehaviour.cs
moves generated syncvar .set method to C#.
weaver simply calls it.
this was manually weaver generated before:
now it's all in NetworkBehaviour. including the GO/NI/NB special persistence cases.
more C# code, but **less weaver code** :)
> Weaver: move [SyncVar] generated setter to C#

- Assets/Mirror/Editor/Weaver/Processors/CommandProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/MethodProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/RpcProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/TargetRpcProcessor.cs
- Assets/Mirror/Editor/Weaver/Weaver.cs
WIP deadlock test
Deadlock:
Tests/RemoteATtributeTests/ClientRpcOverrideTest/
OverrideVirtualWithBaseCallsBothVirtualAndBase
> fix: Duplicate IL2CPP hashes when building to WebGL (#3061)

- Assets/Mirror/Components/InterestManagement/Distance/DistanceInterestManagement.cs
- Assets/Mirror/Components/InterestManagement/Match/MatchInterestManagement.cs
- Assets/Mirror/Components/InterestManagement/Scene/SceneInterestManagement.cs
- Assets/Mirror/Components/InterestManagement/SpatialHashing/SpatialHashingInterestManagement.cs
- Assets/Mirror/Components/InterestManagement/Team/TeamInterestManagement.cs
- Assets/Mirror/Components/NetworkRoomManager.cs
- Assets/Mirror/Editor/NetworkInformationPreview.cs
- Assets/Mirror/Examples/AdditiveLevels/Scripts/AdditiveLevelsNetworkManager.cs
- Assets/Mirror/Examples/Basic/Scripts/BasicNetManager.cs
- Assets/Mirror/Examples/Chat/Scripts/ChatNetworkManager.cs
- Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/MultiSceneNetManager.cs
- Assets/Mirror/Examples/MultipleMatches/Scripts/CanvasController.cs
- Assets/Mirror/Examples/MultipleMatches/Scripts/MatchNetworkManager.cs
- Assets/Mirror/Examples/Pong/Scripts/NetworkManagerPong.cs
- Assets/Mirror/Runtime/InterestManagement.cs
- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Runtime/NetworkConnectionToClient.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Tests/Common/MirrorTest.cs
- Assets/Mirror/Tests/Editor/NetworkManagerStopHostOnServerDisconnectTest.cs
NetworkConnection contains a lot of server-only code.
that code should be in NetworkConnectionToClient.
=> otherwise it's available on the client in NetworkConnectionToServer as well.
**this PR cleans this all up.**
safer, better code.
and makes future improvements (like host) mode easier if NetworkConnections are implemented cleanly.
**breaks** some user code where NetworkConnection needs to be changed to NetworkConnectionToClient.
in most cases, what they pass to functions already is a NetworkConnectionToClient though.
some callbacks like InterestManagement need parameter changing though.
---
already found a bug in our test code thanks to strong typing:
this used to use FakeNetworkConnection, which is ConnectionToClient, not to Server like NetworkClient.connection is meant to be..
> breaking: NetworkConnection cleanup

- Assets/Mirror/Components/InterestManagement/Match/MatchInterestManagement.cs
- Assets/Mirror/Components/InterestManagement/Team/TeamInterestManagement.cs
Fixes OnCheckObserver to have correct visibility of networked objects where Match / Team ID is not yet assigned
> fix: Match & Team Int Mgmt OnCheckObserver

- Assets/Mirror/Editor/Weaver/Processors/SyncVarAttributeProcessor.cs
- Assets/Mirror/Tests/Editor/SyncVarAttributeHook_HostModeTest.cs
- Assets/Mirror/Tests/Editor/SyncVarAttributeHook_HostModeTest.cs.meta
previously we moved the [SyncVar] setter to C#.
where we use Weaver to convert the hook to Action and pass that to GeneratedSyncVarSetter.
this always forced instance hooks because we pushed 'this.' onto the stack.
now, this support static hooks too.
IMPORTANT: this slipped through our tests. so we'll need a test for this.
before:
after:
also added test coverage so this never happens again:
> fix: host mode [SyncVar] setter hooks now support static functions again

- Assets/Mirror/Components/Discovery/NetworkDiscoveryBase.cs
- Assets/Mirror/Editor/AndroidManifestHelper.cs
- Assets/Mirror/Editor/AndroidManifestHelper.cs.meta
This will add support for turning on and off Multicast for Android devices.
It also contains an Android manifest editor that will add the appropriate permissions.
> fix: Android multicast Discovery. Fixes #2878

- Assets/Mirror/Editor/Weaver/Extensions.cs
- Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/SyncObjectProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/SyncVarAttributeProcessor.cs
- Assets/Mirror/Editor/Weaver/Resolvers.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverNetworkBehaviourTests.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverNetworkBehaviourTests_IsValid/NetworkBehaviourGeneric.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverNetworkBehaviourTests_IsValid/NetworkBehaviourGeneric.cs.meta
- Assets/Mirror/Tests/Editor/Weaver/WeaverNetworkBehaviourTests~/NetworkBehaviourGenericRpc.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverNetworkBehaviourTests~/NetworkBehaviourGenericSyncVar.cs
It's only generic SyncVars (via attribute) and rpcs/cmds we don't want to deal with and that aren't supported.
Even generic `SyncVar<T>` works
I'm currently prototyping some client prediction stuff and this would allow for reducing boilerplate by taking state/input structs via template parameter. For example `class Player : NetworkBehaviourCSP<PlayerState, PlayerInput> { /* ... */}`
> feat: Allow generic NetworkBehaviour subclasses

- Assets/Mirror/Components/Discovery/NetworkDiscoveryBase.cs
- Assets/Mirror/Components/NetworkAnimator.cs
- Assets/Mirror/Editor/Weaver/Processors/CommandProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/RpcProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/TargetRpcProcessor.cs
- Assets/Mirror/Editor/Weaver/WeaverTypes.cs
- Assets/Mirror/Runtime/Batching/Batcher.cs
- Assets/Mirror/Runtime/Batching/Unbatcher.cs
- Assets/Mirror/Runtime/LocalConnectionToClient.cs
- Assets/Mirror/Runtime/LocalConnectionToServer.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkConnection.cs
- Assets/Mirror/Runtime/NetworkReaderPool.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Runtime/NetworkWriterPool.cs
- Assets/Mirror/Runtime/Pool.cs
- Assets/Mirror/Tests/Editor/MessagePackingTest.cs
- Assets/Mirror/Tests/Editor/NetworkBehaviourSerializeTest.cs
- Assets/Mirror/Tests/Editor/NetworkReaderTest.cs
- Assets/Mirror/Tests/Editor/PoolTests.cs
- Assets/Mirror/Tests/Editor/SyncListTest.cs
GetWriter() + Recycle() sounds a bit complicated.
**Take**() and **Return**().
small change, makes API a little bit easier to use.
+ old API still works, shows [Obsolete] messages.
+ consistency with Pool<T> which has Take() and Return()
+ Recycle function's comment explains that it returns a writer. indication for renaming.
> breaking: NetworkReader/WriterPool API simplified: GetReader/Writer => Get; Recycle => Return;

- Assets/Mirror/Tests/Editor/UtilsTests.cs
Since some may use , instead of . as their decimal place seperator
```
PrettyBytes (0,002s)
---
String lengths are both 7. Strings differ at index 1.
Expected: "1.00 KB"
But was:  "1,00 KB"
------------^
---
at Mirror.Tests.UtilsTests.PrettyBytes () [0x0004e] in Mirror\Assets\Mirror\Tests\Editor\UtilsTests.cs:40
```
>  fix: Byte format test uses current culture

- Assets/Mirror/Runtime/NetworkWriterExtensions.cs
- Assets/Mirror/Tests/Editor/NetworkWriterTest.cs
merge, don't squash.
also removes redundant code
NOTE this could be an exception or a warning. both works.
imho it's comparable to a compilation issue, hence the exception
> fix: #2060 serializing GameObjects / NetworkIdentities now throws an obvious exception for prefabs / unspawned objects

- Assets/Mirror/Editor/Weaver/Helpers.cs
- Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/ReaderWriterProcessor.cs
Static constructors are lazily called when the class is first "used"
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/static-constructors
> It is called automatically before the first instance is created or any static members are referenced.
This means, in particular circumstances*, client and server may diverge on which classes they have "loaded"
and thus the rpc index will be desynced
* one such example would be on-demand-loading of prefabs via custom spawn handlers,
where a network behaviour on the prefab is never touched until the prefab is loaded
By just forcing the static constructors to run via the [RuntimeInitializeOnLoadMethod] attribute
this is not a problem anymore, since all static constructors are always run and all rpcs will always be …
> fix: Weaved static constructors need to always run

- Assets/Mirror/Editor/Weaver/Helpers.cs
- Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/ReaderWriterProcessor.cs
- Assets/Mirror/Runtime/Messages.cs
- Assets/Mirror/Runtime/NetworkBehaviour.cs
- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkIdentity.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Runtime/RemoteCalls.cs
- Assets/Mirror/Tests/Common/MirrorTest.cs
> fix: #3138, 3135 revert Cmd/Rpc from 2 byte indices back to 4 byte function hashes for stability

- Assets/Mirror/Runtime/NetworkClient.cs
- Assets/Mirror/Runtime/NetworkManager.cs
- Assets/Mirror/Runtime/NetworkServer.cs
- Assets/Mirror/Runtime/Transport.cs
- Assets/Mirror/Runtime/TransportError.cs
- Assets/Mirror/Runtime/TransportError.cs.meta
- Assets/Mirror/Runtime/Transports/KCP/MirrorTransport/KcpTransport.cs
- Assets/Mirror/Runtime/Transports/MultiplexTransport.cs
- Assets/Mirror/Runtime/Transports/SimpleWebTransport/SimpleWebTransport.cs
- Assets/Mirror/Tests/Editor/MiddlewareTransportTest.cs
=> allows switching on enums
=> simple
=> could send enum over the network (it's a byte)
=> exceptions are for exceptional behaviour. there is nothing exceptional about a network timeout
=> exceptions should be avoided to begin with.
> breaking: OnError(Exception) changed to OnError(enum, reason)

- Assets/Mirror/Runtime/Transports/Telepathy/TelepathyTransport.cs
Kcp calls OnDisconnected for manual disconnections too so this is more consistent
> fix: Telepathy ClientDisconnect calls DC event

- Assets/Mirror/Runtime/NetworkServer.cs
Added a check for repeatedly calling `NetworkServer.Spawn` on the same gameObject.
Allowing user to call `NetworkServer.Spawn` on the same gameObject more than once and does not prints any warning leads to bugs that are hard to detect.
They might call it  `NetworkServer.Spawn` twice but the second time with a owner client connection. The `connectionToClient` field of the `NetworkIdentity` to be spawned will be set by the second call, but `hasAuthority` field will not be updated by the second call, leading to inconsistent behaviours.
Or, when they have a complicated spawner system in their game, wrapped by several layers of class and abstraction, they might have something like this:
```cs
MyNetworkBehaviour item = MySpawner.InstantiateHere(itemPrefab, pos);
item.mySyncVarInt = -1; …
```
> Add Check for NetworkServer.Spawn

- Assets/Mirror/Runtime/NetworkIdentity.cs
This showed up during a recent il2cpp profile and is accounting for 1% of total cpu usage while being completely unnecessary outside of the editor
> perf: Application.isPlaying in hot path is slow

- Assets/Mirror/Core/NetworkIdentity.cs
- Assets/Mirror/Tests/Editor/NetworkIdentitySerializationTests.cs
- Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
previously, byte.max (=255) components were supported.
for each component we would write: **<<index:byte, payload>>**
now, we build only one **64 bit dirty mask**.
which is then **varint** encoded.
=> which means that for the majority of cases, we only need 1 byte in total instead of 1 byte per component :)
> perf: NetworkIdentity.Serialize bandwidth reduced from 1 byte per component index to (roughly) 1 bit per component

- Assets/Mirror/Components/Experimental/NetworkLerpRigidbody.cs
- Assets/Mirror/Components/Experimental/NetworkRigidbody.cs
- Assets/Mirror/Components/Experimental/NetworkRigidbody2D.cs
- Assets/Mirror/Components/NetworkAnimator.cs
- Assets/Mirror/Components/NetworkTransform2k/NetworkTransformBase.cs
- Assets/Mirror/Core/NetworkBehaviour.cs
- Assets/Mirror/Core/NetworkClient.cs
- Assets/Mirror/Core/NetworkIdentity.cs
- Assets/Mirror/Core/NetworkServer.cs
- Assets/Mirror/Editor/NetworkInformationPreview.cs
- Assets/Mirror/Tests/Common/MirrorTest.cs
- Assets/Mirror/Tests/Editor/ClientSceneTests_OnSpawn.cs
- Assets/Mirror/Tests/Editor/NetworkBehaviourTests.cs
- Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
- Assets/Mirror/Tests/Editor/NetworkServerTest.cs
two reasons:
**1. hasAuthority isn't obvious. for example, many components have checks like:**
"clientAuthority && hasAuthority" is just weird logic.
"clientAuthority && owned" is much easier to understand.
**2. prepares for SyncDirection.**
there's going to be a difference between "owned" and "authority":
- owned: if a NetworkIdentity is one of the connection's .owned entities
- authority: if we are allowed to modify this component's state. depends on SyncDirection and owned.
> breaking: .hasAuthority renamed to .isOwned

- Assets/Mirror/Components/NetworkTransform2k/NetworkTransformBase.cs
- Assets/Mirror/Core/NetworkClient.cs
- Assets/Mirror/Core/NetworkConnectionToClient.cs
- Assets/Mirror/Core/NetworkManager.cs
- Assets/Mirror/Core/NetworkServer.cs
- Assets/Mirror/Tests/Editor/NetworkTransform2kTests.cs
server always interpolates client auth movement for smooth visuals in host mode.
this was previously in NetworkTransform.
NT now only interps the transform value. NetworkClient only the time.
this also reduces redundant snapshot time interpolation for connections with multiple owned objects.
prepares for NetworkTransform V3, so we don't need to do time interpolation in there.
> feature: perf: NetworkConnectionToClient snapshot interpolated .remoteTimeline to simplify NetworkTransform

- Assets/Mirror/Components/NetworkTransform2k/NetworkTransform.cs
- Assets/Mirror/Examples/AdditiveLevels/Scripts/PlayerController.cs
- Assets/Mirror/Examples/AdditiveScenes/Scripts/PlayerController.cs
- Assets/Mirror/Examples/Benchmark/Prefabs/Player.prefab
- Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/PlayerController.cs
- Assets/Mirror/Examples/Room/Scripts/PlayerController.cs
- Assets/Mirror/Examples/Tanks/Prefabs/Tank.prefab
- Assets/Mirror/Tests/Editor/NetworkTransform2kTests.cs
merge #3249 first.
baby steps to migrate to V3 easily without breakage.
> [Part 2] breaking: NetworkTransform.clientAuthority flag obsoleted. use SyncDirection instead. automatically sets syncDirection if still used.

- Assets/Mirror/Core/NetworkIdentity.cs
- Assets/Mirror/Core/NetworkServer.cs
- Assets/Mirror/Tests/Editor/NetworkBehaviourTests.cs
- Assets/Mirror/Tests/Editor/NetworkIdentityTests.cs
inspired by Mirror II.
this is much cleaner and much more obvious.
**MERGE, dont squash**
> cleanup NetworkIdentity fields initialization on server

- Assets/Mirror/Core/Messages.cs
- Assets/Mirror/Core/NetworkBehaviour.cs
- Assets/Mirror/Core/NetworkClient.cs
- Assets/Mirror/Core/NetworkConnectionToClient.cs
- Assets/Mirror/Core/NetworkServer.cs
- Assets/Mirror/Tests/Editor/ClientRpcTest.cs
- also prepares for LocalWorldState
- and possibly allows for further optimizations, i.e. <<functionHash, N rpcs...>>
> perf: bundle Rpcs together for each connection. saves 2 bytes of Rpc message headers per Rpc

- Assets/Mirror/Core/NetworkBehaviour.cs
Support for c# versions under 9 (is not to ! is)
Unity 2020 complained about it.
> Support for c# versions under 9 (is not to ! is)

- Assets/Mirror/Core/Tools/Vector3Long.cs
There is no HashCode.Combine in this function, so 2021 define is not needed. Removing the define brings back support for under Unity 2021's
> A define mistake, fixed Under 2021 support.

- Assets/Mirror/Transports/Mirror.Transports.asmdef
- Assets/Mirror/Transports/Mirror.Transports.asmdef.meta
- Keeps transports in their own assembly to users' own AsmDef's can reference them.
See conversation in Discord - Light-Reflective-Mirror channel.
> feat: Add Mirror.Transports AsmDef

- Assets/Mirror/Tests/Editor/MultiplexTransportTest.cs
- Assets/Mirror/Transports/Multiplex/MultiplexTransport.cs
replaces the formula with a lookup table, starting multiplexed connectionIds at "0".
> fix: #3280 #3083 #3217 MultiplexTransport connectionId multiplexing out of int.max range

- Assets/Mirror/Core/NetworkReaderExtensions.cs
- Assets/Mirror/Core/NetworkWriterExtensions.cs
- Assets/Mirror/Tests/Editor/NetworkWriterTest.cs
Added functionality for HashSet's to be automatically serialized in the same way Array's and List's are.
> Added Weaver Compatibility with HashSet<T>

- Assets/Mirror/Core/NetworkManager.cs
TODO
- try in all examples
- try in my assets
- can someone connect between starthost() and finishhost(): need to only process connects after finishhost
> fix: #3302 StartHost: user callbacks OnStartServer/OnStartHost aren't invoked until everything was set up in FinishStartHost.

- Assets/Mirror/Core/NetworkIdentity.cs
> fix: #3308 scene change NetworkClient.owned null entry. NetworkIdentity.OnDestroy now removes from owned.

- Assets/Mirror/Core/NetworkClient.cs
- Assets/Mirror/Core/NetworkIdentity.cs
> fix: #2240 #3324 NetworkIdentity.OnDestroy removes from spawned if not removed yet. prevents null entries in .spawned.

- Assets/Mirror/Core/NetworkManagerHUD.cs
Since #2954 was fixed, Host mode needs a StopClient button.
- Puts server in Server Only mode, continues to function normally.
> feat: NetManHUD StopClient button for Host

- Assets/Mirror/Core/NetworkClient.cs
This eliminates allocations, at least in the editor, per Unity docs.
> NetworkClient - Use TryGetComponent

- Assets/Mirror/Core/NetworkClient.cs
- DestroyAllClientObjects needs to be able to call Unspawn handlers
- Fixes: #3334
> fix: #3334 NetworkClient DestroyAllClientObjects Before ClearSpawners

- Assets/Mirror/Core/NetworkIdentity.cs
Fixes: #3326 
- All callers to Reset are either unspawning (disabling) the object or have run a custom UnSpawnHandler
- Sync collections should retain their data in any case because the object may get respawned
- When it is respawned, OnDeserializeAll clears the internal collection and changes lists before adding back the entire payload.
- Users can always call the public Reset on the SyncObject themselves if they want it wiped.
> fix: #3326 NetworkIdentity doesn't reset SyncObjects anymore

- Assets/Mirror/Core/NetworkClient.cs
- Assets/Mirror/Core/NetworkClient_TimeInterpolation.cs
- Assets/Mirror/Core/NetworkServer.cs
> fix: #3351 - Reset Statics in NS, NC, and NC_TimeInterpolation

- Assets/Mirror/Examples/Tanks/Scripts/Tank.cs
To prevent multiple editors/builds on same PC effecting all players tanks. A few have been needing this, so nice to slip it into Mirror code somewhere for people to learn/reference from. Kudos to Zankaster and the others in Discord.
> Application.isFocused check on tanks Update input.

- Assets/Mirror/Editor/Weaver/Processors/SyncObjectProcessor.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverNetworkBehaviourTests_IsValid/NetworkBehaviourGeneric.cs
T[] would cause a NRE:
(0,0): error ----------------------------------------------
(0,0): error Exception :System.NullReferenceException: Object reference not set to an instance of an object.
(0,0): error    at Mirror.Weaver.Extensions.IsDerivedFrom(TypeReference tr, Type baseClass) in Mirror\Editor\Weaver\Extensions.cs:line 21
(0,0): error    at Mirror.Weaver.Extensions.IsDerivedFrom[T](TypeReference tr) in Mirror\Editor\Weaver\Extensions.cs:line 17
(0,0): error    at Mirror.Weaver.SyncObjectProcessor.FindSyncObjectsFields(Writers writers, Readers readers, Logger Log, TypeDefinition td, Boolean& WeavingFailed) in Mirror\Editor\Weaver\Processors\SyncObjectProcessor.cs:line 25
(0,0): error    at Mirror.Weaver.NetworkBehaviourProcessor.Process(Boolean& WeavingFailed) in …
> fix: Weaver doesn't NRE on generic array

- Assets/Mirror/Core/NetworkReaderExtensions.cs
- Assets/Mirror/Core/NetworkWriterExtensions.cs
- no UTC conversion...users can do that on their own if they want / need to.
- Nullable support included
- WriteDouble and ReadDouble already have unit tests.
DateTime is a public struct but has no public fields (all properties) so no error is thrown if users try to use it in SyncVar / Cmd / Rpc / NetMsg, but no value is put on the wire and SyncVar hooks don't fire because the client determines no actual value change.
> feat: Read / Write DateTime

- Assets/Mirror/Core/NetworkReaderExtensions.cs
- Assets/Mirror/Core/NetworkWriter.cs
- Assets/Mirror/Core/NetworkWriterExtensions.cs
- local `realsize` in NetworkReaderExtensions.ReadString changed to ushort with proper casting
- Comments added to NetworkWriterExtensions
- Comments added to NetworkReaderExtensions
- Log output updated in both for consistency
> fix: NetworkWriter - Change MaxStringLength to ushort.MaxValue

- Assets/Mirror/Core/Tools/Extensions.cs
- Static dictionary of message hashes
- ResetStatics
BEFORE
AFTER
Debug output of the dictionary:
```
17570: System.Void Mirror.NetworkTransform::CmdClientToServerSync(System.Nullable`1<UnityEngine.Vector3>,System.Nullable`1<UnityEngine.Quaternion>,System.Nullable`1<UnityEngine.Vector3>)
11031: System.Void Mirror.NetworkTransform::RpcServerToClientSync(System.Nullable`1<UnityEngine.Vector3>,System.Nullable`1<UnityEngine.Quaternion>,System.Nullable`1<UnityEngine.Vector3>)
39853: System.Void Mirror.NetworkTransformBase::CmdTeleport(UnityEngine.Vector3)
30084: System.Void Mirror.NetworkTransformBase::CmdTeleport(UnityEngine.Vector3,UnityEngine.Quaternion)
1762: System.Void Mirror.NetworkTransformBase::RpcTeleport(UnityEngine.Vector3)
16047: System.Void …
```
> perf: Cache Stable Hashes

- Assets/Mirror/Core/NetworkClient.cs
- Assets/Mirror/Core/NetworkMessages.cs
- Assets/Mirror/Core/NetworkServer.cs
- Assets/Mirror/Tests/Editor/NetworkMessagesTest.cs
**MrG Note:** This obsoletes NetworkMessages.GetId, which forwards callers to the new NetworkMessageId static class and generic, so not a breaking change at this point.  Breaking change will come in 3 mos when the obsolete is removed.
Note we already use this technique for NetworkWriter (&reader), so should work across all platforms:
https://github.com/MirrorNetworking/Mirror/blob/59dc88c981b1612cbf62a2a4f739d6475e1bb338/Assets/Mirror/Core/NetworkWriter.cs#L245-L251
we can (ab)use c# generics to cache the message id in a static field
this is significantly faster than doing a runtime Dictionary lookup in my testing (16% thread cpu-> ~0.22% for 121 moving nts) 
vs
> perf: Use static generic class to cache message id

- Assets/Mirror/Components/NetworkTransformBase.cs
- Assets/Mirror/Components/NetworkTransformReliable/NetworkTransformReliable.cs
- Assets/Mirror/Components/NetworkTransformUnreliable/NetworkTransform.cs
- Assets/Mirror/Tests/Editor/NetworkTransform2kTests.cs
Gives a snap-like effect to position, rotation and scaling.
Video
First half is interpolations off
Second half is interpolations on
(Note: SendRate was set from 30* to 5, for video, as it was too smooth at 30 to see interpolation off)
I dont know what to set in the NetworkTransform2kTests - base.Apply(interpolated, THIS->interpolated);
https://user-images.githubusercontent.com/57072365/218549286-83c03a3e-bc8a-4b86-9a75-d0c2516d8269.mp4
> feature: NetworkTransform interpolation can be disabled

- Assets/Mirror/Core/InterestManagement.cs
- Assets/Mirror/Core/NetworkServer.cs
- Assets/Mirror/Tests/Editor/NetworkServerTest.cs
This cleanup step prepares for InterestManagement classes being able to customize the rebuild logic, but for that we should move it out of the NetworkServer class
> Code cleanup: move observer HashSet rebuild logic to InterestManagement

- Assets/Mirror/Core/InterestManagement.cs
- Assets/Mirror/Core/InterestManagementBase.cs
- Assets/Mirror/Core/InterestManagementBase.cs.meta
- Assets/Mirror/Core/NetworkClient.cs
- Assets/Mirror/Core/NetworkServer.cs
A low level interest management base class that allows more advanced interest management by bypassing the built-in HashSet checks
Full compatibility with existing interest management classes is preserved, this is technically a breaking change since NetworkServer.aoi/NetworkClient.aoi is a different type (but with same api), but that is the only breaking change I can think of
See previous PR #2764
See also https://github.com/vis2k/Mirror/pull/2581#issuecomment-780471482
> feat: InterestManagementBase

- Assets/Mirror/Core/NetworkBehaviour.cs
- Assets/Mirror/Editor/Weaver/Processors/CommandProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/RpcProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/TargetRpcProcessor.cs
Instead of computing it at runtime for every call
See #3381, #3377 and #3375
> perf: Weave in pre-computed function hash for RPCs

- Assets/Mirror/Core/NetworkClient.cs
Exactly the opposite of what's in the comment happens (and is explained below) 😁
> Remove outdated comment

- Assets/Mirror/Editor/Weaver/Extensions.cs
- Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/SyncVarAttributeProcessor.cs
- Assets/Mirror/Editor/Weaver/Readers.cs
- Assets/Mirror/Editor/Weaver/Writers.cs
Not only types derived from NetworkBehaviour, but also NetworkBehaviour itself
Fixes #2939 
Demo: 
(low IM range, tank top-left with net id 1 is server, video is client with netid 2, "name text" fields are syncvars)
https://user-images.githubusercontent.com/1426904/219615313-05c51c5c-215c-4401-861d-2c8596314410.mp4
> fix: NetworkBehaviour SyncVar uses netId lookup

- Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
We always use a specific reader for NB syncvars, so if a custom defined writer handles data differently this leads to data mismatches.
Supporting custom readers for NB syncvars will just lead to too many edge cases and unexpected behaviour, so dont do it (see https://github.com/MirrorNetworking/Mirror/issues/2680#issuecomment-1435093212 for rationale).
Fixes #2680
> fix: #2680 Weaver: never use custom NB writers for SyncVars

- Assets/Mirror/Editor/Weaver/WeaverTypes.cs
- Put all NetworkBehaviors together
- Put Writer with Reader
- Put Remote things together
- moved ScriptableObjectType down
- moved NetworkClientConnectionReference up
> Organize WeaverTypes

- Assets/Mirror/Transports/KCP/KcpTransport.cs
- Assets/Mirror/Transports/KCP/kcp2k/VERSION.txt
- Assets/Mirror/Transports/KCP/kcp2k/highlevel/Common.cs
- Assets/Mirror/Transports/KCP/kcp2k/highlevel/Extensions.cs
- Assets/Mirror/Transports/KCP/kcp2k/highlevel/KcpClient.cs
- Assets/Mirror/Transports/KCP/kcp2k/highlevel/KcpConfig.cs
- Assets/Mirror/Transports/KCP/kcp2k/highlevel/KcpServer.cs
- fix: set send/recv buffer sizes directly instead of iterating to find the limit. fixes: https://github.com/MirrorNetworking/Mirror/issues/3390
- fix: server & client sockets are now always non-blocking to ensure main thread never blocks on socket.recv/send. Send() now also handles WouldBlock.
- fix: socket.Receive/From directly with non-blocking sockets and handle WouldBlock, instead of socket.Poll. faster, more obvious, and fixes Poll() looping forever while socket is in error state. fixes: https://github.com/MirrorNetworking/Mirror/issues/2733
socker buffer sizes are now exposed in the inspector:
> fix: kcp2p V1.30. fixes #3390 #2733

- Assets/Mirror/Core/NetworkTime.cs
Shortened PingWindowSize to get a faster more accurate result. It taking too long to calculate the average may look bad to users, choosing 6 gives us an average of 3 results, where as the previous 10, would wait for 5, it should be a slight visual improvement.
> Shortened PingWindowSize to get a faster more accurate result.

- Assets/Mirror/Core/NetworkWriterExtensions.cs
- Assets/Mirror/Tests/Editor/NetworkWriterTest.cs
Instead of writing 0 and component index which does not match what the reader expects (it will stop reading netId is 0)
Also includes a failing test in the first commit.
Fixes #3399
> fix: Write for non-spawned NB only writes 0 netId (fixes: #3399)

- Assets/Mirror/Core/NetworkIdentity.cs
- Assets/Mirror/Editor/NetworkScenePostProcess.cs
- Assets/Mirror/Editor/Weaver/EntryPoint/CompilationFinishedHook.cs
- Assets/Mirror/Tests/Editor/NetworkLoopTests.cs
We only support Unity 2019.4.40 and later LTS releases.
BREAKING: Removed old 2018 / 2019 compiler defines
> breaking: Removed old Unity 2018 / 2019_3 compiler defines

- Assets/Mirror/Core/NetworkReaderExtensions.cs
- Assets/Mirror/Core/NetworkWriterExtensions.cs
Added explicit writer and reader for struct types that don't have public fields, only properties, because WriteBlittable shouldn't work with those.
Oddly, existing tests pass, but users report nulls / empty / default on the receiving side.
> fix: Reader / Writer extensions for Unity structs with properties

- Assets/Mirror/Core/InterestManagementBase.cs
Fix: InterestManagement still partially working when using Awake, OnEnable fixes it.
To test, open CCU Example, build Server with SHIM component disabled on NetworkManager.
Join as client/editor.
You will see client only has objects around itself within SHIM visibility range, despite it being disabled.
Currently if you move player around in this situation, it only ever has that initial network spawn that surrounded it, it never see's new spawns. (it should show all of them from the very beginning)
- We need to stop SHIM from working if its disabled in inspector.
Discussion is in Discord, maybe OnDestroyed needs to become OnDisabled too, but this effects many scripts that use the OnDestroyed Override.
And to note, theres a comment description above the change talking about Awake, that will …
> Fix(InterestManagementBase): Disable feature fully, if component unticked.

- Assets/Mirror/Components/NetworkTransformBase.cs
- Assets/Mirror/Core/NetworkClient_TimeInterpolation.cs
- Assets/Mirror/Core/NetworkServer.cs
- Assets/Mirror/Core/NetworkTime.cs
- Assets/Mirror/Examples/Snapshot Interpolation/ClientCube.cs
- Assets/Mirror/Examples/Snapshot Interpolation/ServerCube.cs
- Use NetworkTime.localTime everywhere for Unity 2019 LTS compatibility.
> fix: Remove all usage of Time.timeAsDouble

- Assets/Mirror/Core/NetworkServer.cs
This may or may not be malicious.  It could well be a message in flight when RemoveClientAuthority is called on server, especially for things like NT that send at higher frequency.
> fix(NetworkServer): Don't disconnect on EntityStateMessage for object without authority

- Assets/Mirror/Core/PortTransport.cs
- Assets/Mirror/Core/PortTransport.cs.meta
- Assets/Mirror/Transports/KCP/KcpTransport.cs
- Assets/Mirror/Transports/SimpleWeb/SimpleWebTransport.cs
- Assets/Mirror/Transports/Telepathy/TelepathyTransport.cs
merge, not squash.
as requested by lots of users over the years.
some just want to set the transport's port, independent of which transport is active.
alternatively, Kcp : PortTransport : Transport 
if it's a class then Port can be a field and serialized by Unity
> feature: PortTransport interface for convenience

- Assets/Mirror/Core/NetworkBehaviour.cs
- Assets/Mirror/Tests/Editor/NetworkBehaviourTests.cs
- Assets/Mirror/Tests/Editor/SyncVarAttributeTest.cs
Closed one and made a new PR because I made a mistake on branch names.
"Cached SyncVar" as in SyncVars of type `NetworkIdentity`, `NetworkBehaviour` and `GameObject`, which hold netId to prevent the field being forever null.
This fixes #3447 with respective tests for each modified `GetSyncVar~` methods.
PR also modifies some tests that relies on undefined behaviors, which are `GetSyncVarGameObjectOnClient()` and `TestSyncingAbstractNetworkBehaviour()`.
This change also implies that when you access cached SyncVars of non-spawned objects in clients, they will no longer try to pull from `NetworkClient.spawned`. But that doesn't make sense to do in the first place, so I'm pretty sure it's fine.
> fix: #3447 make cached SyncVar fallback to original field value when there is no network context

- Assets/Mirror/Core/NetworkManager.cs
- If none assigned, tries to use first Transport available and warns user
- If none available, throws clear error to user what to do.
> fix(NetworkManager): Try to avoid missing transport errors

- Assets/Mirror/Editor/Weaver/Processors/SyncVarAttributeProcessor.cs
- Assets/Mirror/Tests/Editor/SyncVarAttributeHook_HostModeTest.cs
- Assets/Mirror/Tests/Editor/SyncVarAttributeTest.cs
This fixes #3457.
In `SyncVarAttributeProcessor.ProcessSyncVars()`, each SyncVar's dirty bit is determined.
To take derived NBs into account, `dirtyBitCounter` starts from base class SyncVar count.
```cs
int dirtyBitCounter = syncVarAccessLists.GetSyncVarStart(td.BaseType.FullName);
```
Which is recorded at the end of `ProcessSyncVars()`.
```cs
List<FieldDefinition> syncVars = new List<FieldDefinition>();
// ...
syncVars.Add(fd);
ProcessSyncVar(td, fd, syncVarNetIds, 1L << dirtyBitCounter, ref WeavingFailed);
dirtyBitCounter += 1;
// ...
syncVarAccessLists.SetNumSyncVars(td.FullName, syncVars.Count);
```
However `syncVars` only has SyncVars from current class, not those from the base class, hence this starts causing problems next round of inheritance.
```cs
public class Entity : …
```
> fix: #3457 Make NumSyncVars take parent class syncvars into account

- Assets/Mirror/Transports/SimpleWeb/SimpleWebTransport.cs
When running websocket server behind reverse proxy client should connect via port 80 or 443. the reverse proxy should then forward requests to the ServerPort  running on localhost.
> feat(SimpleWebTransport): adding option to set server and client port different

- Assets/Mirror/Components/Discovery/NetworkDiscovery.cs
- Assets/Mirror/Components/Discovery/NetworkDiscoveryBase.cs
I'm was currently trying to create a custom NetworkDiscovery like explained in the documentation and i encountered a problem with the `ServerFoundUnityEvent` object: i didn't allow to use a custom struct like suggested in the [examples](https://mirror-networking.gitbook.io/docs/manual/components/network-discovery#custom-network-discovery).
So here is my little fix: `ServerFoundUnityEvent` can now receive a generic type from the class to allow custom responses.
> breaking: NetworkDiscovery ServerFoundUnityEvent now supports custom ServerResponse types

- Assets/Mirror/Components/NetworkTransformUnreliable/NetworkTransform.cs
Changed sendIntervalCounter logic to fix the issue where if sendIntervalMultiplier = 1, NT will send every frame instead of every send interval. This is due to sendIntervalCounter being initialised to 1 instead of 0, after NT has triggered it's send.
> fix #3478 - Changed sendIntervalCounter increment logic

- Assets/Mirror/Components/Experimental/NetworkLerpRigidbody.cs
- Assets/Mirror/Components/Experimental/NetworkRigidbody.cs
- Assets/Mirror/Components/Experimental/NetworkRigidbody2D.cs
- Assets/Mirror/Components/NetworkAnimator.cs
- Assets/Mirror/Components/NetworkTransformBase.cs
- Assets/Mirror/Components/RemoteStatistics.cs
- Assets/Mirror/Core/NetworkBehaviour.cs
- Assets/Mirror/Core/NetworkIdentity.cs
- Assets/Mirror/Examples/AdditiveLevels/Scripts/PlayerController.cs
- Assets/Mirror/Examples/AdditiveScenes/Scripts/PlayerController.cs
- Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/PhysicsCollision.cs
- Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/PlayerController.cs
- Assets/Mirror/Examples/MultipleAdditiveScenes/Scripts/Reward.cs
- Assets/Mirror/Examples/RigidbodyPhysics/Scripts/AddForce.cs
- Assets/Mirror/Examples/Room/Scripts/PlayerController.cs
- Assets/Mirror/Examples/Room/Scripts/Reward.cs
- Assets/Mirror/Examples/Tanks/Prefabs/Tank.prefab
- Assets/Mirror/Examples/Tanks/Readme.txt
- Assets/Mirror/Examples/Tanks/Readme.txt.meta
- Assets/Mirror/Tests/Common/MirrorTest.cs
- Assets/Mirror/Tests/Editor/NetworkBehaviour/NetworkBehaviourChildSerializeTest.cs
- Assets/Mirror/Tests/Editor/NetworkBehaviour/NetworkBehaviourChildSerializeTest.cs.meta
- Assets/Mirror/Tests/Editor/NetworkBehaviour/NetworkBehaviourSerializeTest.cs
- Assets/ScriptTemplates/52-Mirror__Network Behaviour-NewNetworkBehaviour.cs.txt
TODO
this has been requested a lot: https://github.com/MirrorNetworking/Mirror/issues/2276
> feature: allow NetworkBehaviour components in children. solves #2276

- Assets/Mirror/Core/NetworkClient.cs
- Assets/Mirror/Core/NetworkIdentity.cs
> fix: Disallow Child-NetworkIdentities in Scene objects

- Assets/Mirror/Components/NetworkTransformUnreliable/NetworkTransform.cs
5 (the previous default) covers really bad pings in return for noticeable delay.
However, not every game should have this as their default.
With something as low as 1 being almost instant movement for minimal smoothing (could be best for VR and other uses), from testing 3 is a nice balanced result between the two variations.
Tested with different network manager send rates, tanks example (body and turret NT's), bufferResetMultiplier 1,3 and 5, with a few latency simulator variations too.
> Changed default NT BRM to 3

- Assets/Mirror/Tests/Common/NetworkClientTestsBase.cs
OneTimeSetUp: Unhandled log message: '[Error] 'PrefabWithChildrenForClientScene' has another NetworkIdentity component on 'Child Network Identity'. There should only be one NetworkIdentity, and it must be on the root object. Please remove the other one.'. Use UnityEngine.TestTools.LogAssert.Expect
> fix: failing NetworkClientTests

- .github/workflows/RunUnityTests.yml
Seems like testing is broken in 2022.2, so temporarily disable until we fix them properly
> fix: Temporarily disable 2022 CI

- Assets/Mirror/Transports/SimpleWeb/SimpleWeb/AssemblyInfo.cs
- Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Common/Connection.cs
- Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Common/Request.cs
- Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Common/Request.cs.meta
- Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Server/ServerHandshake.cs
- Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Server/SimpleWebServer.cs
- Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Server/WebSocketServer.cs
- Assets/Mirror/Transports/SimpleWeb/SimpleWebTransport.cs
When running behind a reverse proxy the IP endpoints will be that of the reverse proxy, not the client. Reverse proxies like Nginx set the ip if the host in a http header, the server can read this header during the handshake and store it so it knows the IP address of the client
> feat: adding option to get Ip behind reverse proxy

- Assets/Mirror/Core/NetworkClient.cs
- Assets/Mirror/Core/NetworkServer.cs
- Assets/Mirror/Core/WeaverFuse.cs
- Assets/Mirror/Core/WeaverFuse.cs.meta
- Assets/Mirror/Editor/Weaver/Weaver.cs
- Assets/Mirror/Editor/Weaver/WeaverTypes.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverFuseTests.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverFuseTests.cs.meta
allows for much more pleasant debugging.
weaver failures can be detected easily at runtime, with a clean stop.
instead of throwing thousands of 'no writer found ...' error later on
ILPostProcessor weaver errors automatically block entering playmode:
However, this can ensure that ILPostProcessor actually ran.
It's also useful for CompilationFinishedHook, where weaver errors would not block entering play mode.
Tested in uMMORPG:
> fix: Weaver runtime fuse to ensure weaving succeeded before starting Server/Client

- Assets/Mirror/Core/NetworkClient.cs
- Assets/Mirror/Tests/Editor/NetworkClient/NetworkClientTests.cs
Fixes a bug where host mode scene transitions would still receive a previous scene's data.
credit: BigBoxVR
TODO
> fix: NetworkClient unbatcher is now reset in host mode connect as well [credit: BigBoxVR]

- Assets/Mirror/Core/NetworkBehaviour.cs
- Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
Previously Weaver would add:
```cs
private void MirrorProcessed() {}
```
This PR changes adds a base function to NetworkBehaviour:
```cs
public virtual void Weaved() { return false; }
```
And Weaver now tags processed component with:
```cs
public override void Weaved() { return true; }
```
Which means that we can now check at runtime:
```cs
if (!Monster.Weaved()) throw;
Assert.That(Monster.Weaved(), Is.True);
etc.
```
> feature: Weaver adds 'bool Weaved()' to each NetworkBehaviour, which can be checked at runtime

- Assets/Mirror/Components/NetworkPingDisplay.cs
- Assets/Mirror/Core/ConnectionQuality.cs
- Assets/Mirror/Core/ConnectionQuality.cs.meta
- Assets/Mirror/Core/NetworkClient.cs
- Assets/Mirror/Core/NetworkManager.cs
- Assets/Mirror/Examples/Tanks/Scenes/Scene.unity
ConnectionQuality enum:
```cs
public enum ConnectionQuality : byte
{
EXCELLENT,
GOOD,
FAIR,
POOR,
ESTIMATING,
}
```
Several Heuristics:
```cs
public static ConnectionQuality Simple(double rtt, double jitter)
{
// estimations use round trip time, which is roughly 2x ping.
if (rtt <= 0.100 && jitter <= 0.10) return ConnectionQuality.EXCELLENT;
if (rtt <= 0.200 && jitter <= 0.20) return ConnectionQuality.GOOD;
if (rtt <= 0.400 && jitter <= 0.50) return ConnectionQuality.FAIR;
return ConnectionQuality.POOR;
}
// snapshot interpolation based estimation.
public static ConnectionQuality Pragmatic(double targetBufferTime, double currentBufferTime)
{
double multiplier = currentBufferTime / targetBufferTime;
if (multiplier <= 1.2) return ConnectionQuality.EXCELLENT;
if (multiplier <= 1.75) return …
```
> feature: ConnectionQuality Heuristic + Callback + GUI

- Assets/Mirror/Core/NetworkClient.cs
fixes: https://github.com/MirrorNetworking/Mirror/issues/3541
Should be safe to remove this extra check complete, it is safe to add spawned object to `spawnableObjects`. For now this just changes it to NetId to ensure that the object really is unspawned and not just enabled
> fix: PrepareToSpawnSceneObjects checks netId instead of activeSelf [fixes: #3541]

- Assets/Mirror/Editor/Weaver/EntryPoint/CompilationFinishedHook.cs
We excluded editor assemblies from weaving which is now an issue since tests use an assembly matching the "is editor assembly" check
This only affects 2019 since newer unity versions use the ILPostProcessor which does not have such a check
> fix: 2019 tests work again

- Assets/Mirror/Examples/TanksCoop.meta
- Assets/Mirror/Examples/TanksCoop/Materials.meta
- Assets/Mirror/Examples/TanksCoop/Materials/MaterialPlayer.mat
- Assets/Mirror/Examples/TanksCoop/Materials/MaterialPlayer.mat.meta
- Assets/Mirror/Examples/TanksCoop/Materials/MaterialTrigger.mat
- Assets/Mirror/Examples/TanksCoop/Materials/MaterialTrigger.mat.meta
- Assets/Mirror/Examples/TanksCoop/Prefabs.meta
- Assets/Mirror/Examples/TanksCoop/Prefabs/Player.prefab
- Assets/Mirror/Examples/TanksCoop/Prefabs/Player.prefab.meta
- Assets/Mirror/Examples/TanksCoop/Prefabs/Projectile.prefab
- Assets/Mirror/Examples/TanksCoop/Prefabs/Projectile.prefab.meta
- Assets/Mirror/Examples/TanksCoop/Prefabs/TankShared.prefab
- Assets/Mirror/Examples/TanksCoop/Prefabs/TankShared.prefab.meta
- Assets/Mirror/Examples/TanksCoop/SceneTanksCoop.unity
- Assets/Mirror/Examples/TanksCoop/SceneTanksCoop.unity.meta
- Assets/Mirror/Examples/TanksCoop/Scripts.meta
- Assets/Mirror/Examples/TanksCoop/Scripts/AuthorityNetworkManager.cs
- Assets/Mirror/Examples/TanksCoop/Scripts/AuthorityNetworkManager.cs.meta
- Assets/Mirror/Examples/TanksCoop/Scripts/PlayerCamera.cs
- Assets/Mirror/Examples/TanksCoop/Scripts/PlayerCamera.cs.meta
- Assets/Mirror/Examples/TanksCoop/Scripts/PlayerController.cs
- Assets/Mirror/Examples/TanksCoop/Scripts/PlayerController.cs.meta
- Assets/Mirror/Examples/TanksCoop/Scripts/Projectile.cs
- Assets/Mirror/Examples/TanksCoop/Scripts/Projectile.cs.meta
- Assets/Mirror/Examples/TanksCoop/Scripts/RandomColor.cs
- Assets/Mirror/Examples/TanksCoop/Scripts/RandomColor.cs.meta
- Assets/Mirror/Examples/TanksCoop/Scripts/TankController.cs
- Assets/Mirror/Examples/TanksCoop/Scripts/TankController.cs.meta
Spawn as a capsule player, enter tanks 'trigger zone' and press E to enter, Q to exit.
Assigns authority of vehicle to that player to control (disables their current player input).
Supports multiple vehicles (duplicate or drag in another Tank prefab).
**Early video preview.**
https://github.com/MirrorNetworking/Mirror/assets/57072365/38a7af54-624a-4480-afed-acb00c159d81
- AuthorityNetworkManager, unassigns authority from controlled vehicles if a player disconnects whilst in one.
- TankController, similar to previous Tank script, contains a sync var for current owner.
- PlayerController, similar to other PlayerController script, contains 5 new functions, Button-Input TriggerEnter/Exit, CommandAssign/Remove authority.
- Unchanged from other examples (uses TanksCoop namespace) PlayerCamera, …
> Tanks co-op example, take control of vehicles via Mirrors Authority assigning feature.

- Assets/Mirror/Components/NetworkTransform/NetworkTransformBase.cs
- Assets/Mirror/Components/NetworkTransform/NetworkTransformReliable.cs
- Assets/Mirror/Components/NetworkTransform/NetworkTransformUnreliable.cs
Currently NT is local, and in some cases world is needed.
If people decided to change hierarchy, change child/parent, things can get out of sync, world fixes that.
- All tested, using tanks example, and dragging a player tank into empty gameobject, then this gameobjects position/rotation/scale and hierarchy changing live during gameplay. Switching to world bool fixes any problems caused by that.
Before
After
> feature: NetworkTransform WorldScale option

- Assets/Mirror/Core/NetworkClient.cs
- Assets/Mirror/Core/NetworkIdentity.cs
- Assets/Mirror/Tests/Editor/NetworkIdentity/NetworkIdentityTests.cs
- Assets/Mirror/Tests/Editor/SyncVars/SyncVarAttributeTest.cs
Testing the new BenchmarkIdle example with 100k objects, IL2CPP build
```
Before:  4.7 - 10.4 ms broadcast()
After:   4.5 -  9.7 ms broadcast()
```
> perf: remove O(N) ClearDirtyComponentsDirtyBits calls in NetworkServer.Broadcast() and NetworkClient.Broadcast()

- Assets/Mirror/Presets/NetworkTransform/ClientAuth-Balanced.preset
- Assets/Mirror/Presets/NetworkTransform/ClientAuth-FastPaced.preset
- Assets/Mirror/Presets/NetworkTransform/ClientAuth-VeryCasual.preset
As title suggests, the rename of NetworkTransform to NetworkTransformUnreliable means the pre-set examples for users needed updating.
> NT rename broke presets, fix.

- Assets/Mirror/Core/Messages.cs
- Assets/Mirror/Core/NetworkClient.cs
- Assets/Mirror/Core/NetworkConnectionToClient.cs
- Assets/Mirror/Core/NetworkTime.cs
> feature: NetworkTime.predictedTime to prepare for Prediction

- Assets/Mirror/Core/NetworkMessages.cs
- Assets/Mirror/Core/Tools/Extensions.cs
- Assets/Mirror/Tests/Editor/NetworkMessages/NetworkMessagesTest.cs
- Assets/Mirror/Tests/Editor/Tools/ExtensionsTest.cs
We got a hash collision for 2 network messages in our game even though we only have 68 network messages.
The old stable hash code function for strings did not create a good hash so I replaced it with the fnv1a algorithm to reduce hash collisions.
Mirror then casted the 32bit hash to a 16bit hash which made us lose 50% of the hash, so now I fold the 32 bit hash inside itself, 
which means we take the highest 16bit of the hash and xor them with the lowest 16bit of the hash to create a 16bit hash which is still uniform and avoids hash collisions.
We tested this change in Nimoyd besides also running the mirror tests.
> fix: improve NetworkMessage ID Hashing to minimize collisions

- Assets/Mirror/Core/NetworkManager.cs
Updating tooltip to include mentioning Unitys latest Dedicated Server platform option, should help some with some confusion that was seen in # help.    
old  
new
> Updated server build tooltip on NM

- Assets/Mirror/Core/NetworkLoop.cs
- Assets/Mirror/Core/NetworkTime.cs
Since we don't have double time there yet and the stopwatch will change during the frame which (can?) cause jitter and other artifacts 
supersedes #3623
See also #2838
> fix: NetworkTime creates it's own frame time in 2019

- Assets/Mirror/Transports/Edgegap/EdgegapRelay/EdgegapKcpClient.cs
- Assets/Mirror/Transports/Edgegap/EdgegapRelay/EdgegapKcpTransport.cs
- Assets/Mirror/Transports/KCP/KcpTransport.cs
- Assets/Mirror/Transports/KCP/kcp2k/VERSION.txt
- Assets/Mirror/Transports/KCP/kcp2k/highlevel/KcpClient.cs
- Assets/Mirror/Transports/KCP/kcp2k/highlevel/KcpHeader.cs
- Assets/Mirror/Transports/KCP/kcp2k/highlevel/KcpPeer.cs
- Assets/Mirror/Transports/KCP/kcp2k/highlevel/KcpServer.cs
- Assets/Mirror/Transports/KCP/kcp2k/highlevel/KcpServerConnection.cs
- Assets/Mirror/Transports/KCP/kcp2k/highlevel/KcpState.cs
- Assets/Mirror/Transports/KCP/kcp2k/highlevel/KcpState.cs.meta
- fix: mismatching cookie race condition. cookie is now included in all messages. https://github.com/MirrorNetworking/kcp2k/issues/54
- feature: Exposed local end point on KcpClient/Server
- refactor: KcpPeer refactored as abstract class to remove KcpServer initialization workarounds
> fix: KCP V1.38 [2023-10-29] cookie fix & refactor

- Assets/Mirror/Core/NetworkServer.cs
Allows users to know if Server has actually started and which port, and not just initialised.
Credits to Gadget for code and suggesting to have it in NetworkServer.
(Originally was going in KCP-only)
> fix: Port log for when Server has started and is listening.

- README.md
Note, somewhere after Unity Station image, the links no longer direct to store hrefs.
> ReadMe updated, Added Shattered Lands.

- Assets/Mirror/Hosting/Edgegap/Editor/EdgegapWindow.cs
The _appName/_appVersionName are only updated to the instance when the window is disabled/once logged in
> fix: EdgegapHosting connect uses passed-in name/version

- Assets/Mirror/Core/Prediction/Prediction.cs
- Unity 2019 doesn't support `public` accessors inside interfaces.
- Compiles fine in all Unity versions without them.
> fix(PredictedState): Remove public accessors

- Assets/Mirror/Core/LocalConnectionToClient.cs
- Assets/Mirror/Core/LocalConnectionToServer.cs
in host mode, [Rpc]s are queued up and invoke in next update - similar to remote client behaviour.
[Command]s however were invoked directly, unlike with remote clients.
=> the behaviour should be the same for [Rpc] and [Command]
=> either invoke both immediately, or queue both for next update
=> queuing will give more predictable behaviour compared to remote clients when testing(!)
testing with Tanks demo:
**before:**
**after:**
> breaking: fix: #3652 host [Command]s are now simulated over a message queue instead of invoking them directly (credits: Brian B.)

- Assets/Mirror/Examples/TanksCoop/Scripts/TankController.cs
Added OnStopServer  - nulls, to prevent a bug that can be caused on client host, when scenes do not reset during play, tank variables are set as "missing", which Unity does not count as null/empty.
Tested as best I can.
If the logic checks out, should be good to merge.
> fix: TanksCoop example, reset host values.

- Assets/Mirror/Core/NetworkManager.cs
- Two checkboxes are replaced with a dropdown
- Implementation self-adjusts to what user had selected so no breaking change.
Opening and saving a scene with any change results in this in version control, which is exactly what we want.
> feat(NetworkManager): Refactor Headless Start

- Assets/Mirror/Core/NetworkManager.cs
IsHeadless returns false for null graphics device in editor so isEditor check is never reached, let alone evaluated.
> fix(NetworkManager): Remove check for editor in Start

- Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
- Assets/Mirror/Editor/Weaver/Processors/SyncVarAttributeProcessor.cs
This commit makes a couple of small modification to the weaving around syncvars.
I identified 2 cases in which we weave code to invoke the hook for setting a syncvar's value:
1) When the setter is called on the weaved Network<SyncVarFieldName> property
2) When deserializing messages where the message contains a new value for the syncvar from the remote source
As stated in the linked issue, when the syncvar hook is invoked (if there even is a syncvar hook), an instantiation occurs:
`new Action<T, T>(HookMethod)`
The modifications to the weaving do the following:
- For each syncvar that contains a hook, a new `Action<T, T>` instance field is added to the class being weaved, where `T` is the field type of the syncvar field.
- During constructor injection weaving, all of the `Action<T, T>` …
> perf: SyncVar hook invocations no longer instantiate a new action delegate on every call

- Assets/Mirror/Components/NetworkTransform/NetworkTransformUnreliable.cs
Fixes spazzing out of rotations, which was caused by flicking between compressed quaternion and world rotation. Happened only if using NetworkTransformUnreliable, local worldspace and quat compression.
> fix: NT-UR Compression using world and not local rotation when null value.

- Assets/Mirror/Core/NetworkManager.cs
Server may change scenes while a connected client is in the middle of authentication. That sends NotReadyMessage to all connections. If client receives that while not yet authenticated, they'd get kicked when they shouldn't.
A not-yet-authenticated client isn't Ready, so receiving a NotReadyMessage does nothing.
> fix(NetworkManager): No Auth Required for NotReadyMessage

- Assets/Mirror/Components/NetworkAnimator.cs
No need to send the Trigger message back to the owner since we already called animator.SetTrigger
- RpcOnAnimationTriggerClientMessage
- RpcOnAnimationResetTriggerClientMessage
> perf(NetworkAnimator): ClientRpc includeOwner False

- Assets/Mirror/Core/NetworkClient.cs
- Same as NetworkServer...allows NetworkMessage handlers to have a channelId param
This is NetworkServer's version:
```cs
public static void RegisterHandler<T>(Action<NetworkConnectionToClient, T, int> handler, bool requireAuthentication = true)
where T : struct, NetworkMessage
{
ushort msgType = NetworkMessageId<T>.Id;
if (handlers.ContainsKey(msgType))
{
Debug.LogWarning($"NetworkServer.RegisterHandler replacing handler for {typeof(T).FullName}, id={msgType}. If replacement is intentional, use ReplaceHandler instead to avoid this warning.");
}
// register Id <> Type in lookup for debugging.
NetworkMessages.Lookup[msgType] = typeof(T);
handlers[msgType] = NetworkMessages.WrapHandler(handler, requireAuthentication, exceptionsDisconnect);
}
```
Server version usage:
```cs …
```
> feat(NetworkClient): Add RegisterHandler with ChannelId

- Assets/Mirror/Core/NetworkClient.cs
- Assets/Mirror/Core/NetworkIdentity.cs
- Assets/Mirror/Core/NetworkServer.cs
- Assets/Mirror/Tests/Editor/NetworkIdentity/NetworkIdentitySerializationTests.cs
- Assets/Mirror/Tests/Editor/NetworkIdentity/NetworkIdentityTests.cs
We should not have hijacked Unity's callback for runtime resets.
> fix(NetworkIdentity): Separate ResetState

- Assets/Mirror/Components/InterestManagement/Distance/DistanceInterestManagement.cs
- Assets/Mirror/Components/InterestManagement/SpatialHashing/SpatialHashingInterestManagement.cs
- Assets/Mirror/Core/InterestManagementBase.cs
- Assets/Mirror/Core/NetworkServer.cs
- Assets/ScriptTemplates/54-Mirror__Custom Interest Management-CustomInterestManagement.cs.txt
We should not have hijacked Unity's callback for runtime resets.
> fix(InterestManagement): Separate ResetState

- Assets/Mirror/Components/NetworkTransform/NetworkTransformBase.cs
- Assets/Mirror/Tests/Editor/NetworkTransform/NetworkTransform2kTests.cs
- This is done in Reset so Network Behaviour isn't effected.
- This will not change NT components already in place on objects / prefabs unless user manually chooses Reset in the inspector.
> feat(NetworkTransform): Default Sync Direction = Client To Server

- Assets/Mirror/Core/NetworkServer.cs
There is a RegisterHandler function that takes an channelId, but we dont have any replace handler override for this, yet we log warnings if a user replaces a handler to use a not existing ReplaceHandler function.
> Fix: Add missing replace handler override to NetworkServer

- Assets/Mirror/Examples/BenchmarkIdle/MirrorBenchmarkIdle.unity
50k causes a long delay, and looks like Unity has initially frozen, even on beefy machines. To prevent users from thinking this, and perhaps force closing, amount is lowered to something still crazy, but more reasonable. :)
- Nothing else has been touched
> perf: Lowered spawn amount from 50k, to 10k- Low risk, Low priority

- Assets/Mirror/Editor/Weaver/Processors/SyncVarAttributeProcessor.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverSyncVarAttributeTests.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverSyncVarAttributeTests_IsSuccess/SyncVarsCanBeArray.cs
- Assets/Mirror/Tests/Editor/Weaver/WeaverSyncVarAttributeTests_IsSuccess/SyncVarsCanBeArray.cs.meta
Tested host and remote client with the following:
```cs
[SyncVar(hook = nameof(DataChanged))] public byte[] data;
void DataChanged(byte[] _, byte[] newData)
{
Debug.LogFormat(LogType.Log, LogOption.NoStacktrace, this, $"DataChanged: {newData[3]}");
}
public override void OnStartServer()
{
data = new byte[] { 1, 2, 3, (byte)Random.Range(100, 200) };
InvokeRepeating(nameof(UpdateData), 1, 1);
}
[ServerCallback]
void UpdateData()
{
data = new byte[] { 1, 2, 3, (byte)Random.Range(100, 200) };
}
```
We have this in Reader / Writer extensions:
```cs
public static T[] ReadArray<T>(this NetworkReader reader)
{
int length = reader.ReadInt();
// 'null' is encoded as '-1'
if (length < 0) return null;
// prevent allocation attacks with a reasonable limit.
//   server shouldn't allocate too much on …
```
> feat(SyncVar): Arrays are supported

- Assets/Mirror/Core/NetworkServer.cs
ReplaceHandler can register handler without ever calling RegisterHandler, which is a valid use case as there is no function to call to check if a handler is registered, so in cases where classes can be destroyed and recreated ReplaceHandler can be used to avoid warnings.
This PR makes sure that if RegisterHandler was never called the NetworkMessage is still added to our debug lookup dictionary.
> fix(NetworkServer): ReplaceHandler - Add Message To Lookup Dictionary

- Assets/Mirror/Core/NetworkClient.cs
ReplaceHandler can register handler without ever calling RegisterHandler, which is a valid use case as there is no function to call to check if a handler is registered, so in cases where classes can be destroyed and recreated ReplaceHandler can be used to avoid warnings.
This PR makes sure that if RegisterHandler was never called the NetworkMessage is still added to our debug lookup dictionary.
> fix(NetworkClient): ReplaceHandler - Add Message To Lookup Dictionary

- Assets/Mirror/Core/Tools/Extensions.cs
Doesn't exist in older unity versions
> fix: Add shim for transform.GetPositionAndRotation

- Assets/Mirror/Core/NetworkBehaviour.cs
- Assets/Mirror/Editor/Weaver/Processors/NetworkBehaviourProcessor.cs
- Assets/Mirror/Editor/Weaver/Resolvers.cs
- Assets/Mirror/Editor/Weaver/WeaverTypes.cs
@miwarnec saw the property showing up while profiling. 
Very much unnecessary, so lets change that to a field.
BREAKING: Changed NetworkBehaviour.syncVarDirtyBits from a "get-only" property to a field
> breaking: perf: change NB.syncVarDirtyBits to field

- Assets/Mirror/Examples/BilliardsPredicted/Player/PlayerPredicted.cs
- Assets/Mirror/Examples/CharacterSelection/Scripts/PlayerControllerScript.cs
- Assets/Mirror/Examples/CharacterSelection/Scripts/PlayerEmpty.cs
- Assets/Mirror/Examples/CouchCoop/Scripts/CouchPlayer.cs
- Assets/Mirror/Examples/CouchCoop/Scripts/CouchPlayerManager.cs
- Assets/Mirror/Examples/MultipleMatches/Scripts/MatchController.cs
- Assets/Mirror/Examples/MultipleMatches/Scripts/MatchGUI.cs
- Assets/Mirror/Examples/_Common/Scripts/CanvasNetworkManagerHUD/CanvasNetworkManagerHUD.cs
Unity docs are a mess on when FindAnyObjectByType was implemented:
- 2021.3 says it is
- 2022.1 says it's not
- 2022.2 says it is
We were not getting compile errors with 2021.3 latest build versions, but apparently some of the earlier builds it wasn't there yet, e.g.  2021.3.8 according to some Discord users, so bumping the compiler symbol up to 2022.2 is safer for compatibility.
> fix: Safer version for FindAnyObjectByType

- Assets/Mirror/Transports/SimpleWeb/SimpleWebTransport.cs
TLS isn't technically correct, but there's no good way to get that info
> feat: SWT overrides Transport.IsEncrypted & EncryptionCipher

- Assets/Mirror/Transports/Edgegap/EdgegapLobby/LobbyServiceCreateDialogue.cs
There's currently a bug where lobby names longer than 5 characters can fail to deploy correctly and will return a "503 Service Temporarily Unavailable"
So we'll just add a warning so users are aware to use a short name for now
> fix(LobbyServiceCreateDialogue): Added warning about Edgegap Lobby Name bug

- Assets/Mirror/Core/SyncDictionary.cs
- Assets/Mirror/Tests/Editor/SyncCollections/SyncDictionaryTest.cs
This allows the data to be available in the callback for users to iterate and take actions as needed before it's wiped.
> fix(SyncDictionary): Clear after Callback

- Assets/Mirror/Core/SyncDictionary.cs
- Assets/Mirror/Examples/MultipleMatches/Scripts/MatchController.cs
- Assets/Mirror/Tests/Editor/SyncCollections/SyncDictionaryTest.cs
- Set and Remove Actions pass **OLD** item
- Deprecates Callback Action
With the new Set and Remove Actions, users will be able to do work with the previous values, while accessing the new values by the dictionary key.
Below is an example that would be applicable for a card game or inventory:
```cs
using UnityEngine;
using Mirror;
using System;
public class SyncDictTest : NetworkBehaviour
{
public struct ItemData
{
public byte prefabIndex;
public Vector3 position;
public Quaternion rotation;
// this is not networked or serialized, it's only used on the client
// to hold reference to the instantiated object for a dictionary item.
[NonSerialized]
public GameObject clientObject;
public void CreateClientObject(GameObject prefab, Vector3 pos, Quaternion rot)
{
clientObject = …
```
> feat(SyncDictionary): Add individual Actions for operations

- Assets/Mirror/Core/Attributes.cs
The current comments for SyncVar is somewhat misleading. That is to say, it is mentioned in the comments that SyncVar can only be modified on the server side, and will be automatically synchronized to the client. But in fact, if syncDirection is set to ClientToServer, SyncVar should be modified on the client and automatically synchronized to the server and other clients. The same error exists in the comments of hook attribute
> Update comments for SyncVar

- Assets/Mirror/Core/SyncList.cs
- Assets/Mirror/Tests/Editor/SyncCollections/SyncListStructTest.cs
- Assets/Mirror/Tests/Editor/SyncCollections/SyncListTest.cs
- Set and Remove Actions pass **OLD** item
- Deprecates Callback Action
With the new Set and Remove Actions, users will be able to do work with the previous values, while accessing the new values by the dictionary key.
> feat(SyncList): Add individual Actions for operations

- Assets/Mirror/Components/NetworkAnimator.cs
- Animator.speed default is 1, not zero
This ensures that if animatorSpeed is set to zero at runtime the hook fires appropriately, and doesn't fire erroneously when it's 1.
Fixes: #3793
> fix(NetworkAnimator): Default animatorSpeed to 1

- Assets/ScriptTemplates/Editor.meta
- Assets/ScriptTemplates/Editor/MoveToAssetsFolder.cs
- Assets/ScriptTemplates/Editor/MoveToAssetsFolder.cs.meta
- Ensures ScriptTemplates folder is in Assets root
- Allows ScriptTemplates folder to be included in Asset Store package under Mirror folder
- Only runs once when Unity first loads project via SessionState flag
> feat(MoveToAssetsFolder): Editor Script Moves ScriptTemplates to Assets

- Assets/Mirror/Core/NetworkServer.cs
Interest Management does this in Rebuild, but without IM involved, we need to handle this case in RebuildObserversDefault
> fix(NetworkServer): Spawn for owner client even when Force Hidden

- Assets/Mirror/Tests/Editor/Weaver/WeaverAssembler.cs
We have #3630 for this...silence warning until Unity tells us what to use instead.
> fix(WeaverAssembler): Silence Obsolete Warning

- Assets/Mirror/Transports/Latency/LatencySimulation.cs
Fixes a bug in a project that was trying to simulate latency.
They checked "if Transport is PortTransport" during setup, which silently broke with LatencySimulation since that's not a PortTransport.
This PR makes it a PortTransport, and warns if it isn't.
Instead of not being a PortTransport, which is wrong in 99% of the cases.
> fix(LatencySimulation): implement PortTransport since almost all underlying Transports are PortTransports

- Assets/Mirror/Core/NetworkServer.cs
- Assets/Mirror/Examples/AdditiveLevels/Scripts/Portal.cs
- Assets/Mirror/Examples/MultipleMatches/Scripts/MatchController.cs
- Assets/Mirror/Tests/Editor/NetworkServer/NetworkServerTest.cs
- Assets/Mirror/Tests/Runtime/NetworkServerRuntimeTest.cs
- Replaces `destroyServerObject` with `RemovePlayerOptions`
- Option to keep the player object on server and clients
- Obsoletes old method by calling new method with correct option
- Examples and Tests updated
> feat(NetworkServer): Improves RemovePlayerForConnectsion

- Assets/Mirror/Examples/StackedPrediction/NetworkManagerStackedPrediction.cs
- Assets/Mirror/Examples/StackedPrediction/PredictedCube.prefab
Minor drag on cube prefabs, to stop them from indefinitely moving/rotating.
(highly recommend to not have 0 drag on released games, unity default Rigidbody drag is 0, take note everyone :D )
Velocity Iterations added to NetworkManager(StackedPrediction), next to regular Iterations, left as Unity default 1, alerts users to the setting that they can then adjust themselves.
Added tooltip note that unity default is 1, and max is 255.
> Velocity Iterations on NM, Drag on Cube prefabs.

- Assets/Mirror/Components/NetworkRuntimeProfiler.cs
- Assets/Mirror/Components/NetworkRuntimeProfiler.cs.meta
Adds a simple text-based network profiler for use at runtime, also compatible with older unity versions!
https://github.com/MirrorNetworking/Mirror/assets/1426904/804b5c1b-4067-43de-9bc7-d404240b6e58
Output example:
```
Stats for 25/06/2024 13:17:44 (5.0s interval)
-------------------------------------------------------------------------------------------------------------------------------
|                                                        IN Message | Recent Bytes | Recent Count | Total Bytes | Total Count |
-------------------------------------------------------------------------------------------------------------------------------
|                                                 Mirror.RpcMessage |     2.82 KiB |          160 |    8.27 KiB |         469 |
| …
```
> feat: NetworkRuntimeProfiler

- Assets/Mirror/Examples/CouchCoop/MirrorCouchCoop.unity
- Assets/Mirror/Examples/CouchCoop/Prefabs/CouchPlayer.prefab
- Assets/Mirror/Examples/CouchCoop/Scripts/MovingPlatform.cs
- Assets/Mirror/Examples/CouchCoop/Scripts/MovingPlatform.cs.meta
- Assets/Mirror/Examples/CouchCoop/Scripts/PlatformMovement.cs
- Assets/Mirror/Examples/CouchCoop/Scripts/PlatformMovement.cs.meta
No constant network sync for platforms, they just resync at start and end destination.
2 scripts, one for handling player moving WITH the platform, WITHOUT parent/childing the player itself.
Second script for moving platform locally, and the resync position Rpc, send via server.
Enjoy the compressed video preview, here at the beginning when client joins, you can see the platforms sync to their 'master' position. If player lags or pauses game, the platforms will fix themselves.
This is designed to be a starter point for people needing moving platforms in multiplayer, upto you, the user to adjust and improve, good luck!
https://github.com/MirrorNetworking/Mirror/assets/57072365/447313e3-a52b-44b3-b56d-665d2aba8fff
Edited: added some optional platform features.
Move sync var, to stop and …
> feat: MOVING Platforms to Couch Coop Example

- Assets/Mirror/Core/NetworkServer.cs
- Assets/Mirror/Examples/Basic/Scripts/Player.cs
- Assets/Mirror/Tests/Editor/NetworkBehaviour/NetworkBehaviourTests.cs
explanation:
NS.Destroy() calls NS.Unspawn() which calls ResetState() which resets isServer
for prefabs, Destroy(go) -> OnDestroy() is called after, with isServer false due to the reset.
this change does not call ResetState() for prefabs anymore.
fixes the runtime test too:
> fix: #3832 NetworkServer.Destroy now doesn't call ResetState for prefabs, fixes isServer flag always being false in OnDestroy

- Assets/Mirror/Components/NetworkRigidbody/NetworkRigidbodyReliable.cs
- Assets/Mirror/Components/NetworkRigidbody/NetworkRigidbodyReliable2D.cs
- Assets/Mirror/Components/NetworkRigidbody/NetworkRigidbodyUnreliable.cs
- Assets/Mirror/Components/NetworkRigidbody/NetworkRigidbodyUnreliable2D.cs
- Assets/Mirror/Components/NetworkTransform/NetworkTransformBase.cs
- Assets/Mirror/Core/NetworkBehaviour.cs
OnValidate only runs in Editor, but can get invoked in PlayMode if user fiddles with the inspector or by other Unity activities.
> fix(NetworkBehaviour): Skip OnValidate in Editor Play Mode

- Assets/Mirror/Core/LocalConnectionToClient.cs
- Assets/Mirror/Core/NetworkConnectionToClient.cs
- Assets/Mirror/Core/NetworkServer.cs
- Assets/Mirror/Core/Transport.cs
- Assets/Mirror/Tests/Editor/NetworkServer/NetworkServerTest.cs
- Assets/Mirror/Transports/Edgegap/EdgegapRelay/EdgegapKcpServer.cs
- Assets/Mirror/Transports/Edgegap/EdgegapRelay/EdgegapKcpTransport.cs
- Assets/Mirror/Transports/KCP/KcpTransport.cs
- Assets/Mirror/Transports/KCP/kcp2k/highlevel/KcpServer.cs
- Assets/Mirror/Transports/Threaded/ThreadedTransport.cs
Transports can now pass the remote client address directly to NetworkServer Action
- Facliltates ThreadedTransport passing the client Address
- KCP Transport Updated accordingly
- Original OnTransportConnected passes ServerGetClientAddress result to new method OnTransportConnectedWithAddress
- Saves round trips back to the transport for client address whenever it's needed
Alternative to #3829
> feat(Transport): Added OnServerConnectedWithAddress

- Assets/Mirror/Transports/SimpleWeb/SimpleWebTransport.cs
Some browsers will send handshake larger than 3k, setting default limit to 16k so user dont have to worry about changing it
> fix(SimpleWebTransport): increasing default handshake max size

- Assets/Mirror/Examples/AutoLANClientController.meta
- Assets/Mirror/Examples/AutoLANClientController/MirrorAutoLANClientController.unity
- Assets/Mirror/Examples/AutoLANClientController/MirrorAutoLANClientController.unity.meta
- Assets/Mirror/Examples/AutoLANClientController/Prefabs.meta
- Assets/Mirror/Examples/AutoLANClientController/Prefabs/PlayerController.prefab
- Assets/Mirror/Examples/AutoLANClientController/Prefabs/PlayerController.prefab.meta
- Assets/Mirror/Examples/AutoLANClientController/Scripts.meta
- Assets/Mirror/Examples/AutoLANClientController/Scripts/AutoLANNetworkDiscovery.cs
- Assets/Mirror/Examples/AutoLANClientController/Scripts/AutoLANNetworkDiscovery.cs.meta
- Assets/Mirror/Examples/AutoLANClientController/Scripts/CanvasHUD.cs
- Assets/Mirror/Examples/AutoLANClientController/Scripts/CanvasHUD.cs.meta
- Assets/Mirror/Examples/AutoLANClientController/Scripts/CustomNetworkManager.cs
- Assets/Mirror/Examples/AutoLANClientController/Scripts/CustomNetworkManager.cs.meta
- Assets/Mirror/Examples/AutoLANClientController/Scripts/NetworkSceneScript.cs
- Assets/Mirror/Examples/AutoLANClientController/Scripts/NetworkSceneScript.cs.meta
New example for a use-case that's been brought up many times over the years.
Contains 2 main parts.
- Auto connecting over LAN, no need to enter IP's.
- Client acting as a controller for main server screen, each with its own UI.
Details:
Auto Start button checks for local broadcasting servers, if non found, one is created.
Once connected, server and client each have their own UI.
Clients can interact and send data to server, as seen via the Button and Text Result.
Video:
https://github.com/user-attachments/assets/2d98f2f7-7645-4215-9786-9f173e4bb0be
Folder hierarchy:
Needs some code comments and maybe a tidy up, but minor priority.
> feat: Auto LAN connect + client controller example.

- Assets/Mirror/Transports/SimpleWeb/SimpleWeb/Client/StandAlone/ClientSslHelper.cs
Hi
We've found that when trying to connect to a Mirror server with a WebSocket transport using a https Uri, the client doesn't use SSL. Although it might be more technically correct to specify a wss Uri, if a connection is made with a https Uri then the intention would (surely) be to use SSL.
I've included a simple change which we've tested that seems to work fine if you wish to incorporate this.
> ClientSslHelper to wrap https in SSL

- Assets/Mirror/Components/NetworkTransform/NetworkTransformUnreliable.cs
- Assets/Mirror/Tests/Editor/NetworkTransform/NetworkTransform2kTests.cs
Remove old code, that was used as a backup during testing new features.
(210 less lines of code)
> chore(CI): Old code removed from NetworkTransformUnreliable

- Assets/Mirror/Examples/CouchCoop/MirrorCouchCoop.unity
- Assets/Mirror/Examples/CouchCoop/Scripts/MovingPlatform.cs
- Assets/Mirror/Examples/CouchCoop/Scripts/PlatformMovement.cs
- Assets/Mirror/Examples/TopDownShooter/Prefabs/EnemyPrefab.prefab
No idea what happened, but some colliders seem to have changed their size.
Also added missing namespace to the 2 latest platform scripts on CouchCoop example.
> fix: Examples colliders and missing namespace.

- Assets/Mirror/Core/NetworkReaderExtensions.cs
- Assets/Mirror/Core/NetworkWriterExtensions.cs
- Assets/Mirror/Tests/Editor/NetworkServer/NetworkServerTest.cs
- 2% worse CPU perf
- 15% better bandwidth
pending more tests to see if this is worth it.
all ArraySegment/List/Collection .Counts are now encoded as VarInt instead of full 4 bytes int.
this will reduce bandwidth for the majority of collections down from 4 to 1 (or 2) bytes.
Examples/Benchmark:
- before: 150 KB/s
- after: 120 KB/s
> perf: NetworkReader/Writer: read/write collection size headers as VarInt (Benchmark: 150 -> 120 KB/s)

- Assets/Mirror/Core/NetworkClient.cs
- This is for host client to match logical call order as remote client
```cs
public override void OnStartClient()
{
Debug.Log($"OnStartClient: {isOwned} {isLocalPlayer}");
}
public override void OnStartAuthority()
{
Debug.Log($"OnStartAuthority: {isOwned} {isLocalPlayer}");
}
public override void OnStartLocalPlayer()
{
Debug.Log($"OnStartLocalPlayer: {isOwned} {isLocalPlayer}");
}
```
Host Client
Remote Client
> fix(NetworkClient): InvokeIdentityCallbacks call OnStartClient first

- Assets/Mirror/Components/NetworkRoomManager.cs
- Assets/Mirror/Core/NetworkServer.cs
- Assets/Mirror/Examples/CharacterSelection/Scripts/NetworkManagerCharacterSelection.cs
- Assets/Mirror/Examples/TankTheftAuto/Scripts/TankAuthority.cs
- Assets/Mirror/Tests/Editor/NetworkServer/NetworkServerTest.cs
- ReplacePlayerOptions: KeepAuthority, KeepActive, Unspawn, Destroy
- NetworkServer tests updated
- Examples updated and work correctly
Eliminates need to make a coroutine to replace & destroy player.
> feat(NetworkServer): Improved ReplacePlayerForConnection

- Assets/Mirror/Core/Attributes.cs
- Assets/Mirror/Core/NetworkReaderExtensions.cs
- Assets/Mirror/Core/NetworkWriterExtensions.cs
- Assets/Mirror/Editor/Weaver/Readers.cs
- Assets/Mirror/Editor/Weaver/Weaver.cs
- Assets/Mirror/Editor/Weaver/Writers.cs
- Assets/Mirror/Tests/Editor/NetworkReaderWriter/NetworkWriterCollectionTest.cs
- Assets/Mirror/Tests/Editor/NetworkReaderWriter/NetworkWriterTest.cs
- Assets/Mirror/Tests/Editor/NetworkServer/NetworkServerTest.cs
- 2% worse CPU perf
- 15% better bandwidth
pending more tests to see if this is worth it.
**MERGE, DONT SQUASH**
automatically compress all game integers!
Before:
```cs
public override void SerializeSyncVars(NetworkWriter writer, bool forceAll)
{
base.SerializeSyncVars(writer, forceAll);
if (forceAll)
{
writer.WriteInt(health);
return;
}
writer.WriteULong(syncVarDirtyBits);
if ((syncVarDirtyBits & 1L) != 0L)
{
writer.WriteInt(health);
}
}
```
After:
```cs
public override void SerializeSyncVars(NetworkWriter writer, bool forceAll)
{
base.SerializeSyncVars(writer, forceAll);
if (forceAll)
{
writer.WriteVarInt(health);
return;
}
writer.WriteVarULong(syncVarDirtyBits);
if ((syncVarDirtyBits & 1L) != 0L)
{
writer.WriteVarInt(health);
}
}
```
- before: 120 KB/s
- after: 100 KB/s
> perf: Weaver automatically uses VarInt compression for all integers in [SyncVar]/[Command]/[Rpc]/SyncList/NetworkMessage/etc.

- Assets/Mirror/Transports/Threaded/ThreadedTransport.cs
**optional feature**: ThreadedTransport automatically detects if a device was put to sleep (i.e. phone/VR/etc.)
after a configurable timeout, it then ends the worker thread gracefully.
this is important so we don't drain devices that were put to sleep, and may stay asleep for days.
> fix(ThreadedTransport): sleep detection

- Assets/Mirror/Core/Batching/Batcher.cs
- Assets/Mirror/Tests/Editor/Batching/BatcherTests.cs
fixes subtle jitter in all Mirror games.
https://github.com/user-attachments/assets/c26f2213-cb70-404f-b241-177c65fc42dd
https://github.com/user-attachments/assets/f081cd8d-06e1-4ea3-b93b-465e897a4ff6
fortunately we know who did this.
> fix(Batching): add timestamp safety check to ensure all messages in the batch have the same timestamp

- Assets/Mirror/Editor/Weaver/Processors/ReaderWriterProcessor.cs
#3816
Recursively handle the Network Reader/Writer required by CurrentAssembly.AssemblyReferences.
> fix(ReaderWriterProcessor) : When crossing assemblies problem

- Assets/Mirror/Core/SyncList.cs
- Assets/Mirror/Tests/Editor/SyncCollections/SyncListStructTest.cs
- Assets/Mirror/Tests/Editor/SyncCollections/SyncListTest.cs
we've had 10 years worth of projects hook into SyncLists for changes with (oldItem, newItem).
reducing this to one parameter that is sometimes oldItem, sometimes newItem introduces too much pain when upgrading.
this will save people thousands of dollars in upgrade costs.
> SyncList: keep old OnChange parameters to not break projects

- Assets/Mirror/Core/NetworkManagerHUD.cs
- Assets/Mirror/Core/NetworkServer.cs
- Assets/Mirror/Tests/Editor/NetworkServer/NetworkServerTest.cs
1. changes double negative 'dontListen=false' to 'listen=true'
2. fixes #2536 
MERGE, DONT SQUASH
> NetworkServer.dontListen improvements and fixes

- Assets/Mirror/Core/NetworkReaderExtensions.cs
- Assets/Mirror/Core/NetworkWriterExtensions.cs
- Assets/Mirror/Core/Tools/Half.cs
- Assets/Mirror/Core/Tools/Half.cs.meta
- Assets/Mirror/Tests/Editor/Tools/HalfTests.cs
- Assets/Mirror/Tests/Editor/Tools/HalfTests.cs.meta
Unity's .net version doesn't have half floats.
now we do.
https://devblogs.microsoft.com/dotnet/introducing-the-half-type/
(this is for compression)
> feat: Half Floats

- Assets/Mirror/Core/NetworkManager.cs
- Assets/Mirror/Core/Transport.cs
- Assets/Mirror/Examples/AutoLANClientController/Scripts/AutoLANNetworkManager.cs
- Assets/Mirror/Examples/PlayerTest/PlayerTestNetMan.cs
https://github.com/MirrorNetworking/Mirror/issues/2802
> fix: #2802 NetworkManager uses OnDestroy for shutdown instead of OnApplicationQuit

- Assets/Mirror/Components/NetworkTransform/NetworkTransformHybrid2022.cs
- Assets/Mirror/Components/NetworkTransform/NetworkTransformHybrid2022.cs.meta
TODO DONT MERGE YET:
- interp in lateupdate
-----------------------
Changing Mirror from Reliable to (optional) Unreliable takes significant effort.
Let's do this with incremental PRs, each of them tested in a production game.
1. NetworkTransform Hybrid baseline+deltas
2. Delta Compression via Half Floats
3. Abstract NetworkTransform Hybrid sync into NetworkBehaviourHybrid
4. Use NetworkBehaviourHybrid for more components
5. Implement OnSerializeUnreliable to remove Rpc overhead
6. Move NetworkBehaviourHybrid into NetworkBehaviour core
7. IL Weaving for Unreliable [SyncVar] support etc.
This PR is step 1: **NetworkTransform with Reliable baseline + Unreliable deltas** for proper change detection!
The previous NetworkTransform implements a hacky, 95% correct change detection for Unreliable …
> feat: NetworkTransformHybrid - Hybrid Sync Part 1

- Assets/Mirror/Core/NetworkIdentity.cs
- Assets/Mirror/Tests/Common/MirrorTest.cs
- Assets/Mirror/Tests/Editor/NetworkIdentity/NetworkIdentitySerializationTests.cs
Thanks to EnragedOxygen on Discord for tracking this one down!
Turns out you need to be very explicit with typing otherwise c# will default to int. 
This will cause the component dirty mask to overflow for any components > 32, which causes weird issues since it will cancel each other out (both the bitmask creation and the following IsDirty(componentIndex) overflow)
This will lead to serialization on the component index < 32 and > 32 (so index 33 would deserialize for both 1 and 33), but only sometimes
Generally in real games this would show up as a size mismatch which is how EnragedOxygen discovered it
I've done a quick project wide search for any other occurences, but it seems like everywhere else is typed correctly
> fix: NetworkIdentity component bitmask shifting overflows

- Assets/Mirror/Components/PredictedRigidbody/PredictionUtils.cs
The freezeRotation was overriding the constraints in PredictionUtils.MoveRigidbody
It is indeed a setter and when you set freezeRotation to false it clears all the three flags freezeX, freezeY, freezeZ, so it has to be set before the constraints
> fix(PredictionUtils): move freeze rotation before constraints

- Assets/Mirror/Core/InterestManagementBase.cs
Tested in Additive Levels example by adding terrains with tree details, spot lights, audio sources, and particle systems to each of the two subscenes. Turn sound on / unmute the audio when playing the video below.
- Note that this is a virtual method, works by default for all interest mgmt, and can be overridden.
https://github.com/user-attachments/assets/d06a355a-9f46-45f5-83bb-297e5a2e6974
> fix(InterestManagementBase): Improve SetHostVisibility

- Assets/Mirror/Core/NetworkClient.cs
NetworkServer::UnSpawnInternal already does everything we need to do, and since the identity is removed from spawned before the ObjectDestroyMessage is sent the lookup never succeeds and the spawned.Remove was already done.
- NetworkServer.Destroy calls UnSpawnInternal which does all the cleanup.
> fix(NetworkClient): Remove OnHostClientObjectDestroy

- Assets/Mirror/Core/NetworkServer.cs
- Fixes #3962 
There may be a custom unspawn handler for the prefab and NetworkClient::OnHostClientObjectDestroy doesn't invoke it and can't because it's already out of spawned dictionary.
> fix(NetworkServer): Call NetworkClient.InvokeUnSpawnHandler from UnSpawnInternal

- Assets/Mirror/Core/NetworkClient.cs
Virtually eliminates null refs with GO/NI/NB SyncVars by getting all objects into spawned dictionary before applying payloads and invoking hooks.
- No change to normal spawning, only initial spawn
- Uses and clears a static dictionary, so no garbage allocation
See ticket #3097
Test with PickupsDropsChilds example:
- Added SyncList to PickupsDropsChilds on player for everything player drops
- Added SyncVar to SceneObject for owner player object
- Started with built host client, dropped 3 things, then joined client from editor
- Depending on spawn order, either the SyncVar hook or the SyncList OnAdd handler would've thrown NRE's
```cs
public readonly SyncList<GameObject> drops = new SyncList<GameObject>();
public override void OnStartClient()
{
drops.OnAdd += OnAdd;
for (int i = 0; i < …
```
> fix(NetworkClient): Defer ApplySpawnPayload until OnObjectSpawnFinished #3097

- Assets/Mirror/Core/NetworkConnection.cs
- Assets/Mirror/Core/NetworkConnectionToClient.cs
- Assets/Mirror/Core/NetworkIdentity.cs
- Only transports set connectionId
- None of our transports set it on client side (NetworkConnectionToServer)
- Some projects may be referencing NetworkConnection type instead of NetworkConnectionToClient and we can't obsolete connectionId in the base class
- Requires fixing NI::RemoveObserver to correct type
> breaking: Move connectionId to NetworkConnectionToClient

- Assets/Mirror/Components/NetworkTransform/NetworkTransformBase.cs
Use localPosition and localRotation when calculating velocity and angularVelocity because the interpolated values are in local space and `target` may be a child object.
> fix(NetworkTransformBase): Fixed velocity / angularVelocity

- Assets/Mirror/Core/NetworkBehaviour.cs
`Please add a NetworkIdentity component to {name} or it's parents.` 
should be:
`Please add a NetworkIdentity component to {name} or its parents.`
Not much, just saw it in the Unity console and wanted to fix it :)
> Fix grammatical error in NetworkBehaviour.cs

- Assets/Mirror/Examples/Editor.meta
- Assets/Mirror/Examples/Editor/MirrorRenderPipelineConverter.cs
- Assets/Mirror/Examples/Editor/MirrorRenderPipelineConverter.cs.meta
This pull request introduces `MirrorRenderPipelineConverter`, an editor script that automatically converts materials in the `Assets/Mirror/Examples` folder from Unity’s built-in render pipeline (e.g., `Standard`, `Legacy Shaders`) to the Universal Render Pipeline (URP) in Unity 6000+. It ensures Mirror Networking’s example scenes remain visually consistent and functional in modern URP projects, addressing the shift from the default built-in pipeline (Unity 2019) to URP in Unity 6000.
- **Automatic Conversion**: Runs on project load, detects URP, and prompts with options: “Go Ahead” (convert), “Not Now” (skip), or “Don’t Ask Again” (set flag without converting).
- **Targeted Scope**: Only processes `.mat` files within `Assets/Mirror/Examples` and subfolders, preserving user project assets. …
> feat: Add MirrorRenderPipelineConverter for URP Compatibility

- Assets/Mirror/Components/NetworkTransform/NetworkTransformBase.cs
Effects both NetworkTransformUnreliable and NetworkRigidbodyUnreliable, when a new component is added, it will use the default, does not effect currently placed components.
If a user increases send rate, needing the boost to framerate, but not wanting to increase sends from the components, previously may unexpectedly be sending more data than intended if they left component intervals at default 0, this helps separate NetworkManager SendRate/FrameRate and the components send intervals to prevent such a case.
Kudos to the Gadget Man.
> perf: Update NetworkTransformBase default syncInterval.

- Assets/Mirror/Components/NetworkTransform/NetworkTransformHybrid.cs
> fix(NTHybrid): initial child sync (#4004)

- Assets/Mirror/Core/InterestManagementBase.cs
Tested by adding a world canvas with NI into Additive Levels subscene...works as expected.
Fixes #4003
> fix(InterestManagementBase): Hide Canvas in SetHostVisibility

- Assets/Mirror/Components/RemoteStatistics.cs
Allows for quicker testing of remote statistics, or when clients viewing the data is just not a threat.
It is false by default.
> feat: Bool to skip password and auth check in RemoteStatistics.cs

- Assets/Mirror/Core/NetworkServer.cs
This reverts commit 2381edf6148a71e8eff314fe592efa9ca10efc5a.
> Revert "Update NetworkServer.cs (#4010)"

- Assets/Mirror/Editor/NetworkBehaviourInspector.cs
NetworkTransform components are locked to a certain SyncMethod
> fix(NetworkBehaviourInspector): Hide SyncMethod for NT

- Assets/Mirror/Core/NetworkClient.cs
- Assets/Mirror/Core/NetworkServer.cs
- Assets/Mirror/Tests/Editor/NetworkClient/NetworkClientTests.cs
- Assets/Mirror/Tests/Editor/NetworkServer/NetworkServerTest.cs
Applies to both NetworkServer and NetworkClient
Tests updated too
> fix: Reset exceptionsDisconnect in Shutdown

- README.md
Adds the 6 and 6.1 LTSs to the README file. I was going to remove 2019 and 2020 since Unity no longer supports them, but I want to check in with you guys before doing it. Also, 6.1 is "supported", not LTS, so if you want to remove it as well, you may.
> Add 6000 / 6000.1 LTS to README

- README.md
Switched the EOS Transport link from FakeByte's to Katone's, and removed the Oculus P2P Transport. Could you also update the docs? Thanks!
> Update Transports List

- Assets/Mirror/Core/NetworkBehaviour.cs
removed double 'the' in isLocalPlayer summary comment
> Fixed double "the" in comment for NetworkBehaviour.isLocalPlayer method

- Assets/Mirror/Components/NetworkAnimator.cs
Fixes #4052. All details is in issue page. 
The fix is removing (includeOwner = false) parameter from ClientRpc attributes. Besides checking isServer it also checks if the current player is in charge of the NetworkAnimator to prevent double trigger set.
Test scene from the issue with the fix applied after pressing keys on both instances:
> Fixes NetworkAnimator SetTrigger issue #4052
